### ISSUE TITLE
Bug Sklearn

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1000]
Command:
`sct_testing`

Error for:
- test_sct_label_vertebrae
- test_sct_register_multimodal
- test_sct_register_to_template

Error observed for:
- sklearn.decomposition
- sklearn.metrics
- sklearn.svm

Reinstallation on **OSX 10.8.2** (Monk Station) (./install_sct) >> Ok but sklearn warning:
```
Check if scikit-learn (0.17.1) is installed.........[WARNING]
  Detected version: 0.18.dev0. Required version: 0.17.1
```
Reinstallation on El Capitain >> No problem

Example:
```
Split destination volume...
Traceback (most recent call last):
File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_register_to_template.py", line 613, in <module>
main()
File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_register_to_template.py", line 464, in main
warp_forward_out, warp_inverse_out = register(src, dest, paramreg, param, str(i_step))
File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 609, in register
verbose=param.verbose)
File "/Users/chgroc/code/spinalcordtoolbox/scripts/msct_register.py", line 62, in register_slicewise
register2d_centermassrot('src.nii', 'dest.nii', fname_warp=warp_forward_out, fname_warp_inv=warp_inverse_out, rot=1, poly=paramreg.poly, path_qc=path_qc, verbose=verbose)
File "/Users/chgroc/code/spinalcordtoolbox/scripts/msct_register.py", line 135, in register2d_centermassrot
coord_src, pca_src, centermass_src[iz, :] = compute_pca(data_src[:, :, iz])
File "/Users/chgroc/code/spinalcordtoolbox/scripts/msct_register.py", line 810, in compute_pca
from sklearn.decomposition import PCA
File "/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/decomposition/__init__.py", line 10, in <module>
from .kernel_pca import KernelPCA
File "/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/decomposition/kernel_pca.py", line 15, in <module>
from ..metrics.pairwise import pairwise_kernels
File "/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/metrics/__init__.py", line 33, in <module>
from . import cluster
File "/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/metrics/cluster/__init__.py", line 19, in <module>
from .unsupervised import silhouette_samples
File "/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/metrics/cluster/unsupervised.py", line 11, in <module>
from ..pairwise import pairwise_distances
File "/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/metrics/pairwise.py", line 29, in <module>
from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
ImportError: dlopen(/Users/chgroc/.local/lib/python2.7/site-packages/sklearn/metrics/pairwise_fast.so, 2): Library not loaded: libmkl_intel_lp64.dylib
Referenced from: /Users/chgroc/.local/lib/python2.7/site-packages/sklearn/metrics/pairwise_fast.so
Reason: image not found

/Users/chgroc/code/spinalcordtoolbox/scripts/sct_utils.pyNone

[FAIL]
```

**Comment by jcohenadad** [comment]
seems to be fixed on Mountain Lion with new requirements
