### ISSUE TITLE
[sct_dmri_moco] Too many open files

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1015]
COMMANDLINE:
`````
sct_dmri_moco -i qspace_all.nii.gz -bvec bvecs.bvec -bval bvecs.bvals -bvalmin 1500
`````
BUG:
``
```
Merge DW images...
Average DW images...
sct_maths -i dwi_272.nii -o dwi_mean_272.nii -mean t

Merging DW files...
Traceback (most recent call last):
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 546, in <module>
    main()
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 166, in main
    dmri_moco(param)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 296, in dmri_moco
    im_dw_list.append(Image(file_dwi_mean[iGroup] + ext_data))
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/msct_image.py", line 224, in __init__
    self.loadFromPath(param, verbose)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/msct_image.py", line 281, in loadFromPath
    self.data = self.im_file.get_data()
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/spatialimages.py", line 582, in get_data
    data = np.asanyarray(self._dataobj)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/numpy/core/numeric.py", line 525, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 144, in __array__
    raw_data = self.get_unscaled()
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 139, in get_unscaled
    mmap=self._mmap)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/volumeutils.py", line 502, in array_from_file
    offset=offset)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/numpy/core/memmap.py", line 273, in __new__
    self.filename = os.path.abspath(filename.name)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 24] Too many open files
`````

Data in 
`````
folder_shared/sct_issues/20161031_sct_dmri_moco
`````

Also, even though option -g = 1 (no grouping of files). The script starts by merging each image (e.g. : sct_maths -i dwi_268.nii -o dwi_mean_268.nii -mean t), which is useless..

**Comment by peristeri** [comment]
I'm able to reproduce the error and trace it back to the limitation of the OS as well as the msct_image.Image object opens the file twice. 

The maximum number of open files descriptors `ulimit -n` is 256 for a mac machine. It does not help that concat_data requires a list of Images. But the ng_groups = 273 which will continue the problem.

As a temporary solution is to increase the OS maximum of open file descriptors while I look at opening and closing file descriptor dynamically and eliminate duplicate open file descriptor.
