### ISSUE TITLE
straightening failing on data with few slices

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1053]
sct_example_data

~~~
sct_straighten_spinalcord -i mt1.nii.gz -s mt1_seg.nii.gz

--
Spinal Cord Toolbox (master/04536c16c356751bc650c4a66379455f89ab3f84)
Running /Users/julien/temp/sct_qc/scripts/sct_straighten_spinalcord.py -i mt1.nii.gz -s mt1_seg.nii.gz
/Users/julien/temp/sct_qc

Check input arguments:
  Input volume ...................... mt1.nii.gz
  Centerline ........................ mt1_seg.nii.gz
  Final interpolation ............... spline
  Verbose ........................... 1


Create temporary folder...
mkdir tmp.161129162528_56704/

Copy files to tmp folder...
sct_convert -i mt1.nii.gz -o tmp.161129162528_56704/data.nii
sct_convert -i mt1_seg.nii.gz -o tmp.161129162528_56704/centerline.nii.gz

Orient centerline to RPI orientation...
sct_image -i centerline.nii.gz -setorient RPI -o centerline_rpi.nii.gz

Get dimensions...
.. matrix size: 192 x 192 x 5
.. voxel size:  0.84375mm x 0.84375mm x 17.0mm

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 50
Window size is too small. No smoothing was applied.
Window size is too small. No smoothing was applied.

Create the straight space and the safe zone...

Pad input volume to account for spinal cord length...
sct_image -i centerline_rpi.nii.gz -o tmp.centerline_pad.nii.gz -pad 0,0,1
sct_crop_image -i tmp.centerline_pad.nii.gz -o tmp.centerline_pad_crop.nii.gz -dim 0,1,2 -start 55,55,0 -end 137,137,4
WARNING: File tmp.centerline_pad_crop.nii.gz already exists. Deleting it.
Number of voxel = 184320
WARNING: Exception during Straightening:
Error on line 472
shapes (3,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)

Generate output file (in current folder)...
  ERROR: File tmp.161129162528_56704//tmp.curve2straight.nii.gz does not exist. Exit program.

/Users/julien/temp/sct_qc/scripts/sct_utils.pyTraceback (most recent call last):
  File "/Users/julien/temp/sct_qc/scripts/sct_straighten_spinalcord.py", line 472, in straighten
    coord_phys_straight = np.asarray(image_centerline_straight.transfo_pix2phys(coord_straight))
  File "/Users/julien/temp/sct_qc/scripts/msct_image.py", line 751, in transfo_pix2phys
    coordi_phys = np.transpose(coord_origin + np.dot(m_p2f_transfo, coordi_pix))
ValueError: shapes (3,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)
~~~

**Comment by benjamindeleener** [comment]
I'll fix this issue in branch `bdl_issue_1053`

The test is passing. I'll modify `test_sct_straighten_spinalcord` to be more specific.
