### ISSUE TITLE
[sct_resample] BUG when downsampling by more than 10 

### ISSUE THREAD

**Issue by alzaia** [neuropoly/spinalcordtoolbox#1103]
command:
`````
sct_resample -i /Users/alzaia/ariane/test/multilabel_template_seg_reg_crop_reg.nii.gz -f 0.1
`````

BUG:
`````
Traceback (most recent call last):
  File "/Users/alzaia/spinalcordtoolbox/scripts/sct_resample.py", line 365, in <module>
    main()
  File "/Users/alzaia/spinalcordtoolbox/scripts/sct_resample.py", line 362, in main
    resample()
  File "/Users/alzaia/spinalcordtoolbox/scripts/sct_resample.py", line 109, in resample
    R[i, i] = n[i] / float(n_r[i])
ZeroDivisionError: float division by zero
`````

**Comment by alzaia** [comment]
data in foldersahred/sct_issue/20170106_issue1103

**Comment by alzaia** [comment]
Other bug for an other image same folder..
command:
````
sct_resample -i /Users/alzaia/ariane/test/multilabel_histo_seg_crop.nii.gz -f 0.5
````

````

Load data...
Traceback (most recent call last):
  File "/Users/alzaia/spinalcordtoolbox/scripts/sct_resample.py", line 365, in <module>
    main()
  File "/Users/alzaia/spinalcordtoolbox/scripts/sct_resample.py", line 362, in main
    resample()
  File "/Users/alzaia/spinalcordtoolbox/scripts/sct_resample.py", line 64, in resample
    nii = nipy.load_image(param.fname_data)
  File "/Users/alzaia/spinalcordtoolbox/python/lib/python2.7/site-packages/nipy/io/files.py", line 62, in load
    return nifti2nipy(ni_img)
  File "/Users/alzaia/spinalcordtoolbox/python/lib/python2.7/site-packages/nipy/io/nifti_ref.py", line 550, in nifti2nipy
    raise NiftiError("With less than 3 dimensions we cannot be sure "
nipy.io.nifti_ref.NiftiError: With less than 3 dimensions we cannot be sure which input and output dimensions
````

**Comment by alzaia** [comment]
Please assign for me, I don't have rights
