### ISSUE TITLE
issue when flag -init-centerline is used

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1159]
should check for it before starting the process and exit with message

~~~
sct_propseg -i t1.nii.gz -c t1 -init 10 -init-centerline viewer

--
Spinal Cord Toolbox ((detached/45ed20478c7f9919167af5cb3223638b9d9b10d5)
Running /Users/julien/code/sct/scripts/sct_propseg.py -i t1.nii.gz -c t1 -init 10 -init-centerline viewer

Create temporary folder...
sct_image -i "/Users/julien/temp/tom/t1.nii.gz" -o "tmp.170213094456_602876/tmp.t1_SAL.nii.gz" -setorient SAL -v 0 -init-centerline ./t1_mask_viewer.nii.gz -centerline-binary
Running /Users/julien/code/sct/scripts/sct_image.py -i /Users/julien/temp/tom/t1.nii.gz -o tmp.170213094456_602876/tmp.t1_SAL.nii.gz -setorient SAL -v 0 -init-centerline ./t1_mask_viewer.nii.gz -centerline-binary
ERROR: argument -init-centerline does not exist. See documentation.
Aborted...

DESCRIPTION
Perform manipulations on images (e.g., pad, change space, split along dimension). Inputs can be a
number, a 4d image, or several 3d images separated with ","

USAGE
sct_image -i <list of: file>

MANDATORY ARGUMENTS
-i <list of: file>           Input file(s). If several inputs: separate them by a coma without
white space.


OPTIONAL ARGUMENTS
-o <file_output>             Output file.

Basic image operations:
-pad <str>                   Pad 3d image. Specify padding as: "x,y,z" (in voxel)
-pad-asym <str>              Pad 3d image with asymmetric padding. Specify padding as:
"x_i,x_f,y_i,y_f,z_i,z_f" (in voxel)
-copy-header <file>          Copy the header of the input image (specified in -i) to the
destination image (specified here)
-split {x,y,z,t}             Split data along the specified dimension. The suffix _DIM+NUMBER will
be added to the intput file name.
-concat {x,y,z,t}            Concatenate data along the specified dimension
-type {uint8,int16,int32,float32,complex64,float64,int8,uint16,uint32,int64,uint64}Change file type

Orientation operations:
-getorient                   Get orientation of the input image
-setorient {RIP,LIP,RSP,LSP,RIA,LIA,RSA,LSA,IRP,ILP,SRP,SLP,IRA,ILA,SRA,SLA,RPI,LPI,RAI,LAI,RPS,LPS,RAS,LAS,PRI,PLI,ARI,ALI,PRS,PLS,ARS,ALS,IPR,SPR,IAR,SAR,IPL,SPL,IAL,SAL,PIR,PSR,AIR,ASR,PIL,PSL,AIL,ASL}Set orientation of the input image
-setorient-data {RIP,LIP,RSP,LSP,RIA,LIA,RSA,LSA,IRP,ILP,SRP,SLP,IRA,ILA,SRA,SLA,RPI,LPI,RAI,LAI,RPS,LPS,RAS,LAS,PRI,PLI,ARI,ALI,PRS,PLS,ARS,ALS,IPR,SPR,IAR,SAR,IPL,SPL,IAL,SAL,PIR,PSR,AIR,ASR,PIL,PSL,AIL,ASL}Set orientation of the input image's data. Use with care !ro

Multi-component operations on ITK composite warping fields:
-mcs                         Multi-component split: Split ITK warping field into three separate
displacement fields. The suffix _X, _Y and _Z will be added to the
input file name.
-omc                         Multi-component merge: Merge inputted images into one multi-component
image. Requires several inputs.

Warping field operations:
-display-warp                Create a grid and deform it using provided warping field.

Misc
-v {0,1,2}                   Verbose. 0: nothing. 1: basic. 2: extended. Default value = 1

Traceback (most recent call last):
File "/Users/julien/code/sct/scripts/sct_image.py", line 702, in <module>
main()
File "/Users/julien/code/sct/scripts/sct_image.py", line 126, in main
arguments = parser.parse(args)
File "/Users/julien/code/sct/scripts/msct_parser.py", line 374, in parse
self.usage.error("ERROR: argument "+arg+" does not exist. See documentation.")
File "/Users/julien/code/sct/scripts/msct_parser.py", line 567, in error
self.generate(error)
File "/Users/julien/code/sct/scripts/msct_parser.py", line 560, in generate
raise SyntaxError(error)
SyntaxError: ERROR: argument -init-centerline does not exist. See documentation.
Running /Users/julien/code/sct/scripts/sct_image.py -i /Users/julien/temp/tom/t1.nii.gz -o tmp.170213094456_602876/tmp.t1_SAL.nii.gz -setorient SAL -v 0 -init-centerline ./t1_mask_viewer.nii.gz -centerline-binary
ERROR: argument -init-centerline does not exist. See documentation.
Aborted...

DESCRIPTION
Perform manipulations on images (e.g., pad, change space, split along dimension). Inputs can be a
number, a 4d image, or several 3d images separated with ","

USAGE
sct_image -i <list of: file>

MANDATORY ARGUMENTS
-i <list of: file>           Input file(s). If several inputs: separate them by a coma without
white space.


OPTIONAL ARGUMENTS
-o <file_output>             Output file.

Basic image operations:
-pad <str>                   Pad 3d image. Specify padding as: "x,y,z" (in voxel)
-pad-asym <str>              Pad 3d image with asymmetric padding. Specify padding as:
"x_i,x_f,y_i,y_f,z_i,z_f" (in voxel)
-copy-header <file>          Copy the header of the input image (specified in -i) to the
destination image (specified here)
-split {x,y,z,t}             Split data along the specified dimension. The suffix _DIM+NUMBER will
be added to the intput file name.
-concat {x,y,z,t}            Concatenate data along the specified dimension
-type {uint8,int16,int32,float32,complex64,float64,int8,uint16,uint32,int64,uint64}Change file type

Orientation operations:
-getorient                   Get orientation of the input image
-setorient {RIP,LIP,RSP,LSP,RIA,LIA,RSA,LSA,IRP,ILP,SRP,SLP,IRA,ILA,SRA,SLA,RPI,LPI,RAI,LAI,RPS,LPS,RAS,LAS,PRI,PLI,ARI,ALI,PRS,PLS,ARS,ALS,IPR,SPR,IAR,SAR,IPL,SPL,IAL,SAL,PIR,PSR,AIR,ASR,PIL,PSL,AIL,ASL}Set orientation of the input image
-setorient-data {RIP,LIP,RSP,LSP,RIA,LIA,RSA,LSA,IRP,ILP,SRP,SLP,IRA,ILA,SRA,SLA,RPI,LPI,RAI,LAI,RPS,LPS,RAS,LAS,PRI,PLI,ARI,ALI,PRS,PLS,ARS,ALS,IPR,SPR,IAR,SAR,IPL,SPL,IAL,SAL,PIR,PSR,AIR,ASR,PIL,PSL,AIL,ASL}Set orientation of the input image's data. Use with care !ro

Multi-component operations on ITK composite warping fields:
-mcs                         Multi-component split: Split ITK warping field into three separate
displacement fields. The suffix _X, _Y and _Z will be added to the
input file name.
-omc                         Multi-component merge: Merge inputted images into one multi-component
image. Requires several inputs.

Warping field operations:
-display-warp                Create a grid and deform it using provided warping field.

Misc
-v {0,1,2}                   Verbose. 0: nothing. 1: basic. 2: extended. Default value = 1

Traceback (most recent call last):
File "/Users/julien/code/sct/scripts/sct_image.py", line 702, in <module>
main()
File "/Users/julien/code/sct/scripts/sct_image.py", line 126, in main
arguments = parser.parse(args)
File "/Users/julien/code/sct/scripts/msct_parser.py", line 374, in parse
self.usage.error("ERROR: argument "+arg+" does not exist. See documentation.")
File "/Users/julien/code/sct/scripts/msct_parser.py", line 567, in error
self.generate(error)
File "/Users/julien/code/sct/scripts/msct_parser.py", line 560, in generate
raise SyntaxError(error)
SyntaxError: ERROR: argument -init-centerline does not exist. See documentation.

ERROR: Automatic cord detection failed. Please initialize using -init-centerline or -init-mask (see help).

/Users/julien/code/sct/scripts/sct_propseg.pyNone
~~~

**Comment by jcohenadad** [comment]
actually, the error also appears with:
~~~
sct_propseg -i t2.nii.gz -c t2 -init-centerline viewer
~~~

the function sct_image is wrongly passing -init-centerline as argument: 
~~~
Running /Users/julien/code/sct/scripts/sct_image.py -i /Users/julien/temp/tom/t1.nii.gz -o tmp.170213094456_602876/tmp.t1_SAL.nii.gz -setorient SAL -v 0 -init-centerline ./t1_mask_viewer.nii.gz -centerline-binary
~~~

**Comment by benjamindeleener** [comment]
Oops, it has been introduced in commit 26ebdd9ff3cc84b411cc328e9c159e8bf836ecb7

I am working on it. Easy fix.
