### ISSUE TITLE
looking for -vertfile although argument is optional

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1172]
~~~
sct_segment_graymatter -i gre_FA07_WE.nii.gz -s gre_FA07_WE_seg.nii.gz 

--
Spinal Cord Toolbox (jca_newExampleData/b90feb22dc4881f83306003743ce4b474a76f1eb)
Running /Users/julien/code/sct/scripts/sct_segment_graymatter.py -i gre_FA07_WE.nii.gz -s gre_FA07_WE_seg.nii.gz
ERROR: -vertfile input file: "label/template/PAM50_levels.nii.gz" does not exist.
Aborted...

DESCRIPTION
Segmentation of the white and gray matter. The segmentation is based on a multi-atlas method that 
uses a dictionary of pre-segmented gray matter images (already included in SCT) and finds the most 
similar images for identifying the gray matter using label fusion approach. The model used by this 
method contains: a template of the white/gray matter segmentation along the cervical spinal cord, 
and a PCA reduced space to describe the variability of intensity in that template. This method was 
inspired from [Asman et al., Medical Image Analysis 2014] and features the following additions:
  - possibility to add information from vertebral levels for improved accuracy
  - intensity normalization of the image to segment (allows the segmentation of any kind of 
    contrast)
  - pre-registration based on non-linear transformations

USAGE
sct_segment_graymatter -i <file> -s <file>

MANDATORY ARGUMENTS
 -i <file>                    Image to segment              
 -s <file>                    Spinal cord segmentation      

OPTIONAL ARGUMENTS
 -vertfile <str>              Labels of vertebral levels. This could either be an image (e.g., 
                              label/template/PAM50_levels.nii.gz) or a text file that specifies 
                              "slice,level" at each line. Example:
                                0,3
                                1,3
                                2,4
                                3,4
                                4,4
                                 Default value = label/template/PAM50_levels.nii.gz
SEGMENTATION OPTIONS
 -denoising {0,1}             1: Adaptative denoising from F. Coupe algorithm, 0: no  WARNING: It 
                              affects the model you should use (if denoising is applied to the 
                              target, the model should have been computed with denoising too) 
                              Default value = 1
 -normalization {0,1}         Normalization of the target image's intensity using median intensity 
                              values of the WM and the GM, recomended with MT images or other types 
                              of contrast than T2* Default value = 1
 -p <str>                     Registration parameters to register the image to segment on the model 
                              data. Use the same format as for sct_register_to_template and 
                              sct_register_multimodal. Default value = 
                              step=1,type=seg,algo=centermassrot,metric
                              =MeanSquares,smooth=2,poly=0,iter=1:step=
                              2,type=seg,algo=columnwise,metric=MeanSquares,smooth=1,iter=1
 -w-levels <float>            Weight parameter on the level differences to compute the similarities 
                              Default value = 2.5
 -w-coordi <float>            Weight parameter on the euclidean distance (based on images 
                              coordinates in the reduced sapce) to compute the similarities  
                              Default value = 0.0065
 -thr-sim <float>             Threshold to select the dictionary slices most similar to the slice 
                              to segment (similarities are normalized to 1) Default value = 0.0005
 -model <folder>              Path to the computed model    

OUTPUT OTIONS
 -res-type {bin,prob}         Type of result segmentation : binary or probabilistic Default value = 
                              prob
 -ratio {0,slice,level}       Compute GM/WM CSA ratio by slice or by vertebral level (average 
                              across levels) Default value = 0
 -ref <file>                  Reference segmentation of the gray matter for segmentation validation 
                              --> output Dice coefficient and Hausdorff's and median distances)
 -ofolder <folder_creation>   Output folder Default value = ./
MISC
 -qc {0,1}                    Output images for quality control. Default value = 1
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   Verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1

Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_segment_graymatter.py", line 759, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_segment_graymatter.py", line 721, in main
    sct.printv(parser.usage.generate(error='ERROR: -vertfile input file: "'+arguments['-vertfile']+'" does not exist.'))
  File "/Users/julien/code/sct/scripts/msct_parser.py", line 560, in generate
    raise SyntaxError(error)
SyntaxError: ERROR: -vertfile input file: "label/template/PAM50_levels.nii.gz" does not exist.
~~~

**Comment by SaraDupont** [comment]
Fixed in PR #1173
