### ISSUE TITLE
itk::ERROR: MultiThreader(0x19fe6f0): Exception occurred during SingleMethodExecute while ApproximateSignedDistanceMap

### ISSUE THREAD

**Issue by ramidas** [neuropoly/spinalcordtoolbox#1185]

**Comment by peristeri** [comment]
@ramidas can you described the command that caused the error? and also add the details of the environment? (linux or mac, and the contains of version.txt)

**Comment by peristeri** [comment]
This code:
```python
(...)
def reduce_image(args):
     cm, _ = readCmap(args.cmap_file)
     cm = (cm != 0).astype(np.int8)
     img = itk.GetImageFromArray(cm)                                                                                               
     distances = itk.ApproximateSignedDistanceMap(img)
(…)
```
produces this bug:

```
Traceback (most recent call last):
  File "./redukcja.py", line 28, in <module>
    main()
  File "./redukcja.py", line 24, in main
    reduce_image(args)
  File "./redukcja.py", line 16, in reduce_image
    distances = itk.ApproximateSignedDistanceMap(img)
  File "/home/michal/.local/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 11723, in ApproximateSignedDistanceMap
    return _SimpleITK.ApproximateSignedDistanceMap(image1, insideValue, outsideValue)
RuntimeError: Exception thrown in SimpleITK ApproximateSignedDistanceMap: /tmp/SimpleITK-build/ITK/Modules/Core/Common/src/itkMultiThreader.cxx:416:
itk::ERROR: MultiThreader(0x19fe6f0): Exception occurred during SingleMethodExecute
cm variable is 3D binary numpy array```

But this code is not part of the spicalcordtoolbox. I don't see how SCT is impacted, therefore closing this issue.
