### ISSUE TITLE
IndexError when using flag -vert (or -l, which is deprecated)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1191]
to avoid this:
~~~
sct_process_segmentation -i t2s_segm.nii.gz -p csa -size 0 -l 1:7


--

Spinal Cord Toolbox (master/4159bcacd16124ed920d90bd2696299a287bc987)

Running /Users/almartin/sct/scripts/sct_process_segmentation.py -i t2s_segm.nii.gz -p csa -size 0 -l 1:7

WARNING : -l is a deprecated argument and will no longer be updated in future versions. Changing argument to -vert.


Check parameters:

.. segmentation file:             t2s_segm.nii.gz


Create temporary folder...

mkdir tmp.170302082521_807481/


Copying input data to tmp folder and convert to nii...

sct_convert -i /Users/almartin/Documents/mr_data/e23242/t2s/t2s_segm.nii.gz -o tmp.170302082521_807481/segmentation.nii.gz


Change orientation to RPI...

sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz


Open segmentation volume...


Get data dimensions...

  107 x 105 x 12


Smooth centerline/segmentation...

.. Get center of mass of the centerline/segmentation...

.. Computing physical coordinates of centerline/segmentation...

.. Smoothing algo = nurbs

/Users/almartin/sct/scripts/msct_smooth.py:279: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.

  if z == None:


Fitting centerline using B-spline approximation...

Test: # of control points = 5

Error on approximation = 0.2 mm

Test: # of control points = 6

WARNING: NURBS instability -> wrong reconstruction

Test: # of control points = 7

WARNING: NURBS instability -> wrong reconstruction

Test: # of control points = 8

Error on approximation = 0.03 mm

Test: # of control points = 9

Error on approximation = 0.01 mm

Test: # of control points = 10

Error on approximation = 0.14 mm

Test: # of control points = 11

Error on approximation = 1.13 mm

The fitting of the curve was done using  9  control points: the number that gave the best results. 

Error on approximation = 0.01 mm

/Users/almartin/sct/scripts/msct_image.py:780: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.

  if coordi != None:


Compute CSA...


Smooth CSA across slices...

.. No smoothing!


Create volume of CSA values...


Create volume of angle values...

sct_image -i csa_volume_RPI.nii.gz -setorient RPI -o csa_volume_in_initial_orientation.nii.gz

sct_image -i angle_volume_RPI.nii.gz -setorient RPI -o angle_volume_in_initial_orientation.nii.gz


Generate output files...

  WARNING: File /Users/almartin/Documents/mr_data/e23242/t2s/csa_image.nii.gz already exists. Deleting it...

  File created: /Users/almartin/Documents/mr_data/e23242/t2s/csa_image.nii.gz

  WARNING: File /Users/almartin/Documents/mr_data/e23242/t2s/angle_image.nii.gz already exists. Deleting it...

  File created: /Users/almartin/Documents/mr_data/e23242/t2s/angle_image.nii.gz



Display CSA per slice:

z = 0, CSA = 90.203696 mm^2, Angle = 10.851835 deg

z = 1, CSA = 79.904919 mm^2, Angle = 6.384153 deg

z = 2, CSA = 98.222682 mm^2, Angle = 5.705674 deg

z = 3, CSA = 82.473333 mm^2, Angle = 4.168136 deg

z = 4, CSA = 88.225493 mm^2, Angle = 2.880155 deg

z = 5, CSA = 88.020798 mm^2, Angle = 0.911656 deg

z = 6, CSA = 90.916242 mm^2, Angle = 1.023173 deg

z = 7, CSA = 89.958422 mm^2, Angle = 2.037465 deg

z = 8, CSA = 87.843971 mm^2, Angle = 1.626386 deg

z = 9, CSA = 90.442237 mm^2, Angle = 1.495058 deg

z = 10, CSA = 90.619624 mm^2, Angle = 0.658208 deg

z = 11, CSA = 89.020103 mm^2, Angle = 7.852606 deg

Save results in: /Users/almartin/Documents/mr_data/e23242/t2s/csa_per_slice.txt


Save results in: /Users/almartin/Documents/mr_data/e23242/t2s/csa_per_slice.pickle


Selected vertebral levels... 1:7

  OK: ./label/template/PAM50_levels.nii.gz

Find slices corresponding to vertebral levels based on the centerline...

Traceback (most recent call last):

  File "/Users/almartin/sct/scripts/sct_process_segmentation.py", line 1236, in <module>

    main(sys.argv[1:])

  File "/Users/almartin/sct/scripts/sct_process_segmentation.py", line 255, in main

    compute_csa(fname_segmentation, output_folder, overwrite, verbose, remove_temp_files, step, smoothing_param, figure_fit, slices, vert_lev, fname_vertebral_labeling, algo_fitting=param.algo_fitting, type_window=param.type_window, window_length=param.window_length, angle_correction=angle_correction, use_phys_coord=use_phys_coord)

  File "/Users/almartin/sct/scripts/sct_process_segmentation.py", line 820, in compute_csa

    slices, vert_levels_list, warning = get_slices_matching_with_vertebral_levels_based_centerline(vert_levels, im_vertebral_labeling.data, z_centerline)

  File "/Users/almartin/sct/scripts/sct_process_segmentation.py", line 1113, in get_slices_matching_with_vertebral_levels_based_centerline

    vertebral_labeling_slice_zz = vertebral_labeling_data[:, :, int(zz)]

IndexError: index -61 is out of bounds for axis 2 with size 12
~~~

**Comment by peristeri** [comment]
I can't seam to reproduce the error. Do we have access to the files that caused the error?

**Comment by jcohenadad** [comment]
actually, the existence of file is checked (see "OK: ./label/template/PAM50_levels.nii.gz"). however the error is probably due to index error, and should be managed in a better way.
you can try to reproduce by asking for levels that are not in the input image.
