### ISSUE TITLE
wrong calculation of CSA and sometimes IndexError

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1202]
sct_example_data/t1

~~~
sct_process_segmentation -i t1_seg.nii.gz -p csa -vert 3:4

--
Spinal Cord Toolbox (jca_newExampleData/8ce411597f5587aef407eea2ccdbf457ad109942)
Running /Users/julien/code/sct/scripts/sct_process_segmentation.py -i t1_seg.nii.gz -p csa -vert 3:4

Check parameters:
.. segmentation file:             t1_seg.nii.gz

Create temporary folder...
mkdir tmp.170310085548_750385/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/sct_example_data/t1/t1_seg.nii.gz -o tmp.170310085548_750385/segmentation.nii.gz

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
  192 x 240 x 320

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = nurbs
/Users/julien/code/sct/scripts/msct_smooth.py:279: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if z == None:

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 0.36 mm
Test: # of control points = 6
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 7
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 8
Error on approximation = 0.03 mm
Test: # of control points = 9
Error on approximation = 0.02 mm
Test: # of control points = 10
Error on approximation = 0.01 mm
Test: # of control points = 11
Error on approximation = 0.01 mm
Number of control points of the optimal NURBS = 11
/Users/julien/code/sct/scripts/msct_image.py:780: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if coordi != None:

Compute CSA...

Smooth CSA across slices...
.. No smoothing!

Create volume of CSA values...

Create volume of angle values...
sct_image -i csa_volume_RPI.nii.gz -setorient AIL -o csa_volume_in_initial_orientation.nii.gz
sct_image -i angle_volume_RPI.nii.gz -setorient AIL -o angle_volume_in_initial_orientation.nii.gz

Generate output files...
  WARNING: File /Users/julien/sct_example_data/t1/csa_image.nii.gz already exists. Deleting it...
  File created: /Users/julien/sct_example_data/t1/csa_image.nii.gz
  WARNING: File /Users/julien/sct_example_data/t1/angle_image.nii.gz already exists. Deleting it...
  File created: /Users/julien/sct_example_data/t1/angle_image.nii.gz


Display CSA per slice:
z = 0, CSA = 54.390800 mm^2, Angle = 13.768739 deg
z = 1, CSA = 55.341703 mm^2, Angle = 13.854472 deg
z = 2, CSA = 54.342543 mm^2, Angle = 13.974676 deg
z = 3, CSA = 56.253989 mm^2, Angle = 14.094275 deg
z = 4, CSA = 55.253679 mm^2, Angle = 14.219271 deg
z = 5, CSA = 56.191493 mm^2, Angle = 14.345602 deg
z = 6, CSA = 57.128717 mm^2, Angle = 14.468913 deg
z = 7, CSA = 57.096140 mm^2, Angle = 14.594995 deg
z = 8, CSA = 56.096582 mm^2, Angle = 14.719248 deg
z = 9, CSA = 57.998624 mm^2, Angle = 14.840241 deg
z = 10, CSA = 56.035059 mm^2, Angle = 14.956575 deg
z = 11, CSA = 57.938249 mm^2, Angle = 15.063699 deg
z = 12, CSA = 58.875512 mm^2, Angle = 15.165909 deg
z = 13, CSA = 59.814376 mm^2, Angle = 15.258565 deg
z = 14, CSA = 56.898063 mm^2, Angle = 15.339786 deg
z = 15, CSA = 62.663735 mm^2, Angle = 15.408183 deg
z = 16, CSA = 59.756392 mm^2, Angle = 15.460861 deg
z = 17, CSA = 58.781598 mm^2, Angle = 15.499506 deg
z = 18, CSA = 60.702336 mm^2, Angle = 15.521706 deg
z = 19, CSA = 61.664425 mm^2, Angle = 15.526523 deg
z = 20, CSA = 58.777068 mm^2, Angle = 15.515422 deg
z = 21, CSA = 61.672830 mm^2, Angle = 15.498390 deg
z = 22, CSA = 61.678365 mm^2, Angle = 15.479835 deg
z = 23, CSA = 59.756748 mm^2, Angle = 15.459627 deg
z = 24, CSA = 61.690910 mm^2, Angle = 15.437699 deg
z = 25, CSA = 61.697777 mm^2, Angle = 15.414586 deg
z = 26, CSA = 59.777102 mm^2, Angle = 15.388906 deg
z = 27, CSA = 58.820775 mm^2, Angle = 15.361203 deg
z = 28, CSA = 57.864777 mm^2, Angle = 15.331337 deg
z = 29, CSA = 61.731895 mm^2, Angle = 15.299254 deg
z = 30, CSA = 61.741748 mm^2, Angle = 15.265788 deg
z = 31, CSA = 62.717443 mm^2, Angle = 15.228985 deg
z = 32, CSA = 63.694202 mm^2, Angle = 15.189688 deg
z = 33, CSA = 66.602606 mm^2, Angle = 15.147757 deg
z = 34, CSA = 62.754789 mm^2, Angle = 15.103155 deg
z = 35, CSA = 65.665802 mm^2, Angle = 15.055745 deg
z = 36, CSA = 65.681267 mm^2, Angle = 15.005497 deg
z = 37, CSA = 65.697136 mm^2, Angle = 14.953769 deg
z = 38, CSA = 65.714302 mm^2, Angle = 14.897613 deg
z = 39, CSA = 66.698988 mm^2, Angle = 14.838394 deg
z = 40, CSA = 67.684581 mm^2, Angle = 14.777733 deg
z = 41, CSA = 68.672174 mm^2, Angle = 14.712196 deg
z = 42, CSA = 67.726252 mm^2, Angle = 14.643416 deg
z = 43, CSA = 69.683513 mm^2, Angle = 14.573290 deg
z = 44, CSA = 69.707297 mm^2, Angle = 14.497881 deg
z = 45, CSA = 71.669013 mm^2, Angle = 14.419106 deg
z = 46, CSA = 73.633106 mm^2, Angle = 14.336852 deg
z = 47, CSA = 71.723324 mm^2, Angle = 14.249256 deg
z = 48, CSA = 74.661910 mm^2, Angle = 14.155590 deg
z = 49, CSA = 76.635595 mm^2, Angle = 14.053165 deg
z = 50, CSA = 73.762149 mm^2, Angle = 13.938560 deg
z = 51, CSA = 77.685921 mm^2, Angle = 13.814470 deg
z = 52, CSA = 77.729096 mm^2, Angle = 13.684368 deg
z = 53, CSA = 75.831836 mm^2, Angle = 13.540902 deg
z = 54, CSA = 74.907608 mm^2, Angle = 13.387583 deg
z = 55, CSA = 75.930212 mm^2, Angle = 13.228734 deg
z = 56, CSA = 79.878881 mm^2, Angle = 13.060322 deg
z = 57, CSA = 78.962855 mm^2, Angle = 12.877172 deg
z = 58, CSA = 79.023287 mm^2, Angle = 12.683938 deg
z = 59, CSA = 79.084225 mm^2, Angle = 12.486108 deg
z = 60, CSA = 82.078489 mm^2, Angle = 12.278653 deg
z = 61, CSA = 83.123493 mm^2, Angle = 12.061615 deg
z = 62, CSA = 85.152578 mm^2, Angle = 11.828579 deg
z = 63, CSA = 83.268170 mm^2, Angle = 11.585666 deg
z = 64, CSA = 81.379695 mm^2, Angle = 11.339818 deg
z = 65, CSA = 85.376909 mm^2, Angle = 11.084777 deg
z = 66, CSA = 85.453096 mm^2, Angle = 10.820698 deg
z = 67, CSA = 86.513034 mm^2, Angle = 10.547761 deg
z = 68, CSA = 86.591159 mm^2, Angle = 10.266167 deg
z = 69, CSA = 83.714798 mm^2, Angle = 9.976142 deg
z = 70, CSA = 86.747569 mm^2, Angle = 9.678090 deg
z = 71, CSA = 84.850614 mm^2, Angle = 9.377912 deg
z = 72, CSA = 86.896594 mm^2, Angle = 9.082779 deg
z = 73, CSA = 85.977459 mm^2, Angle = 8.793153 deg
z = 74, CSA = 87.031342 mm^2, Angle = 8.509045 deg
z = 75, CSA = 83.134820 mm^2, Angle = 8.230470 deg
z = 76, CSA = 85.171921 mm^2, Angle = 7.957440 deg
z = 77, CSA = 86.217577 mm^2, Angle = 7.689971 deg
z = 78, CSA = 88.253106 mm^2, Angle = 7.428076 deg
z = 79, CSA = 89.295869 mm^2, Angle = 7.171773 deg
z = 80, CSA = 88.351464 mm^2, Angle = 6.921078 deg
z = 81, CSA = 89.388521 mm^2, Angle = 6.682720 deg
z = 82, CSA = 89.430368 mm^2, Angle = 6.449751 deg
z = 83, CSA = 91.459163 mm^2, Angle = 6.215697 deg
z = 84, CSA = 89.509046 mm^2, Angle = 5.987348 deg
z = 85, CSA = 88.549902 mm^2, Angle = 5.764736 deg
z = 86, CSA = 89.578415 mm^2, Angle = 5.547897 deg
z = 87, CSA = 90.605519 mm^2, Angle = 5.336875 deg
z = 88, CSA = 90.634450 mm^2, Angle = 5.137313 deg
z = 89, CSA = 91.657790 mm^2, Angle = 4.943391 deg
z = 90, CSA = 90.687487 mm^2, Angle = 4.749800 deg
z = 91, CSA = 89.714835 mm^2, Angle = 4.562254 deg
z = 92, CSA = 86.745818 mm^2, Angle = 4.380832 deg
z = 93, CSA = 88.759806 mm^2, Angle = 4.210379 deg
z = 94, CSA = 88.778243 mm^2, Angle = 4.045490 deg
z = 95, CSA = 88.796709 mm^2, Angle = 3.873325 deg
z = 96, CSA = 90.811189 mm^2, Angle = 3.691525 deg
z = 97, CSA = 90.830209 mm^2, Angle = 3.500591 deg
z = 98, CSA = 90.848450 mm^2, Angle = 3.307156 deg
z = 99, CSA = 88.869177 mm^2, Angle = 3.106970 deg
z = 100, CSA = 89.885093 mm^2, Angle = 2.895580 deg
z = 101, CSA = 90.900439 mm^2, Angle = 2.680414 deg
z = 102, CSA = 91.914947 mm^2, Angle = 2.463890 deg
z = 103, CSA = 90.929519 mm^2, Angle = 2.255176 deg
z = 104, CSA = 91.940992 mm^2, Angle = 2.052220 deg
z = 105, CSA = 91.951762 mm^2, Angle = 1.855484 deg
z = 106, CSA = 89.961347 mm^2, Angle = 1.679276 deg
z = 107, CSA = 90.967200 mm^2, Angle = 1.538397 deg
z = 108, CSA = 88.971884 mm^2, Angle = 1.440223 deg
z = 109, CSA = 86.974140 mm^2, Angle = 1.397018 deg
z = 110, CSA = 86.973249 mm^2, Angle = 1.420874 deg
z = 111, CSA = 87.969527 mm^2, Angle = 1.507878 deg
z = 112, CSA = 88.963113 mm^2, Angle = 1.649650 deg
z = 113, CSA = 88.954079 mm^2, Angle = 1.840632 deg
z = 114, CSA = 86.943461 mm^2, Angle = 2.065741 deg
z = 115, CSA = 84.930594 mm^2, Angle = 2.315567 deg
z = 116, CSA = 84.914137 mm^2, Angle = 2.575536 deg
z = 117, CSA = 83.896272 mm^2, Angle = 2.847680 deg
z = 118, CSA = 84.872650 mm^2, Angle = 3.136765 deg
z = 119, CSA = 85.845723 mm^2, Angle = 3.432449 deg
z = 120, CSA = 85.818671 mm^2, Angle = 3.721335 deg
z = 121, CSA = 84.792520 mm^2, Angle = 4.004095 deg
z = 122, CSA = 84.762189 mm^2, Angle = 4.286923 deg
z = 123, CSA = 83.733996 mm^2, Angle = 4.560961 deg
z = 124, CSA = 82.705760 mm^2, Angle = 4.825893 deg
z = 125, CSA = 80.682502 mm^2, Angle = 5.074671 deg
z = 126, CSA = 80.651783 mm^2, Angle = 5.314662 deg
z = 127, CSA = 83.605857 mm^2, Angle = 5.552581 deg
z = 128, CSA = 84.567620 mm^2, Angle = 5.781563 deg
z = 129, CSA = 85.528599 mm^2, Angle = 6.001813 deg
z = 130, CSA = 85.494782 mm^2, Angle = 6.213559 deg
z = 131, CSA = 85.461185 mm^2, Angle = 6.417049 deg
z = 132, CSA = 81.455374 mm^2, Angle = 6.607247 deg
z = 133, CSA = 82.417843 mm^2, Angle = 6.790050 deg
z = 134, CSA = 83.379097 mm^2, Angle = 6.970722 deg
z = 135, CSA = 83.347857 mm^2, Angle = 7.144156 deg
z = 136, CSA = 84.309027 mm^2, Angle = 7.310606 deg
z = 137, CSA = 84.278548 mm^2, Angle = 7.470324 deg
z = 138, CSA = 83.257531 mm^2, Angle = 7.623554 deg
z = 139, CSA = 84.219488 mm^2, Angle = 7.770534 deg
z = 140, CSA = 82.209995 mm^2, Angle = 7.911496 deg
z = 141, CSA = 82.182814 mm^2, Angle = 8.046666 deg
z = 142, CSA = 83.146160 mm^2, Angle = 8.176262 deg
z = 143, CSA = 82.131239 mm^2, Angle = 8.297137 deg
z = 144, CSA = 82.106833 mm^2, Angle = 8.413084 deg
z = 145, CSA = 82.082426 mm^2, Angle = 8.527467 deg
z = 146, CSA = 83.047392 mm^2, Angle = 8.637070 deg
z = 147, CSA = 84.012516 mm^2, Angle = 8.742077 deg
z = 148, CSA = 86.954048 mm^2, Angle = 8.842668 deg
z = 149, CSA = 83.967622 mm^2, Angle = 8.938983 deg
z = 150, CSA = 84.934061 mm^2, Angle = 9.030340 deg
z = 151, CSA = 86.888766 mm^2, Angle = 9.115008 deg
z = 152, CSA = 90.818655 mm^2, Angle = 9.191745 deg
z = 153, CSA = 88.827144 mm^2, Angle = 9.260013 deg
z = 154, CSA = 88.811971 mm^2, Angle = 9.319849 deg
z = 155, CSA = 90.772050 mm^2, Angle = 9.371700 deg
z = 156, CSA = 94.706476 mm^2, Angle = 9.416254 deg
z = 157, CSA = 96.668857 mm^2, Angle = 9.454309 deg
z = 158, CSA = 101.591366 mm^2, Angle = 9.486680 deg
z = 159, CSA = 102.569463 mm^2, Angle = 9.514141 deg
z = 160, CSA = 110.451899 mm^2, Angle = 9.537395 deg
z = 161, CSA = 115.376125 mm^2, Angle = 9.557065 deg
z = 162, CSA = 117.342630 mm^2, Angle = 9.573688 deg
z = 163, CSA = 120.295873 mm^2, Angle = 9.587725 deg
z = 164, CSA = 126.207763 mm^2, Angle = 9.599275 deg
z = 165, CSA = 135.077854 mm^2, Angle = 9.609032 deg
z = 166, CSA = 141.976668 mm^2, Angle = 9.616118 deg
Save results in: /Users/julien/sct_example_data/t1/csa_per_slice.txt

Save results in: /Users/julien/sct_example_data/t1/csa_per_slice.pickle

Selected vertebral levels... 3:4
  OK: ./label/template/PAM50_levels.nii.gz
	Find slices corresponding to vertebral levels based on the centerline...
Mean CSA: 0.0 +/- 0.0 mm^2
Mean angle: 0.0 +/- 0.0 degrees
Save results in: /Users/julien/sct_example_data/t1/csa_mean.txt

Save results in: /Users/julien/sct_example_data/t1/angle_mean.txt

Volume in between the selected slices: 0.0 mm^3
Save results in: /Users/julien/sct_example_data/t1/csa_volume.txt


Remove temporary files...
rm -rf tmp.170310085548_750385/

Output a nifti file of CSA values along the segmentation: /Users/julien/sct_example_data/t1/csa_image.nii.gz
Output result text file of CSA per slice: /Users/julien/sct_example_data/t1/csa_per_slice.txt
Output result files of the mean CSA across the selected slices: 
		/Users/julien/sct_example_data/t1/csa_mean.txt
		/Users/julien/sct_example_data/t1/csa_mean.xls
		/Users/julien/sct_example_data/t1/csa_mean.pickle
Output result files of the volume in between the selected slices: 
		/Users/julien/sct_example_data/t1/csa_volume.txt
		/Users/julien/sct_example_data/t1/csa_volume.xls
		/Users/julien/sct_example_data/t1/csa_volume.pickle
~~~

In some other images, I get the following error:
~~~
z = 175, CSA = 101.109852 mm^2, Angle = 34.711136 deg
z = 176, CSA = 74.046867 mm^2, Angle = 54.655411 deg
z = 177, CSA = 16.305138 mm^2, Angle = 69.239622 deg
Save results in: /Users/julien/data/temp/sct_013/t1/csa_per_slice.txt

Save results in: /Users/julien/data/temp/sct_013/t1/csa_per_slice.pickle

Selected vertebral levels... 3:4
  OK: ./label/template/PAM50_levels.nii.gz
	Find slices corresponding to vertebral levels based on the centerline...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 1226, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 247, in main
    compute_csa(fname_segmentation, output_folder, overwrite, verbose, remove_temp_files, step, smoothing_param, figure_fit, slices, vert_lev, fname_vertebral_labeling, algo_fitting=param.algo_fitting, type_window=param.type_window, window_length=param.window_length, angle_correction=angle_correction, use_phys_coord=use_phys_coord)
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 812, in compute_csa
    slices, vert_levels_list, warning = get_slices_matching_with_vertebral_levels_based_centerline(vert_levels, im_vertebral_labeling.data, z_centerline)
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 1105, in get_slices_matching_with_vertebral_levels_based_centerline
    for idx, z_slice in enumerate(vertebral_labeling_data.T[z_centerline,:,:]):
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
~~~

**Comment by peristeri** [comment]
The error comes from z_centerline is not of the right type. The z_centerline is a ndarray with no dtype assigned. In most cases, python will "guess" the right and set it to int, but there's occasions where it will set it to a float value.

Suggestion: Set the type when defining the variable, it is explicit and easier to debug:
```python
z_conterline = np.asarray(coordinates, dtype=int)
```
