### ISSUE TITLE
NameError: global name 'Coordinate' is not defined

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1218]
bug seems to have been introduced by https://github.com/neuropoly/spinalcordtoolbox/pull/1157

THIS BUG IS ONLY PRESENT IN DEVEL (NOT MASTER)

~~~
sct_propseg -i t2s.nii.gz -init-centerline viewer -c t2

--
Spinal Cord Toolbox (master/a89a752661582a551e1ce46ebf38b90b32988443)
Running /Users/julien/code/sct/scripts/sct_propseg.py -i t2s.nii.gz -init-centerline viewer -c t2

Create temporary folder...
sct_image -i /Users/julien/data/caterina/20170320_Russell/data/MS079_R01_11/t2s_sup/t2s.nii.gz -o tmp.170321170925_65467/tmp.t2s_SAL.nii.gz -setorient SAL -v 0
/Users/julien/data/caterina/20170320_Russell/data/MS079_R01_11/t2s_sup/t2s.nii.gz
WARNING: File /Users/julien/data/caterina/20170320_Russell/data/MS079_R01_11/t2s_sup/t2s.nii.gz already exists. Deleting it.
Traceback (most recent call last):
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1903, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 188, in on_press
    self.viewer.on_press(event, self)
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 670, in on_press
    self.current_point = Coordinate(point)
NameError: global name 'Coordinate' is not defined
~~~

**Comment by jcohenadad** [comment]
in sct_viewer: line 670: replace
~~~
self.current_point = Coordinate(point)
~~~
with
~~~
self.current_point = msct_types.Coordinate(point)
~~~

**Comment by zougloub** [comment]
Took a look, `from msct_types import *` is used now so this can be closed.
