### ISSUE TITLE
[EXTRACT_METRIC] bug in option -output-map

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1241]
Command:
````
sct_extract_metric -i register/FitResults/Dh_reg.nii -f template_roi/atlas/ -method map -overwrite 0 -output-map test.nii.gz
````
BUG:
````
Traceback (most recent call last):
  File "/autofs/cluster/msilab/users/tools/Spine/SpinalCordToolbox/scripts/sct_extract_metric.py", line 1319, in <module>
    main(fname_data, path_label, method, slices_of_interest, vertebral_levels, fname_output, labels_user, overwrite, fname_normalizing_label, normalization_method, label_to_fix, adv_param_user, fname_output_metric_map, fname_mask_weight)
  File "/autofs/cluster/msilab/users/tools/Spine/SpinalCordToolbox/scripts/sct_extract_metric.py", line 428, in main
    data_metric_map = generate_metric_value_map(fname_output_metric_map, input_im, labels, indiv_labels_value, slices_list, label_to_fix, label_to_fix_fract_vol)
UnboundLocalError: local variable 'slices_list' referenced before assignment

````

**Comment by tanguyduval** [comment]
Note that the metric_label.txt is correctly estimated

**Comment by slevyrosetti** [comment]
@tanguyduval: Could you share the data too please?

Thanks!

Le jeu. 6 avr. 2017 à 15:18, tanguyduval <notifications@github.com> a
écrit :

**Comment by jcohenadad** [comment]
@tanguyduval: could you please point me to the data-- thanks

**Comment by tanguyduval** [comment]
data on folder shared.
command:
`sct_extract_metric -i Dh_reg.nii -f atlas/ -method map -overwrite 1 -output-map test.nii.gz`
