### ISSUE TITLE
ValueError: array of sample points is empty

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1330]
### Description

Error when using init-centerline viewer or init-centerline XXX.

### Steps to Reproduce

1. data: **20170516_issue1330**
2. command: ```sct_propseg -i t2.nii.gz -c t1 -init-centerline t2_mask_viewer.nii.gz ```

**Expected behavior:** Segmentation

**Actual behavior:** Segmentation created, but empty and exit with error.

### Versions

master/4d453e11c5f10e11a8ef8acc1b2979bb285dc5d7

### Additional Information

~~~
sct_propseg -i t2.nii.gz -c t1 -init-centerline t2_mask_viewer.nii.gz 

--
Spinal Cord Toolbox (master/4d453e11c5f10e11a8ef8acc1b2979bb285dc5d7)
Running /Users/julien/code/sct/scripts/sct_propseg.py -i t2.nii.gz -c t1 -init-centerline t2_mask_viewer.nii.gz
isct_propseg -i "/Users/julien/Desktop/chiba_sct-users_GE/t2/t2.nii.gz" -t t1 -o "./" -verbose -init-centerline t2_mask_viewer.nii.gz -centerline-binary
Initialization - using given centerline
Total propagation length = 116.74 mm

Segmentation finished. To view results, type:
fslview /Users/julien/Desktop/chiba_sct-users_GE/t2/t2.nii.gz ./t2_seg.nii.gz &

Check consistency of segmentation...

Create temporary folder...
sct_image -i tmp.segmentation.nii.gz -setorient RPI -o tmp.segmentation_RPI.nii.gz
Running /Users/julien/code/sct/scripts/sct_image.py -i tmp.segmentation.nii.gz -setorient RPI -o tmp.segmentation_RPI.nii.gz
tmp.segmentation.nii.gz

Get dimensions of data...
260 x 512 x 512 x 1

Change orientation...

Generate output files...
WARNING: File tmp.segmentation_RPI.nii.gz already exists. Deleting it.
Created file(s):
--> tmp.segmentation_RPI.nii.gz

sct_image -i tmp.centerline.nii.gz -setorient RPI -o tmp.centerline_RPI.nii.gz
Running /Users/julien/code/sct/scripts/sct_image.py -i tmp.centerline.nii.gz -setorient RPI -o tmp.centerline_RPI.nii.gz
tmp.centerline.nii.gz

Get dimensions of data...
260 x 512 x 512 x 1

Change orientation...

Generate output files...
WARNING: File tmp.centerline_RPI.nii.gz already exists. Deleting it.
Created file(s):
--> tmp.centerline_RPI.nii.gz


Get data dimensions...
sct_image -i tmp.segmentation_RPI_c.nii.gz -setorient RPI -o ../t2_seg.nii.gz
Running /Users/julien/code/sct/scripts/sct_image.py -i tmp.segmentation_RPI_c.nii.gz -setorient RPI -o ../t2_seg.nii.gz
tmp.segmentation_RPI_c.nii.gz

Get dimensions of data...
260 x 512 x 512 x 1

Change orientation...
rm -f tmp.segmentation_RPI_c_RPI.nii.gz

Generate output files...
WARNING: File ../t2_seg.nii.gz already exists. Deleting it.
Created file(s):
--> ../t2_seg.nii.gz


Remove temporary files...
WARNING: File t2_seg.nii.gz already exists. Deleting it.

Remove temporary files...
Traceback (most recent call last):
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file slice.py, line 229
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_propseg.py", line 595, in <module>
    test(qcslice.Axial(fname_input_data, fname_seg))
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/qc.py", line 160, in wrapped_f
    img, mask = func(sct_slice, *args)
  File "/Users/julien/code/sct/scripts/sct_propseg.py", line 593, in test
    return qslice.mosaic()
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/slice.py", line 262, in mosaic
    centers_x, centers_y = self.get_center()
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/slice.py", line 319, in get_center
    return self._axial_center(self.image_seg)
  File "/Users/julien/code/sct/spinalcordtoolbox/reports/slice.py", line 230, in _axial_center
    raise err
ValueError: array of sample points is empty
~~~

**Comment by benjamindeleener** [comment]
There are three different issues here:
(1) empty segmentation
(2) centerline generation from sparse points
(3) the exit error

Discussion about these two issues:
(1) empty segmentation
The segmentation is empty because the image contrast is quite bad, and the segmentation algorithm simply fails at segmenting the spinal cord properly.
Note that the segmentation was not empty initially (though it was bad), but the correction algorithm (line with `Check consistency of segmentation...`) erased it. This is quite an isolated user case and I am not sure if fixing it is worth it, given the new tools that @charleygros developed (`sct_deepseg_sc`).

(2) centerline generation from points
The centerline that is generated by PropSeg using the provided mask does not cover the full spinal cord, while the provided points do. The centerline generation seems currently made by `isct_propseg` and is less reliable than the recent tools in `sct_process_segmentation`. I would suggest the following change:
- when provided a centerline that is not continuous, instead of providing the mask (with only a few points) to `isct_propseg`, we process the mask with `sct_process_segmentation -i t2_mask_viewer.nii.gz -p centerline` and provide the resulting centerline file `t2_mask_viewer_centerline.nii.gz` to `isct_propseg`.
- when using the viewer with `-init-centerline viewer`, the resulting file that is sent to `isct_propseg` should be a continuous centerline.
The floor is open to discussion.

(2) the exit error
This error is related to the QC generation, which I cannot reproduce with the current version of SCT. Therefore, I'll assume that it is fixed.

**Comment by jcohenadad** [comment]
ok, i suggest we close this issue then.

**Comment by benjamindeleener** [comment]
This issue was closed based on a consensus at a SCT meeting, based on the fact that this issue is an isolated case.
