### ISSUE TITLE
AttributeError: 'str' object has no attribute 'change_orientation'

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1335]
data: 20170519_issue1335

~~~
sct_propseg -i mt0.nii.gz -c t2s -qc ~/qc_test1

--
Spinal Cord Toolbox (master/5f1beeea11d952cc36ad0c40b1cebd600e4ee21e)
Running /Users/julien/code/sct/scripts/sct_propseg.py -i mt0.nii.gz -c t2s -qc /Users/julien/qc_test1
Check folder existence...
Detecting the spinal cord using OptiC
isct_propseg -i "/Users/julien/data/temp/mt/mt0.nii.gz" -t t2 -o "./" -verbose -init-centerline ./mt0_centerline_optic.nii.gz -centerline-binary
Initialization - using given centerline
Total propagation length = 110.967 mm

Segmentation finished. To view results, type:
fslview /Users/julien/data/temp/mt/mt0.nii.gz ./mt0_seg.nii.gz &

Check consistency of segmentation...

Create temporary folder...
sct_image -i tmp.segmentation.nii.gz -setorient RPI -o tmp.segmentation_RPI.nii.gz
Running /Users/julien/code/sct/scripts/sct_image.py -i tmp.segmentation.nii.gz -setorient RPI -o tmp.segmentation_RPI.nii.gz
tmp.segmentation.nii.gz

Get dimensions of data...
256 x 256 x 15 x 1

Change orientation...

Generate output files...
WARNING: File tmp.segmentation_RPI.nii.gz already exists. Deleting it.
Created file(s):
--> tmp.segmentation_RPI.nii.gz

sct_image -i tmp.centerline.nii.gz -setorient RPI -o tmp.centerline_RPI.nii.gz
Running /Users/julien/code/sct/scripts/sct_image.py -i tmp.centerline.nii.gz -setorient RPI -o tmp.centerline_RPI.nii.gz
tmp.centerline.nii.gz

Get dimensions of data...
256 x 256 x 15 x 1

Change orientation...

Generate output files...
WARNING: File tmp.centerline_RPI.nii.gz already exists. Deleting it.
Created file(s):
--> tmp.centerline_RPI.nii.gz


Get data dimensions...
sct_image -i tmp.segmentation_RPI_c.nii.gz -setorient RPI -o ../mt0_seg.nii.gz
Running /Users/julien/code/sct/scripts/sct_image.py -i tmp.segmentation_RPI_c.nii.gz -setorient RPI -o ../mt0_seg.nii.gz
tmp.segmentation_RPI_c.nii.gz

Get dimensions of data...
256 x 256 x 15 x 1

Change orientation...
rm -f tmp.segmentation_RPI_c_RPI.nii.gz

Generate output files...
WARNING: File ../mt0_seg.nii.gz already exists. Deleting it.
Created file(s):
--> ../mt0_seg.nii.gz


Remove temporary files...
WARNING: File mt0_seg.nii.gz already exists. Deleting it.

Remove temporary files...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_propseg.py", line 599, in <module>
    test(qcslice.Axial(fname_input_data, fname_seg))
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/slice.py", line 43, in __init__
    self.image.change_orientation('SAL')
AttributeError: 'str' object has no attribute 'change_orientation'
~~~

**Comment by peristeri** [comment]
After some investigation, the error is caused by switching branches. And is not a bug in the code itself.
