### ISSUE TITLE
Problem with MPI on Cedar (Compute Canada)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1373]
SCT installed with --mpi option.

My job:
~~~
#!/bin/bash
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2048M
#SBATCH --time=03:00:00
#SBATCH --job-name=sct_pipeline
#SBATCH --output=sct_pipeline-%J.out
#SBATCH --mail-user=XXX
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-type=ALL

export PATH_DATA="/home/jcohen/data/sct_testing/large/"
export SCRATCH="/scratch/jcohen"
cd $SCRATCH
sct_pipeline -f sct_register_to_template -d $PATH_DATA -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz\" -email add
r_to=XXX,passwd_from=XXX -cpu-nb 64
~~~

sct_pipeline-73.out 
~~~
--
Spinal Cord Toolbox (jca_issue1362/1795a89130c457176811ef8c7707ff3aac73fc08)
Sourcing sct_laucher in your environement /home/jcohen/sct
srun: error: Duplicated NodeHostName cdr575 in the config file
srun: error: Duplicated NodeHostName cdr585 in the config file
srun: error: Duplicated NodeHostName cdr587 in the config file
srun: error: Duplicated NodeHostName cdr588 in the config file
srun: error: Duplicated NodeHostName cdr590 in the config file
srun: error: Duplicated NodeHostName cdr614 in the config file
srun: error: Duplicated NodeHostName cdr625 in the config file
srun: error: Duplicated NodeHostName cdr627 in the config file
srun: error: Duplicated NodeHostName cdr671 in the config file
srun: error: Duplicated NodeHostName cdr690 in the config file
srun: error: Duplicated NodeHostName cdr730 in the config file
srun: error: Duplicated NodeHostName cdr764 in the config file
srun: error: Duplicated NodeHostName cdr770 in the config file
srun: error: Duplicated NodeHostName cdr772 in the config file
srun: error: Duplicated NodeHostName cdr773 in the config file
srun: error: Duplicated NodeHostName cdr776 in the config file
srun: error: Duplicated NodeHostName cdr777 in the config file
srun: error: Duplicated NodeHostName cdr781 in the config file
srun: error: Duplicated NodeHostName cdr797 in the config file
srun: error: Duplicated NodeHostName cdr801 in the config file
srun: error: Duplicated NodeHostName cdr814 in the config file
srun: error: Duplicated NodeHostName cdr825 in the config file
srun: error: Duplicated NodeHostName cdr829 in the config file
srun: error: Duplicated NodeHostName cdr832 in the config file
srun: error: Duplicated NodeHostName cdr833 in the config file
srun: error: Duplicated NodeHostName cdr851 in the config file
srun: error: Duplicated NodeHostName cdr852 in the config file
srun: error: Duplicated NodeHostName cdr862 in the config file
srun: error: Duplicated NodeHostName cdr863 in the config file
srun: error: Duplicated NodeHostName cdr867 in the config file
srun: error: Duplicated NodeHostName cdr869 in the config file
srun: error: Duplicated NodeHostName cdr873 in the config file
srun: error: Duplicated NodeHostName cdr873 in the config file
srun: error: Duplicated NodeHostName cdr583 in the config file
srun: error: Duplicated NodeHostName cdr586 in the config file
srun: error: Duplicated NodeHostName cdr589 in the config file
srun: error: Duplicated NodeHostName cdr597 in the config file
srun: error: Duplicated NodeHostName cdr620 in the config file
srun: error: Duplicated NodeHostName cdr687 in the config file
srun: error: Duplicated NodeHostName cdr709 in the config file
srun: error: Duplicated NodeHostName cdr710 in the config file
srun: error: Duplicated NodeHostName cdr714 in the config file
srun: error: Duplicated NodeHostName cdr723 in the config file
srun: error: Duplicated NodeHostName cdr746 in the config file
srun: error: Duplicated NodeHostName cdr750 in the config file
srun: error: Duplicated NodeHostName cdr751 in the config file
srun: error: Duplicated NodeHostName cdr753 in the config file
srun: error: Duplicated NodeHostName cdr755 in the config file
srun: error: Duplicated NodeHostName cdr756 in the config file
srun: error: Duplicated NodeHostName cdr759 in the config file
srun: error: Duplicated NodeHostName cdr760 in the config file
srun: error: Duplicated NodeHostName cdr765 in the config file
srun: error: Duplicated NodeHostName cdr786 in the config file
srun: error: Duplicated NodeHostName cdr789 in the config file
srun: error: Duplicated NodeHostName cdr793 in the config file
srun: error: Duplicated NodeHostName cdr794 in the config file
srun: error: Duplicated NodeHostName cdr795 in the config file
srun: error: Duplicated NodeHostName cdr819 in the config file
srun: error: Duplicated NodeHostName cdr823 in the config file
srun: error: Duplicated NodeHostName cdr835 in the config file
srun: error: Duplicated NodeHostName cdr839 in the config file
srun: error: Duplicated NodeHostName cdr859 in the config file
srun: error: Duplicated NodeHostName cdr866 in the config file
srun: error: Duplicated NodeHostName cdr875 in the config file
srun: error: Duplicated NodeHostName cdr633 in the config file
srun: error: Duplicated NodeHostName cdr672 in the config file
srun: error: Duplicated NodeHostName cdr736 in the config file
srun: error: Duplicated NodeHostName cdr745 in the config file
srun: error: Duplicated NodeHostName cdr747 in the config file
srun: error: Duplicated NodeHostName cdr748 in the config file
srun: error: Duplicated NodeHostName cdr762 in the config file
srun: error: Duplicated NodeHostName cdr766 in the config file
srun: error: Duplicated NodeHostName cdr769 in the config file
srun: error: Duplicated NodeHostName cdr790 in the config file
srun: error: Duplicated NodeHostName cdr792 in the config file
srun: error: Duplicated NodeHostName cdr799 in the config file
srun: error: Duplicated NodeHostName cdr802 in the config file
srun: error: Duplicated NodeHostName cdr803 in the config file
srun: error: Duplicated NodeHostName cdr804 in the config file
srun: error: Duplicated NodeHostName cdr810 in the config file
srun: error: Duplicated NodeHostName cdr812 in the config file
srun: error: Duplicated NodeHostName cdr818 in the config file
srun: error: Duplicated NodeHostName cdr820 in the config file
srun: error: Duplicated NodeHostName cdr827 in the config file
srun: error: Duplicated NodeHostName cdr828 in the config file
srun: error: Duplicated NodeHostName cdr830 in the config file
srun: error: Duplicated NodeHostName cdr836 in the config file
srun: error: Duplicated NodeHostName cdr853 in the config file
srun: error: Duplicated NodeHostName cdr858 in the config file
srun: error: Duplicated NodeHostName cdr860 in the config file
srun: error: Duplicated NodeHostName cdr871 in the config file
srun: error: Duplicated NodeHostName cdr872 in the config file
srun: error: Duplicated NodeHostName cdr874 in the config file
srun: error: Duplicated NodeHostName cdr907 in the config file
srun: error: Duplicated NodeHostName cdr915 in the config file
srun: error: Duplicated NodeHostName cdr566 in the config file
srun: error: Duplicated NodeHostName cdr576 in the config file
srun: error: Duplicated NodeHostName cdr595 in the config file
srun: error: Duplicated NodeHostName cdr607 in the config file
srun: error: Duplicated NodeHostName cdr609 in the config file
srun: error: Duplicated NodeHostName cdr618 in the config file
srun: error: Duplicated NodeHostName cdr630 in the config file
srun: error: Duplicated NodeHostName cdr655 in the config file
srun: error: Duplicated NodeHostName cdr668 in the config file
srun: error: Duplicated NodeHostName cdr698 in the config file
srun: error: Duplicated NodeHostName cdr706 in the config file
srun: error: Duplicated NodeHostName cdr718 in the config file
srun: error: Duplicated NodeHostName cdr757 in the config file
srun: error: Duplicated NodeHostName cdr763 in the config file
srun: error: Duplicated NodeHostName cdr775 in the config file
srun: error: Duplicated NodeHostName cdr779 in the config file
srun: error: Duplicated NodeHostName cdr782 in the config file
srun: error: Duplicated NodeHostName cdr788 in the config file
srun: error: Duplicated NodeHostName cdr791 in the config file
srun: error: Duplicated NodeHostName cdr796 in the config file
srun: error: Duplicated NodeHostName cdr815 in the config file
srun: error: Duplicated NodeHostName cdr822 in the config file
srun: error: Duplicated NodeHostName cdr834 in the config file
srun: error: Duplicated NodeHostName cdr838 in the config file
srun: error: Duplicated NodeHostName cdr842 in the config file
srun: error: Duplicated NodeHostName cdr843 in the config file
srun: error: Duplicated NodeHostName cdr849 in the config file
srun: error: Duplicated NodeHostName cdr865 in the config file
srun: error: Duplicated NodeHostName cdr870 in the config file
srun: error: Duplicated NodeHostName cdr905 in the config file
srun: error: Duplicated NodeHostName cdr906 in the config file
srun: error: Duplicated NodeHostName cdr907 in the config file
srun: error: Duplicated NodeHostName cdr909 in the config file
Traceback (most recent call last):
  File "/home/jcohen/sct/scripts/sct_pipeline.py", line 52, in <module>
    from distribute2mpi import MpiPool as Pool
  File "/home/jcohen/sct/python/lib/python2.7/site-packages/distribute2mpi.py", line 15, in <module>
    from mpi4py import MPI
ImportError: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/librt.so.1: symbol __recv, version GLIBC_PRIVATE not defined i
n file libc.so.6 with link time reference
~~~

**Comment by poquirion** [comment]
C'est peut-être cassé, mais les nouvelles machines vont VITE! Juste à l'installation, on peut sentir la puissance du système.

**Comment by poquirion** [comment]
Seems to be linked to compatibility with CENTOS7 and not the the slurm system.

I am getting the same error just import the MPI interfave if mpi4py.

I will check that in more details when back from Vancouver

**Comment by poquirion** [comment]
@jcohenadad @peristeri, Did the order installation of the pip and conda package changed? 

It seems that it is the pip version (broken) of mpi4py that is installed now not the conda (working) one.

**Comment by jcohenadad** [comment]
what seems to be happening, is that conda installs the 9.0.1 pip properly, but then the installation of another package (dunno which one) downgrades it to 8.X

**Comment by poquirion** [comment]
So, it was somewhat liked to #1372. On top of un-setting pythonpath we also need to set PYTHONNOUSERSITE=1 and tweak a bit the pip installation parameters. 

I am a bit surprised that this bug had not surfaced before. In any case, it should be fixed and the whole install process is now more robust.
