### ISSUE TITLE
ImportError: libSM.so.6: cannot open shared object file on Cedar (Compute Canada) 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1374]
on Cedar (Compute Canada)

~~~
Running /home/jcohen/sct/scripts/sct_register_to_template.py -qc /home/jcohen/qc_data -c t2 -l /home/jcohen/data/sct_testing/large/vand
erbilt_sct-users_20150910-joshua/t2/labels.nii.gz -i /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/t2.nii
.gz -t /home/jcohen/sct/data/PAM50 -v 1 -s /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/t2_seg_manual.ni
i.gz -r 1 -ref template -ofolder sct_register_to_template_vanderbilt_sct-users_20150910-joshua_170623111911_118831/
Check folder existence...
Check folder existence...
Check folder existence...

Check template files...
OK: /home/jcohen/sct/data/PAM50/template/PAM50_t2.nii.gz
OK: /home/jcohen/sct/data/PAM50/template/PAM50_levels.nii.gz
OK: /home/jcohen/sct/data/PAM50/template/PAM50_cord.nii.gz

Check parameters:
Data:                 /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/t2.nii.gz
Landmarks:            /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/labels.nii.gz
Segmentation:         /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/t2_seg_manual.nii.gz
Path template:        /home/jcohen/sct/data/PAM50/
Remove temp files:    1

Check input labels...

Create temporary folder...

Copying input data to tmp folder and convert to nii...
sct_convert -i /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/t2.nii.gz -o tmp.170623111911_903687/data.ni
i
sct_convert -i /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/t2_seg_manual.nii.gz -o tmp.170623111911_903
687/seg.nii.gz
sct_convert -i /home/jcohen/data/sct_testing/large/vanderbilt_sct-users_20150910-joshua/t2/labels.nii.gz -o tmp.170623111911_903687/lab
el.nii.gz
sct_convert -i /home/jcohen/sct/data/PAM50/template/PAM50_t2.nii.gz -o tmp.170623111911_903687/template.nii
sct_convert -i /home/jcohen/sct/data/PAM50/template/PAM50_cord.nii.gz -o tmp.170623111911_903687/template_seg.nii.gz

Generate labels from template vertebral labeling
sct_label_utils -i /home/jcohen/sct/data/PAM50/template/PAM50_levels.nii.gz -vert-body 0 -o template_label.nii.gz

Check if provided labels are available in the template

Binarize segmentation
sct_maths -i seg.nii.gz -bin 0.5 -o seg.nii.gz

Resample data to 1mm isotropic...
sct_resample -i data.nii -mm 1.0x1.0x1.0 -x linear -o data_1mm.nii
Running /home/jcohen/sct/scripts/sct_resample.py -i data.nii -mm 1.0x1.0x1.0 -x linear -o data_1mm.nii
Traceback (most recent call last):
File "/home/jcohen/sct/scripts/sct_resample.py", line 365, in <module>
main()
File "/home/jcohen/sct/scripts/sct_resample.py", line 362, in main
resample()
File "/home/jcohen/sct/scripts/sct_resample.py", line 59, in resample
from nipy.algorithms.registration import resample
File "/home/jcohen/sct/python/lib/python2.7/site-packages/nipy/algorithms/registration/__init__.py", line 18, in <module>
from .scripting import space_time_realign, aff2euler
File "/home/jcohen/sct/python/lib/python2.7/site-packages/nipy/algorithms/registration/scripting.py", line 22, in <module>
import matplotlib.pyplot as plt
File "/home/jcohen/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
_backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
File "/home/jcohen/sct/python/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
globals(),locals(),[backend_name],0)
File "/home/jcohen/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
File "/home/jcohen/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
from .backend_qt5 import QtCore
File "/home/jcohen/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
File "/home/jcohen/sct/python/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
from PyQt4 import QtCore, QtGui
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

/home/jcohen/sct/scripts/sct_utils.pyNone


/home/jcohen/sct/scripts/sct_utils.pyNone
~~~

~~~
sct_check_dependencies 

--
Spinal Cord Toolbox (jca_issue1362/1795a89130c457176811ef8c7707ff3aac73fc08)
Running /home/jcohen/sct/scripts/sct_check_dependencies.py

OS: linux (Linux-3.10.0-514.21.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core)
CPU cores: Available: 32, Used by SCT: 32
RAM: MemTotal:       264035648 kB
total        used        free      shared  buff/cache   available
Mem:         257847        3095      226543         406       28207      250061
Swap:          4095           0        4095
SCT path: /home/jcohen/sct
Installation type: git
  commit: 1795a89130c457176811ef8c7707ff3aac73fc08
  branch: jca_issue1362
Check Python path...................................[OK]
Check if data are installed.........................[OK]
Check if xlwt (1.0.0) is installed..................[OK]
Check if xlutils (1.7.1) is installed...............[OK]
Check if cryptography (1.6) is installed............[OK]
Check if scikit-learn (0.17.1) is installed.........[OK]
Check if scikit-image (0.12.3) is installed.........[OK]
Check if pyqt (4.11.4) is installed.................[OK]
Check if psutil (5.2.2) is installed................[OK]
Check if matplotlib (1.5.1) is installed............[OK]
Check if pip (9.0.1) is installed...................[WARNING]
  Detected version: 8.1.2. Required version: 9.0.1
Check if requests (2.12.4) is installed.............[OK]
Check if xlrd (0.9.4) is installed..................[OK]
Check if pandas (0.18.1) is installed...............[OK]
Check if mpi4py (2.0.0) is installed................[OK]
Check if dipy (0.11.0) is installed.................[OK]
Check if distribute2mpi (0.3.0) is installed........[OK]
Check if nibabel (2.1.0) is installed...............[OK]
Check if tqdm (4.11.2) is installed.................[OK]
Check if nipy (0.4.0) is installed..................[OK]
Check if numpy is installed.........................[OK]
Check if scipy is installed.........................[OK]
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[FAIL]
~~~

**Comment by peristeri** [comment]
This library is a Qt dependency. 

One solution is to disable display backend by creating a file `~/.config/matplotlib/matplotlibrc` and add the following parameter
```
backend      : Agg
```
