### ISSUE TITLE
[sct_register_multimodal] check if more than 2 slices when using slicereg

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1434]
Bug is very unclear. New users don't understand their error.

**Comment by daryamor** [comment]
error (so that future users can search for it)
````
Traceback (most recent call last):
  File "/Users/damor/sct_dev/scripts/sct_register_multimodal.py", line 762, in <module>
    main()
  File "/Users/damor/sct_dev/scripts/sct_register_multimodal.py", line 469, in main
    warp_forward_out, warp_inverse_out = register(src, dest, paramreg, param, str(i_step))
  File "/Users/damor/sct_dev/scripts/sct_register_multimodal.py", line 581, in register
    zmin_src, zmax_src = find_zmin_zmax(src_th)
  File "/Users/damor/sct_dev/scripts/msct_image.py", line 1169, in find_zmin_zmax
    zmin, zmax = output[output.find('Dimension 2: ')+13:].split('\n')[0].split(' ')
ValueError: too many values to unpack
````

**Comment by joshuacwnewton** [comment]
We now use a different method for finding zmin/zmax:

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/spinalcordtoolbox/image.py#L889-L904

I believe this newer method is not susceptible to the issue described here. So, I think this is outdated, and I'm closing it.
