### ISSUE TITLE
Crash in specific OS

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1456]
### Description

QC crashes in some images, in some OSs. Tested done:
- OSX --> works
- Debian (via Travis) --> works
- CentOS (rosenberg) --> fails

Image tested: vanderbilt_gmsegChallenge16_03/t2s/t2s.nii.gz

### Proposed fix

add a try/except when calling the QC.

### State of spinalcordtoolbox

Spinal Cord Toolbox (master/a0617b16c5d7776a91ff8b8e2bc03c95fb869ba3)

### Additional Information

~~~
[neuropoly@rosenberg t2s]$ sct_propseg -i t2s.nii.gz -c t2s

--
Spinal Cord Toolbox (master/a0617b16c5d7776a91ff8b8e2bc03c95fb869ba3)
Running /home/neuropoly/sct/scripts/sct_propseg.py -i t2s.nii.gz -c t2s
Detecting the spinal cord using OptiC
isct_propseg -i "/home/neuropoly/data/vanderbilt_gmsegChallenge16_03/t2s/t2s.nii.gz" -t t2 -o "./" -verbose -init-centerline ./t2s_centerline_optic.nii.gz -centerline-binary
Initialization - using given centerline
Total propagation length = 87.1234 mm

Segmentation finished. To view results, type:
fslview /home/neuropoly/data/vanderbilt_gmsegChallenge16_03/t2s/t2s.nii.gz ./t2s_seg.nii.gz &

Check consistency of segmentation...

Create temporary folder...
sct_image -i tmp.segmentation.nii.gz -setorient RPI -o tmp.segmentation_RPI.nii.gz
Running /home/neuropoly/sct/scripts/sct_image.py -i tmp.segmentation.nii.gz -setorient RPI -o tmp.segmentation_RPI.nii.gz
tmp.segmentation.nii.gz

Get dimensions of data...
560 x 560 x 14 x 1

Change orientation...

Generate output files...
WARNING: File tmp.segmentation_RPI.nii.gz already exists. Deleting it.

Finished. To view results, type:
fslview tmp.segmentation_RPI.nii.gz &

sct_image -i tmp.centerline.nii.gz -setorient RPI -o tmp.centerline_RPI.nii.gz
Running /home/neuropoly/sct/scripts/sct_image.py -i tmp.centerline.nii.gz -setorient RPI -o tmp.centerline_RPI.nii.gz
tmp.centerline.nii.gz

Get dimensions of data...
560 x 560 x 14 x 1

Change orientation...

Generate output files...
WARNING: File tmp.centerline_RPI.nii.gz already exists. Deleting it.

Finished. To view results, type:
fslview tmp.centerline_RPI.nii.gz &


Get data dimensions...
sct_image -i tmp.segmentation_RPI_c.nii.gz -setorient RPI -o /home/neuropoly/data/vanderbilt_gmsegChallenge16_03/t2s/t2s_seg.nii.gz
Running /home/neuropoly/sct/scripts/sct_image.py -i tmp.segmentation_RPI_c.nii.gz -setorient RPI -o /home/neuropoly/data/vanderbilt_gmsegChallenge16_03/t2s/t2s_seg.nii.gz
tmp.segmentation_RPI_c.nii.gz

Get dimensions of data...
560 x 560 x 14 x 1

Change orientation...
rm -f tmp.segmentation_RPI_c_RPI.nii.gz

Generate output files...
WARNING: File /home/neuropoly/data/vanderbilt_gmsegChallenge16_03/t2s/t2s_seg.nii.gz already exists. Deleting it.

Finished. To view results, type:
fslview /home/neuropoly/data/vanderbilt_gmsegChallenge16_03/t2s/t2s_seg.nii.gz &


Remove temporary files...
WARNING: File t2s_seg.nii.gz already exists. Deleting it.

Remove temporary files...
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/neuropoly/sct/scripts/sct_propseg.py", line 546, in <module>
    test(qcslice.Axial(Image(fname_input_data), Image(fname_seg)))
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/qc.py", line 174, in wrapped_f
    self.qc_report.update_description_file(img.shape)
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/qc.py", line 320, in update_description_file
    results = json.load(open(self.qc_params.qc_results, 'r'))
  File "/home/neuropoly/sct/python/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/neuropoly/sct/python/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/neuropoly/sct/python/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 12290 column 2 - line 12292 column 2 (char 617388 - 617407)
~~~

**Comment by peristeri** [comment]
Can you include the json file. The error is saying that there's 2 document instances in the file.
