### ISSUE TITLE
crash with few slices

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1469]
~~~
sct_get_centerline -i epi_32.nii.gz -method viewer

--
Spinal Cord Toolbox (master/481bd8840e144b51bc70369aa1b8fdbd6856eae3)
Running /Users/julien/code/sct/scripts/sct_get_centerline.py -i epi_32.nii.gz -method viewer
rm -rf tmp.170920165558_870854/
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 266, in <module>
    run_main()
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 169, in run_main
    fname_points = viewer_centerline(image_fname=reoriented_image_filename, interslice_gap=interslice_gap, verbose=verbose)
  File "/Users/julien/code/sct/scripts/sct_get_centerline.py", line 20, in viewer_centerline
    viewer = ClickViewerPropseg(image_input_reoriented)
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 811, in __init__
    input_type=input_type)
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 495, in __init__
    self.pad_data()
  File "/Users/julien/code/sct/scripts/sct_viewer.py", line 314, in pad_data
    constant_values=(0, 0))
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1295, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1080, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1039, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from ((0, 0), (0, 0), (30, 30))
~~~

**Comment by jcohenadad** [comment]
was a 4d file.

would be good to check for it
