### ISSUE TITLE
Error when crop image in sct_straighten_spinalcord after NURBS

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1478]
### Steps to Reproduce

```
cd /Volumes/folder_shared/sct_issues/20171006_issue1478/
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -o t2_straight.nii.gz -v 1
```

**Actual behavior:**

```
evans:/Volumes/folder_shared/sct_issues/20171006_issue1478 $ sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -o t2_straight.nii.gz -v 1

--
Spinal Cord Toolbox (master/a183f1490a03b0e1f19203298d053185621af1dc)
Running /Users/chgroc/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py -i t2.nii.gz -s t2_seg.nii.gz -o t2_straight.nii.gz -v 1
/Users/chgroc/spinalcordtoolbox

Check input arguments:
  Input volume ...................... t2.nii.gz
  Centerline ........................ t2_seg.nii.gz
  Final interpolation ............... spline
  Verbose ........................... 1


Create temporary folder...

Copy files to tmp folder...
sct_convert -i t2.nii.gz -o tmp.171006162327_308583/data.nii
sct_convert -i t2_seg.nii.gz -o tmp.171006162327_308583/centerline.nii.gz

Orient centerline to RPI orientation...
sct_image -i centerline.nii.gz -setorient RPI -o centerline_rpi.nii.gz

Get dimensions...
.. matrix size: 22 x 320 x 196
.. voxel size:  3.0mm x 0.625mm x 0.625mm

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = nurbs

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 0.7 mm
Test: # of control points = 6
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 7
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 8
Error on approximation = 0.15 mm
Test: # of control points = 9
Error on approximation = 0.11 mm
Test: # of control points = 10
Error on approximation = 0.09 mm
Test: # of control points = 11
Error on approximation = 0.09 mm
Test: # of control points = 12
Error on approximation = 0.08 mm
Number of control points of the optimal NURBS = 12

Create the straight space and the safe zone...

Pad input volume to account for spinal cord length...
sct_image -i centerline_rpi.nii.gz -o tmp.centerline_pad.nii.gz -pad 0,0,3
sct_crop_image -i tmp.centerline_pad.nii.gz -o tmp.centerline_pad_crop.nii.gz -dim 0,1,2 -start 0,104,0 -end 22,216,198
Running /Users/chgroc/spinalcordtoolbox/scripts/sct_crop_image.py -i tmp.centerline_pad.nii.gz -o tmp.centerline_pad_crop.nii.gz -dim 0,1,2 -start 0,104,0 -end 22,216,198
isct_crop_image -i tmp.centerline_pad.nii.gz -o tmp.centerline_pad_crop.nii.gz -start 0.0,104.0,0.0 -end 22.0,216.0,198.0 -dim 0,1,2
Cropping the following region:
Dimension 0: 0 22
Dimension 1: 104 216
Dimension 2: 0 198
Exception caught while updating cropFilter

itk::InvalidRequestedRegionError (0x7fbdba724988)
Location: "unknown"
File: /Users/benjamindeleener/code/ITK/Modules/Core/Common/src/itkDataObject.cxx
Line: 393
Description: Requested region is (at least partially) outside the largest possible region.


Exception caught while updating writerCrop

itk::ImageFileWriterException (0x7fbdba44ce68)
Location: "unknown"
File: /usr/local/itk/include/ITK-4.8/itkImageFileWriter.hxx
Line: 408
Description: Did not get requested region!
Requested:
ImageRegion (0x7fff5377fa50)
Dimension: 3
Index: [0, 104, 0]
Size: [23, 113, 199]
Actual:
ImageRegion (0x7fff5377fa18)
Dimension: 3
Index: [0, 0, 0]
Size: [0, 0, 0]



Traceback (most recent call last):
File "/Users/chgroc/spinalcordtoolbox/scripts/sct_crop_image.py", line 445, in <module>
cropper.crop()
File "/Users/chgroc/spinalcordtoolbox/scripts/sct_crop_image.py", line 115, in crop
self.result = Image(self.output_filename, verbose=self.verbose)
File "/Users/chgroc/spinalcordtoolbox/scripts/msct_image.py", line 227, in __init__
self.loadFromPath(param, verbose)
File "/Users/chgroc/spinalcordtoolbox/scripts/msct_image.py", line 281, in loadFromPath
self.im_file = load(path)
File "/Users/chgroc/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/loadsave.py", line 40, in load
raise FileNotFoundError("No such file: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file: 'tmp.centerline_pad_crop.nii.gz'

/Users/chgroc/spinalcordtoolbox/scripts/sct_utils.pyNone
```

**Comment by benjamindeleener** [comment]
Ths issue was caused by an approximation error that was not checked properly during straightening. More specifically, the straight space that is created is, at some point, cropped, and the crop size depends on several parameters (curvature, length, size, etc.). In this specific case, the crop region was larger than the straight image and produced an error. I added a check in the x-y direction to avoid this error in the future.
