### ISSUE TITLE
viewer broken

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1483]
### Description

Viewer broken. The QT windows opens, then closes with error on Terminal.

### Steps to Reproduce

See below.

### State of spinalcordtoolbox

Spinal Cord Toolbox (master/69b28b03f6a615cf45ae8b3c734ef905afbd8e9e)

### Additional Information

~~~
sct_propseg -i avg.016.nii -c t2s -init-mask viewer

--
Spinal Cord Toolbox (master/69b28b03f6a615cf45ae8b3c734ef905afbd8e9e)
Running /Users/julien/code/sct/scripts/sct_propseg.py -i avg.016.nii -c t2s -init-mask viewer
/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/axes/_base.py:1215: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aspect == 'normal':
/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/axes/_base.py:1220: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aspect in ('equal', 'auto'):
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_propseg.py", line 444, in <module>
    controller = launch_centerline_dialog(image, tmp_output_file, params)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/centerline.py", line 209, in launch_centerline_dialog
    dialog_ = Centerline(controller)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/centerline.py", line 109, in __init__
    super(Centerline, self).__init__(*args, **kwargs)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/base.py", line 100, in __init__
    self._init_ui()
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/base.py", line 112, in _init_ui
    self.setWindowTitle(self.params.dialog_title)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/spinalcordtoolbox/gui/base.py", line 54, in dialog_title
    self._title = '{}: manual labeling'.format(self.input_file_name)
AttributeError: 'AnatomicalParams' object has no attribute 'input_file_name'
~~~

**Comment by aliikhatibi** [comment]
same message appears when I use -initc2 in sct_label_vertebrae

**Comment by jcohenadad** [comment]
thank you for the feedback Ali, we are working on it with high priority
