### ISSUE TITLE
Installer continues on failure

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1541]
Did a `SIGSTOP/SIGCONT` during installation and got the following:

```
Status:  66%|############################################################################################################################################4                                                                         | 51.7M/78.8M [43:05<22:33, 20.0KB/s]

Download complete

Check if folder already exists...

Unzip data to: /home/cJ/sct_dev/data
ERROR: ZIP package corrupted. Please try downloading again.

../scripts/sct_download_data.pyTraceback (most recent call last):
  File "../scripts/sct_download_data.py", line 116, in unzip
    zf = zipfile.ZipFile(compressed)
  File "/home/cJ/sct_dev/python/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/home/cJ/sct_dev/python/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

Traceback (most recent call last):
  File "../scripts/sct_download_data.py", line 173, in <module>
    main()
  File "../scripts/sct_download_data.py", line 103, in main
    unzip(tmp_file, dest_folder, verbose)
  File "../scripts/sct_download_data.py", line 122, in unzip
    verbose, 'error')
  File "/home/cJ/sct_dev/scripts/sct_utils.py", line 758, in printv
    raise RunError('raise in printv, read log above for more info')
sct_utils.RunError: raise in printv, read log above for more info
>> python ../scripts/sct_download_data.py -d gm_model

```

Ie. a download aborted (understandable because I suspended the task), didn't resume, but installation continued.

**Comment by poquirion** [comment]
We can add the following, after the download data block

```bash
   elif [ $OS == "osx" ]; then
        cmd="python ../scripts/sct_download_data.py -d binaries_osx -o ${SCT_DIR}/${BIN_DIR}"; echo ">> "$cmd; $cmd
    fi
+    retval=$?
+    if [[ $retval ne 0 ]] ; then
+      exit  $retval
+    fi
fi
```
Should do the trick

**Comment by zougloub** [comment]
Rather than testing all the time, I'll try to use `set -e` and see what happens...
