### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1556]
### Description

Bug might have been introduced by recent changes.

### Steps to Reproduce

~~~
sct_testing_data/t2 $ sct_image -i t2.nii.gz -split t
~~~

**Actual behavior:**

~~~
--
Spinal Cord Toolbox (poq_issue_1507_progress/32a1bf244dc13569d53ae9ec6550ebd2392151c3)
Running /Users/julien/code/sct/scripts/sct_image.py -i t2.nii.gz -split t
Generate output files...
WARNING: File t2_T0000.nii.gz already exists. Deleting it.
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_image.py", line 763, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_image.py", line 265, in main
    sct.display_viewer_syntax([fname_out])
  File "/Users/julien/code/sct/scripts/sct_utils.py", line 329, in display_viewer_syntax
    cmd += ' ' + files[i]
TypeError: cannot concatenate 'str' and 'NoneType' objects
~~~

**Comment by jcohenadad** [comment]
actually, the command was wrong: trying to split along t, in an image with only one volume (3d, not 4d). However, the crash should not occur. I moved it to medium priority.
