### ISSUE TITLE
Correct the output verbose when files do not exist

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1689]
### Prerequisites

* [x] Did you check past issues for similar issue(s) ?
* [x] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [x] If you are using a development environment, is your environment updated ?

### Description

The flag `-param` does not parse and pass the arguments properly (i.e. it has no effect). 

### Steps to Reproduce

~~~
sct_label_vertebrae -i t2r.nii.gz -s t2r_seg.nz -c t2 -qc ${PATH_QC} -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50

--
Spinal Cord Toolbox (master/caf11f46d92fe8765490a53325acbf0e2b36b8f1)
Running /Users/julien/code/sct/scripts/sct_label_vertebrae.py -i t2r.nii.gz -s t2r_seg.nii.gz -c t2 -qc /Users/julien/Dropbox/documents/processing/20180424_nadia/quality_control/ -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50
Traceback (most recent call last):
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/julien/code/sct/python/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file msct_parser.py, line 251
~~~

**Comment by fperdigon** [comment]
The parser is working well and the expected results are obtained. I think there was an error typing the segmentation file. does not have the correct extension should be nii.gz instead of nz.

PS: if I put the -qc option I get errors related to QC. I have the dependencies updated.

`QC: layout with Sagittal slice
Traceback (most recent call last):
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 941, in <module>
    main()
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 356, in main
    generate_qc(fname_in, labeled_seg_file, args, path_qc)
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 409, in generate_qc
    qcslice_layout=lambda x: x.single(),
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/qc.py", line 401, in add_entry
    layout(qcslice)
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/qc.py", line 169, in wrapped_f
    img, mask = func(sct_slice, *args)
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/qc.py", line 399, in layout
    return qcslice_layout(qslice)
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 409, in <lambda>
    qcslice_layout=lambda x: x.single(),
  File "/Users/fperdigon_admin/Documents/spinalcordtoolbox/python/lib/python2.7/site-packages/spinalcordtoolbox/reports/slice.py", line 300, in single
    assert len(set([x.data.shape for x in self._images])) == 1, "Volumes don't have the same size"
AssertionError: Volumes don't have the same size`

**Comment by jcohenadad** [comment]
thank you @fperdigon, well spotted. However the output verbose is not acceptable: it should say something like "this file does not exist" or something like that... could you appropriately rename this issue and address it?

regarding the QC issue: pls open a new issue with instructions to reproduce

**Comment by fperdigon** [comment]
@jcohenadad  This issue was fixed by @zougloub [here](https://github.com/neuropoly/spinalcordtoolbox/commit/a576106a5bc6f55b04bc01d1765ab65e0c8d5819#diff-31b7cd49a74ad9e8d82353e2fe72a244). I already tested and the parser is working fine. I will close this issue.
