### ISSUE TITLE
Failing sending email via gmail account

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1701]
### Description

When the process ends, the user has the possibility to have an email sent to him. So far we have used gmail SMTP, however the increasing security of Google email is now causing problems. Recent example below:
~~~
Sending email...
Traceback (most recent call last):
  File "/home/jcohen/sct/scripts/sct_pipeline.py", line 674, in <module>
    message=message, filename=fname_log, html=True)
  File "/home/jcohen/sct/scripts/sct_utils.py", line 1028, in send_email
    server.login(addr_from, passwd_from)
  File "/home/jcohen/sct/python/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsZ\n5.7.14 CeiRre
e18dKJ1azIOyBYp4TP0TdcrbriMUONUHTwaus4FQE0Rcf6tAIN1U2J_ac3xJ4-pc\n5.7.14 K9BKnVNQl4dNnys6JVIxbDsT9TDNpzU7_LJx2SkSFYafdAEFWAcrKNuotg-
8J_8tHuygO0\n5.7.14 STujLXgTRYs99X6J8AAVsG9KpWgq_AXzwEQKdCyfacUKUf6EgB4Ihjm2oy6YQpgSqBipSb\n5.7.14 cebGH2TJTNjvbmToUZ8s_MyFMYWQE> Pl
ease log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/
78754 e80sm9340617pfb.41 - gsmtp')
~~~

My suggestion would be to find an alternative to Gmail. Maybe Sentry can be useful there? Any idea welcome.

**Comment by zougloub** [comment]
For sure, hard-coding gmail in the code is not the best.

On the particular error message: when you access Google services using same credentials but from very different geographic areas (eg. Canada vs Japan) (or browsers), the security measures might trip, and there is nothing you can do except logging in by HTTP and calming them down.
