### ISSUE TITLE
Install fails from github tarball if git not installed

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1718]
A regression arose during the Sentry merge:
```
Installing binaries...
>> . /home/sct/sct_dev/python/bin/activate /home/sct/sct_dev/python
>> python ../scripts/sct_download_data.py -d binaries_centos -o /home/sct/sct_dev/bin
Traceback (most recent call last):
  File "../scripts/sct_download_data.py", line 26, in <module>
    from msct_parser import Parser
  File "/home/sct/sct_dev/scripts/msct_parser.py", line 81, in <module>
    import sct_utils as sct
  File "/home/sct/sct_dev/scripts/sct_utils.py", line 27, in <module>
    import sct_config
  File "/home/sct/sct_dev/scripts/sct_config.py", line 57, in <module>
    __version__ = '-'.join(_git_info(commit_env='SCT_COMMIT', branch_env='SCT_BRANCH'))
  File "/home/sct/sct_dev/scripts/sct_config.py", line 39, in _git_info
    sct_commit = os.getenv(commit_env, __get_commit())
  File "/home/sct/sct_dev/scripts/sct_config.py", line 29, in __get_commit
    cwd=__sct_dir__)
  File "/home/sct/sct_dev/python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/sct/sct_dev/python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Failed to download SCT binaries.
```

**Comment by zougloub** [comment]
Fixed by #1703
