### ISSUE TITLE
Error when -qc option is used on  sct_label_vertebrae

### ISSUE THREAD

**Issue by fperdigon** [neuropoly/spinalcordtoolbox#1725]
### Prerequisites

* [X] Did you check past issues for similar issue(s) ?
* [X] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [X] If you are using a development environment, is your environment updated ?

### Description

Error when -qc option is used on  sct_label_vertebrae

### Steps to Reproduce
data: sct_testing_data/t2
branch: master
commit #: HEAD/caf11f46d92fe8765490a53325acbf0e2b36b8f1

sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc ./qc -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50

**Actual behavior:**

<details>

```
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc ./qc -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50

--
Spinal Cord Toolbox ((HEAD/caf11f46d92fe8765490a53325acbf0e2b36b8f1)
Running /home/fco/spinalcordtoolbox/scripts/sct_label_vertebrae.py -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc ./qc -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50
Traceback (most recent call last):
  File "/home/fco/spinalcordtoolbox/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/fco/spinalcordtoolbox/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/fco/spinalcordtoolbox/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/home/fco/spinalcordtoolbox/python/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file msct_parser.py, line 251

Create temporary folder (/tmp/sct-180512234203-label_vertebrae-GWSS0W)...

Copying input data to tmp folder...
sct_convert -i t2.nii.gz -o /tmp/sct-180512234203-label_vertebrae-GWSS0W/data.nii # in /home/fco/spinalcordtoolbox/sct_testing_data/t2                                                                                      
sct_convert -i t2_seg.nii.gz -o /tmp/sct-180512234203-label_vertebrae-GWSS0W/segmentation.nii.gz # in /home/fco/spinalcordtoolbox/sct_testing_data/t2                                                                       

Create label to identify disc...

Straighten spinal cord...
WARNING: It looks like straightening was already performed previously. Copying warping fields...
cp /home/fco/spinalcordtoolbox/sct_testing_data/t2/warp_curve2straight.nii.gz warp_curve2straight.nii.gz
cp /home/fco/spinalcordtoolbox/sct_testing_data/t2/warp_straight2curve.nii.gz warp_straight2curve.nii.gz
cp /home/fco/spinalcordtoolbox/sct_testing_data/t2/straight_ref.nii.gz straight_ref.nii.gz
sct_apply_transfo -i data.nii -w warp_curve2straight.nii.gz -d straight_ref.nii.gz -o data_straight.nii # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                                                   

Resample to 0.5mm isotropic...
sct_resample -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                                                                         
Running /home/fco/spinalcordtoolbox/scripts/sct_resample.py -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii

Load data...
pixdim: (1.0, 1.0, 1.0)
shape: (51, 59, 55)

Calculate new dimensions...
new shape: (102, 118, 110)
affine matrix:
[[ -1.          -0.           0.          18.78071594]
[ -0.           1.          -0.         -27.21339417]
[  0.           0.           1.         -20.32167053]
[  0.           0.           0.           1.        ]]

Calculate affine transformation...
transfo:
[[ 0.5   0.    0.   -0.25]
[ 0.    0.5   0.   -0.25]
[ 0.    0.    0.5  -0.25]
[ 0.    0.    0.    1.  ]]
/home/fco/spinalcordtoolbox/python/lib/python2.7/site-packages/nipy/io/files.py:145: FutureWarning: Default `strict` currently False; this will change to True in a future version of nipy
ni_img = nipy2nifti(img, data_dtype = io_dtype)

Done! To view results, type:
fslview data_straightr.nii &

Apply straightening to segmentation...
sct_apply_transfo -i segmentation.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                    
Running /home/fco/spinalcordtoolbox/scripts/sct_apply_transfo.py -i segmentation.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear

Parse list of warping fields...
Transfo #0: warp_curve2straight.nii.gz

Get dimensions of data...
60 x 55 x 52 x 1

Apply transformation...
isct_antsApplyTransforms -d 3 -i segmentation.nii.gz -o segmentation_straight.nii.gz -t warp_curve2straight.nii.gz -r data_straightr.nii -n Linear # in /tmp/sct-180512234203-label_vertebrae-GWSS0W

Done! To view results, type:
fsleyes data_straightr.nii segmentation_straight.nii.gz &

sct_maths -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                                                                        
Running /home/fco/spinalcordtoolbox/scripts/sct_maths.py -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz
WARNING: File segmentation_straight.nii.gz already exists. Deleting it.

Done! To view results, type:
fsleyes segmentation_straight.nii.gz &


Look for template...
Path template: /home/fco/spinalcordtoolbox/data/PAM50

Open template and vertebral levels...

Disc values from template: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Z-values for each disc: [962, 939, 908, 871, 834, 801, 770, 736, 693, 647, 601, 552, 501, 450, 397, 343, 290, 232, 169, 106, 56]
Distances between discs (in voxel): [23, 31, 37, 37, 33, 31, 34, 43, 46, 46, 49, 51, 51, 53, 54, 53, 58, 63, 63, 50]

Detect C2/C3 disk...
.. Peak found: z=81 (correlation = 0.267968327607)
/home/fco/spinalcordtoolbox/python/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Detect intervertebral discs...
Current disc: 2 (z=66). Direction: superior
.. Peak found: z=0 (correlation = 0.374293837659)
Current disc: 1 (z=97). Direction: superior
.. correcting factor: 1.0
.. Switching to inferior direction.
Current disc: 3 (z=29). Direction: inferior
.. Peak found: z=4 (correlation = 0.567550163509)
.. correcting factor: 0.945945945946
Adding top disc based on adjusted template distance: #0
.. approximate distance: 22

Un-straighten labeling...
sct_apply_transfo -i segmentation_straight_labeled.nii.gz -d segmentation.nii.gz -w warp_straight2curve.nii.gz -o segmentation_labeled.nii.gz -x nn # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                       
Running /home/fco/spinalcordtoolbox/scripts/sct_apply_transfo.py -i segmentation_straight_labeled.nii.gz -d segmentation.nii.gz -w warp_straight2curve.nii.gz -o segmentation_labeled.nii.gz -x nn

Parse list of warping fields...
Transfo #0: warp_straight2curve.nii.gz

Get dimensions of data...
102 x 118 x 110 x 1

Apply transformation...
isct_antsApplyTransforms -d 3 -i segmentation_straight_labeled.nii.gz -o segmentation_labeled.nii.gz -t warp_straight2curve.nii.gz -r segmentation.nii.gz -n NearestNeighbor # in /tmp/sct-180512234203-label_vertebrae-GWSS0W

Done! To view results, type:
fsleyes segmentation.nii.gz segmentation_labeled.nii.gz &


Clean labeled segmentation (correct interpolation errors)...
sct_maths -i segmentation_labeled.nii.gz -mul segmentation.nii.gz -o segmentation_labeled_mul.nii.gz # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                                                      
sct_maths -i segmentation_labeled.nii.gz -dilate 2 -o segmentation_labeled_dilate.nii.gz # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                                                                  
sct_maths -i segmentation_labeled_mul.nii.gz -bin 0 -o segmentation_labeled_mul_bin.nii.gz # in /tmp/sct-180512234203-label_vertebrae-GWSS0W                                                                                
WARNING: File segmentation_labeled.nii.gz already exists. Deleting it.

Label discs...

Generate output files...
  File created: ./t2_seg_labeled.nii.gz
  File created: ./t2_seg_labeled_discs.nii.gz
  WARNING: File ./warp_curve2straight.nii.gz already exists. Deleting it...
  File created: ./warp_curve2straight.nii.gz
  WARNING: File ./warp_straight2curve.nii.gz already exists. Deleting it...
  File created: ./warp_straight2curve.nii.gz
  WARNING: File ./straight_ref.nii.gz already exists. Deleting it...
  File created: ./straight_ref.nii.gz
Traceback (most recent call last):
  File "/home/fco/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 952, in <module>
    main()
  File "/home/fco/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 341, in main
    generate_qc(fname_in, labeled_seg_file, args, path_qc)
  File "/home/fco/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 386, in generate_qc
    qc.add_entry(
AttributeError: 'module' object has no attribute 'add_entry'
```
</details>

**Comment by jcohenadad** [comment]
@fperdigon when you report an issue, always specify branch and commit #, as well as the data used.

It works for me with sct_testing_data/t2:

<details>

```
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc ./qc -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50

--
Spinal Cord Toolbox (master/de484af400707468241f7f0e231375e69ffc2ae7)
Running /Users/julien/code/sct/scripts/sct_label_vertebrae.py -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc ./qc -v 2 -r 0 -param size_IS_initc2=41,size_AP_initc2=25,shift_AP_initc2=50

Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t)...

Copying input data to tmp folder...
sct_convert -i t2.nii.gz -o /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t/data.nii # in /Users/julien/sct_testing_data/t2
sct_convert -i t2_seg.nii.gz -o /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t/segmentation.nii.gz # in /Users/julien/sct_testing_data/t2

Create label to identify disc...

Straighten spinal cord...
WARNING: It looks like straightening was already performed previously. Copying warping fields...
cp /Users/julien/sct_testing_data/t2/warp_curve2straight.nii.gz warp_curve2straight.nii.gz
cp /Users/julien/sct_testing_data/t2/warp_straight2curve.nii.gz warp_straight2curve.nii.gz
cp /Users/julien/sct_testing_data/t2/straight_ref.nii.gz straight_ref.nii.gz
sct_apply_transfo -i data.nii -w warp_curve2straight.nii.gz -d straight_ref.nii.gz -o data_straight.nii # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t

Resample to 0.5mm isotropic...
sct_resample -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
Running /Users/julien/code/sct/scripts/sct_resample.py -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii

Load data...
pixdim: (1.0, 1.0, 1.0)
shape: (51, 59, 55)

Calculate new dimensions...
new shape: (102, 118, 110)
affine matrix:
[[ -1.          -0.           0.          18.78071594]
[ -0.           1.          -0.         -27.21339417]
[  0.           0.           1.         -20.32167053]
[  0.           0.           0.           1.        ]]

Calculate affine transformation...
transfo:
[[ 0.5   0.    0.   -0.25]
[ 0.    0.5   0.   -0.25]
[ 0.    0.    0.5  -0.25]
[ 0.    0.    0.    1.  ]]
/Users/julien/code/sct/python/lib/python2.7/site-packages/nipy/io/files.py:145: FutureWarning: Default `strict` currently False; this will change to True in a future version of nipy
ni_img = nipy2nifti(img, data_dtype = io_dtype)

Done! To view results, type:
fsleyes data_straightr.nii &


Apply straightening to segmentation...
sct_apply_transfo -i segmentation.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
Running /Users/julien/code/sct/scripts/sct_apply_transfo.py -i segmentation.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear

Parse list of warping fields...
Transfo #0: warp_curve2straight.nii.gz

Get dimensions of data...
60 x 55 x 52 x 1

Apply transformation...
isct_antsApplyTransforms -d 3 -i segmentation.nii.gz -o segmentation_straight.nii.gz -t warp_curve2straight.nii.gz -r data_straightr.nii -n Linear # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t

Done! To view results, type:
fsleyes data_straightr.nii segmentation_straight.nii.gz &

sct_maths -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
Running /Users/julien/code/sct/scripts/sct_maths.py -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz
WARNING: File segmentation_straight.nii.gz already exists. Deleting it.

Done! To view results, type:
fsleyes segmentation_straight.nii.gz &


Look for template...
Path template: /Users/julien/code/sct/data/PAM50

Open template and vertebral levels...

Disc values from template: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Z-values for each disc: [962, 939, 908, 871, 834, 801, 770, 736, 693, 647, 601, 552, 501, 450, 397, 343, 290, 232, 169, 106, 56]
Distances between discs (in voxel): [23, 31, 37, 37, 33, 31, 34, 43, 46, 46, 49, 51, 51, 53, 54, 53, 58, 63, 63, 50]

Detect C2/C3 disk...
.. Peak found: z=81 (correlation = 0.267968327607)
/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Detect intervertebral discs...
Current disc: 2 (z=66). Direction: superior
.. Peak found: z=0 (correlation = 0.374293837659)
Current disc: 1 (z=97). Direction: superior
.. correcting factor: 1.0
.. Switching to inferior direction.
Current disc: 3 (z=29). Direction: inferior
.. Peak found: z=4 (correlation = 0.567550163509)
.. correcting factor: 0.945945945946
Adding top disc based on adjusted template distance: #0
.. approximate distance: 22

Un-straighten labeling...
sct_apply_transfo -i segmentation_straight_labeled.nii.gz -d segmentation.nii.gz -w warp_straight2curve.nii.gz -o segmentation_labeled.nii.gz -x nn # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
Running /Users/julien/code/sct/scripts/sct_apply_transfo.py -i segmentation_straight_labeled.nii.gz -d segmentation.nii.gz -w warp_straight2curve.nii.gz -o segmentation_labeled.nii.gz -x nn

Parse list of warping fields...
Transfo #0: warp_straight2curve.nii.gz

Get dimensions of data...
102 x 118 x 110 x 1

Apply transformation...
isct_antsApplyTransforms -d 3 -i segmentation_straight_labeled.nii.gz -o segmentation_labeled.nii.gz -t warp_straight2curve.nii.gz -r segmentation.nii.gz -n NearestNeighbor # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t

Done! To view results, type:
fsleyes segmentation.nii.gz segmentation_labeled.nii.gz &


Clean labeled segmentation (correct interpolation errors)...
sct_maths -i segmentation_labeled.nii.gz -mul segmentation.nii.gz -o segmentation_labeled_mul.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
sct_maths -i segmentation_labeled.nii.gz -dilate 2 -o segmentation_labeled_dilate.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
sct_maths -i segmentation_labeled_mul.nii.gz -bin 0 -o segmentation_labeled_mul_bin.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180513105506-label_vertebrae-U9mY9t
WARNING: File segmentation_labeled.nii.gz already exists. Deleting it.

Label discs...

Generate output files...
  File created: ./t2_seg_labeled.nii.gz
  File created: ./t2_seg_labeled_discs.nii.gz
  WARNING: File ./warp_curve2straight.nii.gz already exists. Deleting it...
  File created: ./warp_curve2straight.nii.gz
  WARNING: File ./warp_straight2curve.nii.gz already exists. Deleting it...
  File created: ./warp_straight2curve.nii.gz
  WARNING: File ./straight_ref.nii.gz already exists. Deleting it...
  File created: ./straight_ref.nii.gz
QC: layout with Sagittal slice
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/css/bootstrap.min.css /Users/julien/sct_testing_data/t2/qc/_assets/css
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/css/bootstrap-table.min.css /Users/julien/sct_testing_data/t2/qc/_assets/css
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/css/select2.min.css /Users/julien/sct_testing_data/t2/qc/_assets/css
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/css/bootstrap.min.css.map /Users/julien/sct_testing_data/t2/qc/_assets/css
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/css/style.css /Users/julien/sct_testing_data/t2/qc/_assets/css
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/css/bootstrap-theme.min.css /Users/julien/sct_testing_data/t2/qc/_assets/css
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/js/select2.min.js /Users/julien/sct_testing_data/t2/qc/_assets/js
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/js/jquery-3.1.0.min.js /Users/julien/sct_testing_data/t2/qc/_assets/js
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/js/bootstrap-table.min.js /Users/julien/sct_testing_data/t2/qc/_assets/js
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/js/main.js /Users/julien/sct_testing_data/t2/qc/_assets/js
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/js/bootstrap.min.js /Users/julien/sct_testing_data/t2/qc/_assets/js
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/js/animation.js /Users/julien/sct_testing_data/t2/qc/_assets/js
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/imgs/axial.png /Users/julien/sct_testing_data/t2/qc/_assets/imgs
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/imgs/sagittal.png /Users/julien/sct_testing_data/t2/qc/_assets/imgs
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/imgs/sct_logo.png /Users/julien/sct_testing_data/t2/qc/_assets/imgs
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/fonts/glyphicons-halflings-regular.woff /Users/julien/sct_testing_data/t2/qc/_assets/fonts
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/fonts/glyphicons-halflings-regular.eot /Users/julien/sct_testing_data/t2/qc/_assets/fonts
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/fonts/glyphicons-halflings-regular.woff2 /Users/julien/sct_testing_data/t2/qc/_assets/fonts
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/fonts/glyphicons-halflings-regular.ttf /Users/julien/sct_testing_data/t2/qc/_assets/fonts
cp /Users/julien/code/sct/spinalcordtoolbox/reports/assets/_assets/fonts/glyphicons-halflings-regular.svg /Users/julien/sct_testing_data/t2/qc/_assets/fonts
Sucessfully generated the QC results in /Users/julien/sct_testing_data/t2/qc/qc_results.json
Use the following command to see the results in a browser:
open file "/Users/julien/sct_testing_data/t2/qc/index.html"

Done! To view results, type:
fsleyes t2.nii.gz -a 100.0 ./t2_seg_labeled.nii.gz -cm random -a 50.0 &
```

</details>

**Comment by fperdigon** [comment]
@jcohenadad seems that was already fixed. Now is working as expected on my side. Closing this issue
