### ISSUE TITLE
Crash with -display If no label present

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1739]
### Description

When inputting a black image with `sct_label_utils -i BLACKIMAGE -display` the function lamentably crashes. A more elegant behaviour is advised.

~~~
sct_label_utils -i histo_landmarks.nii.gz -display

--
Spinal Cord Toolbox (jca_batchProc/0f02367a64f6061f1684e53a837fdab1d8aeb003)
Running /Users/julien/code/sct/scripts/sct_label_utils.py -i histo_landmarks.nii.gz -display
Configuring sentry report
sentry is set!
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 883, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 873, in main
    processor.process(process_type)
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 112, in process
    self.display_voxel()
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 544, in display_voxel
    coordinates_input = self.image_input.getNonZeroCoordinates(sorting='value')
  File "/Users/julien/code/sct/scripts/msct_image.py", line 504, in getNonZeroCoordinates
    list_coordinates = sorted(list_coordinates, key=lambda obj: obj.value, reverse=reverse_coord)
UnboundLocalError: local variable 'list_coordinates' referenced before assignment
~~~

**Comment by jcohenadad** [comment]
cannot reproduce error
