### ISSUE TITLE
UnboundLocalError: local variable 'z_centerline_voxel' referenced before assignment

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1791]
I think this issue is related to the centerline not being defined if the flag `-no-angle` is set to 1. Needs further investigations.

~~~
Spinal Cord Toolbox (master/fc72f34d4251de09d3e92071c66b40ac7fe4c92a)
Running /Users/julien/code/sct/scripts/sct_process_segmentation.py -i t2s_gmseg_manual.nii.gz -p csa -no-angle 1 -vert 4 -vertfile t1_seg_labeled_reg.nii.gz -ofolder csa_gm
Folder csa_gm has been created.

Check parameters:
.. segmentation file:             t2s_gmseg_manual.nii.gz

Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180530091520-LylRGO)...

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/data/spine_generic/20180509_julien-skyra/t2s/t2s_gmseg_manual.nii.gz -o /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180530091520-LylRGO/segmentation.nii.gz # in /Users/julien/data/spine_generic/20180509_julien-skyra/t2s

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180530091520-LylRGO

Open segmentation volume...

Get data dimensions...
  448 x 448 x 15

Compute CSA...

Smooth CSA across slices...
.. No smoothing!

Create volume of CSA values...

Create volume of angle values...
sct_image -i csa_volume_RPI.nii.gz -setorient RPI -o csa_volume_in_initial_orientation.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180530091520-LylRGO
sct_image -i angle_volume_RPI.nii.gz -setorient RPI -o angle_volume_in_initial_orientation.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180530091520-LylRGO

Generate output files...
  WARNING: File csa_gm/csa_image.nii.gz already exists. Deleting it...
  File created: csa_gm/csa_image.nii.gz
  WARNING: File csa_gm/angle_image.nii.gz already exists. Deleting it...
  File created: csa_gm/angle_image.nii.gz


Display CSA per slice:
z = 0, CSA = 16.000000 mm^2, Angle = 0.000000 deg
z = 1, CSA = 17.000000 mm^2, Angle = 0.000000 deg
z = 2, CSA = 18.000000 mm^2, Angle = 0.000000 deg
z = 3, CSA = 16.750000 mm^2, Angle = 0.000000 deg
z = 4, CSA = 15.250000 mm^2, Angle = 0.000000 deg
z = 5, CSA = 15.750000 mm^2, Angle = 0.000000 deg
z = 6, CSA = 15.500000 mm^2, Angle = 0.000000 deg
z = 7, CSA = 16.250000 mm^2, Angle = 0.000000 deg
z = 8, CSA = 16.000000 mm^2, Angle = 0.000000 deg
z = 9, CSA = 13.750000 mm^2, Angle = 0.000000 deg
z = 10, CSA = 14.500000 mm^2, Angle = 0.000000 deg
z = 11, CSA = 13.500000 mm^2, Angle = 0.000000 deg
z = 12, CSA = 13.000000 mm^2, Angle = 0.000000 deg
z = 13, CSA = 14.000000 mm^2, Angle = 0.000000 deg
z = 14, CSA = 13.500000 mm^2, Angle = 0.000000 deg
Save results in: csa_gm/csa_per_slice.txt

Save results in: csa_gm/csa_per_slice.pickle

Selected vertebral levels... 4
  OK: t1_seg_labeled_reg.nii.gz
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 1230, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 242, in main
    compute_csa(fname_segmentation, output_folder, overwrite, verbose, remove_temp_files, step, smoothing_param, slices, vert_lev, fname_vertebral_labeling, algo_fitting=param.algo_fitting, type_window=param.type_window, window_length=param.window_length, angle_correction=angle_correction, use_phys_coord=use_phys_coord)
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 827, in compute_csa
    slices, vert_levels_list, warning = get_slices_matching_with_vertebral_levels_based_centerline(vert_levels, im_vertebral_labeling.data, z_centerline_voxel)
UnboundLocalError: local variable 'z_centerline_voxel' referenced before assignment
~~~

**Comment by jcohenadad** [comment]
Further investigations using `sct_testing_data/t2`:
- `-i t2_seg.nii.gz -p csa -no-angle 1` --> PASS
