### ISSUE TITLE
Obscure error message in case cropping is outside of dimension

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1817]
### Description

Error when notifying the output filename in `sct_crop_image`

### Steps to Reproduce

```
cd /Volumes/sct_testing/issues/20180604_issue1817
sct_crop_image -i t2_ax_sup.nii.gz -start 14 -end 47 -dim 2 -o t2_ax_sup_crop.nii.gz

--
Spinal Cord Toolbox (master/ccd858d6a999fc6c2647ffcc969145d83a5e0123)
Running /Users/chgroc/spinalcordtoolbox/scripts/sct_crop_image.py -i t2_ax_sup.nii.gz -start 14 -end 47 -dim 2 -o t2_ax_sup_crop.nii.gz
isct_crop_image -i t2_ax_sup.nii.gz -o t2_ax_sup_crop.nii.gz -start 14.0 -end 47.0 -dim 2 # in /Volumes/sct_testing/issues/20180604_issue1817
Cropping the following region:
Dimension 0: 0 320
Dimension 1: 0 240
Dimension 2: 14 47
Exception caught while updating cropFilter

itk::InvalidRequestedRegionError (0x7fe122890e58)
Location: "unknown"
File: /Users/benjamindeleener/code/ITK/Modules/Core/Common/src/itkDataObject.cxx
Line: 393
Description: Requested region is (at least partially) outside the largest possible region.


Exception caught while updating writerCrop

itk::ImageFileWriterException (0x7fe122890e28)
Location: "unknown"
File: /usr/local/itk/include/ITK-4.8/itkImageFileWriter.hxx
Line: 408
Description: Did not get requested region!
Requested:
ImageRegion (0x7fff5cb9f940)
Dimension: 3
Index: [0, 0, 14]
Size: [320, 240, 34]
Actual:
ImageRegion (0x7fff5cb9f908)
Dimension: 3
Index: [0, 0, 0]
Size: [0, 0, 0]



Traceback (most recent call last):
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_crop_image.py", line 438, in <module>
    cropper.crop()
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_crop_image.py", line 113, in crop
    self.result = Image(self.output_filename, verbose=self.verbose)
  File "/Users/chgroc/spinalcordtoolbox/scripts/msct_image.py", line 226, in __init__
    self.loadFromPath(param, verbose)
  File "/Users/chgroc/spinalcordtoolbox/scripts/msct_image.py", line 290, in loadFromPath
    self.im_file = load(path)
  File "/Users/chgroc/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file: 't2_ax_sup_crop.nii.gz'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
### State of spinalcordtoolbox
```
Spinal Cord Toolbox (master/ccd858d6a999fc6c2647ffcc969145d83a5e0123)
```

**Comment by jcohenadad** [comment]
@charleygros are you sure the problem is related to the output file name? I see the error "itk::InvalidRequestedRegionError (0x7fe122890e58)" which might suggest that the start and/or end are outside the FOV (e.g., is there at least 47 slices in dim=2?)

**Comment by charleygros** [comment]
ok sorry.

**Comment by jcohenadad** [comment]
actually it is good that you opened this issue, because the generated error is ugly and very difficult to understand. So we should fix that :-)  I will reopen the issue and change the title.
