### ISSUE TITLE
No need to call Sentry if user quits with CTRL+C

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1844]
~~~
sct_download_data -d deepseg_sc_models

--
Spinal Cord Toolbox (cJ-misc/5fe166c4f750a32192ee110a3460a00e9f5ec1cf)
Running /Users/julien/code/sct/scripts/sct_download_data.py -d deepseg_sc_models

Trying URL: https://osf.io/mg8wr/?action=download
Downloading 20180211_deepseg_sc_models.zip...
Status:   0%|2                                                   | 172K/37.2M [00:00<02:58, 207KB/s]^C
ERROR: User canceled process.


Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_download_data.py", line 205, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_download_data.py", line 111, in main
    sct.printv('\nERROR: User canceled process.\n', 1, 'error')
  File "/Users/julien/code/sct/scripts/sct_utils.py", line 1093, in printv
    raise RuntimeError("printv(..., type=\"error\")")
RuntimeError: printv(..., type="error")
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
~~~

**Comment by zougloub** [comment]
Fixed by #1872
