### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'list' objects

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1848]
~~~
sct_image -i warp_template2anat.nii.gz -mcs -o warp_vec.nii.gz

--
Spinal Cord Toolbox (master/324589be1b9315c31cfc0248dbe0841f3659ac21)
Running /Users/julien/code/sct/scripts/sct_image.py -i warp_template2anat.nii.gz -mcs -o warp_vec.nii.gz
Generate output files...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_image.py", line 791, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_image.py", line 275, in main
    sct.display_viewer_syntax([fname_out])
  File "/Users/julien/code/sct/scripts/sct_utils.py", line 531, in display_viewer_syntax
    cmd += ' ' + files[i]
TypeError: cannot concatenate 'str' and 'list' objects
~~~

**Comment by abtahizadeh** [comment]
sct_image.py line 275, **fname_out** is already a list, i.e no need to convert the type:

`sct.display_viewer_syntax([fname_out])`
