### ISSUE TITLE
numpy.linalg.linalg.LinAlgError: singular matrix

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1863]
data: mgh-bay3_spine-generic_20171201/t2
~~~
Spinal Cord Toolbox (master/c1e4e9cefd485570916857e17f3703d728160f2a)
Running /Users/julien/code/sct/scripts/sct_process_segmentation.py -i t2_seg_manual.nii.gz -p csa -vert 2 -vertfile t1_seg_labeled_reg.nii.gz -ofolder csa

Check parameters:
.. segmentation file:             t2_seg_manual.nii.gz

Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180613161703-PkT5TR)...

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/code/spine_generic/mgh-bay3_spine-generic_20171201/t2/t2_seg_manual.nii.gz -o /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180613161703-PkT5TR/segmentation.nii.gz # in /Users/julien/code/spine_generic/mgh-bay3_spine-generic_20171201/t2

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180613161703-PkT5TR

Open segmentation volume...

Get data dimensions...
  64 x 320 x 320

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = nurbs

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 42.06 mm
Test: # of control points = 6
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 7
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 8
Error on approximation = 0.79 mm
Test: # of control points = 9
Error on approximation = 0.5 mm
Test: # of control points = 10
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 1231, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 242, in main
    compute_csa(fname_segmentation, output_folder, overwrite, verbose, remove_temp_files, step, smoothing_param, slices, vert_lev, fname_vertebral_labeling, algo_fitting=param.algo_fitting, type_window=param.type_window, window_length=param.window_length, angle_correction=angle_correction, use_phys_coord=use_phys_coord)
  File "/Users/julien/code/sct/scripts/sct_process_segmentation.py", line 647, in compute_csa
    x_centerline_fit, y_centerline_fit, z_centerline, x_centerline_deriv, y_centerline_deriv, z_centerline_deriv = smooth_centerline('segmentation_RPI.nii.gz', algo_fitting=algo_fitting, type_window=type_window, window_length=window_length, nurbs_pts_number=3000, phys_coordinates=True, verbose=verbose, all_slices=False)
  File "/Users/julien/code/sct/scripts/sct_straighten_spinalcord.py", line 157, in smooth_centerline
    z_centerline_deriv, mse = b_spline_nurbs(x_centerline, y_centerline, z_centerline, nbControl=None, path_qc=curdir, point_number=nurbs_pts_number, verbose=verbose, all_slices=all_slices)
  File "/Users/julien/code/sct/scripts/msct_smooth.py", line 298, in b_spline_nurbs
    nurbs = NURBS(degree, point_number, data, False, nbControl, verbose, all_slices=all_slices, twodim=twodim)
  File "/Users/julien/code/sct/scripts/msct_nurbs.py", line 152, in __init__
    self.pointsControle = self.reconstructGlobalApproximation(P_x, P_y, P_z, self.degre, self.nbControle, w)
  File "/Users/julien/code/sct/scripts/msct_nurbs.py", line 645, in reconstructGlobalApproximation
    P_xb = (R.T * W * R).I * Tx.T
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 972, in getI
    return asmatrix(func(self))
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/scipy/linalg/basic.py", line 687, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix
~~~

**Comment by jcohenadad** [comment]
workaround until fixed: use Hanning smoothing:
~~~
sct_process_segmentation -i t2_seg_manual.nii.gz -p csa -vert 2 -vertfile t1_seg_labeled_reg.nii.gz -ofolder csa -a
~~~
