### ISSUE TITLE
INSTALLATION on chinese computer

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1880]
### Prerequisites

* [ ] Did you check past issues for similar issue(s) ?
* [ ] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [ ] If you are using a development environment, is your environment updated ?

### Description

Cannot import tensorflow on a chinese computer. 
Solution: run `export LC_ALL=en_US.UTF-8` prior to installing and using deeplearning methods
see https://github.com/explosion/spaCy/issues/1517

### Steps to Reproduce

1. ./sct_install

### State of spinalcordtoolbox

version 3.2.1

**Comment by Hongcaicai** [comment]
error:
````
Spinal Cord Toolbox (version: 3.2.1)
Running /Users/liuhongcai/sct_3.2.1/scripts/sct_check_dependencies.py
SCT info:
- version: 3.2.1
- path: /Users/liuhongcai/sct_3.2.1
OS: osx (Darwin-15.6.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by SCT: 4
RAM: Primary memory available: 8.00 gigabytes
Check Python executable.............................[OK]
  Using bundled python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] at /Users/liuhongcai/sct_3.2.1/python/bin/python
Check if data are installed.........................[OK]
Check if xlwt (1.0.0) is installed..................[OK]
Check if xlutils (1.7.1) is installed...............[OK]
Check if cryptography (1.6) is installed............[OK]
Check if scikit-learn (0.17.1) is installed.........[OK]
Check if scikit-image (0.12.3) is installed.........[OK]
Check if pyqt (4.11.4) is installed.................[OK]
Check if psutil (5.2.2) is installed................[OK]
Check if matplotlib (1.5.1) is installed............Traceback (most recent call last):
  File "/Users/liuhongcai/sct_3.2.1/scripts/sct_check_dependencies.py", line 448, in <module>
    main()
  File "/Users/liuhongcai/sct_3.2.1/scripts/sct_check_dependencies.py", line 193, in main
    module = module_import(module_name, suppress_stderr)
  File "/Users/liuhongcai/sct_3.2.1/scripts/sct_check_dependencies.py", line 97, in module_import
    module = importlib.import_module(module_name)
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/liuhongcai/sct_3.2.1/python/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
````

**Comment by Hongcaicai** [comment]
thanks sct dev team!

**Comment by perone** [comment]
Duplicate of #1851, [context](https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/938bc133/?limit=25#d27d).

**Comment by tanguyduval** [comment]
not working on german swiss mac neither

**Comment by tanguyduval** [comment]
Works with @abtahizadeh tips, thx

**Comment by zougloub** [comment]
-> #1851
