### ISSUE TITLE
sct_testing gives WARNING instead of FAIL on crash

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1887]
### Description

`sct_testing` gives a WARNING even though the function crashed on execution. A FAIL was expected. I suspect this is because sct.run() (within sct_testing) output a status=0 even though the execution crashed (see OSError below).

### Steps to Reproduce

1. checkout 9c173c6a724dd1eb7609d9fcba8c9e79e7362fff
2. run `sct_testing -f sct_analyze_texture`

**Expected behavior:**

FAIL message

**Actual behavior:**

WARNING message

### Additional Information

~~~
sct_testing -f sct_analyze_texture

--
Spinal Cord Toolbox (jca_extractMetric/9c173c6a724dd1eb7609d9fcba8c9e79e7362fff)
Running /Users/julien/code/sct/scripts/sct_testing.py -f sct_analyze_texture

Path to testing data: /Users/julien/sct_testing_data
Checking sct_analyze_texture........................[WARNING]
   
   ====================================================================================================
   sct_analyze_texture -feature contrast -m /Users/julien/sct_testing_data/t2/t2_seg.nii.gz -i /Users/julien/sct_testing_data/t2/t2.nii.gz -r 1 -ofolder . -dim ax -v 1 -igt /Users/julien/sct_testing_data/t2/t2_contrast_1_mean_ref.nii.gz -distance 1 -angle 0,45,90,135
   ====================================================================================================
   
   Running /Users/julien/code/sct/scripts/sct_analyze_texture.py -feature contrast -m /Users/julien/sct_testing_data/t2/t2_seg.nii.gz -i /Users/julien/sct_testing_data/t2/t2.nii.gz -r 1 -ofolder . -dim ax -v 1 -igt /Users/julien/sct_testing_data/t2/t2_contrast_1_mean_ref.nii.gz -distance 1 -angle 0,45,90,135
   Folder . has been created.
   
   Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180627143323-TfhoWP)...
   cp /Users/julien/sct_testing_data/t2/t2.nii.gz /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180627143323-TfhoWP
   cp /Users/julien/sct_testing_data/t2/t2_seg.nii.gz /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180627143323-TfhoWP
   
   Compute texture metrics...
   Remaining time: 00:00:05.00 (1/55)                      
   Remaining time: 00:00:04.84 (2/55)                      
   Remaining time: 00:00:04.85 (3/55)                      
   Remaining time: 00:00:04.98 (4/55)                      
   Remaining time: 00:00:04.98 (5/55)                      
   Remaining time: 00:00:04.87 (6/55)                      
   Remaining time: 00:00:04.78 (7/55)                      
   Remaining time: 00:00:04.69 (8/55)                      
   Remaining time: 00:00:04.60 (9/55)                      
   Remaining time: 00:00:04.55 (10/55)                      
   Remaining time: 00:00:04.52 (11/55)                      
   Remaining time: 00:00:04.48 (12/55)                      
   Remaining time: 00:00:04.43 (13/55)                      
   Remaining time: 00:00:04.36 (14/55)                      
   Remaining time: 00:00:04.27 (15/55)                      
   Remaining time: 00:00:04.19 (16/55)                      
   Remaining time: 00:00:04.10 (17/55)                      
   Remaining time: 00:00:04.01 (18/55)                      
   Remaining time: 00:00:03.92 (19/55)                      
   Remaining time: 00:00:03.84 (20/55)                      
   Remaining time: 00:00:03.75 (21/55)                      
   Remaining time: 00:00:03.67 (22/55)                      
   Remaining time: 00:00:03.58 (23/55)                      
   Remaining time: 00:00:03.48 (24/55)                      
   Remaining time: 00:00:03.39 (25/55)                      
   Remaining time: 00:00:03.29 (26/55)                      
   Remaining time: 00:00:03.19 (27/55)                      
   Remaining time: 00:00:03.09 (28/55)                      
   Remaining time: 00:00:02.98 (29/55)                      
   Remaining time: 00:00:02.88 (30/55)                      
   Remaining time: 00:00:02.77 (31/55)                      
   Remaining time: 00:00:02.67 (32/55)                      
   Remaining time: 00:00:02.55 (33/55)                      
   Remaining time: 00:00:02.44 (34/55)                      
   Remaining time: 00:00:02.34 (35/55)                      
   Remaining time: 00:00:02.22 (36/55)                      
   Remaining time: 00:00:02.10 (37/55)                      
   Remaining time: 00:00:01.99 (38/55)                      
   Remaining time: 00:00:01.88 (39/55)                      
   Remaining time: 00:00:01.76 (40/55)                      
   Remaining time: 00:00:01.64 (41/55)                      
   Remaining time: 00:00:01.52 (42/55)                      
   Remaining time: 00:00:01.40 (43/55)                      
   Remaining time: 00:00:01.28 (44/55)                      
   Remaining time: 00:00:01.16 (45/55)                      
   Remaining time: 00:00:01.05 (46/55)                      
   Remaining time: 00:00:00.93 (47/55)                      
   Remaining time: 00:00:00.81 (48/55)                      
   Remaining time: 00:00:00.69 (49/55)                      
   Remaining time: 00:00:00.58 (50/55)                      
   Remaining time: 00:00:00.46 (51/55)                      
   Remaining time: 00:00:00.35 (52/55)                      
   Remaining time: 00:00:00.23 (53/55)                      
   Remaining time: 00:00:00.12 (54/55)                      
   Remaining time: 00:00:00.00 (55/55)
   Total time: 00:00:06.36
   WARNING: File t2.nii_contrast_.nii.gz already exists. Deleting it.
   Traceback (most recent call last):
   File "/Users/julien/code/sct/scripts/sct_analyze_texture.py", line 349, in <module>
   main()
   File "/Users/julien/code/sct/scripts/sct_analyze_texture.py", line 337, in main
   fname_out_lst = glcm.extract()
   File "/Users/julien/code/sct/scripts/sct_analyze_texture.py", line 133, in extract
   self.reorient_data()
   File "/Users/julien/code/sct/scripts/sct_analyze_texture.py", line 270, in reorient_data
   os.rename(self.fname_metric_lst[f], add_suffix(''.join(extract_fname(self.param.fname_im)[1:]), '_2reorient'))
   OSError: [Errno 2] No such file or directory
   Sentry is attempting to send 1 pending error messages
   Waiting up to 10 seconds
   Press Ctrl-C to quit
   Total processing time: 0 min 9 s
   
   ====================================================================================================
   INTEGRITY TESTING
   ====================================================================================================
   
   No such file: 't2.nii_contrast_1_mean.gz'
status: [99]
Finished! Elapsed time: 9s

Total processing time: 0 min 10 s
~~~

**Comment by zougloub** [comment]
Can't reproduce. I added an exception in master in reorient_data() and the status is 1.
Please confirm.

**Comment by jcohenadad** [comment]
i confirm it is working fine now (tested on latest master commit 925987e5b179a67cdc95ea9bc10aa7e4758c69d2).
