### ISSUE TITLE
`sct_testing` fails on `sct_register_graymatter` with exception error ...

### ISSUE THREAD

**Issue by abtahizadeh** [neuropoly/spinalcordtoolbox#1900]
When running `sct_testing -d 1` there is a failure on:

<img width="550" alt="screen shot 2018-07-03 at 2 48 06 pm" src="https://user-images.githubusercontent.com/12260844/42238909-59b64c06-7ed0-11e8-99bd-a819be68683e.png">

Log:

<img width="1085" alt="screen shot 2018-07-03 at 2 55 27 pm" src="https://user-images.githubusercontent.com/12260844/42239190-33b4e4ee-7ed1-11e8-9a4c-bad6b36dd390.png">

OS: `Ubuntu` / installation `successful` / Branch: `master`

**Comment by jcohenadad** [comment]
@abtahizadeh please indicate commit number. In the future i suggest to copy/paste the whole terminal output (instead of screenshots, which takes up more physical space and hide useful info, such as commit #).

**Comment by abtahizadeh** [comment]
@jcohenadad I was about to put the full log in an external link, you just replied too fast!
anyway, I put them here:

```
 ====================================================================================================
   sct_register_graymatter -qc 1 -manual-gm /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg_goldstandard.nii.gz -gm /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg.nii.gz -t /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/label/ -w /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/warp_template2mt.nii.gz -v 1 -r 1 -param step=1,type=seg,algo=centermassrot,metric=MeanSquares:step=2,type=im,algo=syn,metric=MeanSquares,iter=3,smooth=0,shrink=2 -sc /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_seg.nii.gz -wm /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_wmseg.nii.gz -ofolder /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi
   ====================================================================================================
   
   Running /home/osboxes/spinalcordtoolbox/scripts/sct_register_graymatter.py -qc 1 -manual-gm /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg_goldstandard.nii.gz -gm /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg.nii.gz -t /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/label/ -w /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/warp_template2mt.nii.gz -v 1 -r 1 -param step=1,type=seg,algo=centermassrot,metric=MeanSquares:step=2,type=im,algo=syn,metric=MeanSquares,iter=3,smooth=0,shrink=2 -sc /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_seg.nii.gz -wm /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_wmseg.nii.gz -ofolder /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi
   Folder /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi has been created.
   OK: /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/label/
   
   Create temporary folder (/tmp/sct-180703145846-ti1ezO)...
   sct_convert -i /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg.nii.gz -o /tmp/sct-180703145846-ti1ezO/mt1_gmseg.nii.gz
   sct_convert -i /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/warp_template2mt.nii.gz -o /tmp/sct-180703145846-ti1ezO/warp_template2mt.nii.gz
   sct_create_mask -i multilabel_automatic_seg.nii.gz -p centerline,multilabel_automatic_seg.nii.gz -f box -size 26 -o square_mask.nii.gz # in /tmp/sct-180703145846-ti1ezO
   sct_crop_image -i multilabel_automatic_seg.nii.gz -m square_mask.nii.gz -o multilabel_automatic_seg_crop.nii.gz # in /tmp/sct-180703145846-ti1ezO
   sct_crop_image -i multilabel_template_seg.nii.gz -m square_mask.nii.gz -o multilabel_template_seg_crop.nii.gz # in /tmp/sct-180703145846-ti1ezO
   sct_maths -i multilabel_template_seg_crop.nii.gz -bin 0 -o multilabel_template_seg_crop_bin.nii.gz # in /tmp/sct-180703145846-ti1ezO
   sct_maths -i multilabel_automatic_seg_crop.nii.gz -bin 50 -o multilabel_automatic_seg_crop_bin.nii.gz # in /tmp/sct-180703145846-ti1ezO
   sct_register_multimodal -i multilabel_template_seg_crop.nii.gz -d multilabel_automatic_seg_crop.nii.gz -param step=1,type=seg,algo=centermassrot,metric=MeanSquares:step=2,type=im,algo=syn,metric=MeanSquares,iter=3,smooth=0,shrink=2 -iseg multilabel_template_seg_crop_bin.nii.gz -dseg multilabel_automatic_seg_crop_bin.nii.gz # in /tmp/sct-180703145846-ti1ezO
   sct_concat_transfo -w warp_template2mt.nii.gz,warp_multilabel_template_seg_crop2multilabel_automatic_seg_crop.nii.gz -d mt1_gmseg.nii.gz -o warp_template2mt_reg_gm.nii.gz # in /tmp/sct-180703145846-ti1ezO
   File created: /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi/warp_template2mt_reg_gm.nii.gz
   
   Create temporary folder (/tmp/sct-180703145855-C65KIu)...
   sct_resample -i grid_3.nii.gz -f 3x3x1 -x nn -o grid_3_resample.nii.gz # in /tmp/sct-180703145855-C65KIu
   sct_apply_transfo -i /tmp/sct-180703145855-C65KIu/grid_3_resample.nii.gz -d /tmp/sct-180703145855-C65KIu/grid_3_resample.nii.gz -w /tmp/sct-180703145846-ti1ezO/warp_multilabel_template_seg_crop2multilabel_automatic_seg_crop.nii.gz -o /tmp/sct-180703145846-ti1ezO/grid_warped_gm.nii.gz # in /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi
   rm -rf /tmp/sct-180703145855-C65KIu
   File created: /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi/grid_warped_gm.nii.gz
   rm -rf /tmp/sct-180703145846-ti1ezO
   
   Create temporary folder (/tmp/sct-180703145857-mcP_w2)...
   cp /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg_goldstandard.nii.gz /tmp/sct-180703145857-mcP_w2/mt1_gmseg_goldstandard.nii.gz
   cp /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_seg.nii.gz /tmp/sct-180703145857-mcP_w2/mt1_seg.nii.gz
   cp /tmp/sct-180703145846-sct_register_graymatter_sct_testing_data-MM0lIi/warp_template2mt_reg_gm.nii.gz /tmp/sct-180703145857-mcP_w2/warp_template2mt_reg_gm.nii.gz
   sct_warp_template -d /home/osboxes/spinalcordtoolbox/sct_testing_data/mt/mt1_gmseg_goldstandard.nii.gz -w warp_template2mt_reg_gm.nii.gz -a 0 # in /tmp/sct-180703145857-mcP_w2
   sct_maths -i mt1_seg.nii.gz -sub mt1_gmseg_goldstandard.nii.gz -o target_manual_wmseg.nii.gz # in /tmp/sct-180703145857-mcP_w2
   sct_compute_hausdorff_distance -i old_template_gm.nii.gz -r mt1_gmseg_goldstandard.nii.gz -t 1 -v 1 # in /tmp/sct-180703145857-mcP_w2
   sct_compute_hausdorff_distance -i new_template_gm.nii.gz -r mt1_gmseg_goldstandard.nii.gz -t 1 -v 1 # in /tmp/sct-180703145857-mcP_w2
   Traceback (most recent call last):
   File "/home/osboxes/spinalcordtoolbox/scripts/sct_register_graymatter.py", line 597, in <module>
   ml_reg.validation(fname_manual_gmseg, fname_sc_seg)
   File "/home/osboxes/spinalcordtoolbox/scripts/sct_register_graymatter.py", line 266, in validation
   i_old, val_old = old_gm_hd[i].split(':')
   ValueError: need more than 1 value to unpack
   Total processing time: 0 min 27 s
```

**Comment by jcohenadad** [comment]
@abtahizadeh i meant the commit number (to know which version you are running).

your bug seems related to https://github.com/neuropoly/spinalcordtoolbox/pull/1875/commits/f157a741d0511174172ad5fdb7c7794ce5a32013

**Comment by abtahizadeh** [comment]
Yes, it's the commit, thanks for your update on this.

**Comment by jcohenadad** [comment]
since `sct_register_graymatter` is becoming obsolete, i suggest we don't waste time trying to band-aid `test_sct_register_graymatter` code (which is pretty old). I would simply suggest to remove it from the test, and eventually we should remove this function from SCT.
