### ISSUE TITLE
Error while using sct_deepseg_sc on the example data

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1921]
I executed the following command:

    sct_deepseg_sc -centerline cnn -kernel 3d -i t2s.nii.gz -c t2s -ofolder m

On the `t2s.nii.gz` from the example data and it triggered the following error:

```
--
Spinal Cord Toolbox (master/f4d917a91cd2834a8d9cf5ee43a1edb2c4d7de63)
Running /Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py -centerline cnn -kernel 3d -i t2s.nii.gz -c t2s -ofolder m2

Method:
	Centerline algorithm: cnn
	Assumes brain section included in the image: False
	Dimension of the segmentation kernel convolutions: 3d

Creating temporary folder...
cp t2s.nii.gz /var/folders/pz/v62wv2tx0gbcj5cc3c62jkhc0000gn/T/sct-180712144620-C0t7iL
Reorient the image to RPI, if necessary...
WARNING: File t2s_RPI.nii.gz already exists. Deleting it.
Resample the image to 0.5 mm isotropic resolution...
/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/site-packages/nipy/io/files.py:145: FutureWarning: Default `strict` currently False; this will change to True in a future version of nipy
  ni_img = nipy2nifti(img, data_dtype = io_dtype)
Finding the spinal cord centerline...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
isct_spine_detect -ctype="dpdt" -lambda="7" "NONE" "t2s_RPI_resampled_heatmap" "t2s_RPI_resampled_heatmap" # in /private/var/folders/pz/v62wv2tx0gbcj5cc3c62jkhc0000gn/T/sct-180712144620-C0t7iL
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 3D patches...
Segmenting the spinal cord using deep learning on 3D patches...
/Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py:494: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if z_idx[x_cOm, y_cOm]:
Traceback (most recent call last):
  File "/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/cProfile.py", line 199, in <module>
    main()
  File "/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/cProfile.py", line 192, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/Users/perone/Devel/sct_deepgmseg/python/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "/Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py", line 807, in <module>
    main()
  File "/Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py", line 798, in main
    remove_temp_files=remove_temp_files, verbose=verbose)
  File "/Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py", line 679, in deep_segmentation_spinalcord
    fname_out=fname_seg_crop_res)
  File "/Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py", line 535, in segment_3d
    pred_seg_pp = post_processing_slice_wise(pred_seg_th[:, :, zz_pp], x_cOm, y_cOm)
  File "/Users/perone/Devel/sct_deepgmseg/scripts/sct_deepseg_sc.py", line 494, in post_processing_slice_wise
    if z_idx[x_cOm, y_cOm]:
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 96
Total processing time: 0 min 54 s
```

**Comment by perone** [comment]
More information: only happens when using the 3D network.
