### ISSUE TITLE
Combined labeling for non-sequential label IDs 

### ISSUE THREAD

**Issue by Aaronearlerichardson** [neuropoly/spinalcordtoolbox#1949]
I am trying to extract DTI metrics from dorsal, intermediate, and ventral white matter columns but I want to extract separate outputs for right versus left. I tried editing the info_label.txt file an added the following lines under the already existing combined labels as is described in issue #1807. 

```
56, left dorsal WM, 0,2
57, right dorsal WM, 1,3
58, left intermediate WM, 4,6,8,10,12
59, right intermediate WM, 5,7,9,11,13
60, left ventral WM, 14,16,18,20,22,24,26,28
61, right ventral WM, 15,17,19,21,23,25,27,29
```

None of these new labels seem to work for sct_extract_metric. Did I do this correctly or is there another way?

**Comment by jcohenadad** [comment]
Hi @Aaronearlerichardson which `info_label.txt` file did you edit? you need to edit the one under your metrics working directory (the one generated by `sct_warp_template`). If you do so, it should work, e.g.:
~~~
sct_extract_metric -l 56 -i mtr.nii.gz 

--
Spinal Cord Toolbox (jca/1920-process_seg-csa-perslice/36a2d957e6de90735c11478e3d6ed12ba1e4e76f)
Running /Users/julien/code/sct/scripts/sct_extract_metric.py -l 56 -i mtr.nii.gz

Checked parameters:
  data ...................... mtr.nii.gz
  path to label ............. label/atlas
  label ..................... 56
  method .................... wath
  slices of interest ........ 
  vertebral levels .......... 
  vertebral labeling file.... ./label/template/PAM50_levels.nii.gz
  advanced parameters ....... ['10', '10']


Load metric image...
WARNING: labels #10 contains only null voxels. Mean and std are set to 0.
WARNING: labels #11 contains only null voxels. Mean and std are set to 0.
WARNING: labels #26 contains only null voxels. Mean and std are set to 0.
WARNING: labels #27 contains only null voxels. Mean and std are set to 0.
WARNING: labels #28 contains only null voxels. Mean and std are set to 0.
WARNING: labels #29 contains only null voxels. Mean and std are set to 0.

Saving results in: metric_label.txt ...
	Done.

Results:
ID, label name [total fractional volume of the label in number of voxels]:    metric value +/- metric STDEV within label
56, left dorsal WM [183.74]:    54.6115741778 +/- 4.73656276218
Total processing time: 0 min 1 s
~~~

**Comment by Aaronearlerichardson** [comment]
According to set_warp_template I am using the default file path which is: `/Users/spineimaging/sct_3.2.2/data/PAM50`
and the info file I edited is 
`/Users/spineimaging/sct_3.2.2/data/PAM50/atlas/info_label.txt` 
This file is attached at the bottom.
This is what I got when I tried to run set_extract_metric
```
Spinal Cord Toolbox (version: 3.2.2)
Running /Users/spineimaging/sct_3.2.2/scripts/sct_extract_metric.py -i mtr.nii.gz -perslice 1 -method map -l 56 -o /Users/spineimaging/Desktop/Pipeline_results_temp/001C_2/MTR_in_RDWM.xls

Checked parameters:
  data ...................... mtr.nii.gz
  path to label ............. label/atlas
  label ..................... 56
  method .................... map
  slices of interest ........ 
  vertebral levels .......... 
  vertebral labeling file.... ./label/template/PAM50_levels.nii.gz
  advanced parameters ....... ['10', '10']


ERROR: At least one of the selected labels ([56]) is not available according to the label list from the text file in the atlas folder. Exit program.


Traceback (most recent call last):
  File "/Users/spineimaging/sct_3.2.2/scripts/sct_extract_metric.py", line 1195, in <module>
    fname_mask_weight, fname_vertebral_labeling=fname_vertebral_labeling, perslice=perslice, perlevel=perlevel)
  File "/Users/spineimaging/sct_3.2.2/scripts/sct_extract_metric.py", line 325, in main
    labels_id_user = check_labels(indiv_labels_ids + combined_labels_ids, parse_num_list(labels_user))
  File "/Users/spineimaging/sct_3.2.2/scripts/sct_extract_metric.py", line 853, in check_labels
    sct.printv('\nERROR: At least one of the selected labels (' + str(list_ids_of_labels_of_interest) + ') is not available according to the label list from the text file in the atlas folder. Exit program.\n\n', type='error')
  File "/Users/spineimaging/sct_3.2.2/scripts/sct_utils.py", line 1089, in printv
    raise RuntimeError("printv(..., type=\"error\")")
RuntimeError: printv(..., type="error")
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
```
[info_label.txt](https://github.com/neuropoly/spinalcordtoolbox/files/2210536/info_label.txt)

**Comment by jcohenadad** [comment]
@Aaronearlerichardson, `sct_warp_template` default is indeed `/Users/spineimaging/sct_3.2.2/data/PAM50/atlas/info_label.txt`, while `sct_extract_metric` default is `./label/atlas/info_label.txt`. Therefore, the file that you edited was not considered by `sct_extract_metric`. You have two options:

 **Option 1:**
- Edit `/Users/spineimaging/sct_3.2.2/data/PAM50/atlas/info_label.txt`
- Run `sct_warp_template`
- Run `sct_extract_metric -l 56 -i METRIC`

**Option 2:**
- Run `sct_warp_template`
- Edit `./atlas/info_label.txt`
- Run `sct_extract_metric -l 56 -i METRIC`

For more information, please see p91 of the [SCT Course Paris'18](https://osf.io/386h7/).

**Comment by Aaronearlerichardson** [comment]
It worked, thank you!
