### ISSUE TITLE
sct_apply_transfo: Error when inputing non-image files as transformation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1999]
### Description

A recent bug was introduced (after v3.2.3), which prevents `sct_apply_transfo` to input .txt (affine-type) as transformation (flag -w). 

A possible solution would be to accept back .txt.

### Steps to Reproduce

~~~
cd sct_testing_data/t2
sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -ldisc labels.nii.gz -ref subject
~~~

Output:

<details>

~~~
--
Spinal Cord Toolbox (master/53187cf96ac3bc5e39b5fcec48d5a8d292d2435b)
Running /Users/julien/code/sct/scripts/sct_register_to_template.py -i t2.nii.gz -s t2_seg.nii.gz -ldisc labels.nii.gz -ref subject

Check template files...
  OK: /Users/julien/code/sct/data/PAM50/template/PAM50_t2.nii.gz
  OK: /Users/julien/code/sct/data/PAM50/template/PAM50_levels.nii.gz
  OK: /Users/julien/code/sct/data/PAM50/template/PAM50_cord.nii.gz

Check parameters:
  Data:                 t2.nii.gz
  Landmarks:            labels.nii.gz
  Segmentation:         t2_seg.nii.gz
  Path template:        /Users/julien/code/sct/data/PAM50
  Remove temp files:    0

Check input labels...

Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4)...

Copying input data to tmp folder and convert to nii...
WARNING: File /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4/template_label.nii.gz already exists. Will overwrite it.

Check if provided labels are available in the template

Binarize segmentation
sct_maths -i seg.nii.gz -bin 0.5 -o seg_bin.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4

Change orientation of input images to RPI...

Remove unused label on template. Keep only label present in the input label image...
sct_label_utils -i template_label.nii.gz -o template_label.nii.gz -remove /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4/label_projected_rpi.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4
WARNING: File /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4/label_projected_rpi.nii.gz already exists. Will overwrite it.
WARNING: File /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4/template_label.nii.gz already exists. Will overwrite it.

Estimate transformation for step #0...
Labels src: [[-0.0, -0.0, 179.5], [-0.0, -0.0, 142.5], [5.0, -0.0, 179.5]]
Labels dest: [[7.2192840576171875, -1.7866058349609375, 24.678329467773438], [7.2192840576171875, -0.7866058349609375, -10.321670532226562], [12.219284057617188, -1.7866058349609375, 24.678329467773438]]
Degrees of freedom (dof): Tx_Ty_Tz_Rx_Ry_Rz_Sz
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 8
         Function evaluations: 817
Matrix:
[[  1.00000000e+00  -1.10761821e-12  -9.69881466e-14]
 [  1.10993636e-12   9.99592086e-01   2.85597739e-02]
 [  6.53152582e-14  -2.85597739e-02   9.99592086e-01]]
Center:
[  8.88595072  -1.4532725   13.0116628 ]
Translation:
[[  -7.21928406    1.4532725   154.15500387]]

Estimate transformation for step #1...
sct_apply_transfo -i template_seg.nii.gz -d /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4/seg_bin_rpi.nii.gz -w template2subjectAffine.txt -o template_seg_regStep0.nii.gz -x nn # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_register_to_template.py", line 802, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_register_to_template.py", line 612, in main
    sct.run(['sct_apply_transfo', '-i', src, '-d', dest, '-w', ','.join(warp_forward), '-o', add_suffix(src, '_regStep' + str(i_step - 1)), '-x', interp_step], verbose)
  File "/Users/julien/code/sct/scripts/sct_utils.py", line 472, in run
    raise RunError(output)
sct_utils.RunError: Running /Users/julien/code/sct/scripts/sct_apply_transfo.py -i template_seg.nii.gz -d /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20180814223811.149075-register_to_template-vVOvw4/seg_bin_rpi.nii.gz -w template2subjectAffine.txt -o template_seg_regStep0.nii.gz -x nn

Parse list of warping fields...
Error: make sure template2subjectAffine.txt is an image.
Traceback (most recent call last):
File "/Users/julien/code/sct/scripts/sct_apply_transfo.py", line 304, in <module>
main()
File "/Users/julien/code/sct/scripts/sct_apply_transfo.py", line 294, in main
transform.apply()
File "/Users/julien/code/sct/scripts/sct_apply_transfo.py", line 136, in apply
if msct_image.Image(fname_warp_list[idx_warp]).header.get_intent()[0] != 'vector':
File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 231, in __init__
self.loadFromPath(param, verbose)
File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 316, in loadFromPath
sct.printv('Error: make sure ' + path + ' is an image.', 1, 'error')
File "/Users/julien/code/sct/scripts/sct_utils.py", line 1012, in printv
raise RuntimeError("printv(..., type=\"error\")")
RuntimeError: printv(..., type="error")
No handlers could be found for logger "sentry.errors"
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 2 s
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
No handlers could be found for logger "sentry.errors"
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 13 s
~~~

</details>

**Comment by jcohenadad** [comment]
BTW: we could take this opportunity to add this scenario in `test_sct_register_to_template`

**Comment by jcohenadad** [comment]
additional info: i noticed in `sct_apply_transfo` v3.2.3 that the description for `-w` was "warping field", which was obviously wrong (because we do want to accept .txt). So i suggest we change this description for "Transformation, including warping field or affine transfo."

**Comment by zougloub** [comment]
Oops, I hadn't realized a warping field could be something else than an Image.
