### ISSUE TITLE
Better management of error message if user inputs non-3D data

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#2019]
### Description
IndexError when resampling data with `resample/nipy_resample.py`.

### Steps to Reproduce
SCT used:
```
Spinal Cord Toolbox (master/c878a7b270e998cf4a441c80e029e239df43cba6)
Running /home/charley/spinalcordtoolbox/scripts/sct_check_dependencies.py
SCT info:
- version: git-master-c878a7b270e998cf4a441c80e029e239df43cba6*
- path: /home/charley/spinalcordtoolbox
OS: linux (Linux-4.15.0-33-generic-x86_64-with-debian-stretch-sid)
```

1. Go to data folder:
```
cd /Volumes/sct_testing/issues/20181009_i2019/20180709_001-CG/t2s/
```

2. Run `sct_deepseg_sc` (note: same behaviour using `sct_deepseg_gm`):
```
sct_deepseg_sc -i t2s.nii.gz -c t2s
```

Output:
```
--
Spinal Cord Toolbox (master/c878a7b270e998cf4a441c80e029e239df43cba6)
Running /home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py -i t2s.nii.gz -c t2s

Method:
	Centerline algorithm: svm
	Assumes brain section included in the image: False
	Dimension of the segmentation kernel convolutions: 2d

Creating temporary folder...
cp t2s.nii.gz /tmp/sct-20180910101459.848306-83TiqJ
Reorient the image to RPI, if necessary...
cp /tmp/sct-20180910101459.848306-83TiqJ/t2s.nii.gz t2s_RPI.nii.gz
Resample the image to 0.5 mm isotropic resolution...
Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 811, in <module>
    main()
  File "/home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 802, in main
    remove_temp_files=remove_temp_files, verbose=verbose)
  File "/home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 636, in deep_segmentation_spinalcord
    'mm', 'linear', verbose=0)
  File "/home/charley/spinalcordtoolbox/spinalcordtoolbox/resample/nipy_resample.py", line 155, in resample_file
    interpolation, verbose)
  File "/home/charley/spinalcordtoolbox/spinalcordtoolbox/resample/nipy_resample.py", line 123, in resample_image
    arr_r3d = arr_r[:, :, :, it]
IndexError: index 2 is out of bounds for axis 3 with size 2
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 25 s
```

**Comment by jcohenadad** [comment]
This bug is due to the input image which is 4D instead of 3D (multiecho data). A workaround is to split the data and only use the first echo for input in SCT:
~~~
sct_image -i t2s.nii.gz -split t 
sct_deepseg_sc -i t2s_T0000.nii.gz -c t2s
~~~

note: while it would be possible (even encouraged) to average all echoes in order to gain SNR, it is not recommended in this specific dataset, which as acquired with alternating polarities, resulting in very large inter-echo A-P shift.

I've renamed this issue to make it a feature request instead, where the user would be informed of the wrong input image type instead of spitting out a cryptic error message.

**Comment by joshuacwnewton** [comment]
`spinalcordtoolbox/resample/nipy_resample.py` was refactored into `spinalcordtoolbox/resampling.py` in #2157, and has undergone many changes since. The section of the codebase that triggered this error no longer exists, so I don't believe this GH issue (as written) is useful anymore, hence closing.
