### ISSUE TITLE
AttributeError: sct_straighten_spinalcord when ldisc_dest and ldisc_input are provided

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#2023]
### Description

I got the below error because of these 2 lines of `sct_straighten_spinalcord`:
- https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L452
- https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L462
--> `*.transfo_pix2phys()` outputs a numpy array, while the above lines expect a list.

### Steps to Reproduce

1. https://github.com/neuropoly/template
--> using the branch `master`

2. `python pipeline.py`
```
(/home/charley/spinalcordtoolbox/python) charley@charley:~/code/exvivo_atlas/template$ python pipeline.py 
/home/charley/code/exvivo_atlas/template/data/
Status: 100%|################################################################################################| 5.00/5.00 [02:45<00:00, 32.8s/B]
Status:   0%|                                                                                                       | 0.00/5.00 [00:00<?, ?B/s]Traceback (most recent call last):
  File "pipeline.py", line 29, in <module>
    straighten_all_subjects(dataset_info=dataset_info, contrast='t1')
  File "/home/charley/code/exvivo_atlas/template/preprocessing.py", line 509, in straighten_all_subjects
    ' -param threshold_distance=1', verbose=1)
  File "/home/charley/spinalcordtoolbox/scripts/sct_utils.py", line 476, in run
    raise RunError(output)
sct_utils.RunError: Running /home/charley/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py -i t1.nii.gz -s t1_centerline_manual.nii.gz -ldisc_input t1_disks_manual.nii.gz -dest /home/charley/code/exvivo_atlas/template/data/template/template_centerline.nii.gz -ldisc_dest /home/charley/code/exvivo_atlas/template/data/template/template_disks.nii.gz -disable-straight2curved -param threshold_distance=1
/home/charley/spinalcordtoolbox

Check input arguments:
Input volume ...................... t1.nii.gz
Centerline ........................ t1_centerline_manual.nii.gz
Final interpolation ............... spline
Verbose ........................... 1


Create temporary folder (/tmp/sct-20180910163626.284849-straighten_spinalcord-aPEpax)...

Copy files to tmp folder...

Orient centerline to RPI orientation...

Get dimensions...
.. matrix size: 173 x 265 x 663
.. voxel size:  1.0mm x 1.0mm x 1.0mm

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = nurbs

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 143.22 mm
Test: # of control points = 6
Error on approximation = 70.1 mm
Test: # of control points = 7
Error on approximation = 65.7 mm
Test: # of control points = 8
Error on approximation = 12.06 mm
Test: # of control points = 9
Error on approximation = 2.91 mm
Test: # of control points = 10
Error on approximation = 2.66 mm
Test: # of control points = 11
Error on approximation = 1.62 mm
Test: # of control points = 12
Error on approximation = 1.3 mm
Test: # of control points = 13
Error on approximation = 0.79 mm
Test: # of control points = 14
Error on approximation = 0.48 mm
Test: # of control points = 15
Error on approximation = 0.31 mm
Test: # of control points = 16
Error on approximation = 0.33 mm
Test: # of control points = 17
Error on approximation = 0.28 mm
Test: # of control points = 18
Error on approximation = 0.27 mm
Test: # of control points = 19
Error on approximation = 0.26 mm
Test: # of control points = 20
Error on approximation = 0.25 mm
Test: # of control points = 21
Error on approximation = 0.24 mm
Test: # of control points = 22
Error on approximation = 0.23 mm
Test: # of control points = 23
Error on approximation = 0.23 mm
Test: # of control points = 24
Error on approximation = 0.23 mm
Number of control points of the optimal NURBS = 24

Create the straight space and the safe zone...

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = nurbs

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 0.04 mm
Test: # of control points = 6
Error on approximation = 0.04 mm
Test: # of control points = 7
Error on approximation = 0.04 mm
Test: # of control points = 8
Error on approximation = 0.04 mm
Test: # of control points = 9
Error on approximation = 0.04 mm
Test: # of control points = 10
Error on approximation = 0.04 mm
Test: # of control points = 11
Error on approximation = 0.04 mm
Test: # of control points = 12
Error on approximation = 0.04 mm
The fitting of the curve was done using 6 control points: the number that gave the best results.
Error on approximation = 0.04 mm
WARNING: Exception during Straightening:
Error on line 453
'numpy.ndarray' object has no attribute 'append'
Traceback (most recent call last):
File "/home/charley/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 1090, in <module>
main()
File "/home/charley/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 1074, in main
fname_straight = sc_straight.straighten()
File "/home/charley/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 453, in straighten
c_p.append(c.value)
AttributeError: 'numpy.ndarray' object has no attribute 'append'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 59 s
```

An easy fix would be to replace:
```
c_p = discs_input_image.transfo_pix2phys([[c.x, c.y, c.z]])[0]
```
by:
```
c_p = discs_input_image.transfo_pix2phys([[c.x, c.y, c.z]]).tolist()[0]
```
but I would like to open here the discussion: I think we should modify `sct_straighten_spinalcord` instead of `msct_image` --> is it correct?

Thank you.

**Comment by zougloub** [comment]
@charleygros I concur, I'd rather modify sct_straighten_spinalcord.
About the change, your immediate fix is good, the surrounding code isn't any better ;)

This regression is mine, it appeared because I modified `transfo_pix2phys` to return a numpy array.

**Comment by jcohenadad** [comment]
@charleygros is this fixed?

**Comment by charleygros** [comment]
@jcohenadad : Yes! I am closing the issue, thank you.
