### ISSUE TITLE
Error: singular matrix during straightening

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2031]
### Steps to Reproduce

Data: 
[data.zip](https://github.com/neuropoly/spinalcordtoolbox/files/2429310/data.zip)

Syntax + output:
~~~
--
Spinal Cord Toolbox (version: dev)
Running /usr/local/sct/scripts/sct_smooth_spinalcord.py -i volume.nii -s centerline_optic.nii.gz

Check input arguments...
  Volume to smooth .................. volume.nii
  Centerline ........................ centerline_optic.nii.gz
  Sigma (mm) ........................ 3
  Verbose ........................... 1

Create temporary folder (/tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK)...

Copying input data to tmp folder and convert to nii...
cp volume.nii /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/anat.nii
cp centerline_optic.nii.gz /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/centerline.nii.gz
sct_convert -i anat.nii -o anat.nii
WARNING: File anat.nii already exists. Will overwrite it.
sct_convert -i centerline.nii.gz -o centerline.nii

Orient input volume to RPI orientation...

Orient centerline to RPI orientation...

Straighten the spinal cord using centerline/segmentation...
sct_straighten_spinalcord -i /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/anat_rpi.nii -o anat_rpi_straight.nii -s /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/centerline_rpi.nii -x spline # in /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK
Traceback (most recent call last):
  File "/usr/local/sct/scripts/sct_smooth_spinalcord.py", line 217, in <module>
    main()
  File "/usr/local/sct/scripts/sct_smooth_spinalcord.py", line 169, in main
    sct.run(['sct_straighten_spinalcord', '-i', fname_anat_rpi, '-o', 'anat_rpi_straight.nii', '-s', fname_centerline_rpi, '-x', 'spline'], verbose)
  File "/usr/local/sct/scripts/sct_utils.py", line 476, in run
    raise RunError(output)
sct_utils.RunError: Running /usr/local/sct/scripts/sct_straighten_spinalcord.py -i /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/anat_rpi.nii -o anat_rpi_straight.nii -s /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/centerline_rpi.nii -x spline
/usr/local/sct

Check input arguments:
Input volume ...................... /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/anat_rpi.nii
Centerline ........................ /tmp/sct-20180927171734.121997-smooth_spinalcord-kN6GNK/centerline_rpi.nii
Final interpolation ............... spline
Verbose ........................... 1


Create temporary folder (/tmp/sct-20180927171734.831909-straighten_spinalcord-h_I4Vn)...

Copy files to tmp folder...

Orient centerline to RPI orientation...

Get dimensions...
.. matrix size: 39 x 48 x 34
.. voxel size:  1.45833mm x 1.45833mm x 4.24999mm

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = nurbs


Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 7.78 mm
Test: # of control points = 6
Error on approximation = 0.9 mm
Test: # of control points = 7
Error on approximation = 0.91 mm
Test: # of control points = 8
Error on approximation = 0.68 mm
Test: # of control points = 9
Error on approximation = 0.56 mm
Test: # of control points = 10
Error on approximation = 0.42 mm
Test: # of control points = 11
Error on approximation = 0.38 mm
Test: # of control points = 12
Error on approximation = 0.34 mm
Test: # of control points = 13
Error on approximation = 0.33 mm
Test: # of control points = 14
Error on approximation = 0.3 mm
Test: # of control points = 15
Error on approximation = 0.3 mm
Test: # of control points = 16
Error on approximation = 0.29 mm
Test: # of control points = 17
Error on approximation = 0.29 mm
Test: # of control points = 18
Error on approximation = 0.31 mm
Test: # of control points = 19
Error on approximation = 0.35 mm
Test: # of control points = 20
Error on approximation = 0.41 mm
Test: # of control points = 21
Error on approximation = 0.47 mm
Test: # of control points = 22
Error on approximation = 0.58 mm
Test: # of control points = 23
Error on approximation = 0.59 mm
Test: # of control points = 24
Error on approximation = 0.57 mm
Test: # of control points = 25
Error on approximation = 0.64 mm
Test: # of control points = 26
Error on approximation = 0.7 mm
Test: # of control points = 27
Error on approximation = 0.79 mm
Test: # of control points = 28
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 29
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 30
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 31
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 32
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 33
WARNING: Exception during Straightening:
Error on line 370
singular matrix
Traceback (most recent call last):
File "/usr/local/sct/scripts/sct_straighten_spinalcord.py", line 1090, in <module>
main()
File "/usr/local/sct/scripts/sct_straighten_spinalcord.py", line 1074, in main
fname_straight = sc_straight.straighten()
File "/usr/local/sct/scripts/sct_straighten_spinalcord.py", line 370, in straighten
centerline = Centerline(*smooth_centerline('centerline_rpi.nii.gz', algo_fitting=algo_fitting, type_window=type_window, window_length=window_length, verbose=verbose, nurbs_pts_number=number_of_points, all_slices=False, phys_coordinates=True, remove_outliers=True))
File "/usr/local/sct/scripts/sct_straighten_spinalcord.py", line 160, in smooth_centerline
z_centerline_deriv, mse = b_spline_nurbs(x_centerline, y_centerline, z_centerline, nbControl=None, path_qc=curdir, point_number=nurbs_pts_number, verbose=verbose, all_slices=all_slices)
File "/usr/local/sct/scripts/msct_smooth.py", line 238, in b_spline_nurbs
nurbs = NURBS(degree, point_number, data, False, nbControl, verbose, all_slices=all_slices, twodim=twodim)
File "/usr/local/sct/scripts/msct_nurbs.py", line 156, in __init__
self.pointsControle = self.reconstructGlobalApproximation(P_x, P_y, P_z, self.degre, self.nbControle, w)
File "/usr/local/sct/scripts/msct_nurbs.py", line 649, in reconstructGlobalApproximation
P_xb = (R.T * W * R).I * Tx.T
File "/usr/local/sct/python/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 972, in getI
return asmatrix(func(self))
File "/usr/local/sct/python/lib/python2.7/site-packages/scipy/linalg/basic.py", line 687, in inv
raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 9 s
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Note: you can opt out of Sentry reporting by editing the file ${SCT_DIR}/bin/sct_launcher and delete the line starting with "export SENTRY_DSN"
Total processing time: 0 min 11 s
~~~

**Comment by jcohenadad** [comment]
@benjamindeleener any idea what could go wrong?

**Comment by benjamindeleener** [comment]
The NURBS algorithm is supposed to detect singular matrices, but I guess it is not all the time done properly. In this case, the approximation of the curve was properly done and gave the best results around  16-17 control points, which is the number that should have been picked up. 

I would suggest improving the algorithm to calculate the number of control points so that it is more efficient and more robust to singular matrices (that are caused by instabilities in the optimization process). Shouldn't take too long and it would fix #1863 as well (while avoiding to use Hanning smoothing).

Have a nice weekend!

**Comment by jcohenadad** [comment]
@benjamindeleener just to be sure: can you do the change you suggested?

**Comment by jcohenadad** [comment]
we should reopen this issue because #2033 did not solve it per se (provides workaround). We should still fix this specific issue.
