### ISSUE TITLE
Crashed when output file name is not given

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2058]
`sct_image` is supposed to have flag `-o` as optional, however when not specified, function crashes.

To reproduce:
~~~
julien-macbook:~/sct_testing_data/t2 $ sct_image -i t2.nii.gz -setorient RPI

--
Spinal Cord Toolbox (master/9d9b320757fc4a1db5bac3f706a01817c6b351c7)
Running /Users/julien/code/sct/scripts/sct_image.py -i t2.nii.gz -setorient RPI
t2.nii.gz
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_image.py", line 623, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_image.py", line 243, in main
    im_out = [msct_image.change_orientation(im_in, arguments["-setorient"]).save(fname_out)]
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 422, in save
    raise RuntimeError("Don't know where to save the image (no absolutepath or path parameter)")
RuntimeError: Don't know where to save the image (no absolutepath or path parameter)
Total processing time: 0 min 1 s
~~~

**Comment by joshuacwnewton** [comment]
Closing as the command in the description no longer crashes. This looks like a fix was implemented incorrectly in #1577 but ultimately fixed by #2371.
