### ISSUE TITLE
Issue while generating QC

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2138]
error only occurred on `rosenberg`

~~~
  File "/home/jcohen/code/sct/scripts/sct_deepseg_gm.py", line 161, in <module>
    run_main()
  File "/home/jcohen/code/sct/scripts/sct_deepseg_gm.py", line 151, in run_main
    generate_qc(input_filename, out_fname, sys.argv[1:], os.path.abspath(path_qc))
  File "/home/jcohen/code/sct/scripts/sct_deepseg_gm.py", line 116, in generate_qc
    qcslice_layout=lambda x: x.mosaic(),
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 410, in add_entry
    layout(qcslice)
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 206, in wrapped_f
    plt.figure()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
Merge within groups: 100%|####################| 11/11 [00:15<00:00,  1.28s/iter]
Z=0/0: 100%|####################################| 1/1 [00:05<00:00,  5.16s/iter]
Z=0/0: 100%|##################################| 11/11 [00:14<00:00,  1.82s/iter]
Z=0/0: 100%|##################################| 33/33 [00:04<00:00,  8.16iter/s]
Traceback (most recent call last):
  File "/home/jcohen/code/sct/scripts/sct_propseg.py", line 649, in <module>
    res = main(arguments)
  File "/home/jcohen/code/sct/scripts/sct_propseg.py", line 640, in main
    generate_qc(fname_input_data, fname_seg, args, os.path.abspath(path_qc))
  File "/home/jcohen/code/sct/scripts/sct_propseg.py", line 370, in generate_qc
    qcslice_layout=lambda x: x.mosaic(),
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 410, in add_entry
    layout(qcslice)
  File "/home/jcohen/code/sct/spinalcordtoolbox/reports/qc.py", line 206, in wrapped_f
    plt.figure()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/jcohen/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
FINISHED :-)
Started: 21/01/19_11:18:33 AM
Ended  : 21/01/19_12:29:42 PM
To open Quality Control (QC) report on a web-browser, run the following:\n
xdg-open /home/jcohen/data/spineGeneric_multiSubjects_qc/index.html
[jcohen@rosenberg spine_generic]$
[jcohen@rosenberg spine_generic]$ ll
~~~

**Comment by jcohenadad** [comment]
running `export MPLBACKEND=Agg` fixes the issue. 
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2137

**Comment by jcohenadad** [comment]
Nice doc to follow to move to OO:
https://python4astronomers.github.io/plotting/advanced.html
