### ISSUE TITLE
ValueError: Array has no mass

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2165]
Source of the issue with access to data: https://sourceforge.net/p/spinalcordtoolbox/help/19/

Probably a regression bug caused by recent changes in straightening algo.

Syntax + Error:
~~~
sct_label_vertebrae -i 546586_T2w_medula.nii -s 546586_T2w_medula_seg.nii.gz -c t2

--
Spinal Cord Toolbox (master/fc2fc50f2061b1046ec53376fa371da014b5ac46)
Running /Users/julien/code/sct/scripts/sct_label_vertebrae.py -i 546586_T2w_medula.nii -s 546586_T2w_medula_seg.nii.gz -c t2

Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE)...

Copying input data to tmp folder...

Create label to identify disc...
Creating temporary folder...
Run C2-C3 detector...
C2-C3 detected...
Remove temporary files...
rm -rf /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145934.104675-fNP60f
WARNING: File /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE/labelz.nii.gz already exists. Will overwrite it.

Done! To view results, type:
fsleyes /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE/labelz.nii.gz &


Straighten spinal cord...
sct_straighten_spinalcord -i data.nii -s segmentation.nii.gz -r 1 # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE

Resample to 0.5mm isotropic...
sct_resample -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE

Apply straightening to segmentation...
sct_apply_transfo -i segmentation.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE
sct_maths -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE

And apply straightening to label...
sct_apply_transfo -i labelz.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o labelz_straight.nii.gz -x nn # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190219145931.531250-label_vertebrae-T8hIRE

Get z and disc values from straight label...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 897, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 303, in main
    init_disc = get_z_and_disc_values_from_label('labelz_straight.nii.gz')
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 641, in get_z_and_disc_values_from_label
    x_label, y_label, z_label = center_of_mass(nii.data)
  File "/Users/julien/code/sct/scripts/sct_label_vertebrae.py", line 42, in center_of_mass
    raise ValueError("Array has no mass")
ValueError: Array has no mass
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Total processing time: 0 min 55 s
~~~

**Comment by jcohenadad** [comment]
Fixed by #2175
