### ISSUE TITLE
Class TKApplication is implemented in both ...

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2196]
Not really a bug, but annoyingly, since v4.0.0 (i think), we get this message when running deepseg_sc/gm:
~~~
objc[5240]: Class TKApplication is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (0x7fffacd241f8) and /Users/julien/code/sct/python/lib/libtk8.5.dylib (0x10e91ae40). One of the two will be used. Which one is undefined.
~~~

**Comment by jcohenadad** [comment]
Appears when running:
~~~
from spinalcordtoolbox.reports.qc import generate_qc
~~~

**Comment by jcohenadad** [comment]
Originates from:
~~~
import skimage.io
~~~

**Comment by jcohenadad** [comment]
Useful info: https://stackoverflow.com/questions/35593602/tk-framework-double-implementation-issue

**Comment by jcohenadad** [comment]
After re-installing SCT, I don't have that issue anymore, however another came up while launching `sct_check_dependencies`:
~~~
Check if figure can be opened.......................Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_check_dependencies.py", line 378, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_check_dependencies.py", line 289, in main
    import matplotlib.pyplot as plt
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named Tkinter
~~~

**Comment by jcohenadad** [comment]
The Tkinter issue was solved by deactivating the mpl config file:
~~~
mv ~/.matplotlib/matplotlibrc ~/.matplotlib/matplotlibrc.bck
~~~
