### ISSUE TITLE
FileNotFoundError: No such file or no access: ‘image_in_RPI_norm.nii’ with kernel 3D

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2233]
This bug happens when using `sct_deepseg_sc` with -kernel 3D. 

Here's the syntax and error:

<details>

~~~
sct_example_data/t2 $ sct_deepseg_sc -i t2.nii.gz -c t2 -brain 1 -kernel 3d

Method:
	Centerline algorithm: svm
	Assumes brain section included in the image: True
	Dimension of the segmentation kernel convolutions: 3d


Create temporary folder (/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190417130541.576773-_NcN1m)...
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
Remove temporary files...
rm -rf /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190417130544.886136-6pIv9s
Resample the image to 0.5 mm isotropic resolution...
Cropping the image around the spinal cord...
Normalizing the intensity...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 185, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 159, in main
    brain_bool=brain_bool, kernel_size=kernel_size, remove_temp_files=remove_temp_files, verbose=verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/core.py", line 640, in deep_segmentation_spinalcord
    'mm', 'linear', verbose=0)
  File "/Users/julien/code/sct/spinalcordtoolbox/resampling.py", line 138, in resample_file
    nii = nipy.load_image(fname_data)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/nipy/io/files.py", line 57, in load
    img = nib.load(filename)
  File "/Users/julien/code/sct/python/lib/python2.7/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: 'image_in_RPI_norm.nii'
~~~

</details>

In addition to fixing the bug, I suggest to increase the sensitivity of the unit test to catch that error.

Also see: http://forum.spinalcordmri.org/t/sct-deepseg-sc-error-using-3d-kernel-v4-0-0-beta-2/56

**Comment by jcohenadad** [comment]
Fixed in b5ea13a4689903b08546b9a10f03c6fb7b60fcef
