### ISSUE TITLE
json.decoder.JSONDecodeError when running subjects in parallel

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2248]
When running several subjects in parallel (using GNU parallel), during QC generation, the following error is observed across ~5% of the subjects:

~~~
QC: layout with Axial slice
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/scripts/sct_deepseg_sc.py", line 185, in <module>
    main()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/scripts/sct_deepseg_sc.py", line 180, in main
    dataset=qc_dataset, subject=qc_subject, process='sct_deepseg_sc')
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/spinalcordtoolbox/reports/qc.py", line 586, in generate_qc
    stretch_contrast_method='equalized',
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/spinalcordtoolbox/reports/qc.py", line 493, in add_entry
    layout(qcslice)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/spinalcordtoolbox/reports/qc.py", line 278, in wrapped_f
    self.qc_report.update_description_file(img.shape)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/spinalcordtoolbox/reports/qc.py", line 428, in update_description_file
    results = json.load(lck_qc_file)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/python/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/python/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/python/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct-py3k/python/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15701 column 202 (char 971122)
~~~

I observed similar error in the past when processing subjects in parallel, which let us implement a [locking feature](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/reports/qc.py#L426) when writing the QC json report. But either it did not solve it, or the error has different cause.

**Comment by jcohenadad** [comment]
Maybe related to https://github.com/neuropoly/spinalcordtoolbox/issues/2205
