### ISSUE TITLE
ImportError: bad magic number in 'test_sct_analyze_lesion': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2249]
When running `sct_testing` on OSX with commit 4c2aca38d2536e202d58b9be646652a0f4280b6a, I obtain the following error:

~~~
Checking sct_analyze_lesion.........................multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/julien/code/sct/python/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 199, in process_function_multiproc
    return process_function(fname, param)
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 161, in process_function
    module_testing = importlib.import_module('test_' + fname)
  File "/Users/julien/code/sct/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1005, in get_code
  File "<frozen importlib._bootstrap_external>", line 458, in _classify_pyc
ImportError: bad magic number in 'test_sct_analyze_lesion': b'\x03\xf3\r\n'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 616, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 319, in main
    res = results[idx_function].get()
  File "/Users/julien/code/sct/python/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ImportError: bad magic number in 'test_sct_analyze_lesion': b'\x03\xf3\r\n'
~~~

**Comment by jcohenadad** [comment]
Error was fixed by doing a fresh re-installation of sct (remove folder, git clone, install_sct)
