### ISSUE TITLE
ERROR: Exception too many values to unpack (expected 3) caught while geting non Zeros coordinates

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2421]
Commit: ff7553098ea27d2b6a51a90965a526f53368805e

Getting this error:
~~~
sct_label_utils -i AtlasRat_spinal_levels.nii.gz -vert-body 5,14 -o AtlasRat_labels.nii.gz 

--
Spinal Cord Toolbox (git-master-ff7553098ea27d2b6a51a90965a526f53368805e)

pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
ERROR: Exception too many values to unpack (expected 3) caught while geting non Zeros coordinates
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 828, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 818, in main
    processor.process(process_type)
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 125, in process
    self.output_image = self.label_vertebrae(self.vertebral_levels)
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 344, in label_vertebrae
    image_cubic2point = self.cubic_to_point()
  File "/Users/julien/code/sct/scripts/sct_label_utils.py", line 285, in cubic_to_point
    coordinates = self.image_input.getNonZeroCoordinates(sorting='value')
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 534, in getNonZeroCoordinates
    list_coordinates = sorted(list_coordinates, key=lambda obj: obj.value, reverse=reverse_coord)
UnboundLocalError: local variable 'list_coordinates' referenced before assignment
~~~

To reproduce: 
[AtlasRat_spinal_levels.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3552903/AtlasRat_spinal_levels.nii.gz)

**Comment by jcohenadad** [comment]
This happened because the input image had 4 dimensions. We can close
