### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2430]
To reproduce:
~~~
cd sct_testing_data/t2
sct_denoising_onlm -i t2.nii.gz 

--
Spinal Cord Toolbox (git-jca/2314-cordLength-0469ed131fb580f01185d54fbda3ee86e9d37025)

Applying Non-local mean filter...
total time: 2.1457672119140625e-06
vol size
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_denoising_onlm.py", line 194, in <module>
    main(file_to_denoise, param, output_file_name)
  File "/Users/julien/code/sct/scripts/sct_denoising_onlm.py", line 137, in main
    before = data[:, :, axial_middle].T
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
~~~

**Comment by charleygros** [comment]
Would be to happy to work on it!
