### ISSUE TITLE
ValueError: min() arg is an empty sequence caused by empty segmentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2464]
For some reasons, a DWI dataset yields an empty segmentation, which causes the postprocessing module to crash. 

We should:
- figure out why the segmentation is failing
- raise a more elegant error during postprocessing if inputing an empty segmentation

To reproduce:

Data: 
[sub-brno02_dwi_crop_moco_dwi_mean.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3672918/sub-brno02_dwi_crop_moco_dwi_mean.nii.gz)
[sub-perform02_dwi_dwi_mean.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3673498/sub-perform02_dwi_dwi_mean.nii.gz)

SCT commit: 2b85953c2f22b0d9225a148173631313b8c3566d
Syntax (with error):
~~~
sct_deepseg_sc -i sub-brno02_dwi_crop_moco_dwi_mean.nii.gz -c dwi -r 0

--
Spinal Cord Toolbox (git-jca/2458-crop-2b85953c2f22b0d9225a148173631313b8c3566d)


Method:
	Centerline algorithm: svm
	Assumes brain section included in the image: False
	Dimension of the segmentation kernel convolutions: 2d


Create temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20190930152748.787127-p3a3u7kb)...
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
Remove temporary files...
rm -rf /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20190930152748.955878-z_k4czod
Resample the image to 0.5x0.5 mm in-plane resolution...
load data...
load data...
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 2D patches...
Reassembling the image...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
Resampling the segmentation to the native image resolution using linear interpolation...
Binarizing the resampled segmentation...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 208, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 178, in main
    remove_temp_files=remove_temp_files, verbose=verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/core.py", line 578, in deep_segmentation_spinalcord
    im_seg_r_postproc = post_processing_volume_wise(im_seg_r)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/postprocessing.py", line 139, in post_processing_volume_wise
    im_seg = _remove_isolated_voxels_on_the_edge(im_seg)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/postprocessing.py", line 110, in _remove_isolated_voxels_on_the_edge
    metrics, _ = compute_shape(im_seg, angle_correction=False)
  File "/Users/julien/code/sct/spinalcordtoolbox/process_seg.py", line 61, in compute_shape
    min_z_index, max_z_index = min(Z), max(Z)
ValueError: min() arg is an empty sequence
~~~

**Comment by jcohenadad** [comment]
It seems that the culprit is the centerline, which is discontinued, yielding a discontinued cropping, as shown below:

![anim](https://user-images.githubusercontent.com/2482071/65920584-5ff12f80-e3ad-11e9-980c-c125387e863d.gif)

**Comment by jcohenadad** [comment]
The centerline is properly estimated, however it becomes discontinued after being resampled [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/core.py#L136).

**Comment by jcohenadad** [comment]
I've started to do some refactoring at the resampling stage, notably: moving the resampling to 0.5mm out of the `find_centerline()` module (which should only focus on finding the centerline). This will notably enable to minimize i/o by passing more Image objects and less file names across the different stages.
