### ISSUE TITLE
UnboundLocalError: local variable 'zmax' referenced before assignment when no overlap between source and destination

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2465]
When the initial warping field applied to the input image does not bring any overlap of the segmentations (and/or images), as shown below, the function crashes. 

![Screen Shot 2019-09-30 at 4 57 16 PM](https://user-images.githubusercontent.com/2482071/65916681-c709e680-e3a3-11e9-940e-c8e91fb55628.png)

A more elegant solution would be to identify the problem and raise an issue easy to comprehend.

Data: 
[Archive.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3673396/Archive.zip)

SCT Commit: 2b85953c2f22b0d9225a148173631313b8c3566d
<details><summary>Syntax with error</summary>

~~~
sct_register_multimodal -i $SCT_DIR/data/PAM50/template/PAM50_t1.nii.gz -iseg $SCT_DIR/data/PAM50/template/PAM50_cord.nii.gz -d sub-oxfordFmrib04_acq-T1w_MTS_crop.nii.gz -dseg sub-oxfordFmrib04_acq-T1w_MTS_seg.nii.gz -param step=1,type=seg,algo=slicereg,metric=MeanSquares,smooth=2:step=2,type=im,algo=syn,metric=CC,iter=5,gradStep=0.5 -initwarp warp_template2T1w.nii.gz
[Archive.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3673396/Archive.zip)


--
Spinal Cord Toolbox (git-jca/2458-crop-2b85953c2f22b0d9225a148173631313b8c3566d)


Input parameters:
  Source .............. /Users/julien/code/sct/data/PAM50/template/PAM50_t1.nii.gz
  Destination ......... sub-oxfordFmrib04_acq-T1w_MTS_crop.nii.gz
  Init transfo ........ /Users/julien/data/spineGeneric_20190925/results/data/sub-oxfordFmrib04/anat/warp_template2T1w.nii.gz
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...

Create temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20190930160525.497608-7pu3enqs)...

Copying input data to tmp folder and convert to nii...

Skip step=0 and replace with initial transformations: 
  /Users/julien/data/spineGeneric_20190925/results/data/sub-oxfordFmrib04/anat/warp_template2T1w.nii.gz

--
ESTIMATE TRANSFORMATION FOR STEP #1

Apply transformation from previous step

Parse list of warping fields...

Get dimensions of data...
  141 x 141 x 991 x 1

Apply transformation...
/Users/julien/code/sct/bin/isct_antsApplyTransforms -d 3 -i src_seg.nii -o src_seg_reg.nii -t /Users/julien/data/spineGeneric_20190925/results/data/sub-oxfordFmrib04/anat/warp_template2T1w.nii.gz -r dest_seg_RPI.nii -n NearestNeighbor # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20190930160525.497608-7pu3enqs
Copy affine matrix from destination space to make sure qform/sform are the same.

Done! To view results, type:
fsleyes dest_seg_RPI.nii src_seg_reg.nii &

Registration parameters:
  type ........... seg
  algo ........... slicereg
  slicewise ...... 0
  metric ......... MeanSquares
  iter ........... 10
  smooth ......... 2
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ... pca
Input image is empty
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_register_multimodal.py", line 895, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_register_multimodal.py", line 518, in main
    warp_forward_out, warp_inverse_out = register(src, dest, paramreg, param, str(i_step))
  File "/Users/julien/code/sct/scripts/sct_register_multimodal.py", line 674, in register
    zmin, zmax = msct_image.find_zmin_zmax(im, threshold=0.1)
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 885, in find_zmin_zmax
    return zmin, zmax
UnboundLocalError: local variable 'zmax' referenced before assignment
~~~

</details>

**Comment by jcohenadad** [comment]
isolated case-- closing
