### ISSUE TITLE
sct_maths -otsu_adap error

### ISSUE THREAD

**Issue by felixsc1** [neuropoly/spinalcordtoolbox#2471]
Apparently, the skimage function _threshold_adaptive()_ has been deprecated. 
threshold_local seems to work similarly, but it doesn't produce a binary output:
https://scikit-image.org/docs/0.15.x/api/skimage.filters.html#skimage.filters.threshold_local

```
sct_maths -i input.nii.gz -otsu-adap 5,0 -o output.nii.gz

--
Spinal Cord Toolbox (git-master-91beb0badf165195caf63abb978a2902059884bc*)

Traceback (most recent call last):
  File "/home/felix/Repos/sct/scripts/sct_maths.py", line 772, in <module>
    main()
  File "/home/felix/Repos/sct/scripts/sct_maths.py", line 251, in main
    data_out = otsu_adap(data, param[0], param[1])
  File "/home/felix/Repos/sct/scripts/sct_maths.py", line 436, in otsu_adap
    from skimage.filters import threshold_adaptive
ImportError: cannot import name 'threshold_adaptive'
```

**Comment by jcohenadad** [comment]
@felixsc1 thank you for catching this! That's an easy fix. We will do it within 1d.
