### ISSUE TITLE
Crashes when trying to remove folder under Singularity container

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2472]
[this change](https://github.com/neuropoly/spinalcordtoolbox/commit/79145306f83157557ddb2a3fc5a13727318f4483#diff-096b5eba0646d82b4e379018d50deaa6R164) causes an issue running the sct install while building a singularity container. More details [here](https://github.com/neuropoly/spinalcordtoolbox/commit/79145306f83157557ddb2a3fc5a13727318f4483#commitcomment-35336200).

Issue likely related to:
- https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link/42400063
- https://github.com/pypa/pip/issues/103
- https://github.com/pypa/pip/issues/6943

A possible solution would be to copy the folder/file instead of moving it.

**Comment by jcohenadad** [comment]
When replacing `shutils.move` by `shutils.copytree`, i get the error below when the unzipped folder is a collection of files, instead of a single folder: 
~~~
julien-macbook:~ $ sct_download_data -d binaries_centos

--
Spinal Cord Toolbox (git-jca/2472-shutils-move-91beb0badf165195caf63abb978a2902059884bc*)


Trying URL: https://osf.io/8kpt4/?action=download
Downloading 20190930_sct_binaries_linux_centos6.tar.gz...
Status: 100%|##################################################################################################| 98.1M/98.1M [00:03<00:00, 29.3MB/s]

Create temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20191003145532.534740-x41qam0z)...

Unzip data to: /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20191003145532.534740-x41qam0z

Check if files or folder already exists on the destination path...
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_download_data.py", line 247, in <module>
    res = main()
  File "/Users/julien/code/sct/scripts/sct_download_data.py", line 160, in main
    copytree(source_path, os.path.join(dest_folder, extracted_files[extracted_files_paths.index(source_path)]))
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
NotADirectoryError: [Errno 20] Not a directory: '/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20191003145532.534740-x41qam0z/isct_propseg'
~~~

For code clarity and lower maintenance, I suggest to enforce that every files downloaded using `sct_download_data` points to a zip files, and that the unzipped file only generates a single folder.
