### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/spinalcordtoolbox#2504]
I tried to resample an image to but the algorithm failed.

<Details>

````
sct_resample -i /Volumes/sct_testing/large/derivatives/labels/sub-amuAMU15001/anat/sub-amuAMU15001_T2star_gmseg-manual.nii.gz  -mm 0.46875x0.46875x17.5 -o /Users/alfoi/Desktop/resample_sub-amuAMU15001_T2star_gmseg-manual.nii.gz -v 2

--
Spinal Cord Toolbox (git-master-6f50fd8e917e8e255a0004daa1966c4a1fec49bf*)

load data...
Affine matrix: 
[[-4.68532801e-01  1.42136868e-02  4.63722833e-02  8.25879211e+01]
 [ 1.41630266e-02  4.58386868e-01  3.62103534e+00 -1.06165199e+02]
 [-1.72638951e-03 -9.69846025e-02  1.71212139e+01 -2.17423553e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Traceback (most recent call last):
  File "/Users/alfoi/code/sct/scripts/sct_resample.py", line 138, in <module>
    run_main()
  File "/Users/alfoi/code/sct/scripts/sct_resample.py", line 133, in run_main
    param.interpolation, param.verbose, fname_ref=param.ref)
  File "/Users/alfoi/code/sct/spinalcordtoolbox/resampling.py", line 149, in resample_file
    nii_r = resample_nib(nii, new_size.split('x'), new_size_type, image_dest=nii_ref, interpolation=interpolation)
  File "/Users/alfoi/code/sct/spinalcordtoolbox/resampling.py", line 89, in resample_nib
    R[i, i] = img.shape[i] / float(shape_r[i])
ZeroDivisionError: float division by zero
````
</Details>

Image:
[sub-amuAMU15001_T2star_seg-manual.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3764735/sub-amuAMU15001_T2star_seg-manual.nii.gz)

**Comment by jcohenadad** [comment]
Maybe related to https://github.com/neuropoly/spinalcordtoolbox/issues/1103
