### ISSUE TITLE
GLIBCXX_3.4.15 not found on CentOS 6

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2600]
After installing SCT (5f09905515c78aefbaed7781e2d0664427e9cf79) on a centos6 station, I ran into the following problem while running `sct_testing`:
~~~
Checking sct_fmri_moco..............................[FAIL]
   
   ====================================================================================================
   sct_fmri_moco -i fmri/fmri_r.nii.gz -g 5 -x nn -r 0
   ====================================================================================================
   
   
   --
   Spinal Cord Toolbox (git-master-5f09905515c78aefbaed7781e2d0664427e9cf79)
   
   Merge within groups:   0%|                              | 0/6 [00:00<?, ?iter/s]
   Merge within groups:  17%|###6                  | 1/6 [00:01<00:08,  1.63s/iter]
   Merge within groups:  33%|#######3              | 2/6 [00:03<00:06,  1.60s/iter]
   Merge within groups:  50%|###########           | 3/6 [00:04<00:04,  1.55s/iter]
   Merge within groups:  67%|##############6       | 4/6 [00:06<00:03,  1.50s/iter]
   Merge within groups:  83%|##################3   | 5/6 [00:07<00:01,  1.48s/iter]
   Merge within groups: 100%|######################| 6/6 [00:08<00:00,  1.50s/iter]
   Merge within groups: 100%|######################| 6/6 [00:08<00:00,  1.50s/iter]
   Z=0/0:   0%|                                            | 0/6 [00:00<?, ?iter/s]
   Z=0/0:   0%|                                            | 0/6 [00:00<?, ?iter/s]
   
   Input parameters:
   input file ............fmri/fmri_r.nii.gz
   
   Create temporary folder (/tmp/sct-20200214135325.614152-fmri_moco-0129le9n)...
   
   Copying input data to tmp folder and convert to nii...
   sct_convert -i /home/jcohen-adad/sct_testing_data/fmri/fmri_r.nii.gz -o /tmp/sct-20200214135325.614152-fmri_moco-0129le9n/fmri.nii
   
   Get dimensions of data...
   34 x 34 x 6 x 30
   
   Data orientation: RPI
   Treated as axial
   
   Split along T dimension...
   
   Merging volumes...
   
   -------------------------------------------------------------------------------
   Estimating motion...
   -------------------------------------------------------------------------------
   
   Input parameters:
   Input file ............fmri_averaged_groups.nii
   Reference file ........fmri_mean_0.nii.gz
   Polynomial degree .....2
   Smoothing kernel ......0
   Gradient step .........1
   Metric ................MeanSquares
   Sampling ..............0.2
   Todo ..................estimate_and_apply
   Mask  .................
   Output mat folder .....mat_groups
   
   Data dimensions:
   34 x 34 x 6 x 6
   
   Copy file_target to a temporary file...
   sct_convert -i fmri_mean_0.nii.gz -o target.nii.gz
   
   Register. Loop across Z (note: there is only one Z if orientation is axial
   Traceback (most recent call last):
   File "/home/jcohen-adad/sct/scripts/sct_fmri_moco.py", line 453, in <module>
   main()
   File "/home/jcohen-adad/sct/scripts/sct_fmri_moco.py", line 213, in main
   fmri_moco(param)
   File "/home/jcohen-adad/sct/scripts/sct_fmri_moco.py", line 350, in fmri_moco
   file_mat = moco.moco(param_moco)
   File "/home/jcohen-adad/sct/scripts/msct_moco.py", line 152, in moco
   file_data_splitZ_splitT_moco[it], im_mask=input_mask)
   File "/home/jcohen-adad/sct/scripts/msct_moco.py", line 276, in register
   status, output = sct.run(cmd, verbose=0, **kw)
   File "/home/jcohen-adad/sct/scripts/sct_utils.py", line 311, in run
   raise RunError(output)
   sct_utils.RunError: /home/jcohen-adad/sct/bin/isct_antsSliceRegularizedRegistration: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/jcohen-adad/sct/bin/isct_antsSliceRegularizedRegistration)
~~~

This issue might be related to https://github.com/neuropoly/spinalcordtoolbox/issues/711, https://github.com/neuropoly/spinalcordtoolbox/issues/158, https://github.com/neuropoly/spinalcordtoolbox/issues/1704

**Comment by cfhammill** [comment]
I've set up a centos6 virtual machine and will investigate.

**Comment by jcohenadad** [comment]
> I've set up a centos6 virtual machine and will investigate.

Awesome! @cfhammill please liaise with @kousu (see https://github.com/neuropoly/spinalcordtoolbox/pull/2642#issuecomment-605150255)

**Comment by kousu** [comment]
Related: #2669, and eventually #2675. Also #2313 .

**Comment by kousu** [comment]
Seeing the same issue with Tensorflow 1.5 on centos6: https://github.com/neuropoly/spinalcordtoolbox/issues/2675#issuecomment-623978583

**Comment by joshuacwnewton** [comment]
Closing, as support for CentOS 6 was dropped in #2699.
