### ISSUE TITLE
Packaging Dependencies

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#2669]
Currently `./install_sct` uses two package managers (actually four if you count conda and brew): `pip` and `sct_download_data`. The latter we are maintaining ourselves, and we use it for dependencies that we "own", namely the large pre-compiled binary programs (particularly `bin/isct_antsApplyTransforms`, `bin/isct_antsRegistration`, and `bin/isct_antsSliceRegularizedRegistration`), some tools from `dev/`, and M Sdika's [ctrDetect](https://www.creatis.insa-lyon.fr/site7/en/ctrDetect) which we don't own but which also isn't packaged by anything other package manager, and also all of our large pre-trained machine learning models, and maintaining the contents and metadata is a fairly manual process documented here:

* https://github.com/neuropoly/spinalcordtoolbox/wiki/Binaries-Compilation
* https://github.com/neuropoly/spinalcordtoolbox/wiki/Compile-binaries
* https://github.com/neuropoly/spinalcordtoolbox/wiki/Package-data-&-binaries

Motivated by #947 / [forum365](http://forum.spinalcordmri.org/t/sct-fmri-moco-very-very-slow/365/2) / #2642, where the issue was that we were shipping very old binaries and easily update them, I want to automate building and packaging these dependencies as much as possible.

Here is my plan

**Comment by kousu** [comment]
I think [this comment in the wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki/Binaries-Compilation#diy) is worth preserving, to demonstrate why getting this automated and repeatable (and *repeated* regularly) is important:

> If you want to build your binaries, as of 2017-12-05, you're on your own, but we are working (#1526) on handling bundled vs. system dependencies and building the binaries as part of the installation process (using distribution packages and ultimately setuptools). Feel free to contribute!

**Comment by kousu** [comment]
# Dependency Graph

This is the conceptual dependency graph; eventually I want to encode this as data, using a package management formats (probably `requirements.txt` but I'm open to suggestions).

* TODO

**Comment by kousu** [comment]
@jcohenadad says that isct_dice_coefficient is unused. So really `spinalcordtoolbox-dev` is just `spinalcordtoolbox-propseg`. It still needs to be recompiled.

**Comment by kousu** [comment]
For reference, the current unfinished procedure for updating ANTs, which is the biggest of these dependencies, is to first merge [upstream](https//github.com/ANTsX/ANTs.git) into https://github.com/kousu/ANTs/tree/matrix-build, wait for the build to run on https://github.com/kousu/ANTs/pull/5 and publish a release to https://github.com/kousu/ANTs/releases, then manually upload the results from /releases to osf.io, and change ./scripts/sct_download_data.py to match to new versions.

I still need to document this better, and migrate that fork to neuropoly/ANTs. It probably also needs to pay closer attention to the git tags, instead of just uploading to a release named after the nonsense sha1sum. When this is actually tidied up, the procedure will be:

```
# one time setup
git clone git@github.com:neuropoly/ANTs;
cd ANTs
git remote add upstream git@github.com:ANTsX/ANTs.git
```

```
# syncing
git checkout build
git rebase upstream/master
git push -f
```

then wait, then manually upload the result to osf.io.

But I also want to automate it further than that and make `sct_download_data.py` use Github directly, to cut out  the osf step and maybe make a cronjob to do the syncing.

**Comment by jcohenadad** [comment]
additional note: for now, the "Linux" binaries to select are the centos7 build.

**Comment by joshuacwnewton** [comment]
Adding a note here for https://github.com/pypa/packaging-problems/issues/64, which I think might be worth reading through. It has lots of input from maintainers who are in similar situations as us, as well as from PyPA devs stating their goals/intentions (highlight: https://github.com/pypa/packaging-problems/issues/64#issuecomment-469409655).

(Also, I believe wheels not supporting post-install scripts was the main roadblock @Drulex encountered when experimenting on the [`aj/pip-only-install`](https://github.com/Drulex/spinalcordtoolbox/tree/aj/pip-only-install) branch.)

**Comment by joshuacwnewton** [comment]
Responding to https://github.com/neuropoly/spinalcordtoolbox/issues/1526#issuecomment-813085296...

> The biggest thing I'm stuck on, and I'm happy to keep chewing on, is how to handle `binaries_*`. We might have to migrate everything else to pip but keep install_sct around for a while until someone can deal with them

An idea for an incremental approach could be to slowly reduce our dependency on external pre-compiled binaries, and instead more closely integrate the source code into `spinalcordtoolbox`:

* ANTs binaries -> ANTsPy (#2007)
* `dev/isct_*` C++ code -> Cython wrapper (See [`scikit-learn`'s guide](https://scikit-learn.org/stable/developers/performance.html) and the [Using C++ in Cython](https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html) doc page.) This would also be closer to the currently-recommend ways of handling ["accelerator modules"](https://packaging.python.org/guides/packaging-binary-extensions/#alternatives-to-handcoded-accelerator-modules).
* I'm not sure how to handle `isct_spine_detect` and `isct_train_svm`, though, because we [don't have access to the source code](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-How-to-compile-binaries-(ANTs,-isct)#isct_spine_detect-isct_train_svm). If we did, we might be able to write Cython wrappers for these, too.

**Comment by kousu** [comment]
Just avoiding the issue would solve a lot!

`spine_detect` is just a call to SVM. We should be able to replace that with [`sklearn.svm`](https://scikit-learn.org/stable/modules/svm.html). I have been hesitant because _numerical stability_ but I think it's worth it. We can patch up whatever goes awry.

I think ANTsPy is a much bigger project. Worth it, but it's just...huge. ANTs underlies most of the operations in SCT doesn't it? Fiddling with that is going to cause a cascade of changes and numerical issues. I originally figured I would get around to solving *this* as an incremental approach towards *that* that but that was overpromising to myself.

**Comment by kousu** [comment]
Another bit of progress: https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models (I don't have access to https://github.com/sct-data/c2c3_disc_models so I moved this back over here; and anyway it's weird to have it split out over there isn't it?)

I learned a lot about how pip and packages work. A package is just a zipfile that gets unpacked into site-packages/; in particular there's no need for it to constrain itself to only unpacking into one top-level folder. In fact every .whl unpacks at least two folders: site-packages/$pkg/ and site-packages/$pkg-$verison.dist-info/. Furthermore, there's nothing stopping a package from unpacking itself inside of a different package's folder.

And so that's what I've done here. I've moved `$SCT_DIR/data/c2c3_disc_models` to `site-packages/spinalcordtoolbox/data/c2c3_disc_models`.

We can access them (and I'll be editing SCT to do this ) with:

```
with importlib.resources.path('spinalcordtoolbox.data.c2c3_disc_models','t1_model.yml') as path: pass
```

or even better:


```
try:
    import spinalcordtoolbox.data.c2c3_disc_models
except ImportError:
    warnings.warn("Missing data needed for ..... run pip install spinalcordtoolbox-data-c2c3_disc_models to get it.")
    raise

...

with importlib.resources.path(spinalcordtoolbox.data.c2c3_disc_models,'t1_model.yml') as path: pass
```

(the weird `with` here is going to have to be idiomatic I think: a long time ago packages were defined as EITHER folders OR zipfiles with room left open for further expansion to e.g. loading code live over the web, so you need the `with` to handle the case where you potentially have temporarily unpacked a virtual file into a real file, but no one uses any other form anymore [1] and I think we should ignore it, hence this idiom; maybe I'll patch `importlib.resources`)

Unpacking into other package's folders has a nasty quirk though: *if* you use `pip install -e` at any point, then you break the easy case and fall into [semi-virtual namespace packages](https://www.python.org/dev/peps/pep-0420/), where the package as seen by python is cobbled together from multiple folders. So despite PEP420 there claiming

> A namespace package is not fundamentally different from a regular package. It is just a different way of creating packages. Once a namespace package is created, there is no functional difference between it and a regular package.

a. you can't use `importlib.resources` on namespace packages (it contains a comment buried that "By definition, namespace packages cannot have resources." which is ridiculous because you can scatter *python files* in any combination across the component pieces of a namespace package and they're all importable, but it blinds itself to non-python files in this case) 
b. a "regular package" is one containing a `__init__.py`, and in that case the scanning algorithm *stops immediately*, so another difference is that a "regular package" cannot have any child packages unless they are physically in the same folder as it -- so `pip install -e spinalcordtoolbox` will blind it to *everything* in `spinalcordtoolbox.data`; `pip install -e spinalcordtoolbox-data-c2c3_disc_models` will be okay but only because I'm not planning on putting any child data folders inside of it

To avoid this, I think we should remove all `__init__.py`s; that's what PEP420 recommends. Except we need to keep them in these data packages, but I can just leave a note there about this weird python bug (and maybe I'll go put it on the python bug tracker and see if I can talk them into changing the API; probably not though, this has already taken a lot of energy).

We could also skip the issue by installing to a separate hierarchy, say, `spinalcordtoolbox-data.c2c3_disc_models`; then `pip install -e spinalcordtoolbox` won't accept. Or even just put every data package as its own top-level package: `spinalcordtoolbox-data-c2c3_data_models`; this is what `flask` plugins do.

Or we could just not worry about it since it's a rare issue anyway? We could just test with `pip install`; that might not be so bad? (or..maybe it is; the skimage people were pretty concerned about how inefficient pip is about rebuilds, especially in the 'modern' age of pyproject.toml: https://github.com/scikit-image/scikit-image/pull/4920#issuecomment-676748922 )

I still think this is a good solution and perfectly serviceable for the size of data we're pushing.

[1]
 > "However, while this behaviour is a natural consequence of the format design, actually relying on it is generally discouraged."
 [cite](https://packaging.python.org/specifications/binary-distribution-format/#is-it-possible-to-import-python-code-directly-from-a-wheel-file)

-

**Comment by kousu** [comment]
And I got it auto-releasing: https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/blob/master/.github/workflows/release.yml

And even better, check this out, we can keep using Github as a mirror with `pip`:

<details><summary>Binary from pypi</summary>

```
(.venv) [kousu@requiem c2c3_disc_models]$ pip install --extra-index-url https://test.pypi.org/simple spinalcordtoolbox-data-c2c3-disc-models
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple
Collecting spinalcordtoolbox-data-c2c3-disc-models
  Downloading https://test-files.pythonhosted.org/packages/2d/9f/fb2b637a179b71706162595b74293350c3418db877c56ce5430ddca8791d/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl (10 kB)
Installing collected packages: spinalcordtoolbox-data-c2c3-disc-models
Successfully installed spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
(.venv) [kousu@requiem c2c3_disc_models]$ cat .venv/lib/python3.9/site-packages/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD 
spinalcordtoolbox/data/c2c3_disc_models/__init__.py,sha256=BiGYrD6AArCZ3GSZTIDBvfEzRkwCX0NQZ6dURjhe4yA,65
spinalcordtoolbox/data/c2c3_disc_models/__pycache__/__init__.cpython-39.pyc,,
spinalcordtoolbox/data/c2c3_disc_models/t1_model.yml,sha256=Z61YZN-zs23kRGPCHe4NZIfN7zOYSE1VybV2ulpq8VA,10933
spinalcordtoolbox/data/c2c3_disc_models/t2_model.yml,sha256=PWFSHRCk52NL29--ScDNK42IRfjwBzH_RegenwziCII,10899
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/METADATA,sha256=nlWC1c9XGpKPz7y0haozWTsfZtcNy0ccBpldjebTF7A,443
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD,,
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/top_level.txt,sha256=Atnb0WhQSzgKr9R4AEJZmOYo8scDV5TtfT1ld0s3MFU,18
(.venv) [kousu@requiem c2c3_disc_models]$ pip uninstall -y spinalcordtoolbox-data-c2c3-disc-models
Found existing installation: spinalcordtoolbox-data-c2c3-disc-models 2019.1.17
Uninstalling spinalcordtoolbox-data-c2c3-disc-models-2019.1.17:
  Successfully uninstalled spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
```

</details>

<details><summary>sdist from pypi</summary>

```
(.venv) [kousu@requiem c2c3_disc_models]$ pip install --no-binary ":all:" --extra-index-url https://test.pypi.org/simple spinalcordtoolbox-data-c2c3-disc-models
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple
Collecting spinalcordtoolbox-data-c2c3-disc-models
  Downloading https://test-files.pythonhosted.org/packages/82/8d/c2389f2b9d1e8016450281640fdb84a7f232be8a2684870c2ad4c958be20/spinalcordtoolbox-data-c2c3_disc_models-2019.1.17.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: spinalcordtoolbox-data-c2c3-disc-models
  Building wheel for spinalcordtoolbox-data-c2c3-disc-models (PEP 517) ... done
  Created wheel for spinalcordtoolbox-data-c2c3-disc-models: filename=spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl size=10603 sha256=063f6ac2d98c6ad851c5438f4c5a3d21d991a581d0f223d5322bb3333e94dfe4
  Stored in directory: /home/kousu/.cache/pip/wheels/ce/16/de/9005170932196ea2180c3452eee889721483f14879e73c9a50
Successfully built spinalcordtoolbox-data-c2c3-disc-models
Installing collected packages: spinalcordtoolbox-data-c2c3-disc-models
Successfully installed spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
(.venv) [kousu@requiem c2c3_disc_models]$ cat .venv/lib/python3.9/site-packages/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD 
spinalcordtoolbox/data/c2c3_disc_models/__init__.py,sha256=BiGYrD6AArCZ3GSZTIDBvfEzRkwCX0NQZ6dURjhe4yA,65
spinalcordtoolbox/data/c2c3_disc_models/__pycache__/__init__.cpython-39.pyc,,
spinalcordtoolbox/data/c2c3_disc_models/t1_model.yml,sha256=Z61YZN-zs23kRGPCHe4NZIfN7zOYSE1VybV2ulpq8VA,10933
spinalcordtoolbox/data/c2c3_disc_models/t2_model.yml,sha256=PWFSHRCk52NL29--ScDNK42IRfjwBzH_RegenwziCII,10899
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/METADATA,sha256=nlWC1c9XGpKPz7y0haozWTsfZtcNy0ccBpldjebTF7A,443
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD,,
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/top_level.txt,sha256=Atnb0WhQSzgKr9R4AEJZmOYo8scDV5TtfT1ld0s3MFU,18
(.venv) [kousu@requiem c2c3_disc_models]$ pip uninstall -y spinalcordtoolbox-data-c2c3-disc-models
Found existing installation: spinalcordtoolbox-data-c2c3-disc-models 2019.1.17
Uninstalling spinalcordtoolbox-data-c2c3-disc-models-2019.1.17:
  Successfully uninstalled spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
```

</details>

<details><summary>Binary from Github:</summary>

```
(.venv) [kousu@requiem c2c3_disc_models]$ pip install -f https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases spinalcordtoolbox-data-c2c3-disc-models
Looking in links: https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases
Collecting spinalcordtoolbox-data-c2c3-disc-models
  Downloading https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases/download/2019.1.17/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl (10 kB)
Installing collected packages: spinalcordtoolbox-data-c2c3-disc-models
Successfully installed spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
(.venv) [kousu@requiem c2c3_disc_models]$ cat .venv/lib/python3.9/site-packages/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD 
spinalcordtoolbox/data/c2c3_disc_models/__init__.py,sha256=BiGYrD6AArCZ3GSZTIDBvfEzRkwCX0NQZ6dURjhe4yA,65
spinalcordtoolbox/data/c2c3_disc_models/__pycache__/__init__.cpython-39.pyc,,
spinalcordtoolbox/data/c2c3_disc_models/t1_model.yml,sha256=Z61YZN-zs23kRGPCHe4NZIfN7zOYSE1VybV2ulpq8VA,10933
spinalcordtoolbox/data/c2c3_disc_models/t2_model.yml,sha256=PWFSHRCk52NL29--ScDNK42IRfjwBzH_RegenwziCII,10899
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/METADATA,sha256=nlWC1c9XGpKPz7y0haozWTsfZtcNy0ccBpldjebTF7A,443
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD,,
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/top_level.txt,sha256=Atnb0WhQSzgKr9R4AEJZmOYo8scDV5TtfT1ld0s3MFU,18
(.venv) [kousu@requiem c2c3_disc_models]$ pip uninstall -y spinalcordtoolbox-data-c2c3-disc-models
Found existing installation: spinalcordtoolbox-data-c2c3-disc-models 2019.1.17
Uninstalling spinalcordtoolbox-data-c2c3-disc-models-2019.1.17:
  Successfully uninstalled spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
```

</details>

<details><summary>sdist from Github:</summary>

```
(.venv) [kousu@requiem c2c3_disc_models]$ pip install --no-binary ":all:" -f https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases spinalcordtoolbox-data-c2c3-disc-models
Looking in links: https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases
Collecting spinalcordtoolbox-data-c2c3-disc-models
  Downloading https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases/download/2019.1.17/spinalcordtoolbox-data-c2c3_disc_models-2019.1.17.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: spinalcordtoolbox-data-c2c3-disc-models
  Building wheel for spinalcordtoolbox-data-c2c3-disc-models (PEP 517) ... done
  Created wheel for spinalcordtoolbox-data-c2c3-disc-models: filename=spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl size=10603 sha256=db7f4d978e76b499602498eecffd3d48f9f8e82a9e5307327ba5e040e08d3028
  Stored in directory: /home/kousu/.cache/pip/wheels/73/c0/c5/122cb6eef9eccde0bd7345d8ccb6ce1e875e53e1a6060500ca
Successfully built spinalcordtoolbox-data-c2c3-disc-models
Installing collected packages: spinalcordtoolbox-data-c2c3-disc-models
Successfully installed spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
(.venv) [kousu@requiem c2c3_disc_models]$ cat .venv/lib/python3.9/site-packages/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD 
spinalcordtoolbox/data/c2c3_disc_models/__init__.py,sha256=BiGYrD6AArCZ3GSZTIDBvfEzRkwCX0NQZ6dURjhe4yA,65
spinalcordtoolbox/data/c2c3_disc_models/__pycache__/__init__.cpython-39.pyc,,
spinalcordtoolbox/data/c2c3_disc_models/t1_model.yml,sha256=Z61YZN-zs23kRGPCHe4NZIfN7zOYSE1VybV2ulpq8VA,10933
spinalcordtoolbox/data/c2c3_disc_models/t2_model.yml,sha256=PWFSHRCk52NL29--ScDNK42IRfjwBzH_RegenwziCII,10899
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/METADATA,sha256=nlWC1c9XGpKPz7y0haozWTsfZtcNy0ccBpldjebTF7A,443
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/RECORD,,
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
spinalcordtoolbox_data_c2c3_disc_models-2019.1.17.dist-info/top_level.txt,sha256=Atnb0WhQSzgKr9R4AEJZmOYo8scDV5TtfT1ld0s3MFU,18
(.venv) [kousu@requiem c2c3_disc_models]$ pip uninstall -y spinalcordtoolbox-data-c2c3-disc-models
Found existing installation: spinalcordtoolbox-data-c2c3-disc-models 2019.1.17
Uninstalling spinalcordtoolbox-data-c2c3-disc-models-2019.1.17:
  Successfully uninstalled spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
```
</details>

With this uploading to pypi, most people will be able to `pip install spinalcordtoolbox` and have things just work.

For people behind firewalls, we can give them extra mirrors by e.g.:

```
# sct.txt
-f https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases
-f https://github.com/neuropoly/spinalcordtoolbox/releases
# ... etc
spinalcordtoolbox
```

And tell people to `pip install -r sct.txt`. We can get osf.io or other sites in the mix if we just generate a page that looks like https://download.pytorch.org/whl/cpu/torch_stable.html too.

**Comment by kousu** [comment]
And by the way, that [RECORD file](https://packaging.python.org/specifications/recording-installed-packages/#the-dist-info-directory) is interesting. We angsted a lot over in distriploy over integrity checking. I haven't figured out how to actually make use of it yet, but pip *does* record hashes of everything it installs. If we can't find a `pip verify` anywhere we can just write our own.

There's also a way to cryptographically pin the dependencies:

```
-f https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases
spinalcordtoolbox_data_c2c3_disc_models==2019.1.17 --hash=sha256:29cde6ee062985b05de2f52ee3a1ca2b07b0aaaf4af321cd69fbd3afebfc9cd9
```

```
(.venv) [kousu@requiem c2c3_disc_models]$ pip install -r requirements.txt 
Looking in links: https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases
Collecting spinalcordtoolbox_data_c2c3_disc_models==2019.1.17
  Downloading https://github.com/neuropoly/spinalcordtoolbox-data-c2c3_disc_models/releases/download/2019.1.17/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl (10 kB)
Installing collected packages: spinalcordtoolbox-data-c2c3-disc-models
Successfully installed spinalcordtoolbox-data-c2c3-disc-models-2019.1.17
```


but if I instead point it at testpypi, which has an imposter version (under the same tag but uploaded a couple hours ago, and pypi URLs are write-once)

```
--extra-index-url https://test.pypi.org/simple
spinalcordtoolbox_data_c2c3_disc_models==2019.1.17 --hash=sha256:29cde6ee062985b05de2f52ee3a1ca2b07b0aaaf4af321cd69fbd3afebfc9cd9
```

```
(.venv) [kousu@requiem c2c3_disc_models]$ pip install -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple
Collecting spinalcordtoolbox_data_c2c3_disc_models==2019.1.17
  Downloading https://test-files.pythonhosted.org/packages/2d/9f/fb2b637a179b71706162595b74293350c3418db877c56ce5430ddca8791d/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl (10 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    spinalcordtoolbox_data_c2c3_disc_models==2019.1.17 from https://test-files.pythonhosted.org/packages/2d/9f/fb2b637a179b71706162595b74293350c3418db877c56ce5430ddca8791d/spinalcordtoolbox_data_c2c3_disc_models-2019.1.17-py3-none-any.whl#sha256=438d76a4a7504ded1b0e40790d73664ce3422524919fe4c53988d8336b16a2a7 (from -r requirements.txt (line 3)):
        Expected sha256 29cde6ee062985b05de2f52ee3a1ca2b07b0aaaf4af321cd69fbd3afebfc9cd9
             Got        438d76a4a7504ded1b0e40790d73664ce3422524919fe4c53988d8336b16a2a7

```


I don't think there's a way to do hash-pinning in setup.py, but only in requirements.txt (:shakes fist:). But I would love to be proven wrong about that.

**Comment by kousu** [comment]
I found more:

https://github.com/neuropoly/spinalcordtoolbox/blob/cf4ed55757107c804b152ac5dc6579c49a54e2a4/spinalcordtoolbox/deepseg/models.py#L20-L80

**Comment by kousu** [comment]
`exvivo_template` doesn't seem to be used.

**Comment by kousu** [comment]
Promising:

```
kousu@ail:~/src/neuropoly$ pip3 install -i https://test.pypi.org/simple/ spinalcordtoolbox-data-deepseg-sc-models
Collecting spinalcordtoolbox-data-deepseg-sc-models
  Downloading https://test-files.pythonhosted.org/packages/4a/d2/0745b9555aace76fcc51a0cb3e3abf5190490c2e7f683d61936bfc6133db/spinalcordtoolbox_data_deepseg_sc_models-2020.12.3-py3-none-any.whl (58.8MB)
    100% |████████████████████████████████| 58.8MB 8.4kB/s 
Installing collected packages: spinalcordtoolbox-data-deepseg-sc-models
Successfully installed spinalcordtoolbox-data-deepseg-sc-models-2020.12.3
kousu@ail:~/src/neuropoly$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spinalcordtoolbox.data.deepseg.sc
>>> import importlib.resources
imTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.resources'
>>> import importlib_resources
>>> importlib_resources.contents(spinalcordtoolbox.data.deepseg.sc)
['__pycache__', 't2s_ctr.h5', 't1_ctr.h5', 't2s_sc_3D.h5', 'dataset.pkl', 't1_sc.h5', 't2_ctr.h5', '__init__.py', 't2s_sc.h5', 'dwi_sc.h5', 't2_sc_3D.h5', 't2_sc.h5', 'dwi_ctr.h5', 't1_sc_3D.h5']
>>> importlib_resources.contents(spinalcordtoolbox.data.deepseg.sc,'t1_sc.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: contents() takes 1 positional argument but 2 were given
>>> importlib_resources.path(spinalcordtoolbox.data.deepseg.sc,'t1_sc.h5')
<contextlib._GeneratorContextManager object at 0x7f62d2f736a0>
>>> importlib_resources.path(spinalcordtoolbox.data.deepseg.sc,'t1_sc.h5').__enter__()
PosixPath('/home/kousu/.local/lib/python3.6/site-packages/spinalcordtoolbox/data/deepseg/sc/t1_sc.h5')
>>> p = importlib_resources.path(spinalcordtoolbox.data.deepseg.sc,'t1_sc.h5').__enter__()
>>> p.is_file()
True
>>> 
```

**Comment by kousu** [comment]
(migrated from https://github.com/neuropoly/spinalcordtoolbox/issues/1526#issuecomment-813085296)

> > Experimentally, Pypi has a 1GB limit on files uploaded to it.
> > Github's is ~2GB~ 100MB but they only tell you that after you've finished uploading, unless you go over 2GB in which case git just drops you; for anything we can't fit on pypi, for packaging data, we can easily use github with direct links, e.g.
> > ```
> > extras_require={
> >   'PAM50': [spinalcordtoolbox-data-pam50@https://github.com/neuropoly/spinalcordtoolbox/releases/download/5.2.0/pam50.whl],
> > ```
> > 
> > 
> > This should be able to replace most of sct_download_data.
> 
> This works for `install_requires` too, right? I ask because it might be a bit awkward to have to manually specify every data/binary package (e.g. `pip install spinalcordtoolbox[PAM50]`).

Of course. Of our current pacakges I think


*install_requires:*
* PAM50
* gm_model
* optic_models
* pmj_models
* binaries_*
* deepseg_gm_models
* deepseg_sc_models
* deepseg_lesion_models
* c2c3_disc_models


*extras_require:*
* sct_example_data
* sct_testing_data
* MNI-Poly-AMU
* course_hawaii17
* course_paris18
* course_london19
* course_bejing19
* exvivo_template

And maybe the course_* ones shouldn't be packaged with `pip` at all, but we should just give people curl commands they can run directly, since they're more of a hands-on sort of thing. Stata has a really neat trick for handling that situation: a Stata package can [define "ancillary" files](
https://www.stata.com/manuals/rnet.pdf), so that

```
. net install $pkg
```

is like `pip install $pkg`

but

```
. net get $pkg
```

gets data files *to your working directory*. For doing science and tutorials that's really really helpful and I've never seen it built in to another language. But I'm sure we'll figure something out.

The biggest thing I'm stuck on, and I'm happy to keep chewing on, is how to handle `binaries_*`. We might have to migrate everything else to pip but keep `install_sct` around for a while until someone can deal with them. See, actually building binaries for multiple platforms is sort of tricky, but I have some of it done in [this branch](https://github.com/kousu/ANTs/tree/matrix-build) (and have a long plan detailed in #2669). If we get that working, pip can automatically figure out what [platform a user is on](https://packaging.python.org/guides/distributing-packages-using-setuptools/#platform-wheels) and finds the right package for you (e.g. https://pypi.org/project/torch/1.5.0/#files covers a subset of {macosx_10_7,macosx_10_6,macosx_10_9,manlinux1}x{x86_64}x{python2.7,python3.5,python3.6,python3.7,python3.8}) so you just say `pip install torch` and it picks an option for you. Right now we have fragile logic in `install_sct` to replicate this feature.

**Comment by kousu** [comment]
(migrated from https://github.com/neuropoly/spinalcordtoolbox/issues/1526#issuecomment-814096301)

* gm_model
* optic_models
* pmj_models
* c2c3_disc_models

are really really small. I think we should probably just keep them directly in this repo, under spinalcordtoolbox/data/{gm,optic,pmj,c2c3}.

**Comment by kousu** [comment]
Food for thought: Should we be packaging the code that *uses* each of these models with the model?

**Comment by kousu** [comment]
This line is going to break when I remove __init__.py

https://github.com/neuropoly/spinalcordtoolbox/blob/3f4b37e09448ba23e9571c4f77645412621c6106/spinalcordtoolbox/compat/launcher.py#L31
