### ISSUE TITLE
Deprecate CentOS 6

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#2675]
CentOS6 [is end-of-life](https://wiki.centos.org/About/Product) in November 2020.

We are currently maintaining ancient CentOS6 compiled dependencies

https://github.com/neuropoly/spinalcordtoolbox/blob/f0a6478d6b0a91209f7a76c1897f4fd1263ad70a/scripts/sct_download_data.py#L105-L106

but we don't test this very well. I also discovered in #2669 that ANTS won't even compile on CentOS 6, so people running on CentOS 6 are using subtly different maths than people on other OSes. We should plan to drop support by November and let everyone know they need to upgrade.

## TODO

* [ ] Remove `binaries_centos(6?)` from `sct_download_data`
* [ ] Update README
* [ ] Make sure this makes it into the changelog for our users.

**Comment by kousu** [comment]
This might have already happened without us! https://api.travis-ci.org/v3/job/683313090/log.txt:

```
Check if tensorflow (1.5.0) is installed............[FAIL]

Traceback (most recent call last):

  File "/repo/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>

    from tensorflow.python.pywrap_tensorflow_internal import *

  File "/repo/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()

  File "/repo/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper

    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "/repo/python/envs/venv_sct/lib/python3.6/imp.py", line 243, in load_module

    return load_dynamic(name, filename, file)

  File "/repo/python/envs/venv_sct/lib/python3.6/imp.py", line 343, in load_dynamic

    return _load(spec)

ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /repo/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

This also happens on old Ubuntu/Debian: #2523

**Comment by jcohenadad** [comment]
Ok let's just drop centos6

**Comment by jcohenadad** [comment]
If you could please update the README about OSs that are supported
