### ISSUE TITLE
AssertionError thrown when processing multiple subjects in parallel

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2725]
SCT Version: jca/947-new-ants-binaries-c1259598f01139eeb1d129a5baea50697f491010
Station: `joplin` (internal)
Syntax: 
~~~
sct_run_batch -jobs 25 -path-data ~/duke/sct_testing/bids/spineGeneric_multiSubjects -path-output spineGeneric_20200521/ -path-segmanual ~/duke/projects/spine_generic/spineGeneric_20191104/seg_manual/ ~/code/spine-generic/processing/process_data.sh
~~~

Error: 
~~~
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/scripts/sct_run_batch.py", line 152, in <module>
    p.map(run_single, subject_dirs)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AssertionError: Processing of subject sub-cmrrb05 failed
~~~

<details><summary>Full output</summary>

~~~
p101317@joplin:~/data_nvme_p101317$ sct_run_batch -jobs 25 -path-data ~/duke/sct_testing/bids/spineGeneric_multiSubjects -path-output spineGeneric_20200521/ -path-segmanual ~/duke/projects/spine_generic/spineGeneric_20191104/seg_manual/ ~/code/spine-generic/processing/process_data.sh
Running sub-amu01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-amu01.log
Running sub-amu04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-amu04.log
Running sub-balgrist02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-balgrist02.log
Running sub-balgrist05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-balgrist05.log
Running sub-barcelona02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-barcelona02.log
Running sub-barcelona05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-barcelona05.log
Running sub-beijingGE02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-beijingGE02.log
Running sub-beijingPrisma01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-beijingPrisma01.log
Running sub-beijingPrisma04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-beijingPrisma04.log
Running sub-beijingVerio02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-beijingVerio02.log
Running sub-brno01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-brno01.log
Running sub-brno04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-brno04.log
Running sub-brno07. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-brno07.log
Running sub-brnoPrisma02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-brnoPrisma02.log
Running sub-brnoPrisma05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-brnoPrisma05.log
Running sub-cardiff02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cardiff02.log
Running sub-cardiff05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cardiff05.log
Running sub-cmrra02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cmrra02.log
Running sub-cmrra05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cmrra05.log
Running sub-cmrrb05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cmrrb05.log
Running sub-cmrrb02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cmrrb02.log
Running sub-dresden01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-dresden01.log
Running sub-geneva02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-geneva02.log
Running sub-geneva05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-geneva05.log
Running sub-hamburg02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-hamburg02.log
Running sub-hamburg05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-hamburg05.log
Running sub-juntendo750w02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-juntendo750w02.log
Running sub-juntendo750w05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-juntendo750w05.log
Running sub-mgh02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mgh02.log
Running sub-mgh05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mgh05.log
Running sub-milan02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-milan02.log
Running sub-milan05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-milan05.log
Running sub-mniPilot1. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mniPilot1.log
Running sub-mniS03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mniS03.log
Running sub-mniS06. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mniS06.log
Running sub-mniS09. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mniS09.log
Running sub-mpicbs03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mpicbs03.log
Running sub-mpicbs07. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-mpicbs07.log
Running sub-nottwil03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-nottwil03.log
Running sub-nottwil06. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-nottwil06.log
Running sub-nwu03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-nwu03.log
Running sub-nwu06. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-nwu06.log
Running sub-oxfordFmrib03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-oxfordFmrib03.log
Running sub-oxfordFmrib06. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-oxfordFmrib06.log
Running sub-oxfordFmrib09. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-oxfordFmrib09.log
Running sub-oxfordOhba01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-oxfordOhba01.log
Running sub-oxfordOhba04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-oxfordOhba04.log
Running sub-pavia02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-pavia02.log
Running sub-pavia05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-pavia05.log
Running sub-perform02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-perform02.log
Running sub-perform05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-perform05.log
Running sub-queensland02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-queensland02.log
Running sub-queensland05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-queensland05.log
Running sub-sapienza02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-sapienza02.log
Running sub-sapienza05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-sapienza05.log
Running sub-sherbrooke02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-sherbrooke02.log
Running sub-sherbrooke05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-sherbrooke05.log
Running sub-stanford01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-stanford01.log
Running sub-stanford04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-stanford04.log
Running sub-strasbourg01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-strasbourg01.log
Running sub-strasbourg04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-strasbourg04.log
Running sub-tehranS01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tehranS01.log
Running sub-tehranS04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tehranS04.log
Running sub-tokyo750w01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyo750w01.log
Running sub-tokyo750w04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyo750w04.log
Running sub-tokyo750w07. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyo750w07.log
Running sub-tokyoIngenia03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyoIngenia03.log
Running sub-tokyoIngenia06. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyoIngenia06.log
Running sub-tokyoSkyra02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyoSkyra02.log
Running sub-tokyoSkyra05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-tokyoSkyra05.log
Running sub-ubc01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-ubc01.log
Running sub-ubc04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-ubc04.log
Running sub-ucl01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-ucl01.log
Running sub-ucl04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-ucl04.log
Running sub-unf01. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-unf01.log
Running sub-unf04. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-unf04.log
Running sub-unf07. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-unf07.log
Running sub-vallHebron03. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-vallHebron03.log
Running sub-vallHebron06. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-vallHebron06.log
Running sub-vuiisAchieva02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-vuiisAchieva02.log
Running sub-vuiisAchieva05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-vuiisAchieva05.log
Running sub-vuiisIngenia02. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-vuiisIngenia02.log
Running sub-vuiisIngenia05. See log file /mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-vuiisIngenia05.log
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/scripts/sct_run_batch.py", line 140, in run_single
    assert res.returncode == 0, 'Processing of subject {} failed'.format(subject)
AssertionError: Processing of subject sub-cmrrb05 failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/scripts/sct_run_batch.py", line 152, in <module>
    p.map(run_single, subject_dirs)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AssertionError: Processing of subject sub-cmrrb05 failed
~~~

</details>

I suspect this might be cause by a RAM saturation. Will do further tests.

**Comment by cfhammill** [comment]
Is there anything interesting in `/mnt/nvme/p101317/spineGeneric_20200521/log/process_data_sub-cmrrb05.log`? 

I assume it's probably gone by now, but if not or the issue reproduces, I'd be curious.

**Comment by jcohenadad** [comment]
that was a good stress-test to assess how well the lab keeps record of previous processing 😉  
we still have that log file (under internal server: `duke:projects/spine_generic/spineGeneric_20200521/log`): 
[err.process_data_sub-cmrrb05.log](https://github.com/neuropoly/spinalcordtoolbox/files/4842961/err.process_data_sub-cmrrb05.log)

so it looks like it was a stupid bug, which, AFAIR was fixed in a previous PR. So nothing related to `sct_run_batch` per say, meaning we can safely close that issue.
