### ISSUE TITLE
sct_create_mask -i <data> with any kind of data (default) doesn't work 

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#279]
Create mask...
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 335, in <module>
    main()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 87, in main
    create_mask()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 216, in create_mask
    mask2d = create_mask2d(center, param.shape, param.size, nx, ny)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 273, in create_mask2d
    radius = round(float(size+1)/2)  # add 1 because the radius includes the center.
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by slevyrosetti** [comment]
fixed in commit #5d57ac1 (2015-03-18)
