### ISSUE TITLE
SpinalCordStraightener depends on sct_utils without importing it

### ISSUE THREAD

**Issue by cfhammill** [neuropoly/spinalcordtoolbox#2922]
`SpinalCordStraightener` cannot be imported without first loading `sct_utils.py`

```python
>>> from spinalcordtoolbox.straightening import SpinalCordStraightener
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chammill/documents/spinalcordtoolbox/unit_testing/test_straightening.py", line 50, in <module>
  File "/home/chammill/documents/spinalcordtoolbox/spinalcordtoolbox/straightening.py", line 22, in <module>
    import sct_utils as sct
ModuleNotFoundError: No module named 'sct_utils'
```

**Comment by joshuacwnewton** [comment]
Not the first time this has happened! :stuck_out_tongue: See also #2627.

Possibly further motivation for #2898.
