### ISSUE TITLE
ReadTheDocs: sct_extract_metric help text fails to render because of FileNotFound

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2934]
### Description

Link: https://spinalcordtoolbox.com/en/latest/user_section/command-line.html#sct-extract-metric

Error message: 

```
--
Spinal Cord Toolbox (dev)


ERROR: The file /home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/data/PAM50/atlas/info_label.txt does not exist. Exit program.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/scripts/sct_extract_metric.py", line 390, in <module>
    parser = get_parser()
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/scripts/sct_extract_metric.py", line 64, in get_parser
    default_info_label = open(file_label, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/data/PAM50/atlas/info_label.txt'
```

### Discussion

Because RTD uses `pip install -r requirements.txt` and not `install_sct`, no `data/` folder is created, so `info_label.txt` isn't available to RTD. 

The file is currently used here:

https://github.com/neuropoly/spinalcordtoolbox/blob/69287b0953fad48bbabc4722d74ccf484ebfbeee/scripts/sct_extract_metric.py#L79-L86

When no error occurs (i.e. on a normal user install), the output of this section should be:

<details>
<summary>Long console snippet, click to open</summary>

```
To compute average MTR in a region defined by a single label file (could be binary or 0-1 weighted mask) between slices 1 and 4: sct_extract_metric.py -i mtr.nii.gz -f my_mask.nii.gz -z 1:4 -m wa
List of labels in /home/joshua/Repos/spinalcordtoolbox/data/PAM50/atlas/info_label.txt:
--------------------------------------------------------------------------------------
# White matter atlas. Generated on: 01-Sep-2016
#
# Keyword=IndivLabels (Please DO NOT change this line)
# ID, name, file
0, WM left fasciculus gracilis, PAM50_atlas_00.nii.gz
1, WM right fasciculus gracilis, PAM50_atlas_01.nii.gz
2, WM left fasciculus cuneatus, PAM50_atlas_02.nii.gz
3, WM right fasciculus cuneatus, PAM50_atlas_03.nii.gz
4, WM left lateral corticospinal tract, PAM50_atlas_04.nii.gz
5, WM right lateral corticospinal tract, PAM50_atlas_05.nii.gz
6, WM left ventral spinocerebellar tract, PAM50_atlas_06.nii.gz
7, WM right ventral spinocerebellar tract, PAM50_atlas_07.nii.gz
8, WM left rubrospinal tract, PAM50_atlas_08.nii.gz
9, WM right rubrospinal tract, PAM50_atlas_09.nii.gz
10, WM left lateral reticulospinal tract, PAM50_atlas_10.nii.gz
11, WM right lateral reticulospinal tract, PAM50_atlas_11.nii.gz
12, WM left spinal lemniscus (spinothalamic and spinoreticular tracts), PAM50_atlas_12.nii.gz
13, WM right spinal lemniscus (spinothalamic and spinoreticular tracts), PAM50_atlas_13.nii.gz
14, WM left spino-olivary tract, PAM50_atlas_14.nii.gz
15, WM right spino-olivary tract, PAM50_atlas_15.nii.gz
16, WM left ventrolateral reticulospinal tract, PAM50_atlas_16.nii.gz
17, WM right ventrolateral reticulospinal tract, PAM50_atlas_17.nii.gz
18, WM left lateral vestibulospinal tract, PAM50_atlas_18.nii.gz
19, WM right lateral vestibulospinal tract, PAM50_atlas_19.nii.gz
20, WM left ventral reticulospinal tract, PAM50_atlas_20.nii.gz
21, WM right ventral reticulospinal tract, PAM50_atlas_21.nii.gz
22, WM left ventral corticospinal tract, PAM50_atlas_22.nii.gz
23, WM right ventral corticospinal tract, PAM50_atlas_23.nii.gz
24, WM left tectospinal tract, PAM50_atlas_24.nii.gz
25, WM right tectospinal tract, PAM50_atlas_25.nii.gz
26, WM left medial reticulospinal tract, PAM50_atlas_26.nii.gz
27, WM right medial reticulospinal tract, PAM50_atlas_27.nii.gz
28, WM left medial longitudinal fasciculus, PAM50_atlas_28.nii.gz
29, WM right medial longitudinal fasciculus, PAM50_atlas_29.nii.gz
30, GM left ventral horn, PAM50_atlas_30.nii.gz
31, GM right ventral horn, PAM50_atlas_31.nii.gz
32, GM left intermediate zone, PAM50_atlas_32.nii.gz
33, GM right intermediate zone, PAM50_atlas_33.nii.gz
34, GM left dorsal horn, PAM50_atlas_34.nii.gz
35, GM right dorsal horn, PAM50_atlas_35.nii.gz
36, CSF contour, PAM50_atlas_36.nii.gz

# Combined labels
# Keyword=CombinedLabels (Please DO NOT change this line)
# ID, name, IDgroup
50, spinal cord, 0:35
51, white matter, 0:29
52, gray matter, 30:35
53, dorsal columns, 0:3
54, lateral funiculi, 4:13
55, ventral funiculi, 14:29

# Clusters used for the first step of the MAP estimation (for advanced users only)
# Keyword=MAPLabels (Please DO NOT change this line)
# Name, IDgroup
white matter, 0:29
gray matter, 30:35
CSF, 36

--------------------------------------------------------------------------------------
```
</details>

**Comment by jcohenadad** [comment]
Hum... i'm not sure how we should fix this. One possibility would be to _not_ display the list of labels (ie not call info_label.txt) on the help, but mention in flag `-l` that if they want to know the list of labels, they need to type e.g. `sct_extract_metric -list-labels` (or something like that...)

**Comment by joshuacwnewton** [comment]
Ah, I've just noticed that we're using the label file from the PAM50 template by default. 

Right now, my long-term to-do list includes writing a user-friendly guide for PAM50 template, because that's part of the SourceForge docs transfer (see the remaining tasks in https://github.com/neuropoly/spinalcordtoolbox/pull/2862). This PAM50 guide could contain the information from `info_labels.txt`. 

(`info_labels.txt` is [briefly mentioned on RTD,](https://spinalcordtoolbox.com/en/jn-2829-transfer-sourceforge-docs/overview/concepts.html#white-matter-atlas) but I think that mention could be expanded. The page I linked still needs a lot of work from me, as it's quite cluttered the way I left it.)

Once that's finished, what we could hypothetically do is say something like:

```
By default, this script uses the label file from the PAM50 template. For more information about the available 
labels from this template, please refer to https://spinalcordtoolbox.com/en/latest/overview/pam50.html
```

**Comment by joshuacwnewton** [comment]
I've just come across #1951, which considers how user-modified `info_label.txt` files are displayed. That should be kept in mind when addressing this issue.

**Comment by joshuacwnewton** [comment]
Good news! I have completed an initial draft for my sourceforge documentation transfer. This includes an updated PAM50 template guide, which displays `info_label.txt` here: https://spinalcordtoolbox.com/en/jn-2829-transfer-sourceforge-docs/overview/concepts/pam50.html#white-matter-atlas-pam50-atlas

Let me know if you think it's feasible to point this page from `sct_extract_metric`. (Barring feedback on that PR, of course. The guide may still need work.)

**Comment by jcohenadad** [comment]
@joshuacwnewton this is **AMAZING**! thank you so much. i'll comment directly on the PR

**Comment by joshuacwnewton** [comment]
On closer inspection, I think the existing `sct_extract_metric` description is outdated in more ways than one. It reads:

<details>
<summary>Long output hidden, click to show</summary>

```
This program extracts metrics (e.g., DTI or MTR) within labels. Labels could be a single file or a folder generated with 'sct_warp_template' and containing multiple label files and a label description file (info_label.txt). The labels should be in the same space coordinates as the input image.

To list white matter atlas labels: sct_extract_metric.py -f /home/joshua/Repos/spinalcordtoolbox/data/atlas

To compute FA within labels 0, 2 and 3 within vertebral levels C2 to C7 using binary method: sct_extract_metric.py -i dti_FA.nii.gz -f label/atlas -l 0,2,3 -v 2:7 -m bin

To compute average MTR in a region defined by a single label file (could be binary or 0-1 weighted mask) between slices 1 and 4: sct_extract_metric.py -i mtr.nii.gz -f my_mask.nii.gz -z 1:4 -m wa
List of labels in /home/joshua/Repos/spinalcordtoolbox/data/PAM50/atlas/info_label.txt:
--------------------------------------------------------------------------------------
# White matter atlas. Generated on: 01-Sep-2016
#
# Keyword=IndivLabels (Please DO NOT change this line)
# ID, name, file
0, WM left fasciculus gracilis, PAM50_atlas_00.nii.gz
1, WM right fasciculus gracilis, PAM50_atlas_01.nii.gz
2, WM left fasciculus cuneatus, PAM50_atlas_02.nii.gz
3, WM right fasciculus cuneatus, PAM50_atlas_03.nii.gz
4, WM left lateral corticospinal tract, PAM50_atlas_04.nii.gz
5, WM right lateral corticospinal tract, PAM50_atlas_05.nii.gz
6, WM left ventral spinocerebellar tract, PAM50_atlas_06.nii.gz
7, WM right ventral spinocerebellar tract, PAM50_atlas_07.nii.gz
8, WM left rubrospinal tract, PAM50_atlas_08.nii.gz
9, WM right rubrospinal tract, PAM50_atlas_09.nii.gz
10, WM left lateral reticulospinal tract, PAM50_atlas_10.nii.gz
11, WM right lateral reticulospinal tract, PAM50_atlas_11.nii.gz
12, WM left spinal lemniscus (spinothalamic and spinoreticular tracts), PAM50_atlas_12.nii.gz
13, WM right spinal lemniscus (spinothalamic and spinoreticular tracts), PAM50_atlas_13.nii.gz
14, WM left spino-olivary tract, PAM50_atlas_14.nii.gz
15, WM right spino-olivary tract, PAM50_atlas_15.nii.gz
16, WM left ventrolateral reticulospinal tract, PAM50_atlas_16.nii.gz
17, WM right ventrolateral reticulospinal tract, PAM50_atlas_17.nii.gz
18, WM left lateral vestibulospinal tract, PAM50_atlas_18.nii.gz
19, WM right lateral vestibulospinal tract, PAM50_atlas_19.nii.gz
20, WM left ventral reticulospinal tract, PAM50_atlas_20.nii.gz
21, WM right ventral reticulospinal tract, PAM50_atlas_21.nii.gz
22, WM left ventral corticospinal tract, PAM50_atlas_22.nii.gz
23, WM right ventral corticospinal tract, PAM50_atlas_23.nii.gz
24, WM left tectospinal tract, PAM50_atlas_24.nii.gz
25, WM right tectospinal tract, PAM50_atlas_25.nii.gz
26, WM left medial reticulospinal tract, PAM50_atlas_26.nii.gz
27, WM right medial reticulospinal tract, PAM50_atlas_27.nii.gz
28, WM left medial longitudinal fasciculus, PAM50_atlas_28.nii.gz
29, WM right medial longitudinal fasciculus, PAM50_atlas_29.nii.gz
30, GM left ventral horn, PAM50_atlas_30.nii.gz
31, GM right ventral horn, PAM50_atlas_31.nii.gz
32, GM left intermediate zone, PAM50_atlas_32.nii.gz
33, GM right intermediate zone, PAM50_atlas_33.nii.gz
34, GM left dorsal horn, PAM50_atlas_34.nii.gz
35, GM right dorsal horn, PAM50_atlas_35.nii.gz
36, CSF contour, PAM50_atlas_36.nii.gz

# Combined labels
# Keyword=CombinedLabels (Please DO NOT change this line)
# ID, name, IDgroup
50, spinal cord, 0:35
51, white matter, 0:29
52, gray matter, 30:35
53, dorsal columns, 0:3
54, lateral funiculi, 4:13
55, ventral funiculi, 14:29

# Clusters used for the first step of the MAP estimation (for advanced users only)
# Keyword=MAPLabels (Please DO NOT change this line)
# Name, IDgroup
white matter, 0:29
gray matter, 30:35
CSF, 36
```
</details>


Some notes:
* `data/atlas` no longer exists, and has been replaced by `data/PAM50`. 
* The commands reference vertebral levels, so I _think_ we should be referring to `PAM50/spinal_levels` and not the white matter atlas labels from `PAM50/atlas` (correct me if I'm wrong)
* The commands with `sct_extract_metric.py` don't work as written.
    * `.py` should be removed.
    * `-f` no longer allows you to list labels, I think?

Here is my proposed rewrite:

```
This program extracts metrics (e.g., DTI or MTR) within labels. Labels could be a 
single file or a folder generated with 'sct_warp_template' and containing multiple 
label files and a label description file (info_label.txt). The labels should be in the 
same space coordinates as the input image.

The default labels are taken from the PAM50 template. To learn about the 
available PAM50 spinal level labels to compute metrics from, please refer to: 
https://spinalcordtoolbox.com/en/latest/overview/concepts/pam50.html#spinal-levels-pam50-spinal-levels

To compute FA within labels 0, 2 and 3 within vertebral levels C2 to C7 using 
binary method: sct_extract_metric -i dti_FA.nii.gz -f label/atlas -l 0,2,3 -v 2:7 -m bin

To compute average MTR in a region defined by a single label file (could be binary 
or 0-1 weighted mask) between slices 1 and 4:
sct_extract_metric -i mtr.nii.gz -f my_mask.nii.gz -z 1:4 -m wa
```

Where the PAM50 link would end up here: https://spinalcordtoolbox.com/en/jn-2829-transfer-sourceforge-docs/overview/concepts/pam50.html#spinal-levels-pam50-spinal-levels

**Comment by jcohenadad** [comment]
> data/atlas no longer exists, and has been replaced by data/PAM50.

you're right

> The commands reference vertebral levels, so I think we should be referring to PAM50/spinal_levels and not the white matter atlas labels from PAM50/atlas (correct me if I'm wrong)

this is where things get confusing. The mention of "vertebral level" refers to the flag `-l`, not `-f`. The latter flag refers to the atlas folder, which is indeed `PAM50/atlas`. However, given that `PAM50/atlas` is the default folder, we could omit it in this example, as to not create confusion. We can later create another example where we would specify a non-default destination for `-f`.
So, the flag `-l` specify the vertebral levels, and if people wants to specify another vertebral level file, they could use the flag `-vertfile` (which by default points to `./label/template/PAM50_levels.nii.gz`).

> The commands with sct_extract_metric.py don't work as written.
.py should be removed.

agreed

> -f no longer allows you to list labels, I think?

wow, good catch! indeed, it does not.

> The second command references -f label/atlas. But, this is also be the default value for -f anyway... hm. And... should this not be data/PAM50/spinal_levels? (Perhaps the argparse values for -f need to be updated too, but I'm unsure.)

I think my explanation above clarifies this.

Here is a modification of your suggested text:
~~~
This program extracts metrics (e.g., DTI or MTR) within labels. Labels could be a 
single file or a folder generated with 'sct_warp_template' and containing multiple 
label files and a label description file (info_label.txt). The labels should be in the 
same space coordinates as the input image.

The default labels are taken from the PAM50 template. To learn about the 
available PAM50 spinal level labels to compute metrics from, please refer to: 
https://spinalcordtoolbox.com/en/latest/overview/concepts/pam50.html#spinal-levels-pam50-spinal-levels

To compute FA within labels 0, 2 and 3 within vertebral levels C2 to C7 using 
binary method: 
sct_extract_metric -i dti_FA.nii.gz -l 0,2,3 -v 2:7 -m bin

To compute average MTR in a region defined by a single label file (could be binary 
or 0-1 weighted mask) between slices 1 and 4:
sct_extract_metric -i mtr.nii.gz -f my_mask.nii.gz -z 1:4 -m wa
~~~

**Comment by jcohenadad** [comment]
> You've clarified most things for me, so thank you for that. But, there's one thing that I'm still unsure about. Two of these default values reference a label/ directory, but as far as I can tell, this directory doesn't exist.

ok, this is also confusing. The folder `label/` is supposed to be created on the current directory by the function `sct_warp_template`. It is mentioned in the usage of `sct_extract_metric`, but I agree it can be confusing:
~~~
This program extracts metrics (e.g., DTI or MTR) within labels. Labels could be a single file or a folder generated with 'sct_warp_template' and containing multiple label files and a label description file (info_label.txt).
~~~
