### ISSUE TITLE
Running `make html` locally throws several new warnings

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2951]
I was making an RTD change, so I built the docs locally. Running `make html` gives the following output:

<details>
<summary>Hidden, click to show</summary>

```
make html
Running Sphinx v3.2.1
sct_root: /home/joshua/Repos/spinalcordtoolbox
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 13 source files that are out of date
updating environment: [new config] 13 added, 0 changed, 0 removed
/home/joshua/Repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading /home/joshua/Repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
reading sources... [100%] user_section/support                                                                  
WARNING: autodoc: failed to import module 'core' from module 'spinalcordtoolbox.deepseg_sc'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'postprocessing' from module 'spinalcordtoolbox.deepseg_sc'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'deepseg_gm' from module 'spinalcordtoolbox.deepseg_gm'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'core' from module 'spinalcordtoolbox.deepseg_lesion'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'optic' from module 'spinalcordtoolbox.centerline'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'process_seg' from module 'spinalcordtoolbox'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'straightening' from module 'spinalcordtoolbox'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'qc' from module 'spinalcordtoolbox.reports'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'slice' from module 'spinalcordtoolbox.reports'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'core' from module 'spinalcordtoolbox.vertebrae'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'detect_c2c3' from module 'spinalcordtoolbox.vertebrae'; the following exception was raised:
No module named 'sct_utils'
/home/joshua/Repos/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py:docstring of spinalcordtoolbox.aggregate_slicewise.merge_dict:3: WARNING: Unexpected indentation.
/home/joshua/Repos/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py:docstring of spinalcordtoolbox.aggregate_slicewise.merge_dict:6: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/joshua/Repos/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py:docstring of spinalcordtoolbox.aggregate_slicewise.merge_dict:8: WARNING: Unexpected indentation.
/home/joshua/Repos/spinalcordtoolbox/spinalcordtoolbox/aggregate_slicewise.py:docstring of spinalcordtoolbox.aggregate_slicewise.merge_dict:10: WARNING: Block quote ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import module 'resampling' from module 'spinalcordtoolbox'; the following exception was raised:
No module named 'sct_utils'
WARNING: autodoc: failed to import module 'moco' from module 'spinalcordtoolbox'; the following exception was raised:
No module named 'sct_utils'
/home/joshua/Repos/spinalcordtoolbox/documentation/source/index.rst:58: WARNING: toctree contains reference to nonexisting document 'dev_section/development'
WARNING: Unexpected return code 1 from command 'sct_deepseg -h'
WARNING: Unexpected return code 2 from command 'isct_convert_binary_to_trilinear -h'
WARNING: Unexpected return code 2 from command 'isct_test_ants -h'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user_section/support                                                                   
generating indices...  genindex py-modindexdone
highlighting module code... [100%] spinalcordtoolbox.utils                                                      
writing additional pages...  searchdone
copying images... [100%] overview/../../imgs/overview.png                                                       
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 21 warnings.

The HTML pages are in build/html.
```

</details>

To summarise:
* Import errors (possibly from `sct_utils` refactor)
* `sct_deepseg` and some `isct` scripts erroring when displaying `-h` help
* There are some linting issues in a docstring from `aggregate_slicewise`
* A toctree is pointing at a non-existent page.

This also might be indicative of a larger testing issue. i.e. Maybe we should be checking to see if `make html` runs without warnings on PR.

**Comment by Drulex** [comment]
One common problem from the list of warnings is an API module trying to import a script from the `scripts` directory and failing. This is expected, because as far as the API is concerned the `scripts` directory doesn't exist.

Some files "hack" their way around by injecting the `scripts` directory in the system path, allowing imports to work. This is definitely not the preferred way and should be kept temporarily until the codebase is properly refactored.

The remaining issues are valid.

**Comment by Drulex** [comment]
>WARNING: Unexpected return code 1 from command 'sct_deepseg -h'

The actual error:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/scripts/sct_deepseg.py", line 179, in <module>
    main()
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/scripts/sct_deepseg.py", line 118, in main
    parser = get_parser()
  File "/home/docs/checkouts/readthedocs.org/user_builds/spinalcordtoolbox/envs/latest/lib/python3.6/site-packages/scripts/sct_deepseg.py", line 58, in get_parser
    choices=list(deepseg.models.TASKS.keys()))
AttributeError: module 'spinalcordtoolbox.deepseg' has no attribute 'models'
```

This is also expected given the current structure of the API modules. The current structure:
```
spinalcordtoolbox                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
├── deepseg                                                                                                                                                                                                                                                                                                                    
│   ├── core.py                                                                                                                                                                                                                                                                                                                
│   ├── __init__.py (empty)                                                                                                                                                                                                                                                                                                            
│   └── models.py                                                                                                                                                                                                                                                                                                              
[...]
```
`sct_deepseg` does ` import spinalcordtoolbox.deepseg as deepseg` and then tries to access `deepseg.models`. This would only work if `spinalcordtoolbox/deepseg/__init__.py` actually imports `models.py` via a `from . import models`, but it is currently empty.

Since none of the `__init__.py` files actually import their relative modules, one cannot simply import a parent module and try to access the children. In this case `sct_deepseg` needs to either:
1. explicitely import models  via `import spinalcordtoolbox.deepseg.models`  and access it via `spinalcordtoolbox.deepseg.models.something()`
2. properly export the modules in the `__init__.py` and stick with the `deepseg.models.something()` approach.

Number `2` is definitely the standard and preferred way to do this. I'm surprised this hasn't broken some tests elsewhere.

**Comment by jcohenadad** [comment]
agreed about number 2-- thanks for looking in to this
