### ISSUE TITLE
Bug with specifying input folder with "~"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2995]
When specifying input files with "~", it produces the following bug:

~~~
 sct_deepseg_sc -i ~/sct_testing_data/t2.nii.gz -c t2

--
Spinal Cord Toolbox (git-lr/missing_disc_label_vertebrae-d9cd23a829e5a2fc92063649ed6a7d6f959a8cce)

Traceback (most recent call last):
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/julien/sct_testing_data/t2.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 208, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 183, in main
    check_dim(fname_image, dim_lst=[2, 3])
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 1416, in check_dim
    dim = Image(fname).hdr['dim'][:4]
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 247, in __init__
    self.loadFromPath(param, verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 349, in loadFromPath
    self.im_file = nib.load(path)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/Users/julien/sct_testing_data/t2.nii.gz'
~~~

**Comment by jcohenadad** [comment]
I'm wondering if this is due to my recent switch to zsh...

**Comment by jcohenadad** [comment]
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/1416

**Comment by joshuacwnewton** [comment]
@jcohenadad Did you mean `~/sct_testing_data/t2/t2.nii.gz`? (The `t2` subdirectory seems to be missing from the command.)

**Comment by jcohenadad** [comment]
omg... 🤦‍♂️
