### ISSUE TITLE
sct_register_multimodal -p is mandatory

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#317]
No defaut value for -p
`````
sct_register_multimodal -i spgr20_crop.nii.gz -d spgr10_crop.nii.gz
Check file existence...
  OK: spgr20_crop.nii.gz
Check file existence...
  OK: spgr10_crop.nii.gz
Traceback (most recent call last):
  File "/Users/taduv/codes/spinalcordtoolbox/bin/sct_register_multimodal", line 470, in <module>
    main()
  File "/Users/taduv/codes/spinalcordtoolbox/bin/sct_register_multimodal", line 210, in main
    paramreg_user = arguments['-p']
KeyError: '-p'
````

**Comment by jcohenadad** [comment]
fixed in 2e31f77061facb0c843de45bbae28c76e9e6cfdf
