### ISSUE TITLE
error with NURBS

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#322]
data:
~~~~
sct_issues/20150415_julien
~~~~

syntax:
~~~~
sct_get_centerline_from_labels -i t1-mask.nii.gz,t1-mask-mask.nii.gz -p binary_centerline
~~~~

error:
~~~~
julien-macbook:~/data/temp/sct_example_data/t1 $ sct_get_centerline_from_labels -i t1-mask.nii.gz,t1-mask-mask.nii.gz -p binary_centerline
Check file existence...
  OK: t1-mask.nii.gz
Check file existence...
  OK: t1-mask-mask.nii.gz
mkdir tmp.150415185938
cp /Users/julien/data/temp/sct_example_data/t1/t1-mask.nii.gz tmp.150415185938
cp /Users/julien/data/temp/sct_example_data/t1/t1-mask-mask.nii.gz tmp.150415185938

Write NIFTI volumes...
mkdir tmp.150415185939
cp /Users/julien/data/temp/sct_example_data/t1/tmp.150415185938/concatenation_file.nii.gz tmp.150415185939
/Users/julien/miniconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/julien/miniconda/lib/python2.7/site-packages/numpy/core/_methods.py:71: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 6.86 mm
Test: # of control points = 6
WARNING: NURBS instability -> wrong reconstruction
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_get_centerline_from_labels", line 163, in <module>
    main(list_file, param, output_file_name, parameter, remove_temp_files, verbose)
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_get_centerline_from_labels", line 69, in main
    fname_output = extract_centerline('concatenation_file.nii.gz', param, remove_temp_files=1)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 281, in extract_centerline
    x_centerline_fit, y_centerline_fit, z_centerline_fit, x_centerline_deriv,y_centerline_deriv,z_centerline_deriv = smooth_centerline(fname_segmentation_orient, param, 1)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 651, in smooth_centerline
    x_centerline_fit, y_centerline_fit, z_centerline_fit, x_centerline_deriv, y_centerline_deriv, z_centerline_deriv = b_spline_nurbs(x_centerline, y_centerline, z_centerline, nbControl=None, verbose=verbose)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_smooth.py", line 269, in b_spline_nurbs
    nurbs = NURBS(degree, point_number, data, False, nbControl, verbose)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_nurbs.py", line 162, in __init__
    self.courbe3D, self.courbe3D_deriv = self.construct3D(self.pointsControle, self.degre, self.precision)  # generate curve with hig resolution
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_nurbs.py", line 322, in construct3D
    raise Exception('WARNING: NURBS instability -> wrong reconstruction')
Exception: WARNING: NURBS instability -> wrong reconstruction
~~~~

**Comment by tanguymagnan** [comment]
Comment est ce ce que je peux récupérer ces datas? Elles sont sur django?

2015-04-15 19:02 GMT-04:00 Julien Cohen-Adad <notifications@github.com>:

> Assigned #322 <https://github.com/neuropoly/spinalcordtoolbox/issues/322>
> to @tanguymagnan <https://github.com/tanguymagnan>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neuropoly/spinalcordtoolbox/issues/322#event-282604890>
> .
>



-- 
Tanguy Magnan de Bornier
Second year student at the Ecole Centrale de Lille, France.
Ph.: 06.77.25.29.91

**Comment by tanguymagnan** [comment]
This was due to the fact that the number of control points of the nurbs had reached the number of points that were given as input while the tolerance was never satisfied. This problem was really particular to a very low number of input points.

It is now fixed by using the last nurbs (i.e. (number of control points, coordinates of points of controle)) that did not raise an exception. A message is also displayed to warn the user.

![screenshot 2015-04-16 17 22 08](https://cloud.githubusercontent.com/assets/11425966/7191892/f97a0e18-e45e-11e4-9852-c0c2d526e810.png)

**Comment by tanguymagnan** [comment]
added and tested on master
