### ISSUE TITLE
Applying straightening on labels makes them "float", causing potential label mismatch

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3229]
### Description

I'm running `sct_register_to_template` on a dataset. The labels are float64, with value 3.0 and 6.0. When launching the command, I get the following error:
~~~
Exception: Error: number of source and destination landmarks are not the same, so landmarks cannot be paired.
~~~

<details><summary>Full output</summary>

```console
julien-macbook:~/Desktop/test $ sct_register_to_template -i dmri_moco_dwi_mean.nii.gz -s dmri_moco_dwi_mean_seg.nii.gz -l dmri_labels_uint8.nii.gz -c t1 -qc ~/qc_DTI_Cordotomy/

--
Spinal Cord Toolbox (git-master-c7810852dc0908e5a1bdede2e544eb8592817b7c)

sct_register_to_template -i dmri_moco_dwi_mean.nii.gz -s dmri_moco_dwi_mean_seg.nii.gz -l dmri_labels.nii.gz -c t1 -qc /Users/julien/qc_DTI_Cordotomy/
--


Check template files...
  OK: /Users/julien/code/sct/data/PAM50/template/PAM50_t1.nii.gz
  OK: /Users/julien/code/sct/data/PAM50/template/PAM50_levels.nii.gz
  OK: /Users/julien/code/sct/data/PAM50/template/PAM50_cord.nii.gz

Check parameters:
  Data:                 dmri_moco_dwi_mean.nii.gz
  Landmarks:            dmri_labels_uint8.nii.gz
  Segmentation:         dmri_moco_dwi_mean_seg.nii.gz
  Path template:        /Users/julien/code/sct/data/PAM50
  Remove temp files:    1

Check input labels...
Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j)

Copying input data to tmp folder and convert to nii...

Generate labels from template vertebral labeling

Check if provided labels are available in the template

Binarize segmentation

Resample data to 1mm isotropic...
load data...

Done! To view results, type:
fsleyes data_1mm.nii &

load data...

Done! To view results, type:
fsleyes seg_bin_1mm.nii.gz &


Change orientation of input images to RPI...

Straighten the spinal cord using centerline/segmentation...
Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201614.624153-straighten_spinalcord-jyw9kc4k)
Copy files to tmp folder...
Create the straight space and the safe zone
Length of spinal cord: 260.39442361185843
Size of spinal cord in z direction: 226.01236893196594
Ratio length/size: 1.1521246595589738
Safe zone boundaries (curved space): [-160.56980634535458, 65.44256258661136]
Safe zone boundaries (straight space): [-177.76083368530084, 82.6335899265576]
Pad input volume to account for spinal cord length...
Time to generate centerline: 22.0 ms
100%|████████████████████████████████████████████████████████████████████████████████| 261/261 [00:05<00:00, 46.18it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 280/280 [00:13<00:00, 21.05it/s]
Warping field generated: tmp.curve2straight.nii.gz
Warping field generated: tmp.straight2curve.nii.gz
Apply transformation to input image...
/Users/julien/code/sct/bin/isct_antsApplyTransforms -d 3 -r tmp.centerline_pad_crop.nii.gz -i data.nii -o tmp.anat_rigid_warp.nii.gz -t tmp.curve2straight.nii.gz -n 'BSpline[3]' # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201614.624153-straighten_spinalcord-jyw9kc4k
Generate output files...
File created: ./warp_curve2straight.nii.gz
File created: ./warp_straight2curve.nii.gz
cp /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201614.624153-straighten_spinalcord-jyw9kc4k/tmp.anat_rigid_warp.nii.gz ./straight_ref.nii.gz
File created: /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/seg_bin_1mm_rpi_crop_straight.nii.gz
Remove temporary files...
rm -rf /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201614.624153-straighten_spinalcord-jyw9kc4k
/Users/julien/code/sct/bin/isct_ComposeMultiTransform 3 warp_straight2curve.nii.gz -R /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/data_1mm_rpi.nii warp_straight2curve.nii.gz # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j

Remove unused label on template. Keep only label present in the input label image...
File template_label_body.nii.gz already exists. Will overwrite it.

Dilating input labels using 3vox ball radius

Apply straightening to labels...

Parse list of warping fields...

Get dimensions of data...
  49 x 277 x 277 x 1

Apply transformation...

Apply transformation and resample to destination space...
/Users/julien/code/sct/bin/isct_antsApplyTransforms -d 3 -i /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/label_projected_1mm_rpi_dilate.nii.gz -o /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/label_projected_1mm_rpi_dilate_straight.nii.gz -t warp_curve2straight.nii.gz -r /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/seg_bin_1mm_rpi_crop_straight.nii.gz -n NearestNeighbor # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j
Copy affine matrix from destination space to make sure qform/sform are the same.

Done! To view results, type:
fsleyes /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/seg_bin_1mm_rpi_crop_straight.nii.gz /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/label_projected_1mm_rpi_dilate_straight.nii.gz &


Estimate transformation for step #0...
Labels src: [[-4.423124828766348, 24.271400733249894, 13.471566987486483], [-8.161115166404265, 24.13651584865247, -45.151987875444576]]
Labels dest: []
Degrees of freedom (dof): Tx_Ty_Tz_Sz
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_register_to_template.py", line 1281, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_register_to_template.py", line 573, in main
    fname_affine='straight2templateAffine.txt', verbose=verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/registration/landmarks.py", line 82, in register_landmarks
    raise Exception('Error: number of source and destination landmarks are not the same, so landmarks cannot be paired.')
Exception: Error: number of source and destination landmarks are not the same, so landmarks cannot be paired.
```

</details>

I strongly suspect this is because the labels are not integer. Indeed, they are not:
~~~
sct_label_utils -i /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/label_projected_1mm_rpi_dilate_straight.nii.gz -display
28,70,198,3.0000457763671875 [...] (truncating the output because there is a bunch of labels in this file-- because of the dilation).
~~~

The step where the "floating" is introduced is the resampling space. Proof:
~~~
sct_label_utils -i /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/label_projected.nii.gz -display
Position=(124,161,6) -- Value= 3
Position=(130,114,5) -- Value= 6
# --> GOOD 👍 

sct_label_utils -i /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210218201610.062434-register_to_template-9jtrfi4j/label_projected_1mm.nii.gz -display
Position=(134,174,21) -- Value= 3.0000457763671875
Position=(141,123,18) -- Value= 5.999999998603016
# --> BAD 👎 
~~~

Context: https://forum.spinalcordmri.org/t/dti-pam50-template-registration/630

### Steps to Reproduce

0. Get those data: [Archive.zip](https://github.com/neuropoly/spinalcordtoolbox/files/6007110/Archive.zip)

1. Run:
~~~
sct_register_to_template -i dmri_moco_dwi_mean.nii.gz -s dmri_moco_dwi_mean_seg.nii.gz -l dmri_labels.nii.gz -c t1
~~~

### Additional investigations

I tried converting the initial labels from FLOAY64 to UINT8 (using the command below), but the same error occurs.
~~~
sct_image -i dmri_labels.nii.gz -type uint8 -o dmri_labels_uint8.nii.gz 
~~~

### Thoughts

I am wondering why this issue happens with this dataset specifically, and not with other datasets... we should identify the exact cause and consider increasing the sensitivity of our testing suite.

**Comment by joshuacwnewton** [comment]
> The step where the "floating" is introduced is the resampling space.

Interestingly, when the images are initially resampled, their values still equal `3.0` and `6.0`. But then once the image is saved...

```python
    # sct_register_to_template.py :: resample_labels()

    resampled_image = sct_labels.create_labels_empty(Image(fname_dest), new_labels)
    print(resampled_image.getNonZeroCoordinates())
    # Output: [(134, 174, 21, 3.0), (141, 123, 18, 6.0)]

    resampled_image.save(path=fname_output)
    print(Image(fname_output).getNonZeroCoordinates())
    # Output: [(134, 174, 21, 3.0000457763671875), (141, 123, 18, 5.999999998603016)]
```

The values only get distorted _when saving the image!_ I'm going to try to find out why.

**Comment by jcohenadad** [comment]
> The values only get distorted when saving the image! I'm going to try to find out why.

yup, that was also my suspicion! i suggest we look into this in a subsequent issue-- the user will imminently try the "fix on master" so we need ot merge asap-- many thanks!
