### ISSUE TITLE
"OSError: [Errno 24] Too many open files" when attempting to create a mask on large data

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3269]
### Description

I am trying to generate a mask on a volume that contains a lot of slices in the Z direction (440). This results in the following bug:

<details><summary>syntax & error</summary>

```console
sct_create_mask -i sub-karoTobiasMS001_acq-sag_T2w_r.nii.gz -p centerline,sub-karoTobiasMS001_acq-sag_T2w_r_seg.nii.gz -o mask_T2w.nii.gz -size 30 -f cylinder -r 0

--
Spinal Cord Toolbox (git-jn/3093-migrate-sct_testing-tests-not-implemented-1f68c39acaa7e6c301e975935ea30d1fa5ae7d79)

sct_create_mask -i sub-karoTobiasMS001_acq-sag_T2w_r.nii.gz -p centerline,sub-karoTobiasMS001_acq-sag_T2w_r_seg.nii.gz -o mask_T2w.nii.gz -size 30 -f cylinder -r 0
--

  OK: sub-karoTobiasMS001_acq-sag_T2w_r_seg.nii.gz
Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210309133748.627392-create_mask-wqc3r7uz)

Orientation:
  AIL

Dimensions:
(125, 440, 440, 1, 0.50160015, 0.5, 0.49999997, 1)

Create mask...
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_create_mask.py", line 358, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_create_mask.py", line 153, in main
    create_mask(param)
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_create_mask.py", line 260, in create_mask
    im_list = [Image(fname) for fname in fname_list]
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_create_mask.py", line 260, in <listcomp>
    im_list = [Image(fname) for fname in fname_list]
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 283, in __init__
    self.loadFromPath(param, verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 405, in loadFromPath
    self.data = self.im_file.get_data()
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/deprecator.py", line 183, in deprecated_func
    return func(*args, **kwargs)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/dataobj_images.py", line 207, in get_data
    data = np.asanyarray(self._dataobj)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/nibabel/volumeutils.py", line 507, in array_from_file
    offset=offset)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/numpy/core/memmap.py", line 278, in __new__
    self.filename = os.path.abspath(fid.name)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 24] Too many open files
```

</details>

### Steps to Reproduce

Get data from our git-annex internal database: 
~~~
sct-testing-large/sub-karoTobiasMS001/anat/sub-karoTobiasMS001_acq-sag_T2w.nii.gz
~~~

Prepare data:
~~~
sct_resample -i sub-karoTobiasMS001_acq-sag_T2w.nii.gz -mm 0.5x0.5x0.5 -o sub-karoTobiasMS001_acq-sag_T2w_r.nii.gz
sct_deepseg_sc -i sub-karoTobiasMS001_acq-sag_T2w_r.nii.gz -c t2 -qc /Users/julien/temp/ms-lesion/results_20210309_131926/qc -qc-subject sub-karoTobiasMS001
~~~

Then run the problematic syntax:
~~~
sct_create_mask -i sub-karoTobiasMS001_acq-sag_T2w_r.nii.gz -p centerline,sub-karoTobiasMS001_acq-sag_T2w_r_seg.nii.gz -o mask_T2w.nii.gz -size 30 -f cylinder -r 0
~~~

Related issues: [OSError: [Errno 24] Too many open files](https://github.com/neuropoly/spinalcordtoolbox/issues?q=is%3Aissue+OSError%3A+%5BErrno+24%5D+Too+many+open+files+is%3Aclosed)

**Comment by dyt811** [comment]
Is this on Mac? Might be related to ulimit as per threads and top Google results suggest below: 

- https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files
- https://github.com/jupyterlab/jupyterlab/issues/6727#issuecomment-506925806

**Comment by jcohenadad** [comment]
> Secondly, and more importantly, is why are so many files remaining "open". Could there be underlying coding/inefficiency issues with not closing files after reading them? Probably worth looking into how Nibabel volumeutils.py is working and raise issues there if needed. I am going to follow up to see if I can reproduce this issue in Ubuntu and other OS.

yup! if someone can look into it that would be great
