### ISSUE TITLE
AttributeError: module 'tensorboard' has no attribute 'lazy'

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3289]
### Description

I am currently working on #3284. I wanted to test the new version of ivadomed 2.7.4, so in a branch, i modified the requirements.txt to change ivadomed==2.7.2 --> 2.7.4.

Then, I activated conda's environment and reinstalled with pip:
```console
cd $SCT_DIR
source python/etc/profile.d/conda.sh
conda activate venv_sct
pip install -r requirements.txt 
```

Installation completed without error.

<details><summary>sct_check_dependencies</summary>

```console
julien-macbook:~/sct_example_data/mt $ sct_check_dependencies 

--
Spinal Cord Toolbox (git-jca/3284-deepseg-qform-60ea08c9d664cf403f2982f8f5c8ae1cc5d704a3*)

sct_check_dependencies 
--

SCT info:
- version: git-jca/3284-deepseg-qform-60ea08c9d664cf403f2982f8f5c8ae1cc5d704a3*
- path: /Users/julien/code/sct
OS: osx (Darwin-19.6.0-x86_64-i386-64bit)
CPU cores: Available: 16, Used by ITK functions: 16
RAM: Total: 16384MB, Used: 9290MB, Available: 7089MB
Check Python executable.............................[OK]
  Using bundled python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] at /Users/julien/code/sct/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.4.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if ivadomed (2.7.4) is installed..............[OK] (2.7.4)
Check if matplotlib is installed....................[OK] (3.3.4)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.19.5)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.1.5)
Check if psutil is installed........................[OK] (5.8.0)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.2.2)
Check if pytest-cov is installed....................[OK] (__version__ = '2.11.1')
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.25.1)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.24.1)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0) is installed.................[OK] (1.5.0)
Check if torchvision (0.6.0) is installed...........[OK] (0.6.0)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.59.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.3)
Check if pytest_console_scripts is installed........[OK]
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............[OK]
```

</details>
<Description of the issue>

However, when running `sct_deepseg` I got the following error:
```console
julien-macbook:~/sct_example_data/mt $ sct_deepseg -i mt1.nii.gz -task seg_sc_t2star
/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_deepseg.py", line 18, in <module>
    from ivadomed import inference as imed_inference
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 16, in <module>
    from ivadomed import training as imed_training
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/training.py", line 13, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 31, in <module>
    from tensorboard.summary import v2  # noqa: F401
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorboard/summary/v2.py", line 24, in <module>
    from tensorboard.plugins.audio.summary_v2 import audio  # noqa: F401
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorboard/plugins/audio/summary_v2.py", line 30, in <module>
    from tensorboard.compat import tf2 as tf
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/tensorboard/compat/__init__.py", line 27, in <module>
    import tensorboard.lazy as _lazy
AttributeError: module 'tensorboard' has no attribute 'lazy'
```

Possibly related to #3035

The workaround I found was to reinstall completely SCT's python (with `install_sct` script), but it is a bit annoying... @joshuacwnewton maybe you have another clue/workaround?

**Comment by joshuacwnewton** [comment]
<details>
<summary> Explanation for why <code>pip install -r requirements.txt</code> causes this tensorboard issue </summary>

The following lines in `install_sct` are what fix the tensorboard issue:

https://github.com/neuropoly/spinalcordtoolbox/blob/60ea08c9d664cf403f2982f8f5c8ae1cc5d704a3/install_sct#L613-L620

So, when you reinstalled this way:

> Then, I activated conda's environment and reinstalled with pip:
> 
> ```
> cd $SCT_DIR
> source python/etc/profile.d/conda.sh
> conda activate venv_sct
> pip install -r requirements.txt
> ```

Some commands were missed (uninstalling `tensorflow-tensorboard`, reinstalling `tensorboard`), so `pip install -r requirements.txt` is not enough.

</details>

The awkward tensorboard situation will be resolved once we remove our dependency on `tensorflow==1.5.0` as part of #3046. (That should happen sometime this year because of the urgency of #3227.)

----

> @joshuacwnewton maybe you have another clue/workaround?

For updating a single package like this, you can instead run `pip install --upgrade ivadomed` and it will leave the rest of your installation alone. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
Closing, as `pip install --upgrade` addresses this for now, and #3046 will address this in the long-term.
