### ISSUE TITLE
-display-warp: TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3336]
Version: b5da17a8858507992513061c46d8eb0d7a7b42f3

<details><summary>Terminal output</summary>

```console
julien-macbook:~/sct_testing_data/t2 $ sct_image -i warp_template2anat.nii.gz -display-warp

--
Spinal Cord Toolbox (git-master-b5da17a8858507992513061c46d8eb0d7a7b42f3)

sct_image -i warp_template2anat.nii.gz -display-warp
--

Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_image.py", line 563, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_image.py", line 233, in main
    visualize_warp(im_warp=im_in, im_grid=None, step=3, rm_tmp=True)
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_image.py", line 520, in visualize_warp
    fname_warp = im_warp.absolutepath()
TypeError: 'str' object is not callable
```

</details>

**Comment by joshuacwnewton** [comment]
Ah. This was a typo on my part, introduced in #3208.

```diff
- im_warp.absolutepath()
+ im_warp.absolutepath
```

This functionality of `sct_image` is not covered by tests, so it wasn't caught.
