### ISSUE TITLE
sct_dmri_separate_b0_and_dwi does not work with parameter -m

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#334]
data used : /Volumes/folder_shared/sct_issues/20150313_allan

command: sct_dmri_separate_b0_and_dwi -i dmrir.nii.gz -b bvecs.txt -m bvals.txt

Return: 

Get dimensions data...
.. 128 x 128 x 12 x 30

Identify b=0 and DWI images...
Traceback (most recent call last):
  File "/Users/tamag/spinalcordtoolbox/bin/sct_dmri_separate_b0_and_dwi", line 301, in <module>
    main()
  File "/Users/tamag/spinalcordtoolbox/bin/sct_dmri_separate_b0_and_dwi", line 131, in main
    index_b0, index_dwi, nb_b0, nb_dwi = identify_b0(fname_bvecs, fname_bvals, param.bval_min, verbose)
  File "/Users/tamag/spinalcordtoolbox/bin/sct_dmri_separate_b0_and_dwi", line 232, in identify_b0
    with open(fname_bvals) as f:
IOError: [Errno 2] No such file or directory: 'bvals.txt'

**Comment by jcohenadad** [comment]
use parser
