### ISSUE TITLE
awk: cannot open /home/neuropoly/.bash_profile (No such file or directory)

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#338]
Error when installing on linux (see below). When running it the 2nd time, it works!

~~~~
=============================
SPINAL CORD TOOLBOX INSTALLER
Modified: 2015-04-17
=============================
Checking if administrator rights are needed for installation...
  No sudo needed for adding elements.

Check if spinalcordtoolbox is already installed (if so, delete it)...
Create folder: ../../Desktop/spinalcordtoolbox ...
>> mkdir ../../Desktop/spinalcordtoolbox
mkdir ../../Desktop/spinalcordtoolbox
Fetch version of the Spinal Cord Toolbox...
  Version: 2.0
Checking for connection and SCT version online...
          
Copy Spinal Cord Toolbox on your computer...
>> cp -r spinalcordtoolbox/* ../../Desktop/spinalcordtoolbox
cp -r spinalcordtoolbox/* ../../Desktop/spinalcordtoolbox

Edit .bashrc...
  Deleting previous SCT entries in .bashrc
>> awk '!/SCT_DIR|SPINALCORDTOOLBOX|ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS/' ~/.bashrc > .bashrc_temp && > ~/.bashrc && cat .bashrc_temp >> ~/.bashrc && rm .bashrc_temp
awk '!/SCT_DIR|SPINALCORDTOOLBOX|ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS/' ~/.bashrc > .bashrc_temp && > ~/.bashrc && cat .bashrc_temp >> ~/.bashrc && rm .bashrc_temp
  Deleting previous SCT entries in .bash_profile
>> awk '!/SCT_DIR|SPINALCORDTOOLBOX|ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS/' ~/.bash_profile > .bash_profile_temp && > ~/.bash_profile && cat .bash_profile_temp >> ~/.bash_profile && rm .bash_profile_temp
awk '!/SCT_DIR|SPINALCORDTOOLBOX|ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS/' ~/.bash_profile > .bash_profile_temp && > ~/.bash_profile && cat .bash_profile_temp >> ~/.bash_profile && rm .bash_profile_temp
awk: cannot open /home/neuropoly/.bash_profile (No such file or directory)
Traceback (most recent call last):
  File "./installer.py", line 881, in <module>
    Installer()
  File "./installer.py", line 696, in __init__
    status, output = runProcess(cmd)
TypeError: 'NoneType' object is not iterable
neuropoly@ferguson:~/Downloads/spinalcordtoolbox_v2.0_linux$ ./installer.py -p ../../Desktop
~~~~

**Comment by jcohenadad** [comment]
fixed in e793276dbc645adcc0b4e933015c9f3ce13b2b75
