### ISSUE TITLE
map method crashes when using label "all cord"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#353]
data: sct_example_data/dmri/

syntax:
~~~~
sct_extract_metric -i dti_FA.nii.gz -f label/atlas/ -l sc -m map
~~~~

error:
~~~~
Extract metric within labels...
  Number of non-null voxels: 1074
Estimation maximum likelihood within clustered labels...
  Number of clusters: 2
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_extract_metric", line 937, in <module>
    main()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_extract_metric", line 317, in main
    metric_mean, metric_std = extract_metric_within_tract(data, labels, method, verbose, ml_clusters_array, adv_param)  # mean and std are lists
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_extract_metric", line 757, in extract_metric_within_tract
    x_cluster[:, i_cluster] = x[:, index_tracts_in_cluster].sum(axis=1)
IndexError: index 2 is out of bounds for axis 1 with size 2
~~~~

**Comment by jcohenadad** [comment]
fixed-- see #656
