### ISSUE TITLE
sct_labels_utils: create labels giving the labels coordinates doesn't work

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#355]
sct_label_utils -i t2crop.nii.gz -t create -x 20,20,74,2:21,17,19,5 -o t2crop_landmarks.nii.gz

Returns
-----------
`Check file existence...`
  `OK: t2crop.nii.gz`
  `OK: t2crop.nii.gz`
`Label #0: 26,177,170 --> 2`
`Traceback (most recent call last):`
 ` File "/Users/slevy_local/spinalcordtoolbox/bin/sct_label_utils", line 522, in <module>
    processor.process(process_type)`
 ` File "/Users/slevy_local/spinalcordtoolbox/bin/sct_label_utils", line 70, in process
   self.output_image = self.create_label()`
 ` File "/Users/slevy_local/spinalcordtoolbox/bin/sct_label_utils", line 354, in create_label
    image_output.data[coord.x, coord.y, coord.z] = int(coord.value)`
`IndexError: index 177 is out of bounds for axis 1 with size 48
`

N.B.: Coordinates were checked, they are correct.

**Comment by slevyrosetti** [comment]
Actually, I had the same bug with other datasets so it doesn't seem to depend on the datasets.
