### ISSUE TITLE
[BUG] IMPOSSIBLE TO SCRIPT WITH MATLAB

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#405]
import matplotlib induce an error in matlab. For instance when using sct_apply_transfo:

`````
File "/Users/taduv_admin/codes/spinalcordtoolbox/bin/sct_apply_transfo", line 24, in <module>
from sct_crop_image import ImageCropper
File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_crop_image.py", line 19, in <module>
import matplotlib.pyplot as plt
File "/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 27, in <module>
import matplotlib.colorbar
File "/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
import matplotlib.collections as collections
File "/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
import matplotlib.backend_bases as backend_bases
File "/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 56, in <module>
import matplotlib.textpath as textpath
File "/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/textpath.py", line 19, in <module>
import matplotlib.font_manager as font_manager
File "/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 57, in <module>
from matplotlib import ft2font
ImportError: dlopen(/Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/ft2font.so, 2): Library not loaded: @loader_path/../../../libfreetype.6.dylib
Referenced from: /Users/taduv_admin/miniconda/lib/python2.7/site-packages/matplotlib/ft2font.so
Reason: Incompatible library version: ft2font.so requires version 16.0.0 or later, but libfreetype.6.dylib provides version 10.0.0[0m
`````

This is because there is a conflict with libfreetype.6.dylib that is also present in Matlab!!
In order to solve this error I did:
`````
sudo mv /Users/taduv/codes/miniconda/lib/libfreetype.6.dylib /Applications/MATLAB_R2014a.app/bin/maci64/libfreetype.6.dylib
`````

**Comment by tanguyduval** [comment]
One solution: import matplotlib only if verbose==1

**Comment by ComtoisOlivier** [comment]
I changed the place at which matlplotlib is imported (it's now imported only when needed), does the problem still persist?

**Comment by tanguyduval** [comment]
Thanks! I'll try to reprduce the bug

**Comment by jcohenadad** [comment]
can we close it?

**Comment by tanguyduval** [comment]
Well it is tricky, we have other conflicts (e.g. isct_warpmovie_generator.py). Can we assume people won't script with MATLAB?
Otherwise it will need testings for all scripts..

**Comment by jcohenadad** [comment]
well, I would strongly encourage people to script with Matlab so that we have better feedback on our end. What's the problem with "isct_warpmovie_generator.py"?

**Comment by tanguyduval** [comment]
In MATLAB: 
```` 
>> unix('python')
>>>> scipy.misc import toimage
 ````
error:
````name 'toimage' is not defined````

However same python in Matlab and terminal:
````
>>unix('which python')
/Users/taduv_admin/miniconda/bin/python
`````

module is in folder:
`````
<module 'scipy.misc' from '/Users/taduv_admin/miniconda/lib/python2.7/site-packages/scipy/misc/__init__.pyc'>
````

**Comment by jcohenadad** [comment]
what if you start Matlab from the terminal that has miniconda's environment variables properly set?

**Comment by tanguyduval** [comment]
Same problem

**Comment by tanguyduval** [comment]
the problem is that libfreetype.6.dylib is also a MATLAB library in the folder:
`/Applications/MATLAB_R2014a.app/bin/maci64/libfreetype.6.dylib`

One trick is to overwrite the Matlab library with the newer version..... but might be problematic..

**Comment by tanguyduval** [comment]
I still have issues when scripting with MATLAB.
SCIPY calls Matlab libraries...
`````
sct_apply_transfo -i AxCaliberT0000.nii.gz -d fsems_96_AxCaliber_d8D3002.nii.gz -w warp_src2dest.nii.gz 

--
Spinal Cord Toolbox (master/63b0d9545013587cf6985879c92dfe45c6ad3f75)
Running /Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_apply_transfo.py -i AxCaliberT0000.nii.gz -d fsems_96_AxCaliber_d8D3002.nii.gz -w warp_src2dest.nii.gz
Traceback (most recent call last):
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 24, in <module>
    from sct_crop_image import ImageCropper
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_crop_image.py", line 23, in <module>
    from msct_image import Image
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/msct_image.py", line 19, in <module>
    from scipy.ndimage import map_coordinates
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/ndimage/__init__.py", line 161, in <module>
    from .filters import *
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/misc/__init__.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/__init__.py", line 636, in <module>
    from ._ufuncs import *
ImportError: dlopen(/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/_ufuncs.so, 2): Symbol not found: __gfortran_stop_numeric_f08
  Referenced from: /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/_ufuncs.so
  Expected in: /Applications/MATLAB_R2014a.app/sys/os/maci64/libgfortran.3.dylib
 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/_ufuncs.so
ERROR!!!!!!!!!!
`````
data in : ````/Volumes/folder_shared/sct_issues/20170224_issue640````

I use MATLAB 2014a
In order to bypass this error I temporarily renamed ````/Applications/MATLAB_R2014a.app/sys/os/maci64/libgfortran.3.dylib````

**Comment by peristeri** [comment]
This should be fix with the fix #1266 . Will need to reinstall SCT to test it.
@tanguyduval can you confirm this?

**Comment by tanguyduval** [comment]
Bug persists. Here what I've done:
1. Close Matlab
2. pull the new SCT version.
2. I changed to sct_dir and I launched the command sct_install.
3. source .bachrc
4. launch Matlab
5. bug:
````
Traceback (most recent call last):
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_dmri_create_noisemask.py", line 17, in <module>
    from dipy.denoise.noise_estimate import piesno
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/dipy/denoise/noise_estimate.py", line 5, in <module>
    from scipy.special import gammainccinv
  File "/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: dlopen(/Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/_ufuncs.so, 2): Symbol not found: __gfortran_stop_numeric_f08
  Referenced from: /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/_ufuncs.so
  Expected in: /Applications/MATLAB_R2014a.app/sys/os/maci64/libgfortran.3.dylib
 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/special/_ufuncs.so
````

**Comment by tanguyduval** [comment]
Installation log:
````
./install_sct 

Welcome to the SCT installer!

SCT version ......... dev
Installation type ... git
Operating system .... osx
sudo mode ........... 0

SCT will be installed here: [/Users/taduv_admin/codes/spinalcordtoolbox]
Do you agree? yes/no: yes
mkdir: /Users/taduv_admin/codes/spinalcordtoolbox: File exists

Removing sct and isct softlink from /Users/taduv_admin/codes/spinalcordtoolbox/bin

Skipping copy of source files (source and destination folders are the same)

Create launchers for Python scripts
>> mkdir -p /Users/taduv_admin/codes/spinalcordtoolbox/bin
>> cd /Users/taduv_admin/codes/spinalcordtoolbox/install
>> ./update_bin.sh
#!/bin/bash
$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/sct_launcher $(basename $0).py $@
yes isct_check_detection
yes isct_convert_binary_to_trilinear
yes isct_minc2volume-viewer
yes isct_test_ants
yes isct_test_function
yes isct_warpmovie_generator
yes msct_image
yes msct_multiatlas_seg
yes sct_apply_transfo
yes sct_average_data_within_mask
no sct_change_image_type
yes sct_check_atlas_integrity
yes sct_check_dependencies
yes sct_compute_ernst_angle
yes sct_compute_hausdorff_distance
yes sct_compute_mscc
yes sct_compute_mtr
yes sct_compute_snr
yes sct_concat_transfo
yes sct_convert
yes sct_create_mask
yes sct_crop_image
no sct_denoising_onlm
yes sct_dice_coefficient
yes sct_dmri_compute_dti
yes sct_dmri_concat_bvals
yes sct_dmri_concat_bvecs
yes sct_dmri_create_noisemask
no sct_dmri_eddy_correct
yes sct_dmri_get_bvalue
yes sct_dmri_moco
yes sct_dmri_separate_b0_and_dwi
yes sct_dmri_transpose_bvecs
yes sct_download_data
yes sct_extract_metric
yes sct_flatten_sagittal
yes sct_fmri_compute_tsnr
yes sct_fmri_moco
yes sct_get_centerline
yes sct_image
no sct_invert_image
yes sct_label_utils
yes sct_label_vertebrae
yes sct_make_ground_truth
yes sct_maths
yes sct_merge_images
yes sct_process_segmentation
yes sct_propseg
yes sct_qc
yes sct_register_graymatter
yes sct_register_multimodal
yes sct_register_to_template
yes sct_resample
yes sct_segment_graymatter
yes sct_smooth_spinalcord
yes sct_straighten_spinalcord
yes sct_testing
yes sct_viewer
yes sct_warp_template

Installing conda...
>> rm -rf /Users/taduv_admin/codes/spinalcordtoolbox/python
>> mkdir /Users/taduv_admin/codes/spinalcordtoolbox/python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.3M  100 20.3M    0     0  30.4M      0 --:--:-- --:--:-- --:--:-- 30.3M
exit status is 0
>> bash /var/folders/z2/34pbcyv17cl8q0dgqnnw54k80000gq/T/TMP_DIR.hPLphj4v/miniconda.sh -p /Users/taduv_admin/codes/spinalcordtoolbox/python -b -f
PREFIX=/Users/taduv_admin/codes/spinalcordtoolbox/python
installing: python-2.7.12-1 ...
installing: conda-env-2.5.2-py27_0 ...
installing: openssl-1.0.2h-1 ...
installing: pycosat-0.6.1-py27_1 ...
installing: pyyaml-3.11-py27_4 ...
installing: readline-6.2-2 ...
installing: requests-2.10.0-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.1.11-py27_0 ...
installing: pycrypto-2.6.1-py27_4 ...
installing: pip-8.1.2-py27_0 ...
installing: wheel-0.29.0-py27_0 ...
installing: setuptools-23.0.0-py27_0 ...
Python 2.7.12 :: Continuum Analytics, Inc.
creating default environment...
using -f (force) option
installation finished.
Conda installation successful
>> . /Users/taduv_admin/codes/spinalcordtoolbox/python/bin/activate /Users/taduv_admin/codes/spinalcordtoolbox/python

Installing Python dependencies...
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/taduv_admin/codes/spinalcordtoolbox/python:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    jbig-2.1                   |                0          31 KB
    jpeg-9b                    |                0         240 KB
    mkl-11.3.3                 |                0       101.4 MB
    xz-5.2.2                   |                1         212 KB
    libpng-1.6.27              |                0         240 KB
    libtiff-4.0.6              |                3         756 KB
    decorator-4.0.11           |           py27_0          13 KB
    enum34-1.1.6               |           py27_0          54 KB
    freetype-2.5.5             |                2         738 KB
    idna-2.5                   |           py27_0         121 KB
    ipaddress-1.0.18           |           py27_0          30 KB
    numpy-1.11.2               |           py27_0         3.1 MB
    olefile-0.44               |           py27_0          51 KB
    pyasn1-0.2.3               |           py27_0          75 KB
    pycparser-2.17             |           py27_0         153 KB
    pyparsing-2.1.4            |           py27_0          70 KB
    pytz-2017.2                |           py27_0         203 KB
    requests-2.12.4            |           py27_0         752 KB
    sip-4.18                   |           py27_0         245 KB
    six-1.10.0                 |           py27_0          16 KB
    xlrd-0.9.4                 |           py27_0         179 KB
    xlwt-1.0.0                 |           py27_0         152 KB
    cffi-1.10.0                |           py27_0         195 KB
    cycler-0.10.0              |           py27_0          11 KB
    networkx-1.11              |           py27_0         1.1 MB
    pillow-4.1.1               |           py27_0         490 KB
    pip-9.0.1                  |           py27_1         1.6 MB
    python-dateutil-2.6.0      |           py27_0         232 KB
    qt-4.8.7                   |                4        37.1 MB
    scipy-0.18.1               |      np111py27_0        13.4 MB
    xlutils-1.7.1              |           py27_0          65 KB
    cryptography-1.6           |           py27_0         461 KB
    pandas-0.18.1              |      np111py27_0         7.1 MB
    pyqt-4.11.4                |           py27_4         4.0 MB
    scikit-learn-0.17.1        |      np111py27_2         3.7 MB
    matplotlib-1.5.1           |      np111py27_0         6.2 MB
    pyopenssl-16.2.0           |           py27_0          68 KB
    conda-4.3.21               |           py27_0         493 KB
    scikit-image-0.12.3        |      np111py27_1        18.0 MB
    ------------------------------------------------------------
                                           Total:       202.9 MB

The following NEW packages will be INSTALLED:

    cffi:            1.10.0-py27_0     
    cryptography:    1.6-py27_0        
    cycler:          0.10.0-py27_0     
    decorator:       4.0.11-py27_0     
    enum34:          1.1.6-py27_0      
    freetype:        2.5.5-2           
    idna:            2.5-py27_0        
    ipaddress:       1.0.18-py27_0     
    jbig:            2.1-0             
    jpeg:            9b-0              
    libpng:          1.6.27-0          
    libtiff:         4.0.6-3           
    matplotlib:      1.5.1-np111py27_0 
    mkl:             11.3.3-0          
    networkx:        1.11-py27_0       
    numpy:           1.11.2-py27_0     
    olefile:         0.44-py27_0       
    pandas:          0.18.1-np111py27_0
    pillow:          4.1.1-py27_0      
    pyasn1:          0.2.3-py27_0      
    pycparser:       2.17-py27_0       
    pyopenssl:       16.2.0-py27_0     
    pyparsing:       2.1.4-py27_0      
    pyqt:            4.11.4-py27_4     
    python-dateutil: 2.6.0-py27_0      
    pytz:            2017.2-py27_0     
    qt:              4.8.7-4           
    scikit-image:    0.12.3-np111py27_1
    scikit-learn:    0.17.1-np111py27_2
    scipy:           0.18.1-np111py27_0
    sip:             4.18-py27_0       
    six:             1.10.0-py27_0     
    xlrd:            0.9.4-py27_0      
    xlutils:         1.7.1-py27_0      
    xlwt:            1.0.0-py27_0      
    xz:              5.2.2-1           

The following packages will be UPDATED:

    conda:           4.1.11-py27_0      --> 4.3.21-py27_0
    conda-env:       2.5.2-py27_0       --> 2.6.0-0      
    pip:             8.1.2-py27_0       --> 9.0.1-py27_1 
    requests:        2.10.0-py27_0      --> 2.12.4-py27_0

Fetching packages ...
conda-env-2.6. 100% |##############################################################################################################| Time: 0:00:00 634.00 kB/s
jbig-2.1-0.tar 100% |##############################################################################################################| Time: 0:00:00  22.04 MB/s
jpeg-9b-0.tar. 100% |##############################################################################################################| Time: 0:00:00  30.85 MB/s
mkl-11.3.3-0.t 100% |##############################################################################################################| Time: 0:00:01  63.04 MB/s
xz-5.2.2-1.tar 100% |##############################################################################################################| Time: 0:00:00  25.17 MB/s
libpng-1.6.27- 100% |##############################################################################################################| Time: 0:00:00  27.24 MB/s
libtiff-4.0.6- 100% |##############################################################################################################| Time: 0:00:00  33.65 MB/s
decorator-4.0. 100% |##############################################################################################################| Time: 0:00:00  14.87 MB/s
enum34-1.1.6-p 100% |##############################################################################################################| Time: 0:00:00  21.68 MB/s
freetype-2.5.5 100% |##############################################################################################################| Time: 0:00:00  32.73 MB/s
idna-2.5-py27_ 100% |##############################################################################################################| Time: 0:00:00  23.79 MB/s
ipaddress-1.0. 100% |##############################################################################################################| Time: 0:00:00  26.48 MB/s
numpy-1.11.2-p 100% |##############################################################################################################| Time: 0:00:00  26.37 MB/s
olefile-0.44-p 100% |##############################################################################################################| Time: 0:00:00  22.25 MB/s
pyasn1-0.2.3-p 100% |##############################################################################################################| Time: 0:00:00   4.30 MB/s
pycparser-2.17 100% |##############################################################################################################| Time: 0:00:00  23.34 MB/s
pyparsing-2.1. 100% |##############################################################################################################| Time: 0:00:00  30.66 MB/s
pytz-2017.2-py 100% |##############################################################################################################| Time: 0:00:00  29.08 MB/s
requests-2.12. 100% |##############################################################################################################| Time: 0:00:00  32.89 MB/s
sip-4.18-py27_ 100% |##############################################################################################################| Time: 0:00:00  22.54 MB/s
six-1.10.0-py2 100% |##############################################################################################################| Time: 0:00:00  15.68 MB/s
xlrd-0.9.4-py2 100% |##############################################################################################################| Time: 0:00:00  21.03 MB/s
xlwt-1.0.0-py2 100% |##############################################################################################################| Time: 0:00:00  19.93 MB/s
cffi-1.10.0-py 100% |##############################################################################################################| Time: 0:00:00  24.00 MB/s
cycler-0.10.0- 100% |##############################################################################################################| Time: 0:00:00  13.17 MB/s
networkx-1.11- 100% |##############################################################################################################| Time: 0:00:00  37.56 MB/s
pillow-4.1.1-p 100% |##############################################################################################################| Time: 0:00:00  28.43 MB/s
pip-9.0.1-py27 100% |##############################################################################################################| Time: 0:00:00  44.04 MB/s
python-dateuti 100% |##############################################################################################################| Time: 0:00:00  27.37 MB/s
qt-4.8.7-4.tar 100% |##############################################################################################################| Time: 0:00:00  69.46 MB/s
scipy-0.18.1-n 100% |##############################################################################################################| Time: 0:00:00  41.03 MB/s
xlutils-1.7.1- 100% |##############################################################################################################| Time: 0:00:00  29.27 MB/s
cryptography-1 100% |##############################################################################################################| Time: 0:00:00  28.86 MB/s
pandas-0.18.1- 100% |##############################################################################################################| Time: 0:00:00  59.92 MB/s
pyqt-4.11.4-py 100% |##############################################################################################################| Time: 0:00:00  56.01 MB/s
scikit-learn-0 100% |##############################################################################################################| Time: 0:00:00  54.20 MB/s
matplotlib-1.5 100% |##############################################################################################################| Time: 0:00:00  60.33 MB/s
pyopenssl-16.2 100% |##############################################################################################################| Time: 0:00:00  26.39 MB/s
conda-4.3.21-p 100% |##############################################################################################################| Time: 0:00:00  30.29 MB/s
scikit-image-0 100% |##############################################################################################################| Time: 0:00:00  20.64 MB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
Collecting nipy==0.4.0 (from -r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 1))
  Using cached nipy-0.4.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting nibabel==2.1.0 (from -r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 2))
Collecting dipy==0.11.0 (from -r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 3))
  Using cached dipy-0.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting tqdm==4.11.2 (from -r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 4))
  Downloading tqdm-4.11.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 7.5MB/s 
Collecting sympy>=0.7.0 (from nipy==0.4.0->-r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 1))
Collecting scipy>=0.9 (from dipy==0.11.0->-r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 3))
  Downloading scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.2MB)
    100% |████████████████████████████████| 16.2MB 46kB/s 
Collecting mpmath>=0.19 (from sympy>=0.7.0->nipy==0.4.0->-r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 1))
Collecting numpy>=1.8.2 (from scipy>=0.9->dipy==0.11.0->-r /Users/taduv_admin/codes/spinalcordtoolbox/install/requirements/requirementsPip.txt (line 3))
  Downloading numpy-1.12.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 163kB/s 
Installing collected packages: mpmath, sympy, nibabel, nipy, numpy, scipy, dipy, tqdm
Successfully installed dipy-0.11.0 mpmath-0.19 nibabel-2.1.0 nipy-0.4.0 numpy-1.12.1 scipy-0.19.0 sympy-1.0 tqdm-4.11.2
Processing /Users/taduv_admin/codes/spinalcordtoolbox
Requirement already satisfied: nipy==0.4.0 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied: nibabel==2.1.0 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied: dipy==0.11.0 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied: tqdm==4.11.2 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from spinalcordtoolbox===dev)
Requirement already satisfied: sympy>=0.7.0 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from nipy==0.4.0->spinalcordtoolbox===dev)
Requirement already satisfied: scipy>=0.9 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from dipy==0.11.0->spinalcordtoolbox===dev)
Requirement already satisfied: mpmath>=0.19 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from sympy>=0.7.0->nipy==0.4.0->spinalcordtoolbox===dev)
Requirement already satisfied: numpy>=1.8.2 in /Users/taduv_admin/codes/spinalcordtoolbox/python/lib/python2.7/site-packages (from scipy>=0.9->dipy==0.11.0->spinalcordtoolbox===dev)
Installing collected packages: spinalcordtoolbox
  Running setup.py install for spinalcordtoolbox ... done
Successfully installed spinalcordtoolbox-dev

Installing binaries...
>> . /Users/taduv_admin/codes/spinalcordtoolbox/python/bin/activate /Users/taduv_admin/codes/spinalcordtoolbox/python
>> python ../scripts/sct_download_data.py -d binaries_osx -o /Users/taduv_admin/codes/spinalcordtoolbox/bin
Check folder existence...

Downloading 20170413_sct_binaries_osx.tar.gz...
Status: 100%|############################################################################################################| 64.0M/64.0M [00:03<00:00, 20.2MB/s]

Download complete

Check if folder already exists...

Unzip data to: /Users/taduv_admin/codes/spinalcordtoolbox/bin/

Remove temporary file...
Done!

All requirements installed!
>> . /Users/taduv_admin/codes/spinalcordtoolbox/python/bin/activate /Users/taduv_admin/codes/spinalcordtoolbox/python

Installing data...
>> rm -rf /Users/taduv_admin/codes/spinalcordtoolbox/data
>> mkdir -p /Users/taduv_admin/codes/spinalcordtoolbox/data
>> cd /Users/taduv_admin/codes/spinalcordtoolbox/data
>> python ../scripts/sct_download_data.py -d PAM50

Downloading 20170101_PAM50.zip...
Status: 100%|############################################################################################################| 78.8M/78.8M [00:04<00:00, 19.0MB/s]

Download complete

Check if folder already exists...

Unzip data to: /Users/taduv_admin/codes/spinalcordtoolbox/data/

Remove temporary file...
Done!

>> python ../scripts/sct_download_data.py -d gm_model

Downloading 20160922_gm_model.zip...
Status: 100%|############################################################################################################| 10.3M/10.3M [00:00<00:00, 18.9MB/s]

Download complete

Check if folder already exists...

Unzip data to: /Users/taduv_admin/codes/spinalcordtoolbox/data/

Remove temporary file...
Done!

>> python ../scripts/sct_download_data.py -d optic_models

Downloading 20170413_optic_models.zip...
Status: 100%|############################################################################################################| 17.7K/17.7K [00:00<00:00, 55.7MB/s]

Download complete

Check if folder already exists...

Unzip data to: /Users/taduv_admin/codes/spinalcordtoolbox/data/

Remove temporary file...
Done!


Do you want to add the sct_* scripts to your PATH environment? yes/no: yes



Run sct_check_dependencies...

--
Spinal Cord Toolbox (master/fa65c88bc61fddf6f1df62a0e2616e96739a9df4)
Running /Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_check_dependencies.py

OS: osx (Darwin-14.5.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by SCT: 4
RAM: Primary memory available: 16.00 gigabytes
SCT path: /Users/taduv_admin/codes/spinalcordtoolbox
Installation type: git
  commit: fa65c88bc61fddf6f1df62a0e2616e96739a9df4
  branch: master
Check Python path...................................[OK]
Check if data are installed.........................[OK]
Check if xlwt (1.0.0) is installed..................[OK]
Check if xlutils (1.7.1) is installed...............[OK]
Check if cryptography (1.6) is installed............[OK]
Check if scikit-learn (0.17.1) is installed.........[OK]
Check if scikit-image (0.12.3) is installed.........[OK]
Check if pyqt (4.11.4) is installed.................[OK]
Check if matplotlib (1.5.1) is installed............[OK]
Check if pip (9.0.1) is installed...................[OK]
Check if requests (2.12.4) is installed.............[OK]
Check if xlrd (0.9.4) is installed..................[OK]
Check if pandas (0.18.1) is installed...............[OK]
Check if dipy (0.11.0) is installed.................[OK]
Check if tqdm (4.11.2) is installed.................[OK]
Check if nibabel (2.1.0) is installed...............[OK]
Check if nipy (0.4.0) is installed..................[OK]
Check if numpy is installed.........................[OK]
Check if scipy is installed.........................[OK]
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

INSTALLATION DONE!

Open a new Terminal window to load environment variables, or run:
 source /Users/taduv_admin/.bashrc
````

**Comment by tanguyduval** [comment]
temporary solution. In matlab command window:
`setenv('DYLD_LIBRARY_PATH', '');`

**Comment by peristeri** [comment]
After investigating the problem with Tanguy, we saw that the environment variable is reset by matlab. It is an environment variable specific to Apple and configuration specific to Tanguy's environment. For the time being, this is an edge case and won't continue investing time unless it becomes a recurring problem.

**Comment by tanguyduval** [comment]
This bug affects all mac and all Matlab versions. Unfortunatly, mac users are not a minority in the community... Currently they cannot batch the Spinal Cord toolbox with Matlab. I suppose they do it with shell scripts. Shall we keep priority low?

**Comment by jcohenadad** [comment]
my understanding is that the problem can be solved by typing ```setenv('DYLD_LIBRARY_PATH', '');```. Is that correct?
If so, then I would propose to explicitly mention this fix in the documentation for Matlab+Mac users.
