### ISSUE TITLE
when using flag -f, if function does not exist, do not test all functions

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#473]

**Comment by peristeri** [comment]
Error is thrown if the function does not exists.

**Comment by jcohenadad** [comment]
does not seem to be fixed on latest master version:
~~~
sct_testing -f fdfd

--
Spinal Cord Toolbox (master/7e99a37b872d07ee366c5ce6dba70376dcd42c06)
Running /Users/julien/code/sct/scripts/sct_testing.py -f fdfd

Path to testing data: /Users/julien/sct_testing_data/

Create temporary folder...
Checking test_sct_apply_transfo.....................^CTraceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 318, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 114, in main
    status.append(test_function(f))
  File "/Users/julien/code/sct/scripts/sct_testing.py", line 263, in test_function
    result_test = script_tested.test(param.path_data)
  File "/Users/julien/code/sct/testing/test_sct_apply_transfo.py", line 35, in test
    s, o = commands.getstatusoutput(cmd)
  File "/Users/julien/code/sct/python/lib/python2.7/commands.py", line 60, in getstatusoutput
    text = pipe.read()
KeyboardInterrupt
~~~
