### ISSUE TITLE
batch_processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#548]
~~~
Building the appearance model...
The shape of the dictionary used for the PCA is (5625,367)

Loading a reduced common space (using a PCA) ...

 ---> sum of eigenvalues : 25840774.735
kept eigenvalues (PCA space dimension)  : 47


-------> IN PCA : 

-> kept_modes:[[  3.49398364e-17   1.52343914e-16  -7.58488521e-17 ...,   3.80134817e-16
   -1.89151114e-16   5.03210500e-16]
 [  8.90089761e-17  -1.19838181e-17  -1.66316223e-17 ...,   6.82225569e-16
   -5.54560867e-17   6.59016387e-16]
 [ -1.93464814e-16  -5.61873130e-16   2.97913681e-16 ...,   1.44167405e-15
   -6.91923514e-17   1.34597836e-15]
 ..., 
 [  4.82975213e-41  -1.96928854e-41   7.01142309e-42 ...,  -1.99192770e-40
    7.88297211e-41   4.54343078e-40]
 [  2.30677769e-42   1.98578340e-42  -7.86602226e-43 ...,  -2.10894907e-41
   -1.24018683e-41   1.22609524e-41]
 [ -3.60789799e-42   6.98905602e-42  -7.80287706e-43 ...,   3.91838402e-41
   -3.27249882e-42  -1.60868436e-41]]

-> kept_eigenval:47

--> OK !
WARNING: label/template/MNI-Poly-AMU_level.nii.gz is not a file ...
mkdir tmp_mt1_151001191621

Doing target pre-processing ...
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_segment_graymatter", line 498, in <module>
    gmsegfull = FullGmSegmentation(input_target_fname, input_sc_seg_fname, input_t2_data, input_level_fname, ref_gm_seg=input_ref_gm_seg, compute_ratio=compute_ratio, param=param)
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_segment_graymatter", line 123, in __init__
    self.segmentation_pipeline()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_segment_graymatter", line 143, in segmentation_pipeline
    self.preprocessed = Preprocessing(self.target_fname, self.sc_seg_fname, tmp_dir=self.tmp_dir, t2_data=self.t2_data, level_fname=self.level_fname, denoising=self.param.target_denoising)
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_segment_graymatter", line 33, in __init__
    level_fname_nii = check_file_to_niigz(level_fname)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_gmseg_utils.py", line 421, in check_file_to_niigz
    if os.path.isfile(file_name):
  File "/Users/julien/miniconda/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, bool found

ERROR: The file label/template/MNI-Poly-AMU_WM.nii.gz does not exist. Exit program.

/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 197

Parse list of transformations...
  Transfo #0: warp_template2mt.nii.gz
  Transfo #1: warp_MNI-Poly-AMU_WM2mt1_wmseg.nii.gz

Check file existence...
  OK: mt1.nii.gz
  OK: warp_template2mt.nii.gz

ERROR: The file warp_MNI-Poly-AMU_WM2mt1_wmseg.nii.gz does not exist. Exit program.

/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 197

ERROR: The file warp_template2mt1_corrected_wm.nii.gz does not exist. Exit program.

/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 197

check existence of input files...
  OK: mtr.nii.gz

Warning: The directory /Users/julien/data/temp/sct_example_data/mt/label/atlas does not exist.


ERROR: The file /Users/julien/data/temp/sct_example_data/mt/label/atlas/info_label.txt does not exist. Exit program.

/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 197
~~~

**Comment by SaraDupont** [comment]
Was because of the label folder name (I changed it so that it won't be over written by the second regiater_multimodal/warp_template to be able to compare results before/after the correction of the registration)

**Comment by jcohenadad** [comment]
for the batch processing i would overwrite-- otherwise too confusing for the users.

if we want to compare (e.g. for debugging), it's easy to manually change the name

**Comment by SaraDupont** [comment]
OK !

**Comment by SaraDupont** [comment]
Done! Currently testing it.

**Comment by SaraDupont** [comment]
Segmentation of T1 is not perfect but the rest is good ! 
![2015-10-02-t1_seg](https://cloud.githubusercontent.com/assets/5857909/10251386/51cc0b92-68fe-11e5-86b7-1b5b3a59b2e4.png)

**Comment by jcohenadad** [comment]
segmentation issue is already known.
