### ISSUE TITLE
issue with -method auto -o test.nii.gz

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#551]
data:
~~~
sct_example_data/dmri
~~~

syntax:
~~~
sct_get_centerline -i dwi_moco_mean.nii.gz -method auto -t t1 -o test.nii.gz
~~~

error:
~~~
WARNING : Option string does not exist and will have no effect on the execution of the script
Type -h to see supported options
Execution of the SCAD algorithm in /Users/julien/data/temp/sct_example_data/dmri
mkdir scad_output_151002121948/
sct_convert -i dwi_moco_mean.nii.gz -o /Users/julien/data/temp/sct_example_data/dmri/scad_output_151002121948/raw.nii.gz
mkdir tmp.151002121948/
sct_convert -i dwi_moco_mean.nii.gz -o tmp.151002121948/raw.nii
isct_vesselness -i raw.nii -t t1 -radius 4
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_get_centerline", line 1098, in <module>
    scad.execute()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_get_centerline", line 951, in execute
    conv.convert(path_tmp+img.file_name+img.ext, self.output_filename)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_convert.py", line 61, in convert
    printv('sct_convert -i '+fname_in+' -o '+fname_out, verbose, 'code')
TypeError: cannot concatenate 'str' and 'NoneType' objects
~~~

**Comment by ComtoisOlivier** [comment]
Fixed in 2e658ee1c5e697a1b3bc8e1beae4568684668d17
