### ISSUE TITLE
installation failed on OSX 10.6

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#561]
~~~
./installer.py -p ~/sct

=============================
SPINAL CORD TOOLBOX INSTALLER
Modified: 2015-10-03
=============================

Check which Python distribution is running...
2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:29:08) 
[GCC 4.2.1 (Apple Inc. build 5577)]
.. conda (OK)

Check if pip is installed...
.. OK!

Check if administrator permission is needed for installation...
.. Installation path: /Users/julien/sct
.. no sudo needed for adding elements.


Check if spinalcordtoolbox is already installed (if so, delete it)...

Create folder: /Users/julien/sct ...
mkdir /Users/julien/sct

Fetch version of the Spinal Cord Toolbox...
  Version: 2.1_beta5

Check online if you have the latest version of SCT...
          
Copy Spinal Cord Toolbox on your computer...
cp -r spinalcordtoolbox/* /Users/julien/sct

Edit .bashrc...

Check if .bash_profile exists...
.. .bashrc seems to be called in .bash_profile
>> . ~/.bashrc
. ~/.bashrc

Install dependences... Depending on your internet connection, this may take several minutes.
>> bash requirements.sh
--------------------------
INSTALLER FOR REQUIREMENTS
--------------------------
* CONDA *
Fetching package metadata: ....
Solving package specifications: ..................
Package plan for installation in environment /Users/julien/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |                1         137 KB
    libpng-1.6.17              |                0         184 KB
    freetype-2.5.2             |                2         692 KB
    libtiff-4.0.2              |                1         270 KB
    cython-0.23                |           py27_0         2.3 MB
    decorator-4.0.4            |           py27_0          11 KB
    fastcache-1.0.2            |           py27_0          23 KB
    numpy-1.9.2                |           py27_2         2.9 MB
    pillow-3.0.0               |           py27_0         471 KB
    pyparsing-2.0.3            |           py27_0          63 KB
    pytz-2015.6                |           py27_0         173 KB
    qt-4.8.6                   |                3        39.0 MB
    sip-4.16.5                 |           py27_0         234 KB
    six-1.9.0                  |           py27_0          16 KB
    networkx-1.10              |           py27_0         1.1 MB
    pyqt-4.11.3                |           py27_0         4.0 MB
    python-dateutil-2.4.2      |           py27_0         219 KB
    scipy-0.16.0               |       np19py27_1        12.5 MB
    sympy-0.7.6                |           py27_0         6.2 MB
    matplotlib-1.4.3           |       np19py27_3        40.8 MB
    scikit-image-0.11.3        |       np19py27_0        16.1 MB
    ------------------------------------------------------------
                                           Total:       127.3 MB

The following NEW packages will be INSTALLED:

    cython:          0.23-py27_0      
    decorator:       4.0.4-py27_0     
    fastcache:       1.0.2-py27_0     
    freetype:        2.5.2-2          
    jpeg:            8d-1             
    libpng:          1.6.17-0         
    libtiff:         4.0.2-1          
    matplotlib:      1.4.3-np19py27_3 
    networkx:        1.10-py27_0      
    numpy:           1.9.2-py27_2     
    pillow:          3.0.0-py27_0     
    pyparsing:       2.0.3-py27_0     
    pyqt:            4.11.3-py27_0    
    python-dateutil: 2.4.2-py27_0     
    pytz:            2015.6-py27_0    
    qt:              4.8.6-3          
    scikit-image:    0.11.3-np19py27_0
    scipy:           0.16.0-np19py27_1
    sip:             4.16.5-py27_0    
    six:             1.9.0-py27_0     
    sympy:           0.7.6-py27_0     

Fetching packages ...
jpeg-8d-1.tar. 100% |###############################| Time: 0:00:00   1.74 MB/s
libpng-1.6.17- 100% |###############################| Time: 0:00:00 837.29 kB/s
freetype-2.5.2 100% |###############################| Time: 0:00:00   3.12 MB/s
libtiff-4.0.2- 100% |###############################| Time: 0:00:00   1.79 MB/s
cython-0.23-py 100% |###############################| Time: 0:00:00   3.88 MB/s
decorator-4.0. 100% |###############################| Time: 0:00:00   9.12 MB/s
fastcache-1.0. 100% |###############################| Time: 0:00:00   1.48 MB/s
numpy-1.9.2-py 100% |###############################| Time: 0:00:00   4.14 MB/s
pillow-3.0.0-p 100% |###############################| Time: 0:00:00   1.82 MB/s
pyparsing-2.0. 100% |###############################| Time: 0:00:00 141.90 kB/s
pytz-2015.6-py 100% |###############################| Time: 0:00:00   1.06 MB/s
qt-4.8.6-3.tar 100% |###############################| Time: 0:00:06   6.11 MB/s
sip-4.16.5-py2 100% |###############################| Time: 0:00:00   1.21 MB/s
six-1.9.0-py27 100% |###############################| Time: 0:00:00 294.98 kB/s
networkx-1.10- 100% |###############################| Time: 0:00:00   2.07 MB/s
pyqt-4.11.3-py 100% |###############################| Time: 0:00:00   5.14 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   1.18 MB/s
scipy-0.16.0-n 100% |###############################| Time: 0:00:02   4.75 MB/s
sympy-0.7.6-py 100% |###############################| Time: 0:00:01   4.52 MB/s
matplotlib-1.4 100% |###############################| Time: 0:00:07   5.73 MB/s
scikit-image-0 100% |###############################| Time: 0:00:02   6.41 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
* PIP *
Collecting nibabel==2.0.1 (from -r requirementsPip.txt (line 1))
  Downloading nibabel-2.0.1-py2-none-any.whl (2.5MB)
Installing collected packages: nibabel
Successfully installed nibabel-2.0.1

Create links to python scripts...
>> /Users/julien/sct/install/create_links.sh -a
/Users/julien/sct/install/create_links.sh -a

Check for latest patches online...
  No connexion or no patch available for this version of the toolbox.

Compile external packages...
>> pip install *.whl
pip install *.whl
Processing ./dipy-0.10.0.dev0-cp27-none-macosx_10_5_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Processing ./ornlm-0.1-cp27-none-macosx_10_5_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): nibabel>=1.2.0 in /Users/julien/miniconda/lib/python2.7/site-packages (from dipy==0.10.0.dev0)
Installing collected packages: dipy, ornlm
Successfully installed dipy-0.10.0.dev0 ornlm-0.1

Check if other dependent software are installed...
>> sct_check_dependences
sct_check_dependences

Check which OS is running...
osx (Darwin-10.3.0-i386-64bit)
Check RAM...
Primary memory available: 4.00 gigabytes
Wired Memory:		612 MB
Active Memory:		719 MB
Inactive Memory:	728 MB
Free Memory:		281 MB
Check which Python is running ...
/Users/julien/miniconda/bin/python
Fetch version of the Spinal Cord Toolbox...
version: 2.1_beta5
Check if git is installed ..........................[FAIL]
git is not installed.
- To install it: http://git-scm.com/book/en/v1/Getting-Started-Installing-Git
Check if cython (0.23) is installed.................[OK]
Check if scikit-image (0.11.3) is installed.........[OK]
Check if matplotlib (1.4.3) is installed............[OK]
Check if scipy (0.16.0) is installed................[OK]
Check if sympy (0.7.6) is installed.................[OK]
Check if numpy (1.9.2) is installed.................[OK]
Check if nibabel (2.0.1) is installed...............[OK]
Check if ornlm is installed.........................[FAIL]
Check if dipy is installed..........................[OK]
Check ANTs compatibility with OS ...................[FAIL]
Check PropSeg compatibility with OS ................[OK]
Check integrity of ANTs output .....................[FAIL]
mkdir tmp.150427070223

Apply rigid transformation to curved landmarks...
sct_apply_transfo -i data_src.nii.gz -o data_src_rigid.nii.gz -d data_dest.nii.gz -w curve2straight_rigid.txt -x nn

Parse list of warping fields...
  Transfo #0: curve2straight_rigid.txt

Check file existence...
  OK: data_src.nii.gz
  OK: data_dest.nii.gz
  OK: curve2straight_rigid.txt

/Users/julien/sct/scripts/sct_utils.py, line 90
/Users/julien/sct/scripts/sct_utils.py, line 90

Traceback (most recent call last):
  File "./installer.py", line 941, in <module>
    Installer()
  File "./installer.py", line 883, in __init__
    status, output = runProcess(cmd)
TypeError: 'NoneType' object is not iterable
~~~

**Comment by jcohenadad** [comment]
ANTs incompatibility with 10.6 is already known. However, the issue with ornlm is strange. It seems like the image is missing:
~~~
sansfil-public-lassonde-200-40:~ julien$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:29:08) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import ornlm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/julien/miniconda/lib/python2.7/site-packages/ornlm.so, 2): Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Users/julien/miniconda/lib/python2.7/site-packages/ornlm.so
  Reason: image not found
~~~

**Comment by jcohenadad** [comment]
Issue with ANTs is already known: not compatible with 10.6.

Issue with ornlm is related to another problem already reported in issue #558.
