### ISSUE TITLE
bad checking of file existence

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#568]
~~~
 sct_apply_transfo -i labels.nii.gz -o labels_straight2templateAffine.nii -d template.nii -w warp_curve2straightAffine.nii.gz

Parse list of warping fields...
  Transfo #0: warp_curve2straightAffine.nii.gz

Check file existence...
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_apply_transfo", line 239, in <module>
    transform.apply()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_apply_transfo", line 78, in apply
    sct.check_file_exist(fname_src, self.verbose)
  File "/Users/slevy_local/spinalcordtoolbox/scripts/sct_utils.py", line 192, in check_file_exist
    if os.path.isfile(fname):
  File "/Users/slevy_local/miniconda/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
~~~

**Comment by jcohenadad** [comment]
fixed on dev
