### ISSUE TITLE
BUG during sct_segment_graymatter

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#587]
Data: /Volumes/folder_shared/sct_issues/20151014_587
(subject d_sp_pain_01)
Command line:
~~~~~~
sct_segment_graymatter -i t2starcrop.nii.gz -s t2starcrop_seg_ok.nii.gz 
~~~~~
Output error:
~~~~~
Building the appearance model...
The shape of the dictionary used for the PCA is (5625,367)

Loading a reduced common space (using a PCA) ...

 ---> sum of eigenvalues : 25840774.735
kept eigenvalues (PCA space dimension)  : 47


-------> IN PCA : 

-> kept_modes:[[  3.49398364e-17   1.52343914e-16  -7.58488521e-17 ...,   3.80134817e-16
   -1.89151114e-16   5.03210500e-16]
 [  8.90089761e-17  -1.19838181e-17  -1.66316223e-17 ...,   6.82225569e-16
   -5.54560867e-17   6.59016387e-16]
 [ -1.93464814e-16  -5.61873130e-16   2.97913681e-16 ...,   1.44167405e-15
   -6.91923514e-17   1.34597836e-15]
 ..., 
 [  4.82975213e-41  -1.96928854e-41   7.01142309e-42 ...,  -1.99192770e-40
    7.88297211e-41   4.54343078e-40]
 [  2.30677769e-42   1.98578340e-42  -7.86602226e-43 ...,  -2.10894907e-41
   -1.24018683e-41   1.22609524e-41]
 [ -3.60789799e-42   6.98905602e-42  -7.80287706e-43 ...,   3.91838402e-41
   -3.27249882e-42  -1.60868436e-41]]

-> kept_eigenval:47

--> OK !
mkdir tmp_t2starcrop_151014184130

Doing target pre-processing ...
cp t2starcrop.nii.gz tmp_t2starcrop_151014184130/target.nii.gz
cp t2starcrop_seg_ok.nii.gz tmp_t2starcrop_151014184130/target_sc_seg.nii.gz
sct_orientation -i target.nii.gz
sct_resample -i target.nii.gz -mm 0.3x0.3x7.5 -o target_resampled.nii.gz -x spline
sct_orientation -i target_sc_seg.nii.gz
sct_resample -i target_sc_seg.nii.gz -mm 0.3x0.3x7.5 -o target_sc_seg_resampled.nii.gz -x nn
sct_maths -i target_sc_seg_resampled.nii.gz -thr 0.0 -o target_sc_seg_resampled.nii.gz
sct_maths -i target_sc_seg_resampled.nii.gz -bin -o target_sc_seg_resampled.nii.gz
WARNING: File target_resampled.nii.gz already exists. Deleting it.
sct_crop_image -i target_resampled.nii.gz -m target_sc_seg_resampled.nii.gz -b 0 -o target_resampled_seg_in.nii.gz
sct_create_mask -i target_resampled_seg_in.nii.gz -m centerline,target_sc_seg_resampled.nii.gz -s 73 -o target_resampled_square_mask_from_sc_seg.nii.gz -f box
WARNING: an error occured when croping target_resampled... 
 could not broadcast input array from shape (75,75) into shape (75)
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 490, in <module>
    gmsegfull = FullGmSegmentation(input_target_fname, input_sc_seg_fname, input_t2_data, input_level_fname, ref_gm_seg=input_ref_gm_seg, compute_ratio=compute_ratio, param=param)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 122, in __init__
    self.segmentation_pipeline()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 142, in segmentation_pipeline
    self.preprocessed = Preprocessing(self.target_fname, self.sc_seg_fname, tmp_dir=self.tmp_dir, t2_data=self.t2_data, level_fname=self.level_fname, denoising=self.param.target_denoising)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 75, in __init__
    self.square_mask, self.processed_target = crop_t2_star(self.t2star, self.sc_seg, box_size=int(22.5/self.resample_to))
  File "/Users/slevy_local/spinalcordtoolbox/scripts/msct_gmseg_utils.py", line 628, in crop_t2_star
    return mask_box, fname_seg_in_IRP
UnboundLocalError: local variable 'fname_seg_in_IRP' referenced before assignment

**Comment by SaraDupont** [comment]
The issue is due to the crop of the T2star before the segmentation : the spinal cord is too close to the edges of the image. The square mask centered on the spinal cord used to crop the image to the appropriate size "gets out" of the image ==> its size isn't the same on all the slices. I'm going to change the way we obtain and use this mask.

**Comment by SaraDupont** [comment]
I added a padding in the preprocessing and a cropping in the post processing.
