### ISSUE TITLE
BUG in sct_segment_graymatter

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#597]
Data: folder_shared/sct_issues/20151016_597
Command line:
~~~~
sct_segment_graymatter -i t2starcrop.nii.gz -s t2starcrop_seg_ok.nii.gz -l rough_label/template/MNI-Poly-AMU_level.nii.gz -ratio
~~~~
Output:
~~~~
Building the appearance model...
The shape of the dictionary used for the PCA is (5625,367)

Loading a reduced common space (using a PCA) ...

 ---> sum of eigenvalues : 25840774.735
kept eigenvalues (PCA space dimension)  : 47


-------> IN PCA : 

-> kept_modes:[[  3.49398364e-17   1.52343914e-16  -7.58488521e-17 ...,   3.80134817e-16
   -1.89151114e-16   5.03210500e-16]
 [  8.90089761e-17  -1.19838181e-17  -1.66316223e-17 ...,   6.82225569e-16
   -5.54560867e-17   6.59016387e-16]
 [ -1.93464814e-16  -5.61873130e-16   2.97913681e-16 ...,   1.44167405e-15
   -6.91923514e-17   1.34597836e-15]
 ..., 
 [  4.82975213e-41  -1.96928854e-41   7.01142309e-42 ...,  -1.99192770e-40
    7.88297211e-41   4.54343078e-40]
 [  2.30677769e-42   1.98578340e-42  -7.86602226e-43 ...,  -2.10894907e-41
   -1.24018683e-41   1.22609524e-41]
 [ -3.60789799e-42   6.98905602e-42  -7.80287706e-43 ...,   3.91838402e-41
   -3.27249882e-42  -1.60868436e-41]]

-> kept_eigenval:47

--> OK !
mkdir tmp_t2starcrop_151016153355

Doing target pre-processing ...
cp rough_label/template/MNI-Poly-AMU_level.nii.gz tmp_t2starcrop_151016153355/MNI-Poly-AMU_level.nii.gz
cp t2starcrop.nii.gz tmp_t2starcrop_151016153355/target.nii.gz
cp t2starcrop_seg_ok.nii.gz tmp_t2starcrop_151016153355/target_sc_seg.nii.gz
sct_resample -i target.nii.gz -mm 0.3x0.3x7.5 -o target_resampled.nii.gz -x spline
sct_resample -i target_sc_seg.nii.gz -mm 0.3x0.3x7.5 -o target_sc_seg_resampled.nii.gz -x nn
sct_maths -i target_sc_seg_resampled.nii.gz -thr 0.0 -o target_sc_seg_resampled.nii.gz
sct_maths -i target_sc_seg_resampled.nii.gz -bin -o target_sc_seg_resampled.nii.gz
WARNING: File target_resampled.nii.gz already exists. Deleting it.
sct_image -i target_resampled.nii.gz -pad 37,37,0 -o target_resampled_pad.nii.gz
sct_image -i target_sc_seg_resampled.nii.gz -pad 37,37,0 -o target_sc_seg_resampled_pad.nii.gz
sct_crop_image -i target_resampled_pad.nii.gz -m target_sc_seg_resampled_pad.nii.gz -b 0 -o target_resampled_pad_seg_in.nii.gz
sct_create_mask -i target_resampled_pad_seg_in.nii.gz -m centerline,target_sc_seg_resampled_pad.nii.gz -s 73 -o target_resampled_pad_square_mask_from_sc_seg.nii.gz -f box
WARNING: an error occured when croping target_resampled_pad... 
 could not broadcast input array from shape (219,231) into shape (218,230)
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 505, in <module>
    gmsegfull = FullGmSegmentation(input_target_fname, input_sc_seg_fname, input_t2_data, input_level_fname, ref_gm_seg=input_ref_gm_seg, compute_ratio=compute_ratio, param=param)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 132, in __init__
    self.segmentation_pipeline()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 152, in segmentation_pipeline
    self.preprocessed = Preprocessing(self.target_fname, self.sc_seg_fname, tmp_dir=self.tmp_dir, t2_data=self.t2_data, level_fname=self.level_fname, denoising=self.param.target_denoising)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_segment_graymatter", line 87, in __init__
    self.square_mask, self.processed_target = crop_t2_star(self.t2star_pad, self.sc_seg_pad, box_size=box_size)
  File "/Users/slevy_local/spinalcordtoolbox/scripts/msct_gmseg_utils.py", line 633, in crop_t2_star
    return mask_box, fname_seg_in_IRP
UnboundLocalError: local variable 'fname_seg_in_IRP' referenced before assignment
~~~~

**Comment by SaraDupont** [comment]
It works fine with an "OK" segmentation (I corrected your segmentation: available in the same folder). The one you used wasn't good at all: 
![t2star_crop_seg](https://cloud.githubusercontent.com/assets/5857909/10553803/bb027cd0-742b-11e5-9461-7fed20f748db.png)
