### ISSUE TITLE
crashes if not enough space on disc

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#603]
Error is difficult to interpret. Maybe we should add checks for disc space before writing data.

```
sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l labels.nii.gz -p step=1,type=seg,algo=slicereg,metric=MeanSquares:step=2,type=seg,algo=bsplinesyn,iter=5,shrink=2,metric=MeanSquares:step=3,type=im,algo=syn,iter=3,shrink=1,metric=CC

Check template files...
  OK: /Users/julien/sct/data/template/MNI-Poly-AMU_T2.nii.gz
  OK: /Users/julien/sct/data/template/landmarks_center.nii.gz
  OK: /Users/julien/sct/data/template/MNI-Poly-AMU_cord.nii.gz

Check parameters:
.. Data:                 t2.nii.gz
.. Landmarks:            labels.nii.gz
.. Segmentation:         t2_seg.nii.gz
.. Path template:        /Users/julien/sct/data/template
.. Path output:          ./
.. Output type:          1
.. Remove temp files:    1

Parameters for registration:
Step #1
.. Type #seg
.. Algorithm................ slicereg
.. Metric................... MeanSquares
.. Number of iterations..... 10
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #2
.. Type #seg
.. Algorithm................ bsplinesyn
.. Metric................... MeanSquares
.. Number of iterations..... 5
.. Shrink factor............ 2
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #3
.. Type #im
.. Algorithm................ syn
.. Metric................... CC
.. Number of iterations..... 3
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3

Check input labels...

Create temporary folder...
mkdir tmp.151017100028_856440/

Copying input data to tmp folder and convert to nii...
sct_convert -i t2.nii.gz -o tmp.151017100028_856440//data.nii
sct_convert -i labels.nii.gz -o tmp.151017100028_856440//landmarks.nii.gz
sct_convert -i t2_seg.nii.gz -o tmp.151017100028_856440//segmentation.nii.gz
sct_convert -i /Users/julien/sct/data/template/MNI-Poly-AMU_T2.nii.gz -o tmp.151017100028_856440//template.nii
sct_convert -i /Users/julien/sct/data/template/landmarks_center.nii.gz -o tmp.151017100028_856440//template_labels.nii.gz
sct_convert -i /Users/julien/sct/data/template/MNI-Poly-AMU_cord.nii.gz -o tmp.151017100028_856440//template_seg.nii.gz

Resample data to 1mm isotropic...
sct_resample -i data.nii -mm 1.0x1.0x1.0 -x linear -o datar.nii
sct_resample -i segmentation.nii.gz -mm 1.0x1.0x1.0 -x nn -o segmentationr.nii.gz
Position=(210,180,26) -- Value= 2
Position=(238,67,27) -- Value= 9
Useful notation:
210,180,26,2:238,67,27,9
sct_label_utils -i datar.nii -t create -x 210,180,26,2:238,67,27,9 -v 1 -o landmarksr.nii.gz

Change orientation of input images to RPI...
sct_crop_image -i segmentation_rpi.nii.gz -o segmentation_rpi_crop.nii.gz -dim 2 -bzmax

Straighten the spinal cord using centerline/segmentation...
sct_straighten_spinalcord -i segmentation_rpi_crop.nii.gz -c segmentation_rpi_crop.nii.gz -r 0 -v 1
sct_concat_transfo -w warp_straight2curve.nii.gz -d data_rpi.nii -o warp_straight2curve.nii.gz

Remove unused label on template. Keep only label present in the input label image...
sct_label_utils -t remove -i template_labels.nii.gz -o template_label.nii.gz -r landmarks_rpi.nii.gz

Dilating input labels using 3vox ball radius
sct_maths -i landmarks_rpi.nii.gz -o landmarks_rpi_dilated.nii.gz -dilate 3

Apply straightening to labels...
sct_apply_transfo -i landmarks_rpi_dilated.nii.gz -o landmarks_rpi_dilated_straight.nii.gz -d segmentation_rpi_crop_straight.nii.gz -w warp_curve2straight.nii.gz -x nn

Create a 15 mm cross for the template labels...

Create a 15 mm cross for the input labels...

Computing rigid transformation (algo=translation-scaling-z) ...

Apply affine transformation: straight --> template...
sct_concat_transfo -w warp_curve2straight.nii.gz,straight2templateAffine.txt -d template.nii -o warp_curve2straightAffine.nii.gz
sct_apply_transfo -i data_rpi.nii -o data_rpi_straight2templateAffine.nii -d template.nii -w warp_curve2straightAffine.nii.gz
sct_apply_transfo -i segmentation_rpi.nii.gz -o segmentation_rpi_straight2templateAffine.nii.gz -d template.nii -w warp_curve2straightAffine.nii.gz -x linear
sct_crop_image -i segmentation_rpi_straight2templateAffine_th.nii.gz -dim 2 -bmax -o tmp.nii

Crop data in template space (for faster processing)...
sct_crop_image -i template.nii -o template_crop.nii -dim 2 -start 56 -end 490
sct_crop_image -i template_seg.nii.gz -o template_seg_crop.nii.gz -dim 2 -start 56 -end 490
sct_crop_image -i data_rpi_straight2templateAffine.nii -o data_rpi_straight2templateAffine_crop.nii -dim 2 -start 56 -end 490
crop
isct_crop_image -i data_rpi_straight2templateAffine.nii -o data_rpi_straight2templateAffine_crop.nii -start 56.0 -end 490.0 -dim 2
Cropping the following region:
Dimension 0: 0 120
Dimension 1: 0 120
Dimension 2: 56 490
** ERROR: NWAD: wrote only 19734176 of 50112000 bytes to file
Traceback (most recent call last):
File "/Users/julien/sct/bin/sct_crop_image", line 413, in <module>
cropper.crop()
File "/Users/julien/sct/bin/sct_crop_image", line 105, in crop
self.result = Image(self.output_filename, verbose=self.verbose)
File "/Users/julien/sct/scripts/msct_image.py", line 44, in __init__
self.loadFromPath(param, verbose)
File "/Users/julien/sct/scripts/msct_image.py", line 101, in loadFromPath
self.data = im_file.get_data()
File "/Users/julien/miniconda/lib/python2.7/site-packages/nibabel/spatialimages.py", line 582, in get_data
data = np.asanyarray(self._dataobj)
File "/Users/julien/miniconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 514, in asanyarray
return array(a, dtype, copy=False, order=order, subok=True)
File "/Users/julien/miniconda/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 144, in __array__
raw_data = self.get_unscaled()
File "/Users/julien/miniconda/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 139, in get_unscaled
mmap=self._mmap)
File "/Users/julien/miniconda/lib/python2.7/site-packages/nibabel/volumeutils.py", line 525, in array_from_file
getattr(infile, 'name', 'object')))
IOError: Expected 50112000 bytes, got 19734176 bytes from data_rpi_straight2templateAffine_crop.nii
- could the file be damaged?
```

**Comment by benjamindeleener** [comment]
Actually, the error seems to be displayed above:

``
** ERROR: NWAD: wrote only 19734176 of 50112000 bytes to file
``

You could detect that into sct.run().

**Comment by joshuacwnewton** [comment]
IMO, not having enough free space on disk seems like a tricky thing to try and catch. I imagine there are many possible points of failure when free space is low -- monitoring one failure point (e.g. `sct.run`) might work okay, but then other failures might slip through elsewhere (e.g. `img.save`). It's like whack-a-mole. :stuck_out_tongue: 

> Actually, the error seems to be displayed above:

Given the above, I think it's more reasonable to expect the user to monitor their own disk usage when running SCT, and to help them debug in the rare cases it comes up on the forum. So, I'm closing here.
