### ISSUE TITLE
should check that there is two inputs for initz

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#626]
```
sct_label_vertebrae -i t2.nii.gz -seg t2_seg_manual.nii.gz -initz 120 -v 2

Create temporary folder...
main
mkdir tmp.151024191808/

Copying input data to tmp folder...
sct_convert -i t2.nii.gz -o tmp.151024191808/data.nii
sct_convert -i t2_seg_manual.nii.gz -o tmp.151024191808/segmentation.nii.gz

Create label to identify disc...
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_label_vertebrae", line 649, in <module>
    main()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_label_vertebrae", line 130, in main
    create_label_z('segmentation.nii.gz', initz[0], initz[1])  # create label located at z_center
IndexError: list index out of range
```

**Comment by abtahizadeh** [comment]
I'm on this

**Comment by jcohenadad** [comment]
Should be addressed when refactoring with argparse https://github.com/neuropoly/spinalcordtoolbox/issues/1548
