### ISSUE TITLE
stops if process crashes-- should return 256 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#630]
command:
~~~
isct_test_function -f sct_register_to_template -d /Volumes/data_raid/data_shared/sct_testing/small/ -p "-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz -param-straighten '-params bspline_meshsize=3x3x5' -cpu-nb 0"
~~~

results:
~~~
.. Landmarks:            /Volumes/data_raid/data_shared/sct_testing/small/sct_example_data/t2/labels.nii.gz
.. Segmentation:         /Volumes/data_raid/data_shared/sct_testing/small/sct_example_data/t2/t2_seg_manual.nii.gz
.. Path template:        /Users/jcohen/code/spinalcordtoolbox/data/template
.. Path output:          sct_register_to_template_sct_example_data_151025202015_621116/
.. Output type:          1
.. Remove temp files:    1

Parameters for registration:
Step #1
.. Type #seg
.. Algorithm................ slicereg
.. Metric................... MeanSquares
.. Number of iterations..... 10
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #2
.. Type #seg
.. Algorithm................ bsplinesyn
.. Metric................... MI
.. Number of iterations..... 3
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #3
.. Type #im
.. Algorithm................ syn
.. Metric................... CC
.. Number of iterations..... 0
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3

Check input labels...

Create temporary folder...
mkdir tmp.151025202017_886559/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Volumes/data_raid/data_shared/sct_testing/small/sct_example_data/t2/t2.nii.gz -o tmp.151025202017_886559/data.nii
sct_convert -i /Volumes/data_raid/data_shared/sct_testing/small/sct_example_data/t2/t2_seg_manual.nii.gz -o tmp.151025202017_886559/seg.nii.gz
sct_convert -i /Volumes/data_raid/data_shared/sct_testing/small/sct_example_data/t2/labels.nii.gz -o tmp.151025202017_886559/label.nii.gz
sct_convert -i /Users/jcohen/code/spinalcordtoolbox/data/template/MNI-Poly-AMU_T2.nii.gz -o tmp.151025202017_886559/template.nii
sct_convert -i /Users/jcohen/code/spinalcordtoolbox/data/template/MNI-Poly-AMU_cord.nii.gz -o tmp.151025202017_886559/template_seg.nii.gz
sct_convert -i /Users/jcohen/code/spinalcordtoolbox/data/template/landmarks_center.nii.gz -o tmp.151025202017_886559/template_label.nii.gz

Smooth segmentation...

Resample data to 1mm isotropic...
sct_resample -i data.nii -mm 1.0x1.0x1.0 -x linear -o data_1mm.nii
sct_resample -i seg.nii.gz -mm 1.0x1.0x1.0 -x linear -o seg_1mm.nii.gz
Position=(210,180,26) -- Value= 2
Position=(238,67,27) -- Value= 9
Useful notation:
210,180,26,2:238,67,27,9
sct_label_utils -i data_1mm.nii -t create -x 210,171,26,2:238,64,27,9 -v 1 -o label_1mm.nii.gz

Change orientation of input images to RPI...
sct_image -i data_1mm.nii -setorient RPI -o data_1mm_rpi.nii
sct_image -i seg_1mm.nii.gz -setorient RPI -o seg_1mm_rpi.nii.gz
sct_image -i label_1mm.nii.gz -setorient RPI -o label_1mm_rpi.nii.gz
sct_crop_image -i seg_1mm_rpi.nii.gz -o seg_1mm_rpi_crop.nii.gz -dim 2 -bzmax

Straighten the spinal cord using centerline/segmentation...
sct_straighten_spinalcord -i seg_1mm_rpi_crop.nii.gz -c seg_1mm_rpi_crop.nii.gz -o seg_1mm_rpi_crop_straight.nii.gz -r 0 -v 1 
sct_concat_transfo -w warp_straight2curve.nii.gz -d data_1mm_rpi.nii -o warp_straight2curve.nii.gz
cp template_label.nii.gz template_labels.nii.gz
cp label_1mm_rpi.nii.gz landmarks_rpi.nii.gz
cp seg_1mm_rpi_crop_straight.nii.gz segmentation_rpi_crop_straight.nii.gz

Remove unused label on template. Keep only label present in the input label image...
sct_label_utils -t remove -i template_labels.nii.gz -o template_label.nii.gz -r landmarks_rpi.nii.gz

Convert landmarks to INT...
sct_convert -i template_label.nii.gz -o template_label.nii.gz
WARNING: File template_label.nii.gz already exists. Deleting it.

Create a 5 mm cross for the template labels...
sct_label_utils -t cross -i template_label.nii.gz -o template_label_cross.nii.gz -c 5

Create a 5mm cross for the input labels and dilate for straightening preparation...
sct_label_utils -t cross -i landmarks_rpi.nii.gz -o landmarks_rpi_cross3x3.nii.gz -c 5 -d
sct_crop_image -i landmarks_rpi_cross3x3.nii.gz -o landmarks_rpi_cross3x3_crop.nii.gz -dim 2 -start 0 -end 194
crop
isct_crop_image -i landmarks_rpi_cross3x3.nii.gz -o landmarks_rpi_cross3x3_crop.nii.gz -start 0.0 -end 194.0 -dim 2
Cropping the following region:
Dimension 0: 0 52
Dimension 1: 0 384
Dimension 2: 0 194
Exception caught while updating cropFilter

itk::InvalidRequestedRegionError (0x7faac37265c8)
Location: "unknown"
File: /Users/benjamindeleener/code/ITK/Modules/Core/Common/src/itkDataObject.cxx
Line: 393
Description: Requested region is (at least partially) outside the largest possible region.


Exception caught while updating writerCrop

itk::ImageFileWriterException (0x7faac4000928)
Location: "unknown"
File: /usr/local/itk/include/ITK-4.8/itkImageFileWriter.hxx
Line: 408
Description: Did not get requested region!
Requested:
ImageRegion (0x7fff57147bc0)
Dimension: 3
Index: [0, 0, 0]
Size: [52, 384, 195]
Actual:
ImageRegion (0x7fff57147b88)
Dimension: 3
Index: [0, 0, 0]
Size: [0, 0, 0]



Traceback (most recent call last):
File "/Users/jcohen/code/spinalcordtoolbox/bin/sct_crop_image", line 413, in <module>
cropper.crop()
File "/Users/jcohen/code/spinalcordtoolbox/bin/sct_crop_image", line 105, in crop
self.result = Image(self.output_filename, verbose=self.verbose)
File "/Users/jcohen/code/spinalcordtoolbox/scripts/msct_image.py", line 44, in __init__
self.loadFromPath(param, verbose)
File "/Users/jcohen/code/spinalcordtoolbox/scripts/msct_image.py", line 97, in loadFromPath
im_file = load(path)
File "/Users/jcohen/miniconda/lib/python2.7/site-packages/nibabel-2.0.1-py2.7.egg/nibabel/loadsave.py", line 44, in load
return guessed_image_type(filename).from_filename(filename, **kwargs)
File "/Users/jcohen/miniconda/lib/python2.7/site-packages/nibabel-2.0.1-py2.7.egg/nibabel/loadsave.py", line 76, in guessed_image_type
with BinOpener(filename) as fobj:
File "/Users/jcohen/miniconda/lib/python2.7/site-packages/nibabel-2.0.1-py2.7.egg/nibabel/openers.py", line 74, in __init__
self.fobj = opener(fileish, *args, **kwargs)
File "/Users/jcohen/miniconda/lib/python2.7/site-packages/nibabel-2.0.1-py2.7.egg/nibabel/openers.py", line 23, in _gzip_open
gzip_file = gzip.open(fileish, *args, **kwargs)
File "/Users/jcohen/miniconda/lib/python2.7/gzip.py", line 34, in open
return GzipFile(filename, mode, compresslevel)
File "/Users/jcohen/miniconda/lib/python2.7/gzip.py", line 94, in __init__
fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'landmarks_rpi_cross3x3_crop.nii.gz'
/Users/jcohen/code/spinalcordtoolbox/scripts/sct_utils.py, line 97
/Users/jcohen/code/spinalcordtoolbox/scripts/sct_utils.py, line 97
~~~

**Comment by jcohenadad** [comment]
fixed
