### ISSUE TITLE
crashes if apply transfo on 4d images

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#640]
error:

```
Merge file back...
Traceback (most recent call last):
File "/Users/julien/code/spinalcordtoolbox/bin/sct_apply_transfo", line 274, in <module>
main()
File "/Users/julien/code/spinalcordtoolbox/bin/sct_apply_transfo", line 265, in main
transform.apply()
File "/Users/julien/code/spinalcordtoolbox/bin/sct_apply_transfo", line 210, in apply
im_out = concat_data(im_list, 3)
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_image.py", line 292, in concat_data
if dim > im_in_list[0].data.ndim-1:
IndexError: list index out of range
/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 97
```

**Comment by SaraDupont** [comment]
the destination image and the warping fields were not copied into the temporary folder in ```sct_apply_transfo``` so when ```isct_antsApplyTransforms``` was called in the tmp folder with **relative path** for the destination image and the warping fields, it didn't output any image (nor raise any error for the missing files) and concat_data was called on an empty list of images. (It worked fine with **absolute path**.)
I added a copy of dest and warps to the tmp folder, the tests are fine, if it doesn't create any issues elsewhere, we can close this.

**Comment by tanguyduval** [comment]
Apply_transfo on 4D data, 1 slice create a bug:
data in ````/Volumes/folder_shared/sct_issues/20170224_issue640````
`````
$sct_apply_transfo -i AxCaliber.nii.gz -d sems_96_AxCaliber_d8D3002.nii.gz -w warp_src2dest.nii.gz 

--
Spinal Cord Toolbox (master/63b0d9545013587cf6985879c92dfe45c6ad3f75)
Running /Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_apply_transfo.py -i /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/AxCaliber.nii.gz -d /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/fsems_96_AxCaliber_d8D3002.nii.gz -w /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/warp_src2dest.nii.gz

Parse list of warping fields...
  Transfo #0: /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/warp_src2dest.nii.gz

Get dimensions of data...
  96 x 96 x 1 x 254

Create temporary folder...
mkdir tmp.170224112723/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/AxCaliber.nii.gz -o tmp.170224112723/data.nii
cp /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/fsems_96_AxCaliber_d8D3002.nii.gz tmp.170224112723/fsems_96_AxCaliber_d8D3002.nii.gz
cp /Users/taduv_admin/data/ICM/s_20170213_Tanguy_ratfixedGa2PFA4_DiffusionYogesh_rescan/ProcessedData/warp_src2dest.nii.gz tmp.170224112723/warp_src2dest.nii.gz

Split along T dimension...

Apply transformation to each 3D volume...
isct_antsApplyTransforms -d 3 -i data_T0000.nii -o data_reg_T0000.nii -t warp_src2dest.nii.gz -r fsems_96_AxCaliber_d8D3002.nii.gz -n BSpline[3]
isct_antsApplyTransforms -d 3 -i data_T0001.nii -o data_reg_T0001.nii -t warp_src2dest.nii.gz -r fsems_96_AxCaliber_d8D3002.nii.gz -n BSpline[3]
file data_T0001.nii does not exist .
libc++abi.dylib: terminating with uncaught exception of type itk::ExceptionObject: /Users/sadup/code/antsbin/ITKv4/Modules/Core/Common/src/itkProcessObject.cxx:1387:
itk::ERROR: ResampleImageFilter(0x7fc102074cc0): Input Primary is required but not set.

/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_utils.pyNone

`````

**Comment by tanguyduval** [comment]
bug still exists

**Comment by tanguyduval** [comment]
I created 2 slices using the same dataset
`fslmerge -z 2slices.nii.gz AxCaliber.nii.gz AxCaliber.nii.gz`
And I have the same bug...

**Comment by tanguyduval** [comment]
Also, destination has to be 3D. with a 4D destination:
`````
 ../../3Dqspace/DWI.nii is not a 3D volume. Exit program.
`````

**Comment by charleygros** [comment]
Fixed: https://github.com/neuropoly/spinalcordtoolbox/pull/1408
