### ISSUE TITLE
Installer crashes if glitch in internet connection

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#655]
error below:
~~~
Create links to python scripts...
/usr/local/spinalcordtoolbox/install/create_links.sh

Check for latest patches online...
Traceback (most recent call last):
  File "./installer.py", line 950, in <module>
    Installer()
  File "./installer.py", line 828, in __init__
    version_sct.isEqualTo_MajorMinor(version_sct_online) and \
UnboundLocalError: local variable 'version_sct_online' referenced before assignment
~~~

**Comment by jcohenadad** [comment]
now checked in new installer
