### ISSUE TITLE
default installer if non admin

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#686]
~~~
./installer.py

=============================
SPINAL CORD TOOLBOX INSTALLER
Modified: 2015-10-24
=============================

Check if administrator permission is needed for installation...
.. Installation path: /usr/local/spinalcordtoolbox
.. sudo needed for adding elements.

Check which Python distribution is running...
2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]
.. conda (OK)

Check if pip is installed...
pip
.. OK!


Check if spinalcordtoolbox is already installed (if so, delete it)...

Create folder: /usr/local/spinalcordtoolbox ...
sudo mkdir /usr/local/spinalcordtoolbox
Password:
Password:
Password:

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Sorry, try again.
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts


Fetch version of the Spinal Cord Toolbox...
  Version: 2.1

Check online if you have the latest version of SCT...
          
Copy Spinal Cord Toolbox on your computer...
sudo cp -r spinalcordtoolbox/* /usr/local/spinalcordtoolbox
Password:
Password:
Password:

ERROR! 

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Sorry, try again.
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts
Exit program.


Edit profile files...
Delete previous SCT entries in existing profile files...
.. .bashrc: Found! Deleting previous SCT entries...
awk '!/SCT_DIR|SPINALCORDTOOLBOX|ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS/' ~/.bashrc > .bashrc_temp && > ~/.bashrc && cat .bashrc_temp >> ~/.bashrc && rm .bashrc_temp
.. .profile: Not found.
.. .bash_login: Not found.
.. .bash_profile: Found! Deleting previous SCT entries...
Add entries to .bashrc...
Check if no profile file other than .bashrc exist...
.. OK: Default profile file is:.bash_profile
Check if .bashrc is sourced in default profile...
.. .bashrc seems to be sourced already
Source .bashrc:
. ~/.bashrc

Install dependences... Depending on your internet connection, this may take several minutes.
Traceback (most recent call last):
  File "./installer.py", line 950, in <module>
    Installer()
  File "./installer.py", line 803, in __init__
    os.chdir(self.SCT_DIR+"/install/requirements")
OSError: [Errno 2] No such file or directory: '/usr/local/spinalcordtoolbox/install/requirements'
~~~

**Comment by poquirion** [comment]
Solved with new installer
