### ISSUE TITLE
ImportError: dlopen(/Users/sct/miniconda2/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#687]
~~~
./installer.py -p ~/sct

=============================
SPINAL CORD TOOLBOX INSTALLER
Modified: 2015-10-24
=============================

Check if administrator permission is needed for installation...
.. Installation path: /Users/sct/sct
.. no sudo needed for adding elements.

Check which Python distribution is running...
2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)]
.. conda (OK)

Check if pip is installed...
pip
.. WARNING: pip is not installed. Installing it with conda...
conda
conda install pip -y
.. Testing pip...
pip
.. OK!


Check if spinalcordtoolbox is already installed (if so, delete it)...
.. No sudo needed for removing SCT.
rm -rf /Users/sct/sct

Create folder: /Users/sct/sct ...
mkdir /Users/sct/sct

Fetch version of the Spinal Cord Toolbox...
  Version: 2.1

Check online if you have the latest version of SCT...
Traceback (most recent call last):
  File "./installer.py", line 950, in <module>
    Installer()
  File "./installer.py", line 761, in __init__
    version_result = download_file(url_version, file_name)
  File "./installer.py", line 469, in download_file
    result = open_url(url, 0, timeout)
  File "./installer.py", line 431, in open_url
    import urllib2
  File "/Users/sct/miniconda2/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/Users/sct/miniconda2/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/Users/sct/miniconda2/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Users/sct/miniconda2/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/sct/miniconda2/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/sct/miniconda2/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/sct/miniconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup
~~~

**Comment by benjamindeleener** [comment]
The download of patches has been temporarily removed in v2.2.

**Comment by jcohenadad** [comment]
fixed in new installer
