### ISSUE TITLE
error on CSA for small FOV

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#706]
~~~
sct_process_segmentation -i t2star_mean_crop_seg.nii.gz -p csa

Check parameters:
.. segmentation file:             t2star_mean_crop_seg.nii.gz

Create temporary folder...
mkdir tmp.160119152705_337940/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/data/caterina/212015/t2star/t2star_mean_crop_seg.nii.gz -o tmp.160119152705_337940/segmentation.nii.gz

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
  153 x 153 x 11

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 50
WARNING: The smoothing window is larger than the number of points. New value: 11
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_process_segmentation", line 818, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_process_segmentation", line 235, in main
    compute_csa(fname_segmentation, verbose, remove_temp_files, step, smoothing_param, figure_fit, param.file_csa_volume, slices, vert_lev, fname_vertebral_labeling, algo_fitting = param.algo_fitting, type_window= param.type_window, window_length=param.window_length)
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_process_segmentation", line 475, in compute_csa
    x_centerline_fit, y_centerline_fit, z_centerline, x_centerline_deriv, y_centerline_deriv, z_centerline_deriv = smooth_centerline('segmentation_RPI.nii.gz', algo_fitting=algo_fitting, type_window=type_window, window_length=window_length, verbose=verbose)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 136, in smooth_centerline
    verbose=verbose, robust=0, remove_edge_points=remove_edge_points)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_smooth.py", line 545, in smoothing_window
    x_extended = append(x_extended, 2*x_extended_tmp[-1] - x_extended_tmp[-2-i])
IndexError: index -8 is out of bounds for axis 0 with size 7
~~~

**Comment by jcohenadad** [comment]
bug happens in msct_smooth: smoothing_window, if size padding is larger than x_extended.
