### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#715]
error if too many files to concatenate. In this example: 384 files.
data: errsm_40/t2 --> split them along y, then concatenate.

~~~
sct_image -i tmp.anat_orient_fit_Z*.nii -o test.nii.gz -concat z
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_image", line 474, in <module>
    main()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_image", line 120, in main
    im_in = [Image(fn) for fn in fname_in]
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_image.py", line 44, in __init__
    self.loadFromPath(param, verbose)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_image.py", line 100, in loadFromPath
    self.orientation = get_orientation(path, filename=True)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_image.py", line 420, in get_orientation
    status, output = run('isct_orientation3d -i '+im+' -get ', 0)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py", line 80, in run
    process = subprocess.Popen(cmd, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/Users/julien/miniconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/julien/miniconda/lib/python2.7/subprocess.py", line 1223, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/Users/julien/miniconda/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
~~~

also called in sct_flatten_sagittal

**Comment by jcohenadad** [comment]
create a loop and open/close each file within the loop

**Comment by poquirion** [comment]
I've been checking my wrapper with this function to kill two bird with one stone, and it seems that the bug is pretty deep in nibabel. The  `get_unscaled()` method of the `ArrayProxy()` class in `nibabel/arrayproxy.py` line 128.

```python
   def get_unscaled(self):
        ''' Read of data from file

        This is an optional part of the proxy API
        '''
        with BinOpener(self.file_like) as fileobj:
            raw_data = array_from_file(self._shape,
                                       self._dtype,
                                       fileobj,
                                       offset=self._offset,
                                       order=self.order,
                                       mmap=self._mmap)
        return raw_data```


The fileobj is never pour out of scope, so the file does not close. And file keeps opening. 

I manage to fix it in nibable... I can open a ticket with them.

The fix
      def get_unscaled(self):
           ''' Read of data from file

           This is an optional part of the proxy API
           '''
           with BinOpener(self.file_like) as fileobj:
               raw_data = array_from_file(self._shape,
                                          self._dtype,
                                          fileobj,
                                          offset=self._offset,
                                          order=self.order,
                                          mmap=self._mmap)
+++        fileobj.close()
           return raw_data```

**Comment by SaraDupont** [comment]
Fixed on branch ``ìssue_715```. Tested split+concat along Y on errsm_40, result is identical to original image :
![fixed](https://cloud.githubusercontent.com/assets/5857909/12678442/b95b5d14-c66c-11e5-8f3a-edd9fa0511d2.png)
