### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,0) (2,3) 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#716]
data:
~~~
folder_shared/sct_issues/20160127_register_to_template
~~~

Command + output:
~~~
sct_register_to_template -i t2_crop.nii.gz -l labels.nii.gz -s t2_crop_seg.nii.gz -param step=1,type=seg,algo=slicereg:step=2,type=seg,algo=bsplinesyn,iter=5,shrink=2:step=3,type=im,algo=syn,iter=3,shrink=1

Check template files...
  OK: /Users/julien/code/spinalcordtoolbox/data/template/MNI-Poly-AMU_T2.nii.gz
  OK: /Users/julien/code/spinalcordtoolbox/data/template/landmarks_center.nii.gz
  OK: /Users/julien/code/spinalcordtoolbox/data/template/MNI-Poly-AMU_cord.nii.gz

Check parameters:
.. Data:                 t2_crop.nii.gz
.. Landmarks:            labels.nii.gz
.. Segmentation:         t2_crop_seg.nii.gz
.. Path template:        /Users/julien/code/spinalcordtoolbox/data/template
.. Path output:          
.. Output type:          1
.. Remove temp files:    1

Parameters for registration:
Step #1
.. Type #seg
.. Algorithm................ slicereg
.. Metric................... MeanSquares
.. Number of iterations..... 10
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #2
.. Type #seg
.. Algorithm................ bsplinesyn
.. Metric................... MeanSquares
.. Number of iterations..... 5
.. Shrink factor............ 2
.. Smoothing factor......... 1
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #3
.. Type #im
.. Algorithm................ syn
.. Metric................... CC
.. Number of iterations..... 3
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3

Check input labels...

Create temporary folder...
mkdir tmp.160127115156_521265/

Copying input data to tmp folder and convert to nii...
sct_convert -i t2_crop.nii.gz -o tmp.160127115156_521265/data.nii
sct_convert -i t2_crop_seg.nii.gz -o tmp.160127115156_521265/seg.nii.gz
sct_convert -i labels.nii.gz -o tmp.160127115156_521265/label.nii.gz
sct_convert -i /Users/julien/code/spinalcordtoolbox/data/template/MNI-Poly-AMU_T2.nii.gz -o tmp.160127115156_521265/template.nii
sct_convert -i /Users/julien/code/spinalcordtoolbox/data/template/MNI-Poly-AMU_cord.nii.gz -o tmp.160127115156_521265/template_seg.nii.gz
sct_convert -i /Users/julien/code/spinalcordtoolbox/data/template/landmarks_center.nii.gz -o tmp.160127115156_521265/template_label.nii.gz

Smooth segmentation...
sct_maths -i seg.nii.gz -smooth 1.5 -o seg_smooth.nii.gz

Resample data to 1mm isotropic...
sct_resample -i data.nii -mm 1.0x1.0x1.0 -x linear -o data_1mm.nii
sct_resample -i seg_smooth.nii.gz -mm 1.0x1.0x1.0 -x linear -o seg_smooth_1mm.nii.gz
Position=(141,214,34) -- Value= 2
Position=(153,113,34) -- Value= 7
Useful notation:
141,214,34,2:153,113,34,7
sct_label_utils -i data_1mm.nii -p create -coord 132,131,31,2:143,69,31,7 -v 1 -o label_1mm.nii.gz

Change orientation of input images to RPI...
sct_image -i data_1mm.nii -setorient RPI -o data_1mm_rpi.nii
sct_image -i seg_smooth_1mm.nii.gz -setorient RPI -o seg_smooth_1mm_rpi.nii.gz
sct_image -i label_1mm.nii.gz -setorient RPI -o label_1mm_rpi.nii.gz
sct_crop_image -i seg_smooth_1mm_rpi.nii.gz -o seg_smooth_1mm_rpi_crop.nii.gz -dim 2 -bzmax

Straighten the spinal cord using centerline/segmentation...
sct_straighten_spinalcord -i seg_smooth_1mm_rpi_crop.nii.gz -s seg_smooth_1mm_rpi_crop.nii.gz -o seg_smooth_1mm_rpi_crop_straight.nii.gz -qc 0 -r 0 -v 1 
sct_concat_transfo -w warp_straight2curve.nii.gz -d data_1mm_rpi.nii -o warp_straight2curve.nii.gz

Remove unused label on template. Keep only label present in the input label image...
sct_label_utils -p remove -i template_label.nii.gz -o template_label.nii.gz -r label_1mm_rpi.nii.gz

Dilating input labels using 3vox ball radius
sct_maths -i label_1mm_rpi.nii.gz -o label_1mm_rpi_dilate.nii.gz -dilate 3

Apply straightening to labels...
sct_apply_transfo -i label_1mm_rpi_dilate.nii.gz -o label_1mm_rpi_dilate_straight.nii.gz -d seg_smooth_1mm_rpi_crop_straight.nii.gz -w warp_curve2straight.nii.gz -x nn

Create a 15 mm cross for the template labels...

Create a 15 mm cross for the input labels...

Computing rigid transformation (algo=translation-scaling-z) ...
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_register_to_template", line 541, in <module>
    main()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_register_to_template", line 384, in main
    (rotation_matrix, translation_array, points_moving_reg, points_moving_barycenter) = msct_register_landmarks.getRigidTransformFromLandmarks(points_moving, points_fixed, constraints='translation-scaling-z', show=show_transfo)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_register_landmarks.py", line 388, in getRigidTransformFromLandmarks
    tol=1e-8, options={'xtol': 1e-8, 'ftol': 1e-8, 'maxiter': 10000, 'maxfev': 10000, 'disp': show})
  File "/Users/julien/miniconda/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 432, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/Users/julien/miniconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 435, in _minimize_neldermead
    fsim[0] = func(x0)
  File "/Users/julien/miniconda/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 285, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_register_landmarks.py", line 121, in minTranslationScalingZTransform
    sse_results.append(SSE(matrix(points_fixed), points_moving_reg))
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_register_landmarks.py", line 49, in SSE
    return sum(array(pointsA[:, 0:3]-pointsB[:, 0:3])**2.0)
ValueError: operands could not be broadcast together with shapes (1,0) (2,3) 
~~~

**Comment by jcohenadad** [comment]
problem arises because ```labels.nii.gz```and `t2_crop.nii.gz```are not in the same space. This needs to be checked.

**Comment by benjamindeleener** [comment]
When trying with the latest version, source labels are not there:
```
Computing landmark-based transformation...
Labels src: []
Labels dest: [[-0.0, -0.0, 187.5], [-0.0, -0.5, 102.5]]
```

**Comment by benjamindeleener** [comment]
As the source labels are completely off, they are not in the straightened image, and the whole process fails. The solution: check in the straightened image if the labels are still there. If not, display an error message and stop the registration.

I added the following message:
```
Computing landmark-based transformation...
Labels src: []
Labels dest: [[-0.0, -0.0, 187.5], [-0.0, -0.5, 102.5]]
ERROR: input labels do not seem to be at the right place. Please check the position of the labels. See documentation for more details: https://sourceforge.net/p/spinalcordtoolbox/wiki/create_labels/

/Users/benjamindeleener/code/sct/scripts/sct_register_to_template.pyTraceback (most recent call last):
  File "/Users/benjamindeleener/code/sct/scripts/sct_register_to_template.py", line 383, in main
    register_landmarks(ftmp_label, ftmp_template_label, 'Tx_Ty_Tz_Sz', fname_affine='straight2templateAffine.txt', verbose=verbose)
  File "/Users/benjamindeleener/code/sct/scripts/msct_register_landmarks.py", line 76, in register_landmarks
    raise Exception('Error: number of source and destination landmarks are not the same, so landmarks cannot be paired.')
Exception: Error: number of source and destination landmarks are not the same, so landmarks cannot be paired.
```
