### ISSUE TITLE
Issue related to fname_template_list being empty (no file found)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#724]
~~~
isct_test_function -f sct_register_to_template -d /Volumes/data_raid/data_shared/sct_testing_small/ -p "-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz"
Check folder existence...
Testing...
Check folder existence...
Check folder existence...
Traceback (most recent call last):
File "/Users/jcohen/code/spinalcordtoolbox/bin/sct_register_to_template", line 541, in <module>
main()
File "/Users/jcohen/code/spinalcordtoolbox/bin/sct_register_to_template", line 192, in main
fname_template = fname_template_list[0]
IndexError: list index out of range
Check folder existence...
Check folder existence...
Traceback (most recent call last):
~~~

**Comment by benjamindeleener** [comment]
New command, due to change of organization in testing data folder on data_shared:
```
isct_test_function -f sct_register_to_template -d /Volumes/data_raid/data_shared/sct_testing/small/ -p "-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz"
```

The issue appeared because the path to the template in test_sct_register_to_template.py was not correctly set. I changed line 53 from
```
dict_param_with_path['-t'] = path_sct + '/data/template/'
```
to
```
dict_param_with_path['-t'] = path_sct + '/data/'
```
and it works now.

Note: sct_register_to_template fails on some tests. See below the error:
```
Check if data, segmentation and landmarks are in the same space...
ERROR: Data image and segmentation are not in the same space. Please check space and orientation of your files
/Users/benjamindeleener/code/spinalcordtoolbox/bin/sct_register_to_template, line 242
/Users/benjamindeleener/code/spinalcordtoolbox/scripts/sct_utils.py, line 98
```
