### ISSUE TITLE
check if input data are 3d, otherwise it fails

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#757]
~~~
sct_register_multimodal -i dmri.nii.gz -d dmri.nii.gz 

Input parameters:
  Source .............. dmri.nii.gz
  Destination ......... dmri.nii.gz
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if destination data is RPI...

Create temporary folder...

Create temporary folder...
mkdir tmp.160308182658_668512/

Copying input data to tmp folder and convert to nii...
sct_convert -i dmri.nii.gz -o tmp.160308182658_668512/src.nii
sct_convert -i dmri.nii.gz -o tmp.160308182658_668512/dest.nii

Estimate transformation for step #0...
isct_antsRegistration --dimensionality 3 --transform syn[0.5,3,0] --metric MI[dest.nii,src.nii,1,32] --convergence 0 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output [step0,src_regStep0.nii] --interpolation BSpline[3]  --verbose 1

Estimate transformation for step #1...
sct_apply_transfo -i src.nii -d dest.nii -w warp_forward_0.nii.gz -o src_reg.nii -x linear
sct_image -i dest.nii -o dest_pad.nii -pad 0,0,5
Traceback (most recent call last):
File "/Users/julien/code/spinalcordtoolbox/bin/sct_image", line 590, in <module>
main()
File "/Users/julien/code/spinalcordtoolbox/bin/sct_image", line 128, in main
im_out = [pad_image(im_in, padding_x=padx, padding_y=pady, padding_z=padz)]
File "/Users/julien/code/spinalcordtoolbox/bin/sct_image", line 235, in pad_image
padded_data[padxi:padxf, padyi:padyf, padzi:padzf] = im.data
ValueError: could not broadcast input array from shape (208,42,5,52) into shape (208,42,5)
/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 98
~~~

**Comment by tanguyduval** [comment]
similar to #737

**Comment by jcohenadad** [comment]
duplicated issue
