### ISSUE TITLE
IndexError: index -8 is out of bounds for axis 1 with size 5

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#760]
data: **/Volumes/folder_shared/sct_issues/20160311_issue760**

~~~
sct_propseg -i dwi_moco_mean.nii.gz -c t1 -init-mask viewerTraceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_propseg", line 287, in <module>
    mask_points = viewer.start()
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_viewer.py", line 257, in start
    self.window = SinglePlot(self.im_plot_axial, self.image, self, self.number_of_slices, self.gap_inter_slice)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_viewer.py", line 72, in __init__
    self.fig.set_data(self.volume.data[:, int(self.list_slices[self.current_slice]), :])
IndexError: index -8 is out of bounds for axis 1 with size 5
~~~

**Comment by benjamindeleener** [comment]
Fixed by commit 6d74c84282923befdafbcc054c88bc174fc71403
