### ISSUE TITLE
failing on docker-debian

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#769]
Dockerfile: https://github.com/neuropoly/docker/blob/master/debian_8.0/Dockerfile

~~~
sct_testing 
SpinalCord Toolbox version 2.2_dev
SCT installed in /home/neuropoly/sct
PYTHON /home/neuropoly/sct/python/bin/python /home/neuropoly/sct/python /home/neuropoly/sct
running /home/neuropoly/sct/scripts/sct_testing.py

Downloading testing data...
sct_download_data -d sct_testing_data

Path to testing data: /home/neuropoly/sct_testing_data/data/
Checking test_sct_apply_transfo.....................[OK]
Checking test_sct_check_atlas_integrity.............[OK]
Checking test_sct_compute_mtr.......................[OK]
Checking test_sct_concat_transfo....................[OK]
Checking test_sct_convert...........................[OK]
Checking test_sct_create_mask.......................[OK]
Checking test_sct_crop_image........................[OK]
Checking test_sct_dmri_compute_dti..................[FAIL]

====================================================================================================
sct_dmri_compute_dti -i /home/neuropoly/sct_testing_data/data/dmri/dmri.nii.gz -bvec /home/neuropoly/sct_testing_data/data/dmri/bvecs.txt -bval /home/neuropoly/sct_testing_data/data/dmri/bvals.txt
====================================================================================================

SpinalCord Toolbox version 2.2_dev
SCT installed in /home/neuropoly/sct
PYTHON /home/neuropoly/sct/python/bin/python /home/neuropoly/sct/python /home/neuropoly/sct
running /home/neuropoly/sct/scripts/sct_dmri_compute_dti.py -i /home/neuropoly/sct_testing_data/data/dmri/dmri.nii.gz -bvec /home/neuropoly/sct_testing_data/data/dmri/bvecs.txt -bval /home/neuropoly/sct_testing_data/data/dmri/bvals.txt
data.shape (40, 42, 5, 7)
Traceback (most recent call last):
  File "/home/neuropoly/sct/scripts/sct_dmri_compute_dti.py", line 174, in <module>
    main()
  File "/home/neuropoly/sct/scripts/sct_dmri_compute_dti.py", line 84, in main
    if not compute_dti(fname_in, fname_bvals, fname_bvecs, prefix):
  File "/home/neuropoly/sct/scripts/sct_dmri_compute_dti.py", line 117, in compute_dti
    import dipy.reconst.dti as dti
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/dipy/reconst/dti.py", line 12, in <module>
    from dipy.data import get_sphere
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/dipy/data/__init__.py", line 29, in <module>
    from dipy.core.sphere import Sphere, HemiSphere
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/dipy/core/sphere.py", line 12, in <module>
    from dipy.reconst.recspeed import remove_similar_vertices
ImportError: libgomp.so.1: cannot open shared object file: No such file or directory
Checking test_sct_dmri_get_bvalue...................[OK]
Checking test_sct_dmri_transpose_bvecs..............[OK]
Checking test_sct_dmri_moco.........................[OK]
Checking test_sct_dmri_separate_b0_and_dwi..........[OK]
Checking test_sct_extract_metric....................[OK]
Checking test_sct_fmri_compute_tsnr.................[OK]
Checking test_sct_fmri_moco.........................[OK]
Checking test_sct_get_centerline....................[OK]
Checking test_sct_image.............................[OK]
Checking test_sct_label_utils.......................[OK]
Checking test_sct_label_vertebrae...................[OK]
Checking test_sct_maths.............................[OK]
Checking test_sct_process_segmentation..............[OK]
Checking test_sct_propseg...........................[OK]
Checking test_sct_register_multimodal...............[OK]
Checking test_sct_register_to_template..............[OK]
Checking test_sct_resample..........................[OK]
Checking test_sct_segment_graymatter................/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/neuropoly/sct/scripts/sct_testing.py", line 297, in <module>
    main()
  File "/home/neuropoly/sct/scripts/sct_testing.py", line 103, in main
    status.append(test_function(f))
  File "/home/neuropoly/sct/scripts/sct_testing.py", line 241, in test_function
    script_tested = importlib.import_module(script_name)
  File "/home/neuropoly/sct/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/neuropoly/sct/testing/test_sct_segment_graymatter.py", line 18, in <module>
    import sct_segment_graymatter
  File "/home/neuropoly/sct/scripts/sct_segment_graymatter.py", line 50, in <module>
    from msct_multiatlas_seg import ModelParam, Model, SegmentationParam, SupervisedSegmentationMethod
  File "/home/neuropoly/sct/scripts/msct_multiatlas_seg.py", line 23, in <module>
    from msct_pca import PCA
  File "/home/neuropoly/sct/scripts/msct_pca.py", line 34, in <module>
    import matplotlib.pyplot as plt
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/neuropoly/sct/python/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
~~~

**Comment by jcohenadad** [comment]
trying to install libgomp on container:
~~~
apt-get install libgomp1
~~~

**Comment by jcohenadad** [comment]
now regarding the other error, seems like libgthread-2.0 is related to package libglib2.0-0. 

Installed it --> now error is:

~~~
sct_testing -f sct_segment_graymatter
SpinalCord Toolbox version 2.2_dev
SCT installed in /root/sct
PYTHON /root/sct/python/bin/python /root/sct/python /root/sct
running /root/sct/scripts/sct_testing.py -f sct_segment_graymatter

Path to testing data: /root/sct_testing_data/data/
Checking test_sct_segment_graymatter................Traceback (most recent call last):
  File "/root/sct/scripts/sct_testing.py", line 297, in <module>
    main()
  File "/root/sct/scripts/sct_testing.py", line 100, in main
    [status.append(test_function(f)) for f in functions if function_to_test == f]
  File "/root/sct/scripts/sct_testing.py", line 241, in test_function
    script_tested = importlib.import_module(script_name)
  File "/root/sct/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/sct/testing/test_sct_segment_graymatter.py", line 18, in <module>
    import sct_segment_graymatter
  File "/root/sct/scripts/sct_segment_graymatter.py", line 50, in <module>
    from msct_multiatlas_seg import ModelParam, Model, SegmentationParam, SupervisedSegmentationMethod
  File "/root/sct/scripts/msct_multiatlas_seg.py", line 23, in <module>
    from msct_pca import PCA
  File "/root/sct/scripts/msct_pca.py", line 34, in <module>
    import matplotlib.pyplot as plt
  File "/root/sct/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/sct/python/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/root/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/root/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/root/sct/python/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/root/sct/python/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

~~~

**Comment by jcohenadad** [comment]
installed: libsm6.

now error is:

~~~
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
~~~e

**Comment by jcohenadad** [comment]
installed: libxrender1

solved problem :-)
