### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#795]
data: **sct_testing/small/20151025_emil**

~~~
isct_test_function -f sct_label_vertebrae -d /Volumes/data_raid/data_shared/sct_testing/small/ -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0\"
SpinalCord Toolbox version 2.2_dev
SCT installed in /Users/jcohen/code/spinalcordtoolbox
PYTHON /Users/jcohen/code/spinalcordtoolbox/python/bin/python /Users/jcohen/code/spinalcordtoolbox/python /Users/jcohen/code/spinalcordtoolbox
running /Users/jcohen/code/spinalcordtoolbox/scripts/isct_test_function.py -f sct_label_vertebrae -d /Volumes/data_raid/data_shared/sct_testing/small/ -p "-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -o t2_seg_labeled.nii.gz -r 0"
Check folder existence...
Testing... (started on: 2016-04-05 13:41:13)
running /Users/jcohen/code/spinalcordtoolbox/scripts/sct_label_vertebrae.py -laplacian 0 -o t2_seg_labeled.nii.gz -i /Volumes/data_raid/data_shared/sct_testing/small/20151025_emil/t2/t2.nii.gz -v 1 -s /Volumes/data_raid/data_shared/sct_testing/small/20151025_emil/t2/t2_seg_manual.nii.gz -r 0 -denoise 0 -ofolder sct_label_vertebrae_20151025_emil_160405134113_683918/ -initz 7,2
Check folder existence...

Create temporary folder...

Create temporary folder...
mkdir tmp.160405134114_663672/

Copying input data to tmp folder...
sct_convert -i /Volumes/data_raid/data_shared/sct_testing/small/20151025_emil/t2/t2.nii.gz -o tmp.160405134114_663672/data.nii
sct_convert -i /Volumes/data_raid/data_shared/sct_testing/small/20151025_emil/t2/t2_seg_manual.nii.gz -o tmp.160405134114_663672/segmentation.nii.gz

Create label to identify disc...

Straighten spinal cord...
sct_straighten_spinalcord -i data.nii -s segmentation.nii.gz -r 0 -qc 0

Apply straightening to segmentation...
sct_apply_transfo -i segmentation.nii.gz -d data_straight.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear
sct_maths -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz

Dilate z-label and apply straightening...
sct_apply_transfo -i labelz.nii.gz -d data_straight.nii -w warp_curve2straight.nii.gz -o labelz_straight.nii.gz -x nn

Get z and disc values from straight label...
.. [8, 2]

Detect intervertebral discs...
.. local adjustment to center disc
.... WARNING: Pattern is missing data (because close to the edge). Using initial current_z provided.
Current disc: 2 (z=8). Direction: superior
.. approximate distance to next disc: 47 mm
.. WARNING: Data contained zero. We are probably at the edge.
Traceback (most recent call last):
File "/Users/jcohen/code/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 679, in <module>
main()
File "/Users/jcohen/code/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 193, in main
vertebral_detection('data_straight.nii', 'segmentation_straight.nii.gz', init_disc, verbose)
File "/Users/jcohen/code/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 391, in vertebral_detection
ind_peak[0] = np.where(I_corr_adj == I_corr_adj.max())[0]  # index of max along z
ValueError: setting an array element with a sequence.
/Users/jcohen/code/spinalcordtoolbox/scripts/sct_utils.py, line 100
~~~

**Comment by jcohenadad** [comment]
fixed
