### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'label/template/MNI-Poly-AMU_level.nii.gz'

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#810]
should add a check if file exists.

~~~
sct_process_segmentation -i t2_seg.nii.gz -p csa -vert 3:4
SpinalCord Toolbox version 2.2_dev
SCT installed in /Users/julien/code/spinalcordtoolbox
PYTHON /Users/julien/code/spinalcordtoolbox/python/bin/python /Users/julien/code/spinalcordtoolbox/python /Users/julien/code/spinalcordtoolbox
running /Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py -i t2_seg.nii.gz -p csa -vert 3:4

Check parameters:
.. segmentation file:             t2_seg.nii.gz

Create temporary folder...
mkdir tmp.160413195734_442430/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/sct_example_data/t2/t2_seg.nii.gz -o tmp.160413195734_442430/segmentation.nii.gz

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
  52 x 384 x 185

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 50

Compute CSA...

Smooth CSA across slices...
.. No smoothing!

Write text file...
z=0: 31.5191193861 mm^2
z=1: 30.564461739 mm^2
z=2: 28.654618606 mm^2
z=3: 30.564461739 mm^2
z=4: 33.4281449556 mm^2
z=5: 33.4250035404 mm^2
z=6: 31.510602777 mm^2
z=7: 31.5045373108 mm^2
z=8: 33.4055449845 mm^2
z=9: 33.3949918765 mm^2
z=10: 34.3357862116 mm^2
z=11: 34.3198013043 mm^2
z=12: 34.3009558132 mm^2
z=13: 36.1833537905 mm^2
z=14: 37.1080437225 mm^2
z=15: 34.2246979219 mm^2
z=16: 32.2926485039 mm^2
z=17: 37.002397335 mm^2
z=18: 37.9067654779 mm^2
z=19: 35.96487314 mm^2
z=20: 34.0239727865 mm^2
z=21: 35.8602987184 mm^2
z=22: 33.9193759923 mm^2
z=23: 35.7446778086 mm^2
z=24: 34.743908926 mm^2
z=25: 35.6187625499 mm^2
z=26: 34.616730302 mm^2
z=27: 37.3509680165 mm^2
z=28: 37.2756789797 mm^2
z=29: 37.1977264552 mm^2
z=30: 38.0452869755 mm^2
z=31: 37.9607826675 mm^2
z=32: 38.7985972784 mm^2
z=33: 36.8661869291 mm^2
z=34: 35.8609050451 mm^2
z=35: 36.6945845662 mm^2
z=36: 38.4407048354 mm^2
z=37: 36.5279060146 mm^2
z=38: 36.4475854035 mm^2
z=39: 37.2782937744 mm^2
z=40: 38.106865612 mm^2
z=41: 38.0281697205 mm^2
z=42: 40.6623753721 mm^2
z=43: 37.8767048635 mm^2
z=44: 43.2035965752 mm^2
z=45: 39.5273538761 mm^2
z=46: 42.1425920211 mm^2
z=47: 37.5892861878 mm^2
z=48: 40.2006381314 mm^2
z=49: 42.803956939 mm^2
z=50: 42.7294417795 mm^2
z=51: 39.9914077603 mm^2
z=52: 40.8133641264 mm^2
z=53: 40.7483919915 mm^2
z=54: 43.3384371525 mm^2
z=55: 39.7400545271 mm^2
z=56: 42.3264259629 mm^2
z=57: 38.7434999572 mm^2
z=58: 41.3279779303 mm^2
z=59: 40.3951869178 mm^2
z=60: 42.0980946508 mm^2
z=61: 42.9226753414 mm^2
z=62: 42.8719706304 mm^2
z=63: 45.4449288418 mm^2
z=64: 46.2683847409 mm^2
z=65: 43.6042974942 mm^2
z=66: 47.9179506673 mm^2
z=67: 47.0036090256 mm^2
z=68: 47.833232458 mm^2
z=69: 49.5337582371 mm^2
z=70: 46.024871442 mm^2
z=71: 49.4671328427 mm^2
z=72: 46.8384345578 mm^2
z=73: 46.8181635677 mm^2
z=74: 49.403485364 mm^2
z=75: 45.9280259124 mm^2
z=76: 48.5256453528 mm^2
z=77: 46.7979520163 mm^2
z=78: 47.6780825871 mm^2
z=79: 48.5668278581 mm^2
z=80: 45.9929224856 mm^2
z=81: 47.7646922926 mm^2
z=82: 47.8079477555 mm^2
z=83: 50.4685991866 mm^2
z=84: 50.5290980172 mm^2
z=85: 52.3417720943 mm^2
z=86: 53.293942375 mm^2
z=87: 50.7572743064 mm^2
z=88: 51.7265389951 mm^2
z=89: 50.9512827632 mm^2
z=90: 51.0630196652 mm^2
z=91: 49.4205650607 mm^2
z=92: 50.4342158966 mm^2
z=93: 48.8015329344 mm^2
z=94: 50.7291959938 mm^2
z=95: 52.6790497247 mm^2
z=96: 51.9635030298 mm^2
z=97: 52.1500235464 mm^2
z=98: 53.2475299248 mm^2
z=99: 56.1721128026 mm^2
z=100: 55.4873203336 mm^2
z=101: 57.5417916456 mm^2
z=102: 59.6170272157 mm^2
z=103: 57.1064275497 mm^2
z=104: 60.1243915503 mm^2
z=105: 56.664345271 mm^2
z=106: 56.9044753155 mm^2
z=107: 59.9541882932 mm^2
z=108: 56.4405212379 mm^2
z=109: 57.6154236877 mm^2
z=110: 58.7938408496 mm^2
z=111: 60.9268870431 mm^2
z=112: 60.201903531 mm^2
z=113: 63.299193109 mm^2
z=114: 63.5213009941 mm^2
z=115: 63.7339706034 mm^2
z=116: 64.9052298631 mm^2
z=117: 66.0714413254 mm^2
z=118: 64.3082037662 mm^2
z=119: 64.4762937075 mm^2
z=120: 65.6117293049 mm^2
z=121: 60.8507164292 mm^2
z=122: 61.9582507074 mm^2
z=123: 65.0290557079 mm^2
z=124: 67.1121313272 mm^2
z=125: 67.2135321855 mm^2
z=126: 68.2942155057 mm^2
z=127: 68.3765046589 mm^2
z=128: 68.4495538009 mm^2
z=129: 71.4930579014 mm^2
z=130: 72.546477429 mm^2
z=131: 73.5944408243 mm^2
z=132: 72.6471394097 mm^2
z=133: 72.6888013722 mm^2
z=134: 73.7217827636 mm^2
z=135: 73.7547540133 mm^2
z=136: 72.7868395323 mm^2
z=137: 72.8122480229 mm^2
z=138: 72.8347761917 mm^2
z=139: 74.8506759611 mm^2
z=140: 74.8684389026 mm^2
z=141: 76.8806669496 mm^2
z=142: 79.8901882999 mm^2
z=143: 80.9012789465 mm^2
z=144: 80.9120269517 mm^2
z=145: 78.9232594146 mm^2
z=146: 77.9320928126 mm^2
z=147: 78.9382846763 mm^2
z=148: 78.9445477837 mm^2
z=149: 77.9507008718 mm^2
z=150: 77.9554345303 mm^2
z=151: 78.958916804 mm^2
z=152: 79.9617219496 mm^2
z=153: 78.9646840724 mm^2
z=154: 76.9672055279 mm^2
z=155: 77.9676391524 mm^2
z=156: 76.9681227219 mm^2
z=157: 76.9674012497 mm^2
z=158: 76.9659101879 mm^2
z=159: 74.9646835037 mm^2
z=160: 74.9620509366 mm^2
z=161: 73.9595492338 mm^2
z=162: 75.9550657504 mm^2
z=163: 74.9522161655 mm^2
z=164: 74.948837676 mm^2
z=165: 74.9455448521 mm^2
z=166: 72.9438781116 mm^2
z=167: 74.9392709546 mm^2
z=168: 75.935540464 mm^2
z=169: 77.9310671852 mm^2
z=170: 77.928540233 mm^2
z=171: 76.927253116 mm^2
z=172: 78.9234052922 mm^2
z=173: 80.9197363969 mm^2
z=174: 79.9192585182 mm^2
z=175: 79.9180095112 mm^2
z=176: 77.9190654969 mm^2
z=177: 80.9151649747 mm^2
z=178: 81.9135604871 mm^2
z=179: 81.9132153328 mm^2
z=180: 78.9162054026 mm^2
z=181: 81.9129119602 mm^2
z=182: 80.9139303385 mm^2
z=183: 82.9118499109 mm^2
z=184: 80.9140176674 mm^2

Create volume of CSA values...
sct_image -i csa_volume_RPI.nii.gz -setorient AIL -o csa_volume.nii.gz

Generate output files...
  WARNING: File /Users/julien/sct_example_data/t2/csa_volume.nii.gz already exists. Deleting it...
  File created: /Users/julien/sct_example_data/t2/csa_volume.nii.gz
	Selected vertebral levels... 3:4
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 869, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 239, in main
    compute_csa(fname_segmentation, verbose, remove_temp_files, step, smoothing_param, figure_fit, param.file_csa_volume, slices, vert_lev, fname_vertebral_labeling, algo_fitting = param.algo_fitting, type_window= param.type_window, window_length=param.window_length)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 587, in compute_csa
    im_vertebral_labeling = set_orientation(Image(fname_vertebral_labeling), 'RPI', fname_out=path_tmp+'vertebral_labeling_RPI.nii')
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_image.py", line 44, in __init__
    self.loadFromPath(param, verbose)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_image.py", line 97, in loadFromPath
    im_file = load(path)
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/loadsave.py", line 44, in load
    return guessed_image_type(filename).from_filename(filename, **kwargs)
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/loadsave.py", line 76, in guessed_image_type
    with BinOpener(filename) as fobj:
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/openers.py", line 120, in __init__
    self.fobj = opener(fileish, *args, **kwargs)
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/nibabel/openers.py", line 63, in _gzip_open
    gzip_file = BufferedGzipFile(fileish, *args, **kwargs)
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'label/template/MNI-Poly-AMU_level.nii.gz'
~~~

**Comment by slevyrosetti** [comment]
Fixed in commit 4d89225: no default is given for the vertebral labeling file anymore and a check is performed in case user asked for vertebral levels but did not provide any labeling file in flag -vertfile. (The error message guides the user towards the potential path `./label/template/MNI-Poly-AMU_level.nii.gz` for the vertebral labeling file.)

**Comment by jcohenadad** [comment]
@slevyrosetti: having a default is super important, since most of the time it will be under label/template, so no need for the user to write it

**Comment by slevyrosetti** [comment]
All right, I will change for that idea.

**Comment by slevyrosetti** [comment]
Fixed in commit 8df77d8.

**Comment by jcohenadad** [comment]
i can see that the flag -vertfile disappeared-- could you please put it back
thanks

**Comment by slevyrosetti** [comment]
Are you sure? It is still there for me and I'm up to date on master...

**Comment by slevyrosetti** [comment]
~~~
pass:/Volumes/slevy-5/data/upgrade_sct_extract_metric/d_sp_pain_01/t2 $ sct_process_segmentation 
SpinalCord Toolbox version 2.2_dev
SCT installed in /Users/slevy_local/spinalcordtoolbox
PYTHON /Users/slevy_local/spinalcordtoolbox/python/bin/python /Users/slevy_local/spinalcordtoolbox/python /Users/slevy_local/spinalcordtoolbox
running /Users/slevy_local/spinalcordtoolbox/scripts/sct_process_segmentation.py

sct_process_segmentation.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Part of the Spinal Cord Toolbox <https://sourceforge.net/projects/spinalcordtoolbox>
Version: 2.2_dev


DESCRIPTION
This program is used to get the centerline of the spinal cord of a subject by using one of the 
three methods describe in the -method flag .

USAGE
sct_process_segmentation.py -i <image_nifti> -p {centerline,length,csa}


MANDATORY ARGUMENTS
  -i <image_nifti>            Spinal Cord segmentation      
  -p {centerline,length,csa}  type of process to be performed:
                                - centerline: extract centerline as binary file.
                                - length: compute length of the segmentation.
                                - csa: computes cross-sectional area by counting pixels in each.
                                  slice and then geometrically adjusting using centerline 
                                  orientation. Outputs:
                                  - csa.txt: text file with z (1st column) and CSA in mm^2 (2nd 
                                  column),
                                  - csa_volume.nii.gz: segmentation where each slice's value is 
                                  equal to the CSA (mm^2).
                                


OPTIONAL ARGUMENTS
  -z <str>                    Slice range to compute the CSA across (requires "-p csa").
  -vert <str>                 Vertebral levels to compute the CSA across (requires "-p csa"). 
                              Example: 2:9 for C2 to T2.
  -vertfile <image_nifti>     Vertebral labeling file. Only use with flag -vert Default value = 
                              ./label/template/MNI-Poly-AMU_level.nii.gz
  -method {counting_ortho_plane,counting_z_plane,ellipse_ortho_plane,ellipse_z_plane}Method to compute CSA Default value = counting_z_plane
  -r {0,1}                    Removes the temporary folder and debug folder used for the algorithm 
                              at the end of execution Default value = 1
  -size <int>                 Window size (in mm) for smoothing CSA. 0 for no smoothing.
  -a {hanning,nurbs}          Algorithm for curve fitting. Default value = hanning
  -v {0,1,2}                  1: display on, 0: display off (default) Default value = 1
  -h                          display this help             


EXAMPLE
sct_process_segmentation.py -i seg.nii.gz -p centerline -z 5:23 -vert 2:9 -vertfile ./label/template/MNI-Poly-AMU_level.nii.gz -method counting_ortho_plane -r 0 -a hanning -v 0
~~~

**Comment by jcohenadad** [comment]
sorry, i meant for sct_extract_metric

**Comment by slevyrosetti** [comment]
There never was. In sct_extract_metric, the user specify the atlas folder in flag -f and the script looks for the vertebral labeling file in the whole directory above.

**Comment by jcohenadad** [comment]
ok, fair enough
