### ISSUE TITLE
Testing on sct_label_vertebrae crashes on NeuroDebian

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#862]
```
brain@neurodebian:~$ sct_testing -f sct_label_vertebrae
cat: /home/brain/sct_3.0_beta8/commit.txt: No such file or directory

Spinal Cord Toolbox (version 3.0_beta8-)
Running /home/brain/sct_3.0_beta8/scripts/sct_testing.py -f sct_label_vertebrae

Path to testing data: /home/brain/sct_testing_data/data/
Checking test_sct_label_vertebrae...................Traceback (most recent call last):
  File "/home/brain/sct_3.0_beta8/scripts/sct_testing.py", line 303, in <module>
    main()
  File "/home/brain/sct_3.0_beta8/scripts/sct_testing.py", line 105, in main
    [status.append(test_function(f)) for f in functions if function_to_test == f]
  File "/home/brain/sct_3.0_beta8/scripts/sct_testing.py", line 247, in test_function
    script_tested = importlib.import_module(script_name)
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/brain/sct_3.0_beta8/testing/test_sct_label_vertebrae.py", line 16, in <module>
    from pandas import DataFrame
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/__init__.py", line 45, in <module>
    from pandas.core.api import *
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/core/groupby.py", line 15, in <module>
    from pandas.core.frame import DataFrame
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/core/frame.py", line 40, in <module>
    from pandas.core.series import Series
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/core/series.py", line 2737, in <module>
    import pandas.tools.plotting as _gfx
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/tools/plotting.py", line 28, in <module>
    import pandas.tseries.converter as conv
  File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb1 in position 35: invalid start byte
```

**Comment by benjamindeleener** [comment]
Don't know the reason, but this could be a reason for using Python 3.x: https://wiki.python.org/moin/UnicodeDecodeError

**Comment by benjamindeleener** [comment]
Could be due to a file that is not encoded in UTF-8...

**Comment by benjamindeleener** [comment]
I get the following error when trying to import matplotlib into the python environment:
```
(/home/brain/sct_3.0_beta8/python)brain@neurodebian:~$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb1 in position 35: invalid start byte
```

**Comment by benjamindeleener** [comment]
This issue was fixed by uninstalling and reinstalling matplotlib (using conda uninstall/install)... It's weird. Something in the installation could cause the error. We should be careful for the future.

**Comment by jcohenadad** [comment]
I spotted another issue: the file commit.txt should be in the package

**Comment by benjamindeleener** [comment]
Yep that's the issue #861 

I don't close this one now as the installing on NeuroDebian is not working.
By the way, after installing correctly matplotlib, other issues came up in sct_testing, issues #863 and #864.

**Comment by benjamindeleener** [comment]
Reinstallation completely SCT worked, meaning that it was a one-time glitch. ```sct_check_dependences```should be more sensitive to python dependences installation (issue #866). In this case, it should test ```import XXX```
