### ISSUE TITLE
Failure in computing hausdorff distance

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#864]
```
brain@neurodebian:~$ sct_testing -f sct_register_graymatter
cat: /home/brain/sct_3.0_beta8/commit.txt: No such file or directory

Spinal Cord Toolbox (version 3.0_beta8-)
Running /home/brain/sct_3.0_beta8/scripts/sct_testing.py -f sct_register_graymatter

Path to testing data: /home/brain/sct_testing_data/data/
Checking test_sct_register_graymatter...............Running /home/brain/sct_3.0_beta8/scripts/sct_register_graymatter.py -qc 0 -manual-gm /home/brain/sct_testing_data/data/mt/mt0_manual_gmseg.nii.gz -gm /home/brain/sct_testing_data/data/mt/mt0_gmseg.nii.gz -t /home/brain/sct_testing_data/data/mt/label/ -w /home/brain/sct_testing_data/data/mt/warp_template2mt.nii.gz -v 1 -r 1 -sc /home/brain/sct_testing_data/data/mt/mt0_seg.nii.gz -wm /home/brain/sct_testing_data/data/mt/mt0_wmseg.nii.gz -ofolder sct_register_graymatterdata_160508215734_468241/
Check folder existence...
Check folder existence...
  OK: /home/brain/sct_testing_data/data/mt/label/

Create temporary folder...
mkdir tmp.160508215734_235507/
sct_convert -i /home/brain/sct_testing_data/data/mt/mt0_gmseg.nii.gz -o tmp.160508215734_235507/mt0_gmseg.nii.gz
sct_convert -i /home/brain/sct_testing_data/data/mt/warp_template2mt.nii.gz -o tmp.160508215734_235507/warp_template2mt.nii.gz
sct_create_mask -i multilabel_automatic_seg.nii.gz -p centerline,multilabel_automatic_seg.nii.gz -f box -size 26 -o square_mask.nii.gz
sct_crop_image -i multilabel_automatic_seg.nii.gz -m square_mask.nii.gz -o multilabel_automatic_seg_crop.nii.gz
sct_crop_image -i multilabel_template_seg.nii.gz -m square_mask.nii.gz -o multilabel_template_seg_crop.nii.gz
sct_register_multimodal -i multilabel_template_seg_crop.nii.gz -d multilabel_automatic_seg_crop.nii.gz -param step=1,algo=slicereg,metric=MeanSquares:step=2,algo=syn,metric=MeanSquares,iter=10,smooth=0,shrink=2:step=3,algo=bsplinesyn,metric=MeanSquares,iter=5,smooth=0
sct_concat_transfo -w warp_template2mt.nii.gz,warp_multilabel_template_seg_crop2multilabel_automatic_seg_crop.nii.gz -d mt0_gmseg.nii.gz -o warp_template2mt0_gmseg.nii.gz
  File created: sct_register_graymatterdata_160508215734_468241/warp_template2mt0_gmseg.nii.gz
rm -rf tmp.160508215734_235507/

Create temporary folder...
mkdir tmp.160508215748_470394/
cp /home/brain/sct_testing_data/data/mt/mt0_manual_gmseg.nii.gz tmp.160508215748_470394/mt0_manual_gmseg.nii.gz
cp /home/brain/sct_testing_data/data/mt/mt0_seg.nii.gz tmp.160508215748_470394/mt0_seg.nii.gz
cp sct_register_graymatterdata_160508215734_468241/warp_template2mt0_gmseg.nii.gz tmp.160508215748_470394/warp_template2mt0_gmseg.nii.gz
sct_warp_template -d /home/brain/sct_testing_data/data/mt/mt0_manual_gmseg.nii.gz -w warp_template2mt0_gmseg.nii.gz -qc 0 -a 0
sct_maths -i mt0_seg.nii.gz -sub mt0_manual_gmseg.nii.gz -o target_manual_wmseg.nii.gz
sct_compute_hausdorff_distance -i old_template_gm.nii.gz -r mt0_manual_gmseg.nii.gz -t 1  -v 1
Running /home/brain/sct_3.0_beta8/scripts/sct_compute_hausdorff_distance.py -i old_template_gm.nii.gz -r mt0_manual_gmseg.nii.gz -t 1 -v 1
/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
WARNING : -r is a deprecated argument and will no longer be updated in future versions. Changing argument to -d.
WARNING : -t is a deprecated argument and will no longer be updated in future versions. Changing argument to -thinning.
mkdir tmp_160508215754
cp old_template_gm.nii.gz tmp_160508215754/im1.nii.gz
cp mt0_manual_gmseg.nii.gz tmp_160508215754/im2.nii.gz
sct_resample -i im1.nii.gz -mm 0.1x0.1x17.0 -o im1_resampled.nii.gz -x nn
sct_maths -i im1_resampled.nii.gz -thr 0.5 -o im1_resampled.nii.gz
sct_maths -i im1_resampled.nii.gz -bin -o im1_resampled.nii.gz
sct_resample -i im2.nii.gz -mm 0.1x0.1x17.0 -o im2_resampled.nii.gz -x nn
sct_maths -i im2_resampled.nii.gz -thr 0.5 -o im2_resampled.nii.gz
sct_maths -i im2_resampled.nii.gz -bin -o im2_resampled.nii.gz
Thinning ... 
Thinning ... 
Computing 2D Hausdorff's distance ... 
Warning: an image is empty
Warning: an image is empty
Computing 2D Hausdorff's distance ... 
Computing 2D Hausdorff's distance ... 
Computing 2D Hausdorff's distance ... 
Computing 2D Hausdorff's distance ... 
Warning: an image is empty
Warning: an image is empty
Traceback (most recent call last):
File "/home/brain/sct_3.0_beta8/scripts/sct_compute_hausdorff_distance.py", line 462, in <module>
computation = ComputeDistances(input_im1, im2=input_im2, param=param)
File "/home/brain/sct_3.0_beta8/scripts/sct_compute_hausdorff_distance.py", line 242, in __init__
med1 = np.median(self.dist1_distribution[i])
File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3084, in median
overwrite_input=overwrite_input)
File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2997, in _ureduce
r = func(a, **kwargs)
File "/home/brain/sct_3.0_beta8/python/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3138, in _median
n = np.isnan(part[..., -1])
IndexError: index -1 is out of bounds for axis 0 with size 0
/home/brain/sct_3.0_beta8/scripts/sct_utils.py, line 100
/home/brain/sct_3.0_beta8/scripts/sct_utils.py, line 100
```

**Comment by benjamindeleener** [comment]
Reinstalling dependences as in #863 fixed the issue. Still, there is an issue in the installation.

**Comment by benjamindeleener** [comment]
Re run installation worked, so it was a one-time glitch.
```sct_check_dependences```should be more sensitive to python dependences installation (issue #866).
