### ISSUE TITLE
error on test_sct_segment_graymatter

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#891]
i'm getting this error, although Travis passes.

~~~
sct_testing -d 1

Spinal Cord Toolbox (version dev-3a70285f795e598795e7824e4c84e8de708e1038)
Running /Users/julien/code/spinalcordtoolbox/scripts/sct_testing.py -d 1

Downloading testing data...
sct_download_data -d sct_testing_data

Path to testing data: /Users/julien/sct_testing_data/data/
Checking test_sct_apply_transfo.....................[OK]
Checking test_sct_check_atlas_integrity.............[OK]
Checking test_sct_compute_mtr.......................[OK]
Checking test_sct_concat_transfo....................[OK]
Checking test_sct_convert...........................[OK]
Checking test_sct_create_mask.......................[OK]
Checking test_sct_crop_image........................[OK]
Checking test_sct_dmri_compute_dti..................[OK]
Checking test_sct_dmri_get_bvalue...................[OK]
Checking test_sct_dmri_transpose_bvecs..............[OK]
Checking test_sct_dmri_moco.........................[OK]
Checking test_sct_dmri_separate_b0_and_dwi..........[OK]
Checking test_sct_extract_metric....................[OK]
Checking test_sct_fmri_compute_tsnr.................[OK]
Checking test_sct_fmri_moco.........................^[[A[OK]
Checking test_sct_image.............................[OK]
Checking test_sct_label_utils.......................[OK]
Checking test_sct_label_vertebrae...................[OK]
Checking test_sct_maths.............................[OK]
Checking test_sct_process_segmentation..............[OK]
Checking test_sct_propseg...........................[OK]
Checking test_sct_register_graymatter...............[OK]
Checking test_sct_register_multimodal...............[OK]
Checking test_sct_register_to_template..............[OK]
Checking test_sct_resample..........................[OK]
Checking test_sct_segment_graymatter................Running /Users/julien/code/spinalcordtoolbox/scripts/sct_segment_graymatter.py -ratio 0 -qc 0 -weight 2.5 -i /Users/julien/sct_testing_data/data/mt/mt0.nii.gz -r 1 -ref /Users/julien/sct_testing_data/data/mt/mt0_manual_gmseg.nii.gz -k 0.8 -ofolder ./ -denoising 1 -v 1 -res-type prob -s /Users/julien/sct_testing_data/data/mt/mt0_seg.nii.gz -vertfile /Users/julien/sct_testing_data/data/mt/label/template/MNI-Poly-AMU_level.nii.gz -normalize 1 -ofolder sct_segment_graymatter_data_160615183756_956449/
Check folder existence...
Check folder existence...

Building the appearance model...

Loading a reduced common space (using a PCA) ...

---> sum of eigenvalues : 25601230.092
kept eigenvalues (PCA space dimension)  : 47


-------> IN PCA : 

-> kept_modes:[[  2.39757031e-16  -8.21900381e-17   2.93683807e-17 ...,   4.24317548e-17
-3.89564413e-17  -9.12340398e-17]
[ -3.79002146e-16   3.60424298e-16  -3.35096744e-16 ...,  -2.00513278e-16
-6.37809817e-16  -7.37722667e-16]
[  8.81995193e-17  -1.86772023e-17  -4.35252228e-17 ...,  -1.35261546e-16
-5.47676640e-16  -6.75053168e-16]
...,
[  2.74755125e-41  -3.70707367e-41  -1.68272897e-41 ...,   4.54141770e-42
-7.48202727e-41   4.22570827e-41]
[  1.75581766e-41  -3.29436870e-41   2.66076533e-41 ...,  -5.07662462e-41
2.05743668e-40   1.53877001e-40]
[ -1.10186724e-44   3.10061910e-42  -4.61501418e-43 ...,   9.75283339e-42
3.05073686e-42   8.30540278e-42]]

-> kept_eigenval:47
mkdir tmp_mt0_160615183757_157466/

Doing target pre-processing ...
cp /Users/julien/sct_testing_data/data/mt/label/template/MNI-Poly-AMU_level.nii.gz tmp_mt0_160615183757_157466//MNI-Poly-AMU_level.nii.gz
cp /Users/julien/sct_testing_data/data/mt/mt0.nii.gz tmp_mt0_160615183757_157466//target.nii.gz
cp /Users/julien/sct_testing_data/data/mt/mt0_seg.nii.gz tmp_mt0_160615183757_157466//target_sc_seg.nii.gz
sct_resample -i target.nii.gz -mm 0.3x0.3x17.0 -o target_resampled.nii.gz -x spline
sct_resample -i target_sc_seg.nii.gz -mm 0.3x0.3x17.0 -o target_sc_seg_resampled.nii.gz -x nn
sct_maths -i target_sc_seg_resampled.nii.gz -thr 0.0 -o target_sc_seg_resampled.nii.gz
sct_maths -i target_sc_seg_resampled.nii.gz -bin -o target_sc_seg_resampled.nii.gz
WARNING: File target_resampled.nii.gz already exists. Deleting it.
sct_image -i target_resampled.nii.gz -pad 39,39,0 -o target_resampled_pad.nii.gz
sct_image -i target_sc_seg_resampled.nii.gz -pad 39,39,0 -o target_sc_seg_resampled_pad.nii.gz
sct_image -i target_resampled_pad.nii.gz -setorient RPI -o target_resampled_pad_RPI.nii.gz
sct_image -i target_sc_seg_resampled_pad.nii.gz -setorient RPI -o target_sc_seg_resampled_pad_RPI.nii.gz
sct_crop_image -i target_resampled_pad_RPI.nii.gz -m target_sc_seg_resampled_pad_RPI.nii.gz -b 0 -o target_resampled_pad_RPI_seg_in.nii.gz
sct_create_mask -i target_resampled_pad_RPI_seg_in.nii.gz -p centerline,target_sc_seg_resampled_pad_RPI.nii.gz -size 75 -o target_resampled_pad_RPI_square_mask_from_sc_seg.nii.gz -f box

Doing target gray matter segmentation ...

Constructing target image ...
mkdir ./affine_transformations
Linear target normalization using median ...
WARNING: The contrast between GM and WM is too small to use the normalization based on median WM-GM values estimated with a pre-registration of the GM template, it will be replaced by a linear normalization using minimum/maximum intensity values
Linear target normalization using min-max ...

Projecting the target image in the reduced common space ...

Computing the similarities between the target and the model slices ...

Selecting the dictionary slices most similar to the target ...

Computing the result gray matter segmentation ...

Registering the result gray matter segmentation back into the target original space...

Doing result post-processing ...
Traceback (most recent call last):
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_segment_graymatter.py", line 694, in <module>
gmsegfull.segment()
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_segment_graymatter.py", line 354, in segment
self.segmentation_pipeline()
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_segment_graymatter.py", line 404, in segmentation_pipeline
self.post_processing()
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_segment_graymatter.py", line 425, in post_processing
res_im_original_space = inverse_square_crop(res_im, square_mask)
File "/Users/julien/code/spinalcordtoolbox/scripts/msct_gmseg_utils.py", line 1082, in inverse_square_crop
assert len(nz_coord) == croped_image.data.size
AssertionError
/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 104
~~~

**Comment by SaraDupont** [comment]
It is because the model changed : run ```./install_sct -m -b``` and it will work.
