### ISSUE TITLE
[SCT_SEGMENT_GRAYMATTER] BUG ON MTV IMAGES

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#928]
Data in: `20160712_issueGMseg`

Command:
`sct_segment_graymatter -i mtv_RPI.nii.gz -s SPGRs_seg_RPI.nii.gz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Spinal Cord Toolbox (version dev-ab0c70811b160c07244207e3f330f9b26749ca5f)
Running /Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_segment_graymatter.py -i mtv_RPI.nii.gz -s SPGRs_seg_RPI.nii.gz

Building the appearance model...

Loading a reduced common space (using a PCA) ...

 ---> sum of eigenvalues : 25601230.092
kept eigenvalues (PCA space dimension)  : 47


-------> IN PCA : 

-> kept_modes:[[  2.39757031e-16  -8.21900381e-17   2.93683807e-17 ...,   4.24317548e-17
   -3.89564413e-17  -9.12340398e-17]
 [ -3.79002146e-16   3.60424298e-16  -3.35096744e-16 ...,  -2.00513278e-16
   -6.37809817e-16  -7.37722667e-16]
 [  8.81995193e-17  -1.86772023e-17  -4.35252228e-17 ...,  -1.35261546e-16
   -5.47676640e-16  -6.75053168e-16]
 ..., 
 [  2.74755125e-41  -3.70707367e-41  -1.68272897e-41 ...,   4.54141770e-42
   -7.48202727e-41   4.22570827e-41]
 [  1.75581766e-41  -3.29436870e-41   2.66076533e-41 ...,  -5.07662462e-41
    2.05743668e-40   1.53877001e-40]
 [ -1.10186724e-44   3.10061910e-42  -4.61501418e-43 ...,   9.75283339e-42
    3.05073686e-42   8.30540278e-42]]

-> kept_eigenval:47
mkdir tmp_mtv_RPI_160712163641_114328/

Doing target pre-processing ...
cp mtv_RPI.nii.gz tmp_mtv_RPI_160712163641_114328//target.nii.gz
cp SPGRs_seg_RPI.nii.gz tmp_mtv_RPI_160712163641_114328//target_sc_seg.nii.gz
sct_resample -i target.nii.gz -mm 0.3x0.3x5.0 -o target_resampled.nii.gz -x spline
sct_resample -i target_sc_seg.nii.gz -mm 0.3x0.3x5.0 -o target_sc_seg_resampled.nii.gz -x nn
sct_maths -i target_sc_seg_resampled.nii.gz -thr 0.0 -o target_sc_seg_resampled.nii.gz
sct_maths -i target_sc_seg_resampled.nii.gz -bin -o target_sc_seg_resampled.nii.gz
WARNING: File target_resampled.nii.gz already exists. Deleting it.
sct_image -i target_resampled.nii.gz -pad 39,39,0 -o target_resampled_pad.nii.gz
sct_image -i target_sc_seg_resampled.nii.gz -pad 39,39,0 -o target_sc_seg_resampled_pad.nii.gz
sct_image -i target_resampled_pad.nii.gz -setorient RPI -o target_resampled_pad_RPI.nii.gz
sct_image -i target_sc_seg_resampled_pad.nii.gz -setorient RPI -o target_sc_seg_resampled_pad_RPI.nii.gz
sct_crop_image -i target_resampled_pad_RPI.nii.gz -m target_sc_seg_resampled_pad_RPI.nii.gz -b 0 -o target_resampled_pad_RPI_seg_in.nii.gz
sct_create_mask -i target_resampled_pad_RPI_seg_in.nii.gz -p centerline,target_sc_seg_resampled_pad_RPI.nii.gz -size 75 -o target_resampled_pad_RPI_square_mask_from_sc_seg.nii.gz -f box
Running /Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_create_mask.py -i target_resampled_pad_RPI_seg_in.nii.gz -p centerline,target_sc_seg_resampled_pad_RPI.nii.gz -size 75 -o target_resampled_pad_RPI_square_mask_from_sc_seg.nii.gz -f box
  OK: target_sc_seg_resampled_pad_RPI.nii.gz

Create temporary folder...
mkdir tmp.160712163701/

Check orientation...
.. RPI
sct_convert -i target_resampled_pad_RPI_seg_in.nii.gz -o tmp.160712163701/data.nii
sct_convert -i target_sc_seg_resampled_pad_RPI.nii.gz -o tmp.160712163701/centerline.nii.gz

Reorient to RPI...

Get dimensions of data...
  238 x 238 x 22 x 1

Create mask...
Traceback (most recent call last):
File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_create_mask.py", line 407, in <module>
main()
File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_create_mask.py", line 90, in main
create_mask()
File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_create_mask.py", line 203, in create_mask
cx[iz], cy[iz] = ndimage.measurements.center_of_mass(numpy.array(data_centerline[:, :, z_centerline_not_null[iz]]))
IndexError: list index out of range
/Users/taduv_admin/codes/spinalcordtoolbox/scripts/sct_utils.py, line 104
`

**Comment by SaraDupont** [comment]
The folder `20160712_issueGMseg` in `folder_shared/sct_issues/` is empty. @tanguyduval  Do you still have the data ? 
This is probably fixed with the new implementation of `sct_segment_graymatter` but I would like to check, to be sure.

**Comment by tanguyduval** [comment]
@SaraDupont ok I copied the data in the folder

**Comment by SaraDupont** [comment]
The issue does not persist with the new implementation of `sct_segment_graymatter`.
