### ISSUE TITLE
enables creation of centerline from a series of points

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#965]
~~~
xuanwu_20160624_yaou_MS013/t1 $ sct_process_segmentation -i t1_mask_viewer.nii.gz -p centerline
----------------------------------------------------------------------------------------------------
Spinal Cord Toolbox (version dev-3e107b779165b4feb9871fa193dec8c660108832)
Running /Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py -i t1_mask_viewer.nii.gz -p centerline

Check parameters:
.. segmentation file:             t1_mask_viewer.nii.gz

Create temporary folder...
mkdir tmp.160819081840_272135/

Copying data to tmp folder...
sct_convert -i /Users/julien/data/test/xuanwu_20160624_yaou_MS013/t1/t1_mask_viewer.nii.gz -o tmp.160819081840_272135/segmentation.nii.gz

Orient centerline to RPI orientation...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
.. matrix size: 96 x 260 x 320
.. voxel size:  1.0mm x 0.98125mm x 0.98125mm
/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 80
WARNING: The smoothing window is larger than the number of points. New value: 11
WARNING: The smoothing window is larger than the number of points. New value: 11
/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py:411: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  data[round(x_centerline_fit[iz-min_z_index]), round(y_centerline_fit[iz-min_z_index]), iz] = 1 # if index is out of bounds here for hanning: either the segmentation has holes or labels have been added to the file
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 997, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 249, in main
    fname_output = extract_centerline(fname_segmentation, remove_temp_files, verbose=param.verbose, algo_fitting=param.algo_fitting)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 411, in extract_centerline
    data[round(x_centerline_fit[iz-min_z_index]), round(y_centerline_fit[iz-min_z_index]), iz] = 1 # if index is out of bounds here for hanning: either the segmentation has holes or labels have been added to the file
IndexError: index 15 is out of bounds for axis 0 with size 15
~~~

**Comment by benjamindeleener** [comment]
Have you tried with NURBS fitting? Because it is basically what is done in PropSeg for fitting a curve on some points. It should work with NURBS.

The command for testing:
```
sct_process_segmentation -i t1_mask_viewer.nii.gz -p centerline -a nurbs
```

**Comment by jcohenadad** [comment]
it worked :-)
maybe we should set nurbs as the default for this function?

**Comment by benjamindeleener** [comment]
I totally agree.

**Comment by jcohenadad** [comment]
i'm on it
