### ISSUE TITLE
sct_process_segmentation: Bug using '-vert' flag

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#989]
Command:
```
sct_process_segmentation -i /Volumes/folder_shared/als_gm_atrophy/test_benjamin/143/t2/t2_seg.nii.gz -p csa -output-type txt -vert 2:13 -vertfile /Volumes/folder_shared/als_gm_atrophy/test_benjamin/143/t2/label/template/PAM50_levels.nii.gz 
```

Error:
```
Selected vertebral levels... 2:13
  OK: /Volumes/folder_shared/als_gm_atrophy/test_benjamin/143/t2/label/template/PAM50_levels.nii.gz
    Find slices corresponding to vertebral levels based on the centerline...
/Users/chgroc/code/spinalcordtoolbox/scripts/sct_process_segmentation.py:915: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if vertebral_labeling_data[np.round(x_centerline_fit[i_z]), np.round(y_centerline_fit[i_z]), z_centerline[i_z]] in range(vert_levels_list[0], vert_levels_list[1]+1):
Traceback (most recent call last):
  File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 1035, in <module>
    main(sys.argv[1:])
  File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 262, in main
    compute_csa(fname_segmentation, output_prefix, param_default.suffix_csa_output_files, output_type, overwrite, verbose, remove_temp_files, step, smoothing_param, figure_fit, slices, vert_lev, fname_vertebral_labeling, algo_fitting = param.algo_fitting, type_window= param.type_window, window_length=param.window_length, angle_correction=angle_correction)
  File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 647, in compute_csa
    slices, vert_levels_list, warning = get_slices_matching_with_vertebral_levels_based_centerline(vert_levels, im_vertebral_labeling.data, x_centerline_fit, y_centerline_fit, z_centerline)
  File "/Users/chgroc/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 919, in get_slices_matching_with_vertebral_levels_based_centerline
    slices = str(min(matching_slices_centerline_vert_labeling))+':'+str(max(matching_slices_centerline_vert_labeling))
ValueError: min() arg is an empty sequence
```

**Comment by benjamindeleener** [comment]
The issue was caused by the NURBS fitting done in physical coordinates.

**Comment by jcohenadad** [comment]
what's the plan to fix it? I put it high priority because it makes batch_processing crashing

**Comment by benjamindeleener** [comment]
I am working on it right now and I am planning to fix it in the next 30 minutes.

I found other bugs in sct_process_segmentation that I am fixing now.

**Comment by jcohenadad** [comment]
great! Once fixed i can create a new release because currently beta21 has a major bug.

Note that we will also need to fix the "-o" vs. "-output-type" in this function (in addition to extract_metric). But let's leave it for later.

**Comment by benjamindeleener** [comment]
The issue is fixed. `sct_testing` works, as well as the `batch_processing`.

Note that the bug affected the computation of CSA. Therefore, all study computing cord CSA need to be done again.
